// ─── Space Tycoon: Finite Demand Pools (Economic PvP Wave E4) ────────────────
// docs/ECONOMY_PVP_2026-08.md §2.1 + §E4 — the wave that ends infinite
// service demand. Every service belongs to a demand market keyed
// (locationId, serviceCategory). Each market has a finite pool D in $/month:
//
//   D = (D_npc + D_derived) × D_mod
//
//   D_npc     — the NPC backdrop floor: authored base per location ×
//               NPC-population scaler that RECEDES as 30-day-active player
//               count grows (NPC_BACKDROP.md: floor, not ceiling).
//   D_derived — demand generated by real economic activity at the location,
//               aggregated across synced profiles: buildings there create
//               power/compute/telecom demand, crewed stations create
//               tourism/insurance demand, ships create launch/logistics
//               demand. Rivals BUILDING at a location grow its demand even
//               as they compete to serve it — agglomeration, like real ports.
//   D_mod     — the season super-cycle bias (economic-seasons.ts), mapped to
//               service categories and bounded ±15%. Deterministic from the
//               season number alone, so server and client agree.
//
// Suppliers split the pool by capacity share (service-pricing.ts is the
// pool-share calculator): saturation means competitors literally take your
// customers; undersupply pays a scarcity premium up to +25%. This REPLACES
// the old global log10 instance-count decay, which is retired.
//
// Boundary (§2 architecture invariant): everything cross-player here is
// computed SERVER-side (hourly cron → LocationDemandPool rows, EMA-smoothed
// on a 7-day horizon so pools shift on the DAILY loop) and delivered to the
// deterministic client tick as a bounded snapshot through the sync pipe —
// exactly how spot prices (marketSnapshot) already flow. This module is
// pure and client-safe (no prisma): the server cron, the sync route, and
// the client's solo/offline fallback all share these functions, which is
// what makes away-catch-up parity and determinism testable.
//
// Solo / logged-out / stale-snapshot players tick against a DETERMINISTIC
// local pool: authored NPC floor (full backdrop — an unsynced world is by
// definition a quiet one) + their OWN activity's derived demand vs. NPC
// supply + their OWN capacity. No cross-player quantity is ever computed
// client-side — the local pool contains only authored constants, world
// clocks, and the player's own save.

import { SERVICE_MAP } from './services';
import { BUILDING_MAP } from './buildings';
import { LOCATION_MAP } from './solar-system';
import { serviceSaturationMultiplier } from './formulas';
import { GAME_START_YEAR } from './server-time';
import { getSuperCycleForSeason } from './economic-seasons';
import type { ServiceType } from './types';

// ─── Service categories (§2.1) ──────────────────────────────────────────────
// `mining_output` services are deliberately EXCLUDED: mined-commodity revenue
// competes through the shared market price + extraction pressure (§2.4/E5),
// not through a service demand pool — pooling it too would double-tax mining.

export type ServiceCategory =
  | 'launch'
  | 'telecom'
  | 'sensor'
  | 'compute'
  | 'power'
  | 'tourism'
  | 'logistics'
  | 'fabrication'
  | 'insurance';

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  'launch', 'telecom', 'sensor', 'compute', 'power', 'tourism', 'logistics', 'fabrication', 'insurance',
];

/** Explicit per-service category assignments where the ServiceType alone is
 *  too coarse (spec §2.1: logistics = depot/debris/nav; insurance is its own
 *  market). Everything else falls back to CATEGORY_BY_SERVICE_TYPE. */
const SERVICE_CATEGORY_OVERRIDES: Record<string, ServiceCategory> = {
  svc_propellant_depot: 'logistics',
  svc_debris_removal: 'logistics',
  svc_navigation: 'logistics',
  svc_space_insurance: 'insurance',
  svc_power_orbital: 'power',
  svc_power_lunar: 'power',
  // M1/F2: svc_propellant_brokerage ("buy cheap fuel at Moon, sell at premium
  // to Mars/Jupiter-bound missions") is logistics/arbitrage in substance, not
  // launch-pad capacity — it was miscategorized into mars_orbit's tiny
  // authored `launch` floor (0.375x flagship, a floor-authoring violation).
  // Recategorizing is the spec's preferred fix over inflating a launch floor
  // that has no other tenant.
  svc_propellant_brokerage: 'logistics',
};

const CATEGORY_BY_SERVICE_TYPE: Partial<Record<ServiceType, ServiceCategory>> = {
  launch_payload: 'launch',
  telecom_service: 'telecom',
  sensor_service: 'sensor',
  ai_datacenter: 'compute',
  tourism: 'tourism',
  fabrication_output: 'fabrication',
  // mining_output intentionally absent → null (handled by §2.4 instead)
};

/** Demand-market category for a service — null for mining_output (exempt). */
export function getServiceCategory(serviceId: string): ServiceCategory | null {
  const override = SERVICE_CATEGORY_OVERRIDES[serviceId];
  if (override) return override;
  const def = SERVICE_MAP.get(serviceId);
  if (!def) return null;
  return CATEGORY_BY_SERVICE_TYPE[def.type] ?? null;
}

/** Canonical market key. */
export function demandPoolKey(locationId: string, category: ServiceCategory): string {
  return `${locationId}:${category}`;
}

export const CATEGORY_LABELS: Record<ServiceCategory, string> = {
  launch: 'Launch', telecom: 'Telecom', sensor: 'Sensor & Ops', compute: 'Compute',
  power: 'Power', tourism: 'Tourism', logistics: 'Logistics', fabrication: 'Fabrication',
  insurance: 'Insurance',
};

// ─── D_npc: the authored NPC backdrop floor (§2.1 / §2.9) ───────────────────
// Authored base demand per (location, category) in $/month. Tuning intent:
// each floor ≈ 2.5-3.5× the flagship service revenue for that market, so a
// FIRST mover is undersupplied (earns the scarcity premium) and the market
// comfortably carries 2-3 suppliers before saturation bites — "LEO telecom
// huge, Titan telecom tiny". Values are the <50-active-player full backdrop;
// npcPopulationScaler recedes them as the server fills up.

// M1/F2 floor-authoring pass: every floor below must be ≥ 2.5x the flagship
// (highest single-instance revenuePerMonth) service placeable in that
// (location, category) market — enforced by
// demand-pools.floor-authoring.test.ts, which iterates BUILDINGS × SERVICES
// the same way the harness's build-menu sweep does. Changed vs. the pre-M1
// authoring: earth_surface.launch 60M→150M (Heavy Launch Pad was saturated
// at N=1); geo.logistics 8M→40M (svc_navigation); lunar_orbit.insurance
// (unauthored → 24M, svc_space_insurance) and lunar_orbit.logistics
// 25M→36M (svc_debris_removal) — both found by the exhaustive sweep, not
// just the two the audit called out by name. mars_orbit.launch is
// unchanged (svc_propellant_brokerage was recategorized to logistics
// instead, see SERVICE_CATEGORY_OVERRIDES above — the preferred fix) and
// mars_orbit.logistics raised 40M→100M for it.
export const NPC_DEMAND_FLOOR: Record<string, Partial<Record<ServiceCategory, number>>> = {
  earth_surface: { launch: 150_000_000, sensor: 18_000_000, telecom: 10_000_000, insurance: 20_000_000, logistics: 12_000_000 },
  leo:           { telecom: 30_000_000, sensor: 12_000_000, tourism: 40_000_000, compute: 40_000_000, power: 10_000_000, fabrication: 30_000_000, logistics: 15_000_000, insurance: 10_000_000, launch: 20_000_000 },
  geo:           { telecom: 28_000_000, sensor: 24_000_000, power: 8_000_000, logistics: 40_000_000, insurance: 6_000_000 },
  lunar_orbit:   { tourism: 80_000_000, telecom: 10_000_000, logistics: 36_000_000, fabrication: 12_000_000, sensor: 10_000_000, launch: 12_000_000, insurance: 24_000_000 },
  lunar_surface: { tourism: 95_000_000, fabrication: 45_000_000, power: 16_000_000, logistics: 20_000_000, telecom: 8_000_000, compute: 10_000_000, sensor: 8_000_000 },
  mars_orbit:    { sensor: 140_000_000, compute: 80_000_000, telecom: 15_000_000, logistics: 100_000_000, launch: 15_000_000, insurance: 8_000_000 },
  mars_surface:  { tourism: 250_000_000, logistics: 65_000_000, fabrication: 30_000_000, power: 15_000_000, sensor: 20_000_000, telecom: 12_000_000, compute: 15_000_000 },
  asteroid_belt: { sensor: 90_000_000, launch: 130_000_000, logistics: 45_000_000, fabrication: 30_000_000, telecom: 10_000_000 },
  jupiter_system: { telecom: 95_000_000, compute: 30_000_000, logistics: 25_000_000, sensor: 15_000_000 },
  // fabrication raised 110M->130M alongside svc_titan_processing's M1 revenue
  // bump (35M->50M) to keep the 2.5-3.5x floor-authoring rule intact.
  saturn_system: { fabrication: 130_000_000, telecom: 20_000_000, logistics: 30_000_000, sensor: 12_000_000 },
  outer_system:  { telecom: 130_000_000, logistics: 30_000_000, sensor: 25_000_000 },

  // ─── AAA Round 1 E3.4 — the 12 colony markets ────────────────────────────
  // Authored at exactly 3.0x each market's flagship service, inside the
  // 2.5-3.5x band this table's own header specifies, so a first mover at a
  // newly unlocked body is undersupplied and earns the scarcity premium while
  // the market still carries two or three suppliers before saturation bites.
  //
  // Without these entries the 12 bodies fell through to
  // DEFAULT_FLOOR_BY_CATEGORY, which is sized for a small market: the colony
  // services saturated their own pools at N=1 and the M1 first-copy ROI guard
  // (tier-ladder-first-copy-roi.test.ts) failed all 23 of them. That failure
  // is where these numbers come from — they were derived from the guard, not
  // guessed and then rubber-stamped by it.
  //
  // Magnitudes stay frontier-scaled (compare jupiter_system compute $30M,
  // saturn_system logistics $30M, outer_system sensor $25M). Nobody is buying
  // $800M/month of compute at Pluto.
  // mining_output has no pool category (§2.4) and needs no floor.
  ceres_surface:     { fabrication: 42_000_000, tourism: 42_000_000 },
  venus_orbit:       { sensor: 42_000_000, tourism: 42_000_000 },
  mercury_surface:   { fabrication: 42_000_000, tourism: 42_000_000 },
  io_surface:        { fabrication: 54_000_000, tourism: 54_000_000 },
  europa_surface:    { sensor: 54_000_000, tourism: 54_000_000 },
  ganymede_surface:  { compute: 54_000_000, tourism: 54_000_000 },
  callisto_surface:  { fabrication: 54_000_000, tourism: 54_000_000 },
  titan_surface:     { fabrication: 66_000_000, tourism: 66_000_000 },
  enceladus_surface: { sensor: 66_000_000, tourism: 66_000_000 },
  titania_surface:   { compute: 66_000_000, tourism: 66_000_000 },
  triton_surface:    { fabrication: 78_000_000, tourism: 78_000_000 },
  pluto_surface:     { compute: 78_000_000, tourism: 78_000_000 },
};

/** Fallback floor per category when a location has no authored entry (future
 *  locations / colony-era additions never fall back to infinite demand). */
export const DEFAULT_FLOOR_BY_CATEGORY: Record<ServiceCategory, number> = {
  launch: 25_000_000, telecom: 20_000_000, sensor: 15_000_000, compute: 20_000_000,
  power: 8_000_000, tourism: 30_000_000, logistics: 15_000_000, fabrication: 20_000_000,
  insurance: 8_000_000,
};

/** Authored full-backdrop floor (unscaled) for a market. */
export function getNpcFloorBase(locationId: string, category: ServiceCategory): number {
  const loc = NPC_DEMAND_FLOOR[locationId];
  if (loc) {
    const v = loc[category];
    if (typeof v === 'number') return v;
    // Authored location with an omitted category = a genuinely tiny market
    // there, not an accident — 20% of the category default keeps it finite
    // but never zero (a zero pool would hard-brick a service the player can
    // legitimately run there).
    return Math.round(DEFAULT_FLOOR_BY_CATEGORY[category] * 0.2);
  }
  return DEFAULT_FLOOR_BY_CATEGORY[category];
}

/** §2.9 dynamic scaling: full backdrop below 50 30-day actives, ~40% at 500,
 *  ~10% at 5,000, hard floor 10% (the "3 NPCs always" invariant — the
 *  backdrop never disappears entirely). Log-linear between anchor points. */
export function npcPopulationScaler(active30d: number): number {
  const a = Math.max(0, active30d);
  if (a <= 50) return 1;
  const lg = Math.log10(a);
  if (a <= 500) {
    // log10: 50→1.699, 500→2.699; scale 1 → 0.4
    return 1 - (lg - Math.log10(50)) * (1 - 0.4);
  }
  if (a <= 5000) {
    // 500→2.699, 5000→3.699; scale 0.4 → 0.1
    return 0.4 - (lg - Math.log10(500)) * (0.4 - 0.1);
  }
  return 0.1;
}

/** Scaled NPC floor demand for a market. */
export function getNpcFloorDemand(locationId: string, category: ServiceCategory, active30d: number): number {
  return getNpcFloorBase(locationId, category) * npcPopulationScaler(active30d);
}

// ─── NPC supply into the pools (§E4 item 4) ─────────────────────────────────
// NPCs SUPPLY each market at a fixed fraction of the (scaled) floor demand
// they generate — so an empty server is always modestly UNDERSUPPLIED:
// prices feel alive, and a first mover always sees the scarcity premium,
// never NPC-caused saturation. CI invariant (demand-pools.test.ts): an
// NPC-only market's multiplier is always in [1.0, DEMAND_PREMIUM_CAP] —
// NPCs are a floor, never a ceiling. NPC supply rides the SAME population
// scaler, so it recedes exactly as fast as the demand it backstops.

export const NPC_SUPPLY_FRACTION = 0.5;

export function getNpcSupplyCapacity(locationId: string, category: ServiceCategory, active30d: number): number {
  return getNpcFloorBase(locationId, category) * NPC_SUPPLY_FRACTION * npcPopulationScaler(active30d);
}

// ─── D_mod: season super-cycle → service-category demand bias ───────────────
// economic-seasons.ts's announced commodity super-cycle finally touches
// service revenue (§2.1 D_mod). Mapped per theme, bounded ±15% — half the
// commodity band, because pools gate INCOME directly. Deterministic from the
// season number (getSuperCycleForSeason is seeded), so the server cron, the
// sync route, and the offline client all compute the identical modifier.

export const SEASON_DEMAND_MOD_MIN = 0.85;
export const SEASON_DEMAND_MOD_MAX = 1.15;

const THEME_CATEGORY_BIAS: Record<string, Partial<Record<ServiceCategory, number>>> = {
  volatiles_boom:       { launch: 0.10, logistics: 0.15, tourism: -0.05 },
  metals_squeeze:       { fabrication: 0.15, logistics: 0.10 },
  precious_rally:       { insurance: 0.10, tourism: 0.10, compute: 0.05 },
  rare_earth_crunch:    { compute: 0.15, sensor: 0.10 },
  exotic_frontier_surge: { sensor: 0.10, compute: 0.10, launch: 0.05 },
  belt_glut:            { logistics: 0.10, fabrication: -0.05, launch: -0.05 },
};

export function getDemandPoolSeasonModifier(category: ServiceCategory, seasonNumber: number): number {
  const theme = getSuperCycleForSeason(seasonNumber);
  const bias = THEME_CATEGORY_BIAS[theme.id]?.[category] ?? 0;
  return Math.max(SEASON_DEMAND_MOD_MIN, Math.min(SEASON_DEMAND_MOD_MAX, 1 + bias));
}

// ─── D_derived: demand from real activity at a location (§2.1, rebased M3/F6) ─
// Authored $/month contributions per unit of activity. Shared verbatim by
// the server cron (summed across all synced profiles) and the client's
// deterministic local fallback (own state only) — one derivation, two data
// sources, which is the whole determinism story.
//
// M3/F6 rebase (docs/MEANINGFUL_2026-08.md §M3): pre-M3 this was a FLAT
// dollar constant per building regardless of the building's own scale — a
// $3.5M-capacity LEO sat and a $160M-capacity Titan hydrocarbon rig
// contributed the IDENTICAL $500K of power demand. Player capacity grew
// ~17x faster than player-derived demand as the server's population and
// building count scaled up (F6: "a LEO telecom sat adds $0.2M/mo of derived
// telecom demand but $3.5M of capacity, 5.7%"), sliding every market toward
// the 0.35 floor exactly as the game succeeds — the macro curve punished
// MAU growth. `addGrossSpreadDemand` below fixes this structurally: a
// building's generic derived-demand contribution is now a PERCENTAGE
// (`DERIVED_DEMAND_GROSS_SHARE`) of its OWN service gross (revenuePerMonth,
// summed across its enabledServices) spread across every OTHER category —
// never its own ("a datacenter demands power/logistics/insurance, never its
// own compute") — so aggregate demand grows with real economic activity
// (population × buildings × their own scale) instead of a per-building head
// count alone. mining_output buildings own no demand-pool category, so their
// (often very large) gross spreads across all five generic categories —
// exactly the "demand grows with the economy" the finding calls for from
// the vertical that was otherwise fully exempt from the pool system.

/** Share of a building's own service gross spread as derived demand into
 *  OTHER categories, per month. Spec range 25-35%; 30% is the midpoint. */
export const DERIVED_DEMAND_GROSS_SHARE = 0.30;

/** Relative weights for the generic gross-spread categories — renormalized
 *  at read time over whichever of these the building does NOT itself supply
 *  (so e.g. a telecom sat's contribution is fully redistributed among
 *  power/logistics/compute/launch, never diluted just because it owns one
 *  of the five weighted categories). */
const GENERIC_SPREAD_WEIGHTS: Partial<Record<ServiceCategory, number>> = {
  power: 0.30, telecom: 0.20, logistics: 0.20, compute: 0.15, launch: 0.15,
};

export const DERIVED_DEMAND_RATES = {
  /** Crewed stations/habitats add tourism traffic, crew comms, and hull
   *  underwriting demand — scaled by building TIER as a headcount proxy
   *  (the save doesn't track per-location crew occupancy; tier is the
   *  closest static "how big is this station" signal a T4 Jovian station
   *  houses far more people than a T1 orbital outpost, so its demand
   *  footprint should too). M3/F6: "crew-headcount demand... the most
   *  organic demand curve in the game" per ECONOMY_PVP §3.1E — this finally
   *  scales with the building generating it instead of a flat per-building
   *  constant. */
  perCrewedBuilding: { tourism: 1_500_000, telecom: 400_000, insurance: 300_000 } as Partial<Record<ServiceCategory, number>>,
  /** Launch pads generate ADDITIONAL propellant/logistics traffic beyond
   *  the generic gross-spread every building already contributes. */
  perLaunchPad: { logistics: 500_000 } as Partial<Record<ServiceCategory, number>>,
  /** Datacenters are power-hungry beyond the generic gross-spread. */
  perDatacenter: { power: 1_000_000 } as Partial<Record<ServiceCategory, number>>,
  /** A ship at a location means launches, transfers, and freight handling. */
  perShip: { launch: 400_000, logistics: 500_000 } as Partial<Record<ServiceCategory, number>>,
  /** Every operating service buys insurance. */
  perServiceInstance: { insurance: 150_000 } as Partial<Record<ServiceCategory, number>>,
};

/** Building categories that count as crewed for derived demand. */
const CREWED_BUILDING_CATEGORIES = new Set(['space_station']);

export interface ActivityBuilding { definitionId: string; locationId: string; isComplete?: boolean; category?: string }
export interface ActivityService { definitionId: string; locationId: string }
export interface ActivityShip { currentLocation?: string | null }

export interface ProfileActivitySummary {
  id: string;
  buildings: ActivityBuilding[];
  services: ActivityService[];
  ships: ActivityShip[];
}

function addDemand(
  out: Map<string, number>,
  locationId: string,
  rates: Partial<Record<ServiceCategory, number>>,
  mult = 1,
): void {
  for (const [cat, v] of Object.entries(rates)) {
    if (!v) continue;
    const key = demandPoolKey(locationId, cat as ServiceCategory);
    out.set(key, (out.get(key) || 0) + v * mult);
  }
}

function buildingCategory(b: ActivityBuilding): string | undefined {
  if (b.category) return b.category;
  return BUILDING_MAP.get(b.definitionId)?.category;
}

/** A building's own service gross ($/mo, summed across enabledServices) and
 *  the set of demand-pool categories that gross belongs to — the categories
 *  the generic gross-spread must never feed back into. */
function ownGrossAndCategories(definitionId: string): { gross: number; categories: Set<ServiceCategory> } {
  const bDef = BUILDING_MAP.get(definitionId);
  let gross = 0;
  const categories = new Set<ServiceCategory>();
  if (bDef) {
    for (const svcId of bDef.enabledServices) {
      const sDef = SERVICE_MAP.get(svcId);
      if (!sDef) continue;
      gross += sDef.revenuePerMonth;
      const cat = getServiceCategory(svcId);
      if (cat) categories.add(cat);
    }
  }
  return { gross, categories };
}

/** Generic gross-spread demand for one building: `DERIVED_DEMAND_GROSS_SHARE`
 *  of its own service gross, distributed across every category it does NOT
 *  itself supply, weighted by `GENERIC_SPREAD_WEIGHTS` (renormalized over
 *  the eligible categories). */
function addGrossSpreadDemand(out: Map<string, number>, locationId: string, definitionId: string): void {
  const { gross, categories } = ownGrossAndCategories(definitionId);
  if (gross <= 0) return;
  let eligibleWeight = 0;
  for (const [cat, w] of Object.entries(GENERIC_SPREAD_WEIGHTS)) {
    if (!categories.has(cat as ServiceCategory)) eligibleWeight += w as number;
  }
  if (eligibleWeight <= 0) return;
  const totalSpread = gross * DERIVED_DEMAND_GROSS_SHARE;
  for (const [cat, w] of Object.entries(GENERIC_SPREAD_WEIGHTS)) {
    if (categories.has(cat as ServiceCategory)) continue;
    const key = demandPoolKey(locationId, cat as ServiceCategory);
    out.set(key, (out.get(key) || 0) + totalSpread * ((w as number) / eligibleWeight));
  }
}

/** Derived demand (Map<poolKey, $/month>) generated by ONE actor's activity.
 *  Pure — same summary in, same map out. */
export function deriveActivityDemand(summary: ProfileActivitySummary): Map<string, number> {
  const out = new Map<string, number>();
  for (const b of summary.buildings) {
    if (b.isComplete === false) continue;
    if (!b.locationId || !LOCATION_MAP.has(b.locationId)) continue;
    addGrossSpreadDemand(out, b.locationId, b.definitionId);
    const cat = buildingCategory(b);
    if (cat && CREWED_BUILDING_CATEGORIES.has(cat)) {
      const tier = Math.max(1, BUILDING_MAP.get(b.definitionId)?.tier || 1);
      addDemand(out, b.locationId, DERIVED_DEMAND_RATES.perCrewedBuilding, tier);
    }
    if (cat === 'launch_pad') addDemand(out, b.locationId, DERIVED_DEMAND_RATES.perLaunchPad);
    if (cat === 'datacenter') addDemand(out, b.locationId, DERIVED_DEMAND_RATES.perDatacenter);
  }
  for (const s of summary.ships) {
    if (s.currentLocation && LOCATION_MAP.has(s.currentLocation)) {
      addDemand(out, s.currentLocation, DERIVED_DEMAND_RATES.perShip);
    }
  }
  for (const svc of summary.services) {
    if (svc.locationId && LOCATION_MAP.has(svc.locationId)) {
      addDemand(out, svc.locationId, DERIVED_DEMAND_RATES.perServiceInstance);
    }
  }
  return out;
}

// ─── Capacity (§2.1: the private multiplier stack becomes a capacity stack) ─
// A supplier's effective capacity in a market is the sum of their services'
// base revenuePerMonth × the existing WITHIN-player saturation curve (the
// 40th duplicate is still individually worse — the pool cap subsumes the old
// curve at market level, the per-instance curve stays as the within-player
// discipline). Server-side we deliberately stop at the base stack: quality
// multipliers are private and client-claimed, and a capacity share biased by
// unverifiable multipliers would let a forged save steal pool share. Base
// revenue × saturation is verifiable from the synced service list alone.

export function computeCapacityByMarket(services: ActivityService[]): Map<string, number> {
  const out = new Map<string, number>();
  const buckets = new Map<string, number>();
  for (const svc of services) {
    const def = SERVICE_MAP.get(svc.definitionId);
    if (!def || !svc.locationId) continue;
    const category = getServiceCategory(svc.definitionId);
    if (!category) continue; // mining_output — §2.4 handles it
    const bucketKey = `${svc.definitionId}@${svc.locationId}`;
    const position = buckets.get(bucketKey) || 0;
    buckets.set(bucketKey, position + 1);
    const key = demandPoolKey(svc.locationId, category);
    out.set(key, (out.get(key) || 0) + def.revenuePerMonth * serviceSaturationMultiplier(position));
  }
  return out;
}

// ─── Server aggregation (the hourly cron's pure core) ───────────────────────

export interface PoolAggregate {
  locationId: string;
  category: ServiceCategory;
  /** Scaled NPC floor demand ($/mo). */
  dNpc: number;
  /** Activity-derived demand across all profiles ($/mo). */
  dDerived: number;
  /** Total supplier capacity ($/mo) — players + NPC backdrop. */
  cSupply: number;
  /** Top-3 supplier capacity shares (fractions of cSupply), anonymized. */
  topShares: number[];
  /** Distinct suppliers with capacity in this market (NPC backdrop counts
   *  as one when it supplies). */
  supplierCount: number;
}

/**
 * Aggregate every profile's activity into per-market pools. Pure and
 * deterministic: same profiles + active count in, same aggregates out
 * (tested). The cron feeds real GameProfile rows; tests feed fixtures.
 *
 * Markets included: every (location, category) with an authored floor, plus
 * any market where player activity created demand or capacity.
 */
export function computePoolAggregates(
  profiles: ProfileActivitySummary[],
  active30d: number,
): Map<string, PoolAggregate> {
  const derived = new Map<string, number>();
  const capacityBySupplier = new Map<string, Map<string, number>>(); // key → supplierId → capacity

  for (const p of profiles) {
    deriveActivityDemand(p).forEach((v, key) => {
      derived.set(key, (derived.get(key) || 0) + v);
    });
    computeCapacityByMarket(p.services).forEach((cap, key) => {
      let m = capacityBySupplier.get(key);
      if (!m) { m = new Map(); capacityBySupplier.set(key, m); }
      m.set(p.id, (m.get(p.id) || 0) + cap);
    });
  }

  // Universe of markets: authored floors ∪ observed activity.
  const keys = new Set<string>();
  for (const locationId of Object.keys(NPC_DEMAND_FLOOR)) {
    for (const cat of Object.keys(NPC_DEMAND_FLOOR[locationId] || {})) {
      keys.add(demandPoolKey(locationId, cat as ServiceCategory));
    }
  }
  derived.forEach((_v, k) => keys.add(k));
  capacityBySupplier.forEach((_v, k) => keys.add(k));

  const out = new Map<string, PoolAggregate>();
  keys.forEach(key => {
    const sep = key.indexOf(':');
    const locationId = key.slice(0, sep);
    const category = key.slice(sep + 1) as ServiceCategory;
    if (!SERVICE_CATEGORIES.includes(category)) return;

    const dNpc = getNpcFloorDemand(locationId, category, active30d);
    const npcSupply = getNpcSupplyCapacity(locationId, category, active30d);
    const suppliers = capacityBySupplier.get(key) || new Map<string, number>();
    const caps: number[] = Array.from(suppliers.values());
    if (npcSupply > 0) caps.push(npcSupply);
    const cSupply = caps.reduce((a, b) => a + b, 0);
    const topShares = cSupply > 0
      ? caps.map(c => Math.round((c / cSupply) * 1000) / 1000).sort((a, b) => b - a).slice(0, 3)
      : [];

    out.set(key, {
      locationId, category,
      dNpc: Math.round(dNpc),
      dDerived: Math.round(derived.get(key) || 0),
      cSupply: Math.round(cSupply),
      topShares,
      supplierCount: caps.length,
    });
  });
  return out;
}

// ─── EMA smoothing (§2.1: "7-day EMA so pools shift on the daily loop") ─────
// The cron runs hourly; a 7-day (168-sample) EMA gives alpha ≈ 0.0118 — a
// rival standing up a new constellation moves your pool over days, never a
// tick-to-tick whipsaw (SESSION_DESIGN: don't collapse the tempo).

export const DEMAND_POOL_EMA_ALPHA = 2 / (168 + 1);

export function emaBlend(prev: number | null | undefined, raw: number, alpha: number = DEMAND_POOL_EMA_ALPHA): number {
  if (prev === null || prev === undefined || !Number.isFinite(prev)) return raw;
  return prev + alpha * (raw - prev);
}

// ─── The sync-down snapshot (delivered like marketSnapshot) ─────────────────

export interface DemandPoolEntry {
  locationId: string;
  category: ServiceCategory;
  /** Pool multiplier, clamped [0.35, 1.25] server-side before send. */
  mult: number;
  /** Total pool demand ($/mo) after the season modifier. */
  dTotal: number;
  /** NPC floor component ($/mo, scaled) — shown so the pool's inputs are
   *  transparent (§7 "pools shown in the P&L panel WITH their inputs"). */
  dNpc: number;
  /** Total supplier capacity ($/mo), NPC backdrop included. */
  cSupply: number;
  /** This player's capacity share of the market, 0..1. */
  playerShare: number;
  /** Previous snapshot's playerShare — stamped client-side when a new
   *  snapshot is applied (server-effects.ts), so the Situation Log can flag
   *  "competitor undercutting at X" on real share drops. */
  prevPlayerShare?: number;
  /** Top-3 supplier shares, anonymized fractions (intel canon: aggregate is
   *  free; named deep detail stays earned via espionage/paid intel). */
  topShares: number[];
  supplierCount: number;
}

export interface DemandPoolSnapshot {
  pools: Record<string, DemandPoolEntry>;
  asOf: number;
}

/** Snapshot older than this degrades to the deterministic local pool —
 *  offline players tick against their last snapshot, staleness-capped. */
export const DEMAND_POOL_STALE_MS = 7 * 24 * 60 * 60 * 1000;

/** Row shape the server reads from LocationDemandPool (or tests fabricate). */
export interface DemandPoolRow {
  locationId: string;
  category: string;
  dNpc: number;
  dDerived: number;
  cSupply: number;
  topShares?: unknown;
  supplierCount?: number;
}

// NOTE: buildDemandPoolSnapshot (rows → sync-down snapshot) lives in
// service-pricing.ts — it needs the pool-share calculator and that module
// already imports this one (no cycle).

// ─── Phase-in (§E4 [SAVE], mirrors E3's 25%→100% over 3 game-months) ────────

export const DEMAND_POOL_PHASE_IN_MONTHS = 3;
export const DEMAND_POOL_PHASE_IN_START = 0.25;

/** Fraction of the pool effect applied at a world month. Null anchor = full
 *  effect (fresh games — pools are not a migration penalty, and new corps
 *  are Frontier-shielded anyway). */
export function getDemandPoolPhaseInFraction(
  phaseInStartMonth: number | null | undefined,
  monthIndex: number,
): number {
  if (phaseInStartMonth === null || phaseInStartMonth === undefined) return 1;
  const monthsIn = monthIndex - phaseInStartMonth;
  if (monthsIn >= DEMAND_POOL_PHASE_IN_MONTHS) return 1;
  if (monthsIn < 0) return DEMAND_POOL_PHASE_IN_START;
  const step = (1 - DEMAND_POOL_PHASE_IN_START) / DEMAND_POOL_PHASE_IN_MONTHS;
  return Math.min(1, DEMAND_POOL_PHASE_IN_START + step * monthsIn);
}

/** gameDate → month index in the STARTING_YEAR/Jan-anchored convention shared
 *  by expeditions.getTotalGameMonths and server-time totalMonths. */
export function gameDateToMonthIndex(gameDate: { year: number; month: number }): number {
  return (gameDate.year - GAME_START_YEAR) * 12 + (gameDate.month - 1);
}
