// ─── Space Tycoon: Modular Construction System ──────────────────────────────
//
// Starbases, space stations, and planetary colonies are no longer monolithic
// buildings. They start as a core hull and are expanded by attaching MODULES.
//
// Each module is a crafted production-chain item (station_module, habitat_pod,
// etc.) that provides specific capabilities when installed.
//
// DESIGN:
// 1. Build core structure (hull) — provides basic functionality
// 2. Attach modules to add capabilities (housing, power, labs, docks)
// 3. Each module type provides different bonuses
// 4. Module slots are limited by hull size (small=4, medium=8, large=16)
// 5. Modules require crafted components — creates demand for production chains
// 6. Modules can be swapped out (lost module, not destroyed)
// 7. Different module combos create different station "specializations"
//
// This integrates with the production chain system — station_module and
// habitat_pod are already craftable items. Now they have a USE.

// ─── Module Definitions ──────────────────────────────────────────────────────

export interface ModuleDefinition {
  id: string;
  name: string;
  icon: string;
  description: string;
  category: ModuleCategory;
  tier: number;
  // What crafted item is consumed to install this module
  requiredItem: string; // ID from production-chains.ts (e.g. 'station_module')
  requiredItemQuantity: number;
  // Additional resource costs for installation
  installCost: number; // Money
  installResources: Record<string, number>;
  installTimeSeconds: number; // Real-time seconds to install
  // What this module provides
  bonuses: {
    populationCapacity?: number;   // How many people this module houses
    revenueBoost?: number;         // +X% revenue for the station/colony
    miningBoost?: number;          // +X% mining output at this location
    researchSpeed?: number;        // +X% research speed
    shipCapacity?: number;         // +X ship docking slots
    defenseRating?: number;        // +X defense against contests
    storageCapacity?: number;      // +X resource storage slots
    powerGeneration?: number;      // +X power units (some modules need power)
    maintenanceReduction?: number; // -X% maintenance cost
  };
  powerCost: number; // Power units consumed (0 = generates power)
  maintenancePerMonth: number; // Monthly upkeep
}

export type ModuleCategory =
  | 'habitation'    // Living quarters, life support
  | 'power'         // Solar arrays, reactors
  | 'science'       // Labs, observatories
  | 'industry'      // Fabrication, refining
  | 'defense'       // Shields, weapons, armor
  | 'docking'       // Ship berths, cargo handling
  | 'storage'       // Resource tanks, warehouses
  | 'communications' // Relay arrays, data centers
  | 'recreation'    // Tourism, morale
  | 'command';      // Bridge, control center

// ─── Station/Colony Hull Types ───────────────────────────────────────────────

export interface HullDefinition {
  id: string;
  name: string;
  icon: string;
  description: string;
  hullType: 'orbital_station' | 'planetary_colony' | 'starbase' | 'outpost';
  tier: number;
  maxModuleSlots: number;
  baseCost: number;
  baseResources: Record<string, number>;
  baseBuildTimeSeconds: number;
  requiredResearch: string[];
  requiredLocation: string[]; // Which locations this hull can be placed
  // Base capabilities (before modules)
  basePower: number;          // Power generated by core reactor
  basePopulation: number;     // Crew the hull can house without hab modules
  baseDefense: number;        // Defense rating of bare hull
  maintenancePerMonth: number;
}

export const HULL_DEFINITIONS: HullDefinition[] = [
  // ─── ORBITAL STATIONS ──────────────────────────────────────────────

  {
    id: 'hull_outpost',
    name: 'Orbital Outpost Hull',
    icon: '🛰️',
    description: 'Small orbital platform. 4 module slots. Good starting station.',
    hullType: 'orbital_station', tier: 1, maxModuleSlots: 4,
    baseCost: 200_000_000, baseResources: { aluminum: 30, iron: 50 },
    baseBuildTimeSeconds: 600,
    requiredResearch: ['modular_spacecraft'],
    requiredLocation: ['leo', 'geo', 'lunar_orbit', 'mars_orbit'],
    basePower: 20, basePopulation: 4, baseDefense: 10,
    maintenancePerMonth: 2_000_000,
  },
  {
    id: 'hull_station',
    name: 'Space Station Hull',
    icon: '🏠',
    description: 'Medium orbital station. 8 module slots. Room to specialize.',
    hullType: 'orbital_station', tier: 2, maxModuleSlots: 8,
    baseCost: 1_000_000_000, baseResources: { aluminum: 80, titanium: 30, iron: 100 },
    baseBuildTimeSeconds: 1200,
    requiredResearch: ['modular_spacecraft', 'rotating_habitats'],
    requiredLocation: ['leo', 'geo', 'lunar_orbit', 'mars_orbit', 'jupiter_system', 'saturn_system'],
    basePower: 40, basePopulation: 8, baseDefense: 20,
    maintenancePerMonth: 5_000_000,
  },
  {
    id: 'hull_megastation',
    name: 'Mega-Station Hull',
    icon: '🏗️',
    description: 'Massive orbital complex. 16 module slots. A city in space.',
    hullType: 'orbital_station', tier: 3, maxModuleSlots: 16,
    baseCost: 10_000_000_000, baseResources: { aluminum: 200, titanium: 80, rare_earth: 30, iron: 300 },
    baseBuildTimeSeconds: 3600,
    requiredResearch: ['mega_structures'],
    requiredLocation: ['leo', 'lunar_orbit', 'mars_orbit', 'jupiter_system'],
    basePower: 80, basePopulation: 16, baseDefense: 40,
    maintenancePerMonth: 15_000_000,
  },

  // ─── PLANETARY COLONIES ────────────────────────────────────────────

  {
    id: 'hull_basecamp',
    name: 'Colony Basecamp',
    icon: '⛺',
    description: 'Surface outpost with pressure dome. 4 module slots.',
    hullType: 'planetary_colony', tier: 1, maxModuleSlots: 4,
    baseCost: 500_000_000, baseResources: { aluminum: 40, iron: 60, titanium: 15 },
    baseBuildTimeSeconds: 900,
    requiredResearch: ['modular_spacecraft', 'resource_prospecting'],
    requiredLocation: ['lunar_surface', 'mars_surface', 'ceres_surface'],
    basePower: 15, basePopulation: 6, baseDefense: 15,
    maintenancePerMonth: 3_000_000,
  },
  {
    id: 'hull_colony',
    name: 'Planetary Colony',
    icon: '🏘️',
    description: 'Full surface colony with interconnected domes. 10 module slots.',
    hullType: 'planetary_colony', tier: 2, maxModuleSlots: 10,
    baseCost: 5_000_000_000, baseResources: { aluminum: 120, titanium: 50, iron: 200, rare_earth: 15 },
    baseBuildTimeSeconds: 2400,
    requiredResearch: ['rotating_habitats', 'resource_prospecting'],
    requiredLocation: ['lunar_surface', 'mars_surface', 'ceres_surface', 'mercury_surface', 'ganymede_surface', 'callisto_surface', 'titan_surface'],
    basePower: 40, basePopulation: 20, baseDefense: 30,
    maintenancePerMonth: 8_000_000,
  },
  {
    id: 'hull_megacolony',
    name: 'Mega-Colony Complex',
    icon: '🌆',
    description: 'Sprawling surface settlement. 20 module slots. A new civilization.',
    hullType: 'planetary_colony', tier: 3, maxModuleSlots: 20,
    baseCost: 50_000_000_000, baseResources: { aluminum: 300, titanium: 150, iron: 500, rare_earth: 50, exotic_materials: 10 },
    baseBuildTimeSeconds: 7200,
    requiredResearch: ['mega_structures'],
    requiredLocation: ['mars_surface', 'titan_surface', 'ganymede_surface'],
    basePower: 100, basePopulation: 50, baseDefense: 60,
    maintenancePerMonth: 25_000_000,
  },

  // ─── ALLIANCE STARBASES ─────────────────────────────────────────────

  {
    id: 'hull_starbase',
    name: 'Alliance Starbase Hull',
    icon: '⭐',
    description: 'Massive alliance-owned orbital fortress. 24 module slots. Requires alliance funding.',
    hullType: 'starbase', tier: 4, maxModuleSlots: 24,
    baseCost: 50_000_000_000, baseResources: { titanium: 500, aluminum: 800, iron: 1000, rare_earth: 200, exotic_materials: 20 },
    baseBuildTimeSeconds: 14400,
    requiredResearch: ['mega_structures'],
    requiredLocation: ['leo', 'lunar_orbit', 'mars_orbit', 'asteroid_belt', 'jupiter_system', 'ceres_surface'],
    basePower: 200, basePopulation: 100, baseDefense: 100,
    maintenancePerMonth: 25_000_000,
  },

  // ─── FRONTIER OUTPOSTS ──────────────────────────────────────────────

  {
    id: 'hull_frontier',
    name: 'Frontier Outpost',
    icon: '🏕️',
    description: 'Minimal deep-space outpost. 3 module slots. For the brave.',
    hullType: 'outpost', tier: 1, maxModuleSlots: 3,
    baseCost: 2_000_000_000, baseResources: { titanium: 40, aluminum: 60, exotic_materials: 3 },
    baseBuildTimeSeconds: 1800,
    requiredResearch: ['nuclear_thermal'],
    requiredLocation: ['io_surface', 'europa_surface', 'enceladus_surface', 'titania_surface', 'triton_surface', 'pluto_surface'],
    basePower: 10, basePopulation: 3, baseDefense: 5,
    maintenancePerMonth: 5_000_000,
  },
];

// ─── Module Definitions ──────────────────────────────────────────────────────

export const MODULE_DEFINITIONS: ModuleDefinition[] = [
  // ─── HABITATION ────────────────────────────────────────────────────

  {
    id: 'mod_crew_quarters',
    name: 'Crew Quarters',
    icon: '🛏️',
    description: 'Standard crew living space. Houses 10 additional personnel.',
    category: 'habitation', tier: 1,
    requiredItem: 'habitat_pod', requiredItemQuantity: 1,
    installCost: 50_000_000, installResources: { aluminum: 10 },
    installTimeSeconds: 300,
    bonuses: { populationCapacity: 10 },
    powerCost: 5, maintenancePerMonth: 500_000,
  },
  {
    id: 'mod_luxury_quarters',
    name: 'Luxury Quarters',
    icon: '🏨',
    description: 'Premium living space for tourists and VIPs. +15% tourism revenue.',
    category: 'habitation', tier: 2,
    requiredItem: 'habitat_pod', requiredItemQuantity: 2,
    installCost: 200_000_000, installResources: { aluminum: 20, gold: 2 },
    installTimeSeconds: 600,
    bonuses: { populationCapacity: 5, revenueBoost: 0.15 },
    powerCost: 8, maintenancePerMonth: 2_000_000,
  },
  {
    id: 'mod_biosphere',
    name: 'Biosphere Dome',
    icon: '🌿',
    description: 'Self-sustaining ecosystem. Reduces life support costs by 20%.',
    category: 'habitation', tier: 3,
    requiredItem: 'habitat_pod', requiredItemQuantity: 3,
    installCost: 500_000_000, installResources: { lunar_water: 100, organic_compounds: 10 },
    installTimeSeconds: 1200,
    bonuses: { populationCapacity: 15, maintenanceReduction: 0.20 },
    powerCost: 10, maintenancePerMonth: 1_000_000,
  },

  // ─── POWER ─────────────────────────────────────────────────────────

  {
    id: 'mod_solar_array',
    name: 'Deployable Solar Array',
    icon: '☀️',
    description: 'Extends power generation capacity.',
    category: 'power', tier: 1,
    requiredItem: 'solar_panel_array', requiredItemQuantity: 3,
    installCost: 30_000_000, installResources: {},
    installTimeSeconds: 180,
    bonuses: { powerGeneration: 20 },
    powerCost: 0, maintenancePerMonth: 200_000,
  },
  {
    id: 'mod_fission_reactor',
    name: 'Compact Fission Reactor',
    icon: '⚛️',
    description: 'Nuclear power for deep-space stations. High output, low maintenance.',
    category: 'power', tier: 2,
    requiredItem: 'electronics_package', requiredItemQuantity: 2,
    installCost: 300_000_000, installResources: { titanium: 20, rare_earth: 10 },
    installTimeSeconds: 600,
    bonuses: { powerGeneration: 50 },
    powerCost: 0, maintenancePerMonth: 500_000,
  },
  {
    id: 'mod_fusion_reactor',
    name: 'Fusion Reactor Module',
    icon: '🔮',
    description: 'Helium-3 fusion power. Enormous output. Endgame power source.',
    category: 'power', tier: 3,
    requiredItem: 'fusion_core', requiredItemQuantity: 1,
    installCost: 2_000_000_000, installResources: { helium3: 5, deuterium: 3 },
    installTimeSeconds: 1800,
    bonuses: { powerGeneration: 200 },
    powerCost: 0, maintenancePerMonth: 3_000_000,
  },

  // ─── SCIENCE ────────────────────────────────────────────────────────

  {
    id: 'mod_research_lab',
    name: 'Research Laboratory',
    icon: '🔬',
    description: 'Scientific research facility. +10% research speed.',
    category: 'science', tier: 1,
    requiredItem: 'electronics_package', requiredItemQuantity: 3,
    installCost: 100_000_000, installResources: { rare_earth: 5 },
    installTimeSeconds: 300,
    bonuses: { researchSpeed: 0.10 },
    powerCost: 10, maintenancePerMonth: 1_000_000,
  },
  {
    id: 'mod_quantum_lab',
    name: 'Quantum Research Lab',
    icon: '🧪',
    description: 'Advanced quantum computing lab. +25% research speed.',
    category: 'science', tier: 2,
    requiredItem: 'ai_compute_cluster', requiredItemQuantity: 2,
    installCost: 500_000_000, installResources: { exotic_materials: 3, rare_earth: 15 },
    installTimeSeconds: 900,
    bonuses: { researchSpeed: 0.25 },
    powerCost: 25, maintenancePerMonth: 3_000_000,
  },
  {
    id: 'mod_xenolab',
    name: 'Xenobiology Lab',
    icon: '🧬',
    description: 'Studies alien organisms. Produces bio samples when at Europa/Enceladus.',
    category: 'science', tier: 3,
    requiredItem: 'ai_compute_cluster', requiredItemQuantity: 3,
    installCost: 1_000_000_000, installResources: { bio_samples: 5, exotic_materials: 5 },
    installTimeSeconds: 1200,
    bonuses: { researchSpeed: 0.15, miningBoost: 0.30 },
    powerCost: 15, maintenancePerMonth: 5_000_000,
  },

  // ─── INDUSTRY ──────────────────────────────────────────────────────

  {
    id: 'mod_fabrication_bay',
    name: 'Fabrication Bay',
    icon: '🔧',
    description: 'In-station manufacturing. +15% fabrication revenue.',
    category: 'industry', tier: 1,
    requiredItem: 'station_module', requiredItemQuantity: 1,
    installCost: 150_000_000, installResources: { iron: 30, aluminum: 20 },
    installTimeSeconds: 300,
    bonuses: { revenueBoost: 0.15 },
    powerCost: 15, maintenancePerMonth: 1_500_000,
  },
  {
    id: 'mod_refinery',
    name: 'Ore Refinery Module',
    icon: '⚙️',
    description: 'Processes raw ore into refined metals. +20% mining output at this location.',
    category: 'industry', tier: 2,
    requiredItem: 'station_module', requiredItemQuantity: 2,
    installCost: 400_000_000, installResources: { titanium: 20, iron: 50 },
    installTimeSeconds: 600,
    bonuses: { miningBoost: 0.20 },
    powerCost: 20, maintenancePerMonth: 2_000_000,
  },

  // ─── DOCKING ───────────────────────────────────────────────────────

  {
    id: 'mod_docking_ring',
    name: 'Docking Ring',
    icon: '🔗',
    description: 'Additional ship berths. +5 docking capacity.',
    category: 'docking', tier: 1,
    requiredItem: 'structural_beams', requiredItemQuantity: 5,
    installCost: 80_000_000, installResources: { aluminum: 15 },
    installTimeSeconds: 240,
    bonuses: { shipCapacity: 5 },
    powerCost: 3, maintenancePerMonth: 300_000,
  },
  {
    id: 'mod_shipyard',
    name: 'Shipyard Bay',
    icon: '🚢',
    description: 'Build and repair ships at this station. +10 docking, +10% ship build speed.',
    category: 'docking', tier: 2,
    requiredItem: 'station_module', requiredItemQuantity: 2,
    installCost: 600_000_000, installResources: { titanium: 30, aluminum: 40 },
    installTimeSeconds: 900,
    bonuses: { shipCapacity: 10, revenueBoost: 0.10 },
    powerCost: 15, maintenancePerMonth: 3_000_000,
  },

  // ─── DEFENSE ───────────────────────────────────────────────────────

  {
    id: 'mod_armor_plating',
    name: 'Armor Plating',
    icon: '🛡️',
    description: 'Reinforced hull. +20 defense rating.',
    category: 'defense', tier: 1,
    requiredItem: 'structural_beams', requiredItemQuantity: 8,
    installCost: 100_000_000, installResources: { titanium: 15, iron: 40 },
    installTimeSeconds: 300,
    bonuses: { defenseRating: 20 },
    powerCost: 0, maintenancePerMonth: 500_000,
  },
  {
    id: 'mod_shield_generator',
    name: 'Shield Generator',
    icon: '💠',
    description: 'Energy shield system. +50 defense rating. Power-hungry.',
    category: 'defense', tier: 2,
    requiredItem: 'electronics_package', requiredItemQuantity: 4,
    installCost: 500_000_000, installResources: { exotic_materials: 3, rare_earth: 20 },
    installTimeSeconds: 900,
    bonuses: { defenseRating: 50 },
    powerCost: 40, maintenancePerMonth: 3_000_000,
  },

  // ─── STORAGE ───────────────────────────────────────────────────────

  {
    id: 'mod_cargo_hold',
    name: 'Cargo Hold',
    icon: '📦',
    description: 'Bulk storage for resources. +500 storage capacity.',
    category: 'storage', tier: 1,
    requiredItem: 'structural_beams', requiredItemQuantity: 4,
    installCost: 50_000_000, installResources: { iron: 20 },
    installTimeSeconds: 180,
    bonuses: { storageCapacity: 500 },
    powerCost: 2, maintenancePerMonth: 200_000,
  },
  {
    id: 'mod_cryo_vault',
    name: 'Cryogenic Vault',
    icon: '❄️',
    description: 'Cold storage for perishable resources. Prevents decay. +200 storage.',
    category: 'storage', tier: 2,
    requiredItem: 'station_module', requiredItemQuantity: 1,
    installCost: 200_000_000, installResources: { titanium: 10, lunar_water: 30 },
    installTimeSeconds: 300,
    bonuses: { storageCapacity: 200 },
    powerCost: 8, maintenancePerMonth: 800_000,
  },

  // ─── COMMUNICATIONS ────────────────────────────────────────────────

  {
    id: 'mod_relay_array',
    name: 'Comm Relay Array',
    icon: '📡',
    description: 'Deep-space communication relay. +10% revenue from data services.',
    category: 'communications', tier: 1,
    requiredItem: 'electronics_package', requiredItemQuantity: 2,
    installCost: 100_000_000, installResources: { rare_earth: 5 },
    installTimeSeconds: 240,
    bonuses: { revenueBoost: 0.10 },
    powerCost: 5, maintenancePerMonth: 500_000,
  },

  // ─── RECREATION ────────────────────────────────────────────────────

  {
    id: 'mod_observation_deck',
    name: 'Observation Deck',
    icon: '🔭',
    description: 'Panoramic viewing area. +20% tourism revenue.',
    category: 'recreation', tier: 1,
    requiredItem: 'station_module', requiredItemQuantity: 1,
    installCost: 80_000_000, installResources: { aluminum: 10 },
    installTimeSeconds: 240,
    bonuses: { revenueBoost: 0.20, populationCapacity: 5 },
    powerCost: 3, maintenancePerMonth: 400_000,
  },

  // ─── COMMAND ───────────────────────────────────────────────────────

  {
    id: 'mod_command_center',
    name: 'Command Center',
    icon: '🎯',
    description: 'Advanced ops center. -10% maintenance for entire station.',
    category: 'command', tier: 1,
    requiredItem: 'electronics_package', requiredItemQuantity: 3,
    installCost: 200_000_000, installResources: { rare_earth: 8 },
    installTimeSeconds: 300,
    bonuses: { maintenanceReduction: 0.10, defenseRating: 10 },
    powerCost: 8, maintenancePerMonth: 1_000_000,
  },
];

// ─── Module Instance (tracked per station/colony) ────────────────────────────

export interface InstalledModule {
  moduleId: string;
  installedAtMs: number;
  slotIndex: number; // Which slot it occupies (0 to maxModuleSlots-1)
}

// ─── Station/Colony Instance ─────────────────────────────────────────────────

export interface ModularStructure {
  instanceId: string;
  hullId: string;
  locationId: string;
  name: string; // Player-customizable name
  isBuilt: boolean;
  buildStartedAtMs: number;
  buildDurationSeconds: number;
  modules: InstalledModule[];
  healthPct: number; // 0-100
  totalPowerGenerated: number;
  totalPowerConsumed: number;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getHullDefinition(hullId: string): HullDefinition | undefined {
  return HULL_DEFINITIONS.find(h => h.id === hullId);
}

export function getModuleDefinition(moduleId: string): ModuleDefinition | undefined {
  return MODULE_DEFINITIONS.find(m => m.id === moduleId);
}

export function getAvailableSlots(structure: ModularStructure): number {
  const hull = getHullDefinition(structure.hullId);
  if (!hull) return 0;
  return hull.maxModuleSlots - structure.modules.length;
}

export function calculateStationBonuses(structure: ModularStructure): {
  totalPopulation: number;
  totalRevenue: number;
  totalMining: number;
  totalResearch: number;
  totalShipCapacity: number;
  totalDefense: number;
  totalStorage: number;
  totalPower: number;
  powerBalance: number;
  maintenanceReduction: number;
} {
  const hull = getHullDefinition(structure.hullId);
  if (!hull) return { totalPopulation: 0, totalRevenue: 0, totalMining: 0, totalResearch: 0, totalShipCapacity: 0, totalDefense: 0, totalStorage: 0, totalPower: 0, powerBalance: 0, maintenanceReduction: 0 };

  let pop = hull.basePopulation;
  let rev = 0, mine = 0, res = 0, ships = 0, def = hull.baseDefense, storage = 0;
  let powerGen = hull.basePower, powerUse = 0, maintRed = 0;

  for (const installed of structure.modules) {
    const mod = getModuleDefinition(installed.moduleId);
    if (!mod) continue;
    if (mod.bonuses.populationCapacity) pop += mod.bonuses.populationCapacity;
    if (mod.bonuses.revenueBoost) rev += mod.bonuses.revenueBoost;
    if (mod.bonuses.miningBoost) mine += mod.bonuses.miningBoost;
    if (mod.bonuses.researchSpeed) res += mod.bonuses.researchSpeed;
    if (mod.bonuses.shipCapacity) ships += mod.bonuses.shipCapacity;
    if (mod.bonuses.defenseRating) def += mod.bonuses.defenseRating;
    if (mod.bonuses.storageCapacity) storage += mod.bonuses.storageCapacity;
    if (mod.bonuses.powerGeneration) powerGen += mod.bonuses.powerGeneration;
    if (mod.bonuses.maintenanceReduction) maintRed += mod.bonuses.maintenanceReduction;
    powerUse += mod.powerCost;
  }

  return {
    totalPopulation: pop,
    totalRevenue: rev,
    totalMining: mine,
    totalResearch: res,
    totalShipCapacity: ships,
    totalDefense: def,
    totalStorage: storage,
    totalPower: powerGen,
    powerBalance: powerGen - powerUse,
    maintenanceReduction: Math.min(0.50, maintRed), // Cap at 50%
  };
}

/** Check if a module can be installed (has power, has slot, etc.) */
export function canInstallModule(
  structure: ModularStructure,
  moduleId: string,
): { canInstall: boolean; reason?: string } {
  const hull = getHullDefinition(structure.hullId);
  const mod = getModuleDefinition(moduleId);
  if (!hull) return { canInstall: false, reason: 'Invalid hull' };
  if (!mod) return { canInstall: false, reason: 'Invalid module' };

  // Check slot availability
  if (structure.modules.length >= hull.maxModuleSlots) {
    return { canInstall: false, reason: `No module slots available (${hull.maxModuleSlots}/${hull.maxModuleSlots} used)` };
  }

  // Check power balance
  const bonuses = calculateStationBonuses(structure);
  if (bonuses.powerBalance < mod.powerCost) {
    return { canInstall: false, reason: `Insufficient power (need ${mod.powerCost}, have ${bonuses.powerBalance} available). Install a power module first.` };
  }

  return { canInstall: true };
}

// ─── Station Specialization Profiles ─────────────────────────────────────────
// Pre-designed module configurations for common use cases.

export const SPECIALIZATION_PROFILES = [
  {
    name: 'Mining Station',
    icon: '⛏️',
    description: 'Optimized for resource extraction. Max mining output.',
    modules: ['mod_refinery', 'mod_refinery', 'mod_cargo_hold', 'mod_docking_ring', 'mod_fission_reactor', 'mod_crew_quarters', 'mod_command_center', 'mod_armor_plating'],
  },
  {
    name: 'Research Station',
    icon: '🔬',
    description: 'Optimized for science. Max research speed.',
    modules: ['mod_research_lab', 'mod_quantum_lab', 'mod_xenolab', 'mod_fission_reactor', 'mod_crew_quarters', 'mod_relay_array', 'mod_solar_array', 'mod_command_center'],
  },
  {
    name: 'Trade Hub',
    icon: '📊',
    description: 'Optimized for commerce. Max docking and storage.',
    modules: ['mod_docking_ring', 'mod_docking_ring', 'mod_shipyard', 'mod_cargo_hold', 'mod_cargo_hold', 'mod_relay_array', 'mod_crew_quarters', 'mod_solar_array'],
  },
  {
    name: 'Tourism Resort',
    icon: '🏖️',
    description: 'Optimized for tourism revenue. Luxury and views.',
    modules: ['mod_luxury_quarters', 'mod_observation_deck', 'mod_biosphere', 'mod_crew_quarters', 'mod_solar_array', 'mod_relay_array', 'mod_cargo_hold', 'mod_command_center'],
  },
  {
    name: 'Fortress',
    icon: '🏰',
    description: 'Optimized for defense. Protects territory from contests.',
    modules: ['mod_armor_plating', 'mod_armor_plating', 'mod_shield_generator', 'mod_fission_reactor', 'mod_crew_quarters', 'mod_docking_ring', 'mod_command_center', 'mod_relay_array'],
  },
];
