// ─── Space Tycoon: Service Definitions (Revenue Generators) ─────────────────
// Balance pass: early-game revenues reduced ~30%, space station tourism fixed,
// Lunar Gateway & Mars Station now have services, solar farms generate revenue.

import type { ServiceDefinition } from './types';

export const SERVICES: ServiceDefinition[] = [
  // ─── GROUND SERVICES ───────────────────────────────────────────────────
  { id: 'svc_ground_tracking', name: 'Satellite Tracking Services', type: 'sensor_service', tier: 1,
    description: 'Sell antenna time and tracking data to other satellite operators.',
    revenuePerMonth: 2_000_000, operatingCostPerMonth: 600_000,
    requiredBuildings: ['ground_station'], requiredResearch: [] },
  { id: 'svc_mission_ops', name: 'Mission Operations Contracts', type: 'sensor_service', tier: 1,
    description: 'Manage missions for government and commercial customers.',
    revenuePerMonth: 4_000_000, operatingCostPerMonth: 1_500_000,
    requiredBuildings: ['mission_control'], requiredResearch: [] },

  // ─── LAUNCH SERVICES ──────────────────────────────────────────────────
  { id: 'svc_launch_small', name: 'Small Launch Services', type: 'launch_payload', tier: 1,
    description: 'Offer payload capacity on small rockets (up to 5 tons to LEO).',
    revenuePerMonth: 5_000_000, operatingCostPerMonth: 2_000_000,
    requiredBuildings: ['launch_pad_small'], requiredResearch: [] },
  { id: 'svc_launch_medium', name: 'Medium Launch Services', type: 'launch_payload', tier: 2,
    description: 'Reusable medium-lift launches for commercial and government payloads.',
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 7_000_000,
    requiredBuildings: ['launch_pad_medium'], requiredResearch: ['reusable_boosters'] },
  { id: 'svc_launch_heavy', name: 'Heavy Launch Services', type: 'launch_payload', tier: 3,
    description: 'Super-heavy launches for space stations, interplanetary missions.',
    revenuePerMonth: 55_000_000, operatingCostPerMonth: 20_000_000,
    requiredBuildings: ['launch_pad_heavy'], requiredResearch: ['super_heavy_lift'] },

  // ─── TELECOM SERVICES ─────────────────────────────────────────────────
  { id: 'svc_telecom_leo', name: 'LEO Broadband', type: 'telecom_service', tier: 1,
    description: 'Low-latency internet service from LEO constellation.',
    revenuePerMonth: 3_500_000, operatingCostPerMonth: 1_200_000,
    requiredBuildings: ['sat_telecom'], requiredResearch: [] },
  { id: 'svc_telecom_geo', name: 'GEO Communications', type: 'telecom_service', tier: 1,
    description: 'High-throughput broadcast and enterprise comms from GEO.',
    revenuePerMonth: 8_000_000, operatingCostPerMonth: 2_500_000,
    requiredBuildings: ['sat_telecom_geo'], requiredResearch: [] },

  // ─── SENSOR SERVICES ──────────────────────────────────────────────────
  { id: 'svc_sensor_leo', name: 'LEO Earth Observation', type: 'sensor_service', tier: 1,
    description: 'Sell satellite imagery and analytics data.',
    revenuePerMonth: 3_000_000, operatingCostPerMonth: 800_000,
    requiredBuildings: ['sat_sensor'], requiredResearch: ['high_res_optical'] },
  { id: 'svc_sensor_geo', name: 'GEO Persistent Monitoring', type: 'sensor_service', tier: 2,
    description: 'Continuous monitoring of specific regions from GEO.',
    revenuePerMonth: 8_000_000, operatingCostPerMonth: 2_500_000,
    requiredBuildings: ['sat_sensor_geo'], requiredResearch: ['high_res_optical'] },

  // ─── AI DATACENTER ────────────────────────────────────────────────────
  { id: 'svc_ai_datacenter', name: 'Orbital AI Compute', type: 'ai_datacenter', tier: 2,
    description: 'Sell AI inference and training compute from orbital data centers.',
    revenuePerMonth: 12_000_000, operatingCostPerMonth: 4_000_000,
    requiredBuildings: ['datacenter_orbital'], requiredResearch: ['rad_hard_processors'] },
  { id: 'svc_ai_mars', name: 'Mars Data Processing', type: 'ai_datacenter', tier: 3,
    description: 'Process Mars surface data and relay analytics to Earth.',
    revenuePerMonth: 25_000_000, operatingCostPerMonth: 8_000_000,
    requiredBuildings: ['datacenter_mars_orbit'], requiredResearch: ['edge_ai'] },

  // ─── MINING OUTPUT ────────────────────────────────────────────────────
  { id: 'svc_mining_lunar', name: 'Lunar Water Sales', type: 'mining_output', tier: 2,
    description: 'Sell water and propellant derived from lunar ice.',
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 7_000_000,
    requiredBuildings: ['mining_lunar_ice'], requiredResearch: ['resource_prospecting'] },
  { id: 'svc_mining_mars', name: 'Mars Resource Extraction', type: 'mining_output', tier: 3,
    description: 'Metals, water, and construction materials from Mars.',
    revenuePerMonth: 35_000_000, operatingCostPerMonth: 13_000_000,
    requiredBuildings: ['mining_mars'], requiredResearch: ['regolith_processing'] },
  { id: 'svc_mining_asteroid', name: 'Asteroid Metals', type: 'mining_output', tier: 3,
    description: 'Platinum group metals and rare elements from asteroids.',
    revenuePerMonth: 50_000_000, operatingCostPerMonth: 18_000_000,
    requiredBuildings: ['mining_asteroid'], requiredResearch: ['asteroid_capture'] },
  { id: 'svc_mining_europa', name: 'Europa Subsurface Resources', type: 'mining_output', tier: 4,
    description: 'Exotic materials from Europa\'s subsurface ocean.',
    revenuePerMonth: 120_000_000, operatingCostPerMonth: 45_000_000,
    requiredBuildings: ['mining_europa'], requiredResearch: ['deep_drilling'] },
  { id: 'svc_mining_titan', name: 'Titan Hydrocarbon Exports', type: 'mining_output', tier: 4,
    description: 'Methane and ethane from Titan for fuel and chemical production.',
    revenuePerMonth: 160_000_000, operatingCostPerMonth: 55_000_000,
    requiredBuildings: ['mining_titan'], requiredResearch: ['deep_drilling'] },

  // ─── TOURISM ──────────────────────────────────────────────────────────
  { id: 'svc_tourism_leo', name: 'LEO Space Tourism', type: 'tourism', tier: 1,
    description: 'Short-duration stays on your orbital outpost.',
    revenuePerMonth: 12_000_000, operatingCostPerMonth: 4_000_000,
    requiredBuildings: ['space_station_small'], requiredResearch: ['modular_spacecraft'] },
  { id: 'svc_tourism_lunar_gateway', name: 'Lunar Gateway Tours', type: 'tourism', tier: 2,
    description: 'Premium lunar flyby experiences from the Gateway station.',
    revenuePerMonth: 25_000_000, operatingCostPerMonth: 10_000_000,
    requiredBuildings: ['space_station_lunar'], requiredResearch: ['modular_spacecraft', 'reusable_boosters'] },
  { id: 'svc_mars_station_ops', name: 'Mars Station Operations', type: 'sensor_service', tier: 3,
    description: 'Deep-space relay, mission staging, and Mars surface coordination.',
    revenuePerMonth: 45_000_000, operatingCostPerMonth: 15_000_000,
    requiredBuildings: ['space_station_mars'], requiredResearch: ['interplanetary_cruisers'] },
  { id: 'svc_tourism_moon', name: 'Lunar Tourism', type: 'tourism', tier: 2,
    description: 'Lunar surface excursions for wealthy tourists.',
    revenuePerMonth: 30_000_000, operatingCostPerMonth: 12_000_000,
    requiredBuildings: ['habitat_lunar'], requiredResearch: ['modular_spacecraft'] },
  { id: 'svc_tourism_mars', name: 'Mars Tourism', type: 'tourism', tier: 3,
    description: 'Multi-month Mars expedition packages.',
    revenuePerMonth: 80_000_000, operatingCostPerMonth: 35_000_000,
    requiredBuildings: ['habitat_mars'], requiredResearch: ['interplanetary_cruisers'] },

  // ─── POWER GENERATION (Solar Farms) ─────────────────────────────────
  { id: 'svc_power_orbital', name: 'Orbital Power Sales', type: 'fabrication_output', tier: 1,
    description: 'Sell solar power to nearby stations and satellites via beamed energy.',
    revenuePerMonth: 3_000_000, operatingCostPerMonth: 800_000,
    requiredBuildings: ['solar_farm_orbital'], requiredResearch: ['triple_junction'] },
  { id: 'svc_power_lunar', name: 'Lunar Power Grid', type: 'fabrication_output', tier: 2,
    description: 'Supply power to lunar surface installations and habitats.',
    revenuePerMonth: 5_000_000, operatingCostPerMonth: 1_200_000,
    requiredBuildings: ['solar_farm_lunar'], requiredResearch: ['triple_junction'] },

  // ─── FABRICATION ──────────────────────────────────────────────────────
  { id: 'svc_fabrication_orbital', name: 'Orbital Manufacturing', type: 'fabrication_output', tier: 2,
    description: 'Sell microgravity-manufactured components.',
    revenuePerMonth: 10_000_000, operatingCostPerMonth: 4_000_000,
    requiredBuildings: ['fabrication_orbital'], requiredResearch: ['orbital_assembly'] },
  { id: 'svc_fabrication_lunar', name: 'Lunar Manufacturing', type: 'fabrication_output', tier: 2,
    description: 'Build components from lunar materials for local use or export.',
    revenuePerMonth: 15_000_000, operatingCostPerMonth: 6_000_000,
    requiredBuildings: ['fabrication_lunar'], requiredResearch: ['orbital_assembly', 'regolith_processing'] },

  // ─── NEW BUSINESS TYPES ─────────────────────────────────────────────
  { id: 'svc_propellant_depot', name: 'Propellant Depot Services', type: 'fabrication_output', tier: 2,
    description: 'Sell rocket fuel produced from water ice. The gas station of space.',
    revenuePerMonth: 20_000_000, operatingCostPerMonth: 7_000_000,
    requiredBuildings: ['fabrication_mars'], requiredResearch: ['resource_prospecting', 'regolith_processing'] },
  { id: 'svc_debris_removal', name: 'Debris Removal Contracts', type: 'sensor_service', tier: 2,
    description: 'Government and commercial contracts to remove orbital debris.',
    revenuePerMonth: 12_000_000, operatingCostPerMonth: 5_000_000,
    requiredBuildings: ['sat_lunar_relay'], requiredResearch: ['autonomous_docking'] },
  { id: 'svc_navigation', name: 'Navigation Services (GPS)', type: 'telecom_service', tier: 2,
    description: 'Positioning, navigation, and timing services for Earth and cislunar space.',
    revenuePerMonth: 15_000_000, operatingCostPerMonth: 4_000_000,
    requiredBuildings: ['solar_farm_geo'], requiredResearch: ['high_power_comms'] },
  { id: 'svc_space_insurance', name: 'Space Insurance Underwriting', type: 'sensor_service', tier: 2,
    description: 'Underwrite launch and satellite insurance policies. Passive income.',
    revenuePerMonth: 8_000_000, operatingCostPerMonth: 1_800_000,
    requiredBuildings: ['sat_lunar_relay'], requiredResearch: ['sar_imaging'] },
  { id: 'svc_asteroid_survey', name: 'Asteroid Survey Data', type: 'sensor_service', tier: 3,
    description: 'Sell prospecting data to mining companies. Precursor to mining operations.',
    revenuePerMonth: 28_000_000, operatingCostPerMonth: 10_000_000,
    requiredBuildings: ['fabrication_asteroid'], requiredResearch: ['resource_prospecting', 'quantum_sensors'] },
  { id: 'svc_propellant_brokerage', name: 'Propellant Brokerage', type: 'launch_payload', tier: 3,
    description: 'Buy cheap fuel at Moon, sell at premium to Mars/Jupiter-bound missions.',
    revenuePerMonth: 40_000_000, operatingCostPerMonth: 15_000_000,
    requiredBuildings: ['sat_mars_relay'], requiredResearch: ['interplanetary_cruisers'] },
];

export const SERVICE_MAP = new Map(SERVICES.map(s => [s.id, s]));
