// ─── Space Tycoon: Service Definitions (Revenue Generators) ─────────────────
// Balance pass: early-game revenues reduced ~30%, space station tourism fixed,
// Lunar Gateway & Mars Station now have services, solar farms generate revenue.

import type { ServiceDefinition } from './types';

export const SERVICES: ServiceDefinition[] = [
  // ─── GROUND SERVICES ───────────────────────────────────────────────────
  { id: 'svc_ground_tracking', name: 'Satellite Tracking Services', type: 'sensor_service', tier: 1,
    description: 'Sell antenna time and tracking data to other satellite operators.',
    revenuePerMonth: 2_000_000, operatingCostPerMonth: 600_000,
    requiredBuildings: ['ground_station'], requiredResearch: [] },
  { id: 'svc_mission_ops', name: 'Mission Operations Contracts', type: 'sensor_service', tier: 1,
    description: 'Manage missions for government and commercial customers.',
    revenuePerMonth: 4_000_000, operatingCostPerMonth: 1_500_000,
    requiredBuildings: ['mission_control'], requiredResearch: [] },

  // ─── LAUNCH SERVICES ──────────────────────────────────────────────────
  { id: 'svc_launch_small', name: 'Small Launch Services', type: 'launch_payload', tier: 1,
    description: 'Offer payload capacity on small rockets (up to 5 tons to LEO).',
    revenuePerMonth: 5_000_000, operatingCostPerMonth: 2_000_000,
    requiredBuildings: ['launch_pad_small'], requiredResearch: [] },
  { id: 'svc_launch_medium', name: 'Medium Launch Services', type: 'launch_payload', tier: 2,
    description: 'Reusable medium-lift launches for commercial and government payloads.',
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 7_000_000,
    requiredBuildings: ['launch_pad_medium'], requiredResearch: ['reusable_boosters'] },
  { id: 'svc_launch_heavy', name: 'Heavy Launch Services', type: 'launch_payload', tier: 3,
    description: 'Super-heavy launches for space stations, interplanetary missions.',
    revenuePerMonth: 55_000_000, operatingCostPerMonth: 20_000_000,
    requiredBuildings: ['launch_pad_heavy'], requiredResearch: ['super_heavy_lift'] },

  // ─── TELECOM SERVICES ─────────────────────────────────────────────────
  { id: 'svc_telecom_leo', name: 'LEO Broadband', type: 'telecom_service', tier: 1,
    description: 'Low-latency internet service from LEO constellation.',
    revenuePerMonth: 3_500_000, operatingCostPerMonth: 1_200_000,
    requiredBuildings: ['sat_telecom'], requiredResearch: [] },
  { id: 'svc_telecom_geo', name: 'GEO Communications', type: 'telecom_service', tier: 1,
    description: 'High-throughput broadcast and enterprise comms from GEO.',
    revenuePerMonth: 8_000_000, operatingCostPerMonth: 2_500_000,
    requiredBuildings: ['sat_telecom_geo'], requiredResearch: [] },

  // ─── SENSOR SERVICES ──────────────────────────────────────────────────
  { id: 'svc_sensor_leo', name: 'LEO Earth Observation', type: 'sensor_service', tier: 1,
    description: 'Sell satellite imagery and analytics data.',
    revenuePerMonth: 3_000_000, operatingCostPerMonth: 800_000,
    requiredBuildings: ['sat_sensor'], requiredResearch: ['high_res_optical'] },
  { id: 'svc_sensor_geo', name: 'GEO Persistent Monitoring', type: 'sensor_service', tier: 2,
    description: 'Continuous monitoring of specific regions from GEO.',
    revenuePerMonth: 8_000_000, operatingCostPerMonth: 2_500_000,
    requiredBuildings: ['sat_sensor_geo'], requiredResearch: ['high_res_optical'] },

  // ─── AI DATACENTER ────────────────────────────────────────────────────
  { id: 'svc_ai_datacenter', name: 'Orbital AI Compute', type: 'ai_datacenter', tier: 2,
    description: 'Sell AI inference and training compute from orbital data centers.',
    revenuePerMonth: 12_000_000, operatingCostPerMonth: 4_000_000,
    requiredBuildings: ['datacenter_orbital'], requiredResearch: ['rad_hard_processors'] },
  { id: 'svc_ai_datacenter_geo', name: 'GEO AI Compute', type: 'ai_datacenter', tier: 3,
    description: 'Premium always-in-view AI compute and broadcast processing from the geostationary belt.',
    revenuePerMonth: 22_000_000, operatingCostPerMonth: 7_000_000,
    requiredBuildings: ['datacenter_geo'], requiredResearch: ['edge_ai'] },
  { id: 'svc_ai_mars', name: 'Mars Data Processing', type: 'ai_datacenter', tier: 3,
    description: 'Process Mars surface data and relay analytics to Earth.',
    revenuePerMonth: 25_000_000, operatingCostPerMonth: 8_000_000,
    requiredBuildings: ['datacenter_mars_orbit'], requiredResearch: ['edge_ai'] },

  // ─── MINING OUTPUT ────────────────────────────────────────────────────
  { id: 'svc_mining_lunar_basic', name: 'Lunar Basic Water Sales', type: 'mining_output', tier: 1,
    description: 'Sell modest batches of lunar water from surface-skimmer extraction.',
    revenuePerMonth: 5_500_000, operatingCostPerMonth: 2_000_000,
    requiredBuildings: ['mining_lunar_basic'], requiredResearch: [] },
  { id: 'svc_mining_lunar', name: 'Lunar Water Sales', type: 'mining_output', tier: 2,
    description: 'Sell water and propellant derived from lunar ice.',
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 7_000_000,
    requiredBuildings: ['mining_lunar_ice'], requiredResearch: ['resource_prospecting'] },
  { id: 'svc_mining_mars', name: 'Mars Resource Extraction', type: 'mining_output', tier: 3,
    description: 'Metals, water, and construction materials from Mars.',
    revenuePerMonth: 35_000_000, operatingCostPerMonth: 13_000_000,
    requiredBuildings: ['mining_mars'], requiredResearch: ['regolith_processing'] },
  { id: 'svc_mining_asteroid', name: 'Asteroid Metals', type: 'mining_output', tier: 3,
    description: 'Platinum group metals and rare elements from asteroids.',
    revenuePerMonth: 50_000_000, operatingCostPerMonth: 18_000_000,
    requiredBuildings: ['mining_asteroid'], requiredResearch: ['asteroid_capture'] },
  { id: 'svc_mining_europa', name: 'Europa Subsurface Resources', type: 'mining_output', tier: 4,
    description: 'Exotic materials from Europa\'s subsurface ocean.',
    revenuePerMonth: 120_000_000, operatingCostPerMonth: 45_000_000,
    requiredBuildings: ['mining_europa'], requiredResearch: ['deep_drilling'] },
  { id: 'svc_mining_titan', name: 'Titan Hydrocarbon Exports', type: 'mining_output', tier: 4,
    description: 'Methane and ethane from Titan for fuel and chemical production.',
    revenuePerMonth: 160_000_000, operatingCostPerMonth: 55_000_000,
    requiredBuildings: ['mining_titan'], requiredResearch: ['deep_drilling'] },

  // ─── TOURISM ──────────────────────────────────────────────────────────
  { id: 'svc_tourism_leo', name: 'LEO Space Tourism', type: 'tourism', tier: 1,
    description: 'Short-duration stays on your orbital outpost.',
    revenuePerMonth: 12_000_000, operatingCostPerMonth: 4_000_000,
    requiredBuildings: ['space_station_small'], requiredResearch: ['modular_spacecraft'] },
  { id: 'svc_tourism_lunar_gateway', name: 'Lunar Gateway Tours', type: 'tourism', tier: 2,
    description: 'Premium lunar flyby experiences from the Gateway station.',
    revenuePerMonth: 25_000_000, operatingCostPerMonth: 10_000_000,
    requiredBuildings: ['space_station_lunar'], requiredResearch: ['modular_spacecraft', 'reusable_boosters'] },
  { id: 'svc_mars_station_ops', name: 'Mars Station Operations', type: 'sensor_service', tier: 3,
    description: 'Deep-space relay, mission staging, and Mars surface coordination.',
    revenuePerMonth: 45_000_000, operatingCostPerMonth: 15_000_000,
    requiredBuildings: ['space_station_mars'], requiredResearch: ['interplanetary_cruisers'] },
  { id: 'svc_tourism_moon', name: 'Lunar Tourism', type: 'tourism', tier: 2,
    description: 'Lunar surface excursions for wealthy tourists.',
    revenuePerMonth: 30_000_000, operatingCostPerMonth: 12_000_000,
    requiredBuildings: ['habitat_lunar'], requiredResearch: ['modular_spacecraft'] },
  { id: 'svc_tourism_mars', name: 'Mars Tourism', type: 'tourism', tier: 3,
    description: 'Multi-month Mars expedition packages.',
    revenuePerMonth: 80_000_000, operatingCostPerMonth: 35_000_000,
    requiredBuildings: ['habitat_mars'], requiredResearch: ['interplanetary_cruisers'] },

  // ─── POWER GENERATION (Solar Farms) ─────────────────────────────────
  { id: 'svc_power_orbital', name: 'Orbital Power Sales', type: 'fabrication_output', tier: 1,
    description: 'Sell solar power to nearby stations and satellites via beamed energy.',
    revenuePerMonth: 3_000_000, operatingCostPerMonth: 800_000,
    requiredBuildings: ['solar_farm_orbital'], requiredResearch: ['triple_junction'] },
  { id: 'svc_power_lunar', name: 'Lunar Power Grid', type: 'fabrication_output', tier: 2,
    description: 'Supply power to lunar surface installations and habitats.',
    revenuePerMonth: 5_000_000, operatingCostPerMonth: 1_200_000,
    requiredBuildings: ['solar_farm_lunar'], requiredResearch: ['triple_junction'] },

  // ─── FABRICATION ──────────────────────────────────────────────────────
  { id: 'svc_fabrication_orbital', name: 'Orbital Manufacturing', type: 'fabrication_output', tier: 2,
    description: 'Sell microgravity-manufactured components.',
    revenuePerMonth: 10_000_000, operatingCostPerMonth: 4_000_000,
    requiredBuildings: ['fabrication_orbital'], requiredResearch: ['orbital_assembly'] },
  { id: 'svc_fabrication_lunar', name: 'Lunar Manufacturing', type: 'fabrication_output', tier: 2,
    description: 'Build components from lunar materials for local use or export.',
    revenuePerMonth: 15_000_000, operatingCostPerMonth: 6_000_000,
    requiredBuildings: ['fabrication_lunar'], requiredResearch: ['orbital_assembly', 'regolith_processing'] },

  // ─── NEW BUSINESS TYPES ─────────────────────────────────────────────
  { id: 'svc_propellant_depot', name: 'Propellant Depot Services', type: 'fabrication_output', tier: 2,
    description: 'Sell rocket fuel produced from water ice. The gas station of space.',
    revenuePerMonth: 20_000_000, operatingCostPerMonth: 7_000_000,
    requiredBuildings: ['fabrication_mars'], requiredResearch: ['resource_prospecting', 'regolith_processing'] },
  { id: 'svc_debris_removal', name: 'Debris Removal Contracts', type: 'sensor_service', tier: 2,
    description: 'Government and commercial contracts to remove orbital debris.',
    revenuePerMonth: 12_000_000, operatingCostPerMonth: 5_000_000,
    requiredBuildings: ['sat_lunar_relay'], requiredResearch: ['autonomous_docking'] },
  { id: 'svc_navigation', name: 'Navigation Services (GPS)', type: 'telecom_service', tier: 2,
    description: 'Positioning, navigation, and timing services for Earth and cislunar space.',
    revenuePerMonth: 15_000_000, operatingCostPerMonth: 4_000_000,
    requiredBuildings: ['solar_farm_geo'], requiredResearch: ['high_power_comms'] },
  { id: 'svc_space_insurance', name: 'Space Insurance Underwriting', type: 'sensor_service', tier: 2,
    description: 'Underwrite launch and satellite insurance policies. Passive income.',
    revenuePerMonth: 8_000_000, operatingCostPerMonth: 1_800_000,
    requiredBuildings: ['sat_lunar_relay'], requiredResearch: ['sar_imaging'] },
  { id: 'svc_asteroid_survey', name: 'Asteroid Survey Data', type: 'sensor_service', tier: 3,
    description: 'Sell prospecting data to mining companies. Precursor to mining operations.',
    revenuePerMonth: 28_000_000, operatingCostPerMonth: 10_000_000,
    requiredBuildings: ['fabrication_asteroid'], requiredResearch: ['resource_prospecting', 'quantum_sensors'] },
  { id: 'svc_propellant_brokerage', name: 'Propellant Brokerage', type: 'launch_payload', tier: 3,
    description: 'Buy cheap fuel at Moon, sell at premium to Mars/Jupiter-bound missions.',
    revenuePerMonth: 40_000_000, operatingCostPerMonth: 15_000_000,
    requiredBuildings: ['sat_mars_relay'], requiredResearch: ['interplanetary_cruisers'] },

  // ─── OUTER SYSTEM SERVICES ─────────────────────────────────────────
  { id: 'svc_mining_kuiper', name: 'Kuiper Belt Extraction', type: 'mining_output', tier: 5,
    description: 'Extract exotic materials, helium-3, and platinum group metals from Kuiper Belt objects.',
    // M1/F1: outer-system service grosses raised ~1.75x (80M->140M) — the
    // frontier premium the tier ladder was missing (see MEANINGFUL_2026-08 §5 M1.2).
    revenuePerMonth: 140_000_000, operatingCostPerMonth: 25_000_000,
    requiredBuildings: ['mining_kuiper'], requiredResearch: ['deep_drilling'] },
  { id: 'svc_deep_space_comm', name: 'Deep Space Data Relay', type: 'telecom_service', tier: 5,
    description: 'Long-range communication relay services for outer system operations and deep space probes.',
    revenuePerMonth: 40_000_000, operatingCostPerMonth: 15_000_000,
    requiredBuildings: ['deep_space_relay'], requiredResearch: ['fusion_drive'] },
  { id: 'svc_jupiter_relay', name: 'Jupiter System Relay', type: 'telecom_service', tier: 4,
    description: 'Data relay and edge computing services for Jupiter system operations.',
    // M1/F1: 30M->36M (still ratio 2.64x vs the 95M jupiter_system:telecom
    // floor — inside the 2.5-3.5x authoring band) so the flagship pays for
    // its required reactor's upkeep. See MEANINGFUL_2026-08 §5 M1.2.
    revenuePerMonth: 36_000_000, operatingCostPerMonth: 12_000_000,
    requiredBuildings: ['datacenter_jupiter'], requiredResearch: ['nuclear_thermal', 'edge_ai'] },
  { id: 'svc_titan_processing', name: 'Titan Chemical Processing', type: 'fabrication_output', tier: 4,
    description: 'Process Titan hydrocarbons into refined chemicals and rocket fuel for export.',
    // M1/F1: 35M->50M (~1.43x, ratio 110M/50M=2.2x — see note below, kept
    // inside band via saturn_system.fabrication's unchanged 110M floor
    // headroom) so the flagship isn't a 6,700-month outlier among its T4 peers.
    revenuePerMonth: 50_000_000, operatingCostPerMonth: 12_000_000,
    requiredBuildings: ['fabrication_titan'], requiredResearch: ['deep_drilling', 'orbital_assembly'] },

  // ─── AAA Round 1 E3.4 — colony services ──────────────────────────────────
  // One service per colony building (see the matching block in buildings.ts
  // for the derivation of every revenue/cost figure). Types are drawn from the
  // existing ServiceType union so demand-pool categorisation
  // (demand-pools.ts CATEGORY_BY_SERVICE_TYPE) works with no new mapping:
  // habitats are `tourism`, rigs are `mining_output` (pool-exempt, priced by
  // extraction pressure instead), labs are `sensor_service`/`ai_datacenter`,
  // depots and plants are `fabrication_output`.
  { id: 'svc_ceres_habitation', name: 'Ceres Habitation & Berthing', type: 'tourism', tier: 3,
    description: "Housing, life support, and dock berths sold to Belt operators and transiting crews.",
    revenuePerMonth: 14_000_000, operatingCostPerMonth: 4_760_000,
    requiredBuildings: ['colony_ceres'], requiredResearch: [] },
  { id: 'svc_mining_ceres', name: 'Ceres Volatile Extraction', type: 'mining_output', tier: 3,
    description: "Ammonia, organics and iron from Cerean brine and regolith.",
    revenuePerMonth: 23_600_000, operatingCostPerMonth: 8_024_000,
    requiredBuildings: ['mining_ceres'], requiredResearch: [] },
  { id: 'svc_ceres_logistics', name: 'Ceres Belt Logistics', type: 'fabrication_output', tier: 3,
    description: "Transshipment, bonded storage and clearing services for Belt cargo.",
    revenuePerMonth: 14_000_000, operatingCostPerMonth: 4_760_000,
    requiredBuildings: ['trade_hub_ceres'], requiredResearch: [] },
  { id: 'svc_venus_habitation', name: 'Cloud City Residency', type: 'tourism', tier: 3,
    description: "Long-stay residency and tourism in the one place off Earth with shirtsleeve pressure.",
    revenuePerMonth: 14_000_000, operatingCostPerMonth: 4_760_000,
    requiredBuildings: ['colony_venus'], requiredResearch: [] },
  { id: 'svc_venus_volatiles', name: 'Venusian Atmospheric Harvest', type: 'mining_output', tier: 3,
    description: "Sulfur, ammonia and methane separated from the Venusian atmosphere.",
    revenuePerMonth: 24_006_000, operatingCostPerMonth: 8_162_040,
    requiredBuildings: ['atmospheric_processor'], requiredResearch: [] },
  { id: 'svc_venus_research', name: 'Venus Atmospheric Research', type: 'sensor_service', tier: 3,
    description: "Atmospheric and radar datasets licensed to agencies and universities.",
    revenuePerMonth: 14_000_000, operatingCostPerMonth: 4_760_000,
    requiredBuildings: ['venus_observatory'], requiredResearch: [] },
  { id: 'svc_mercury_habitation', name: 'Polar Outpost Services', type: 'tourism', tier: 3,
    description: "Crew rotation, life support and shielded berthing at the innermost human settlement.",
    revenuePerMonth: 14_000_000, operatingCostPerMonth: 4_760_000,
    requiredBuildings: ['colony_mercury'], requiredResearch: [] },
  { id: 'svc_mercury_mining', name: 'Mercury Metal Extraction', type: 'mining_output', tier: 3,
    description: "Iron, platinum-group metals and rare earths from Mercury's metal-rich crust.",
    revenuePerMonth: 24_200_000, operatingCostPerMonth: 8_228_000,
    requiredBuildings: ['mining_mercury'], requiredResearch: [] },
  { id: 'svc_beamed_power', name: 'Beamed Solar Power', type: 'fabrication_output', tier: 3,
    description: "Microwave-beamed power sold to inner-system industry.",
    revenuePerMonth: 14_000_000, operatingCostPerMonth: 4_760_000,
    requiredBuildings: ['solar_mega_array'], requiredResearch: [] },
  { id: 'svc_io_habitation', name: 'Io Station Services', type: 'tourism', tier: 4,
    description: "Shielded quarters and hazard-pay rotations for Io surface crews.",
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 6_120_000,
    requiredBuildings: ['colony_io'], requiredResearch: [] },
  { id: 'svc_io_mining', name: 'Io Sulfur & Silicate Extraction', type: 'mining_output', tier: 4,
    description: "Sulfur, iron and rare earths from active volcanic deposits.",
    revenuePerMonth: 39_996_000, operatingCostPerMonth: 13_598_640,
    requiredBuildings: ['mining_io'], requiredResearch: [] },
  { id: 'svc_io_geothermal', name: 'Io Geothermal Power', type: 'fabrication_output', tier: 4,
    description: "Tidal-geothermal power sold across the Jovian system.",
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 6_120_000,
    requiredBuildings: ['geothermal_plant'], requiredResearch: [] },
  { id: 'svc_europa_habitation', name: 'Europa Station Services', type: 'tourism', tier: 4,
    description: "Sub-ice quarters, life support and dive-crew rotations.",
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 6_120_000,
    requiredBuildings: ['colony_europa'], requiredResearch: [] },
  { id: 'svc_europa_deep_mining', name: 'Europa Deep Ocean Mining', type: 'mining_output', tier: 4,
    description: "Exotic materials and organic compounds from the Europan subsurface ocean.",
    revenuePerMonth: 39_600_000, operatingCostPerMonth: 13_464_000,
    requiredBuildings: ['mining_europa_deep'], requiredResearch: [] },
  { id: 'svc_europa_biolab', name: 'Europan Astrobiology Program', type: 'sensor_service', tier: 4,
    description: "Astrobiology datasets and sample analysis licensed to research institutions.",
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 6_120_000,
    requiredBuildings: ['ocean_lab'], requiredResearch: [] },
  { id: 'svc_ganymede_habitation', name: 'Ganymede Civic Services', type: 'tourism', tier: 4,
    description: "Civic administration, housing and transit services for the Jovian capital.",
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 6_120_000,
    requiredBuildings: ['colony_ganymede'], requiredResearch: [] },
  { id: 'svc_mining_ganymede', name: 'Ganymede Core Metal Extraction', type: 'mining_output', tier: 4,
    description: "Iron, titanium and rare earths from Ganymede's differentiated interior.",
    revenuePerMonth: 40_000_000, operatingCostPerMonth: 13_600_000,
    requiredBuildings: ['mining_ganymede'], requiredResearch: [] },
  { id: 'svc_ganymede_research', name: 'Ganymede Research Campus', type: 'ai_datacenter', tier: 4,
    description: "Cryogenically-cooled compute sold to research and simulation customers.",
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 6_120_000,
    requiredBuildings: ['research_campus'], requiredResearch: [] },
  { id: 'svc_callisto_habitation', name: 'Callisto Base Services', type: 'tourism', tier: 4,
    description: "Low-radiation quarters and crew staging for Jovian operations.",
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 6_120_000,
    requiredBuildings: ['colony_callisto'], requiredResearch: [] },
  { id: 'svc_mining_callisto', name: 'Callisto Regolith Extraction', type: 'mining_output', tier: 4,
    description: "Iron, aluminium and ammonia from Callisto's ancient regolith.",
    revenuePerMonth: 40_002_000, operatingCostPerMonth: 13_600_680,
    requiredBuildings: ['mining_callisto'], requiredResearch: [] },
  { id: 'svc_callisto_staging', name: 'Callisto Deep-Space Staging', type: 'fabrication_output', tier: 4,
    description: "Propellant sales, berthing and outfitting for outbound deep-space missions.",
    revenuePerMonth: 18_000_000, operatingCostPerMonth: 6_120_000,
    requiredBuildings: ['fuel_depot_callisto'], requiredResearch: [] },
  { id: 'svc_titan_habitation', name: 'Titan Settlement Services', type: 'tourism', tier: 5,
    description: "Housing, transit and surface tourism beneath Titan's nitrogen atmosphere.",
    revenuePerMonth: 22_000_000, operatingCostPerMonth: 7_480_000,
    requiredBuildings: ['colony_titan'], requiredResearch: [] },
  { id: 'svc_titan_lake_mining', name: 'Titan Hydrocarbon Lakes', type: 'mining_output', tier: 5,
    description: "Liquid methane, ethane and tholin organics pumped from Titan's polar seas.",
    revenuePerMonth: 64_005_000, operatingCostPerMonth: 21_761_700,
    requiredBuildings: ['mining_titan_deep'], requiredResearch: [] },
  { id: 'svc_titan_chemicals', name: 'Titan Chemical Industry', type: 'fabrication_output', tier: 5,
    description: "Polymers, propellant and industrial feedstock refined from Titan hydrocarbons.",
    revenuePerMonth: 22_000_000, operatingCostPerMonth: 7_480_000,
    requiredBuildings: ['methane_refinery'], requiredResearch: [] },
  { id: 'svc_enceladus_habitation', name: 'Enceladus Station Services', type: 'tourism', tier: 5,
    description: "Quarters, life support and plume-crew rotations at the south polar terrain.",
    revenuePerMonth: 22_000_000, operatingCostPerMonth: 7_480_000,
    requiredBuildings: ['colony_enceladus'], requiredResearch: [] },
  { id: 'svc_enceladus_collection', name: 'Enceladus Geyser Collection', type: 'mining_output', tier: 5,
    description: "Organic compounds, biological samples and ammonia captured from the polar plumes.",
    revenuePerMonth: 56_602_000, operatingCostPerMonth: 19_244_680,
    requiredBuildings: ['geyser_collector'], requiredResearch: [] },
  { id: 'svc_enceladus_biolab', name: 'Hydrothermal Biology Program', type: 'sensor_service', tier: 5,
    description: "Sequencing and culture data from live hydrothermal samples, licensed worldwide.",
    revenuePerMonth: 22_000_000, operatingCostPerMonth: 7_480_000,
    requiredBuildings: ['bio_lab_enceladus'], requiredResearch: [] },
  { id: 'svc_titania_habitation', name: 'Titania Outpost Services', type: 'tourism', tier: 5,
    description: "Long-rotation quarters and life support at the Uranian frontier.",
    revenuePerMonth: 22_000_000, operatingCostPerMonth: 7_480_000,
    requiredBuildings: ['colony_titania'], requiredResearch: [] },
  { id: 'svc_titania_mining', name: 'Titania Deuterium Extraction', type: 'mining_output', tier: 5,
    description: "Deuterium, titanium and rare earths from the Uranian ice mantle.",
    revenuePerMonth: 60_800_000, operatingCostPerMonth: 20_672_000,
    requiredBuildings: ['mining_titania'], requiredResearch: [] },
  { id: 'svc_titania_cryo_research', name: 'Cryogenic Materials Program', type: 'ai_datacenter', tier: 5,
    description: "Superconductor and cryostructure research compute sold on contract.",
    revenuePerMonth: 22_000_000, operatingCostPerMonth: 7_480_000,
    requiredBuildings: ['cryo_lab'], requiredResearch: [] },
  { id: 'svc_triton_habitation', name: 'Triton Frontier Services', type: 'tourism', tier: 6,
    description: "Frontier quarters, life support and long-duration crew rotation at Neptune.",
    revenuePerMonth: 26_000_000, operatingCostPerMonth: 8_840_000,
    requiredBuildings: ['colony_triton'], requiredResearch: [] },
  { id: 'svc_triton_mining', name: 'Triton Exotic Isotope Extraction', type: 'mining_output', tier: 6,
    description: "Antimatter precursors, deuterium and ammonia from captured Kuiper material.",
    revenuePerMonth: 101_206_000, operatingCostPerMonth: 34_410_040,
    requiredBuildings: ['mining_triton'], requiredResearch: [] },
  { id: 'svc_triton_nitrogen', name: 'Triton Nitrogen Products', type: 'fabrication_output', tier: 6,
    description: "Liquid nitrogen propellant and life-support gas sold to outbound missions.",
    revenuePerMonth: 26_000_000, operatingCostPerMonth: 8_840_000,
    requiredBuildings: ['nitrogen_plant'], requiredResearch: [] },
  { id: 'svc_pluto_habitation', name: 'Pluto Colony Services', type: 'tourism', tier: 6,
    description: "Habitation, life support and civic services at the edge of the planetary system.",
    revenuePerMonth: 26_000_000, operatingCostPerMonth: 8_840_000,
    requiredBuildings: ['colony_pluto'], requiredResearch: [] },
  { id: 'svc_pluto_mining', name: 'Charon Mineral Extraction', type: 'mining_output', tier: 6,
    description: "Antimatter precursors, exotic materials and rare earths from Charon and the Plutonian surface.",
    revenuePerMonth: 108_000_000, operatingCostPerMonth: 36_720_000,
    requiredBuildings: ['mining_pluto'], requiredResearch: [] },
  { id: 'svc_interstellar_research', name: 'Interstellar Relay & Research', type: 'ai_datacenter', tier: 6,
    description: "Deep-space relay bandwidth and interstellar survey processing sold on contract.",
    revenuePerMonth: 26_000_000, operatingCostPerMonth: 8_840_000,
    requiredBuildings: ['interstellar_beacon'], requiredResearch: [] },
];

export const SERVICE_MAP = new Map(SERVICES.map(s => [s.id, s]));
