// ─── Space Tycoon: Solar System Locations ───────────────────────────────────

import type { SolarSystemLocation } from './types';

export const LOCATIONS: SolarSystemLocation[] = [
  {
    id: 'earth_surface',
    name: 'Earth Surface',
    type: 'earth_surface',
    description: 'Your home base. Build launch pads and ground stations here.',
    distanceFromEarthAU: 0,
    deltaVFromLEO: 0,
    travelTimeMonths: 0,
    unlockCost: 0,
    requiredResearch: [],
    availableBuildings: ['launch_pad_small', 'launch_pad_medium', 'launch_pad_heavy', 'ground_station', 'mission_control'],
    tier: 1,
  },
  {
    id: 'leo',
    name: 'Low Earth Orbit',
    type: 'earth_orbit',
    description: 'The most accessible orbit. Home to satellites, space stations, and data centers.',
    distanceFromEarthAU: 0,
    deltaVFromLEO: 0,
    travelTimeMonths: 0,
    unlockCost: 0,
    requiredResearch: [],
    availableBuildings: ['sat_telecom', 'sat_sensor', 'space_station_small', 'datacenter_orbital', 'solar_farm_orbital', 'fabrication_orbital'],
    tier: 1,
  },
  {
    id: 'geo',
    name: 'Geostationary Orbit',
    type: 'earth_orbit',
    description: 'Premium orbital real estate. Ideal for telecommunications and Earth observation.',
    distanceFromEarthAU: 0,
    deltaVFromLEO: 3800,
    travelTimeMonths: 0,
    unlockCost: 50_000_000,
    requiredResearch: [],
    availableBuildings: ['sat_telecom_geo', 'sat_sensor_geo', 'solar_farm_geo'],
    tier: 1,
  },
  {
    id: 'lunar_orbit',
    name: 'Lunar Orbit',
    type: 'moon',
    description: 'Gateway to the Moon. Staging point for lunar surface operations.',
    distanceFromEarthAU: 0.0026,
    deltaVFromLEO: 4000,
    travelTimeMonths: 1,
    unlockCost: 1_000_000_000,
    requiredResearch: ['reusable_boosters'],
    availableBuildings: ['space_station_lunar', 'sat_lunar_relay'],
    tier: 2,
  },
  {
    id: 'lunar_surface',
    name: 'Lunar Surface',
    type: 'moon',
    description: 'Mine water ice, build habitats, and establish the first off-world economy.',
    distanceFromEarthAU: 0.0026,
    deltaVFromLEO: 5900,
    travelTimeMonths: 1,
    unlockCost: 2_000_000_000,
    requiredResearch: ['reusable_boosters', 'modular_spacecraft'],
    availableBuildings: ['mining_lunar_ice', 'fabrication_lunar', 'solar_farm_lunar', 'habitat_lunar'],
    tier: 2,
  },
  {
    id: 'mars_orbit',
    name: 'Mars Orbit',
    type: 'mars',
    description: 'Staging area for Mars surface operations and interplanetary relay.',
    distanceFromEarthAU: 0.52,
    deltaVFromLEO: 5700,
    travelTimeMonths: 8,
    unlockCost: 10_000_000_000,
    requiredResearch: ['super_heavy_lift', 'ion_drives'],
    availableBuildings: ['space_station_mars', 'sat_mars_relay', 'datacenter_mars_orbit'],
    tier: 3,
  },
  {
    id: 'mars_surface',
    name: 'Mars Surface',
    type: 'mars',
    description: 'The red planet. Mine resources, build habitats, and terraform.',
    distanceFromEarthAU: 0.52,
    deltaVFromLEO: 8500,
    travelTimeMonths: 8,
    unlockCost: 25_000_000_000,
    requiredResearch: ['super_heavy_lift', 'ion_drives', 'resource_prospecting'],
    availableBuildings: ['mining_mars', 'fabrication_mars', 'habitat_mars', 'solar_farm_mars'],
    tier: 3,
  },
  {
    id: 'asteroid_belt',
    name: 'Asteroid Belt',
    type: 'asteroid_belt',
    description: 'Ceres and the main belt. Rich in metals, water, and rare minerals.',
    distanceFromEarthAU: 2.77,
    deltaVFromLEO: 9000,
    travelTimeMonths: 18,
    unlockCost: 15_000_000_000,
    requiredResearch: ['asteroid_capture', 'autonomous_docking'],
    availableBuildings: ['mining_asteroid', 'fabrication_asteroid', 'space_station_belt'],
    tier: 3,
  },
  {
    id: 'jupiter_system',
    name: 'Jupiter System',
    type: 'jupiter',
    description: 'Jupiter\'s moons offer ice, radiation research, and deep-space positioning.',
    distanceFromEarthAU: 5.2,
    deltaVFromLEO: 14000,
    travelTimeMonths: 30,
    unlockCost: 100_000_000_000,
    requiredResearch: ['nuclear_thermal', 'interplanetary_cruisers'],
    availableBuildings: ['space_station_jupiter', 'mining_europa', 'datacenter_jupiter'],
    tier: 4,
  },
  {
    id: 'saturn_system',
    name: 'Saturn System',
    type: 'saturn',
    description: 'Titan offers hydrocarbon resources. Saturn system for deep-space operations.',
    distanceFromEarthAU: 9.5,
    deltaVFromLEO: 18000,
    travelTimeMonths: 60,
    unlockCost: 200_000_000_000,
    requiredResearch: ['nuclear_thermal', 'interplanetary_cruisers', 'deep_drilling'],
    availableBuildings: ['space_station_saturn', 'mining_titan', 'fabrication_titan'],
    tier: 4,
  },
  {
    id: 'outer_system',
    name: 'Outer System',
    type: 'outer_system',
    description: 'Uranus, Neptune, and beyond. The frontier of human expansion.',
    distanceFromEarthAU: 20,
    deltaVFromLEO: 22000,
    travelTimeMonths: 96,
    unlockCost: 500_000_000_000,
    requiredResearch: ['fusion_drive', 'generation_ships'],
    availableBuildings: ['outpost_outer', 'mining_kuiper', 'deep_space_relay'],
    tier: 5,
  },
];

// ─── Expanded Colony Locations ────────────────────────────────────────────────
// Import colony locations and merge into the main LOCATIONS array.
// These add 14 new colonizable bodies to the existing 11 locations.

import { EXPANDED_LOCATIONS } from './colonies';

const COLONY_LOCATIONS_AS_BASE: SolarSystemLocation[] = EXPANDED_LOCATIONS.map(col => ({
  id: col.id,
  name: col.name,
  type: col.type as SolarSystemLocation['type'],
  description: col.description,
  distanceFromEarthAU: col.distanceFromEarthAU,
  deltaVFromLEO: col.deltaVFromLEO,
  travelTimeMonths: col.travelTimeMonths,
  unlockCost: col.unlockCost,
  requiredResearch: col.requiredResearch,
  availableBuildings: col.availableBuildings,
  tier: col.tier,
}));

export const ALL_LOCATIONS = [...LOCATIONS, ...COLONY_LOCATIONS_AS_BASE];

export const LOCATION_MAP = new Map(ALL_LOCATIONS.map(l => [l.id, l]));
