// ─── Space Tycoon: Type Definitions ─────────────────────────────────────────

export interface GameDate {
  year: number;
  month: number; // 1-12
}

export type TickSpeed = 0 | 1 | 2 | 5 | 10;

// ─── Buildings ──────────────────────────────────────────────────────────────

export type BuildingCategory =
  | 'launch_pad'
  | 'rocket'
  | 'satellite'
  | 'space_station'
  | 'fabrication_facility'
  | 'datacenter'
  | 'mining_enterprise'
  | 'ground_station'
  | 'solar_farm';

export type BuildingSynergyRange = 'location' | 'body' | 'system';

/**
 * Comprehensive building stats per STATS_DESIGN.md Phase I. Derived from
 * category + tier when not set explicitly. Populated with sensible defaults
 * by getBuildingDerivedStats.
 */
export interface BuildingDerivedStats {
  // Capacity & throughput
  dockingCapacity: number;
  storageCapacity: number;          // m³
  manufacturingThroughput: number;  // modules/game-month
  refiningThroughput: number;       // units/game-month
  marketLiquidityContribution: number;  // contributes to location market depth
  // Service quality
  serviceQualityMultiplier: number; // 0.5-2.0
  customerCapacity: number;
  uplinkBandwidth: number;          // Gbps
  // Crew
  crewQuarters: number;
  crewMoraleModifier: number;       // 0-1
  // Hazard resilience
  structuralIntegrity: number;
  shieldingRating: number;          // 0-0.9
  stabilityRating: number;          // 0-1
  // Network
  synergyTags: string[];
  synergyRange: BuildingSynergyRange;
  // Upgrade path
  maxUpgradeLevel: number;
}

export interface BuildingDefinition {
  id: string;
  name: string;
  category: BuildingCategory;
  description: string;
  /** Detailed tooltip explaining gameplay purpose, when to build, revenue, and strategy */
  tooltip?: string;
  baseCost: number;
  buildTimeMonths: number;
  maintenanceCostPerMonth: number;
  requiredResearch: string[];
  requiredLocation: string;
  enabledServices: string[];
  tier: number;
  /** Real-time seconds to build (wall clock). Tier 1 ≈ 5 min, max ≈ 24 hr */
  realBuildSeconds: number;
  /** Resource costs to build (in addition to money). Optional for tier 1. */
  resourceCost?: Record<string, number>;
  /** Power required to operate this building (MW). 0 or undefined = no power needed. */
  powerRequired?: number;
  /** Power generated by this building (MW). Solar farms and power plants set this. */
  powerGenerated?: number;
  /** Phase I: optional per-building overrides for any derived stats.
   *  Values not specified here are filled in by category+tier defaults. */
  stats?: Partial<BuildingDerivedStats>;
}

export interface BuildingInstance {
  instanceId: string;
  definitionId: string;
  locationId: string;
  buildStartDate: GameDate;
  completionDate: GameDate;
  isComplete: boolean;
  /** Unix ms timestamp when construction started (real clock) */
  startedAtMs: number;
  /** Real-time seconds required for this instance */
  realDurationSeconds: number;
  /** Building upgrade level: 0=Standard, 1=Advanced, 2=Elite */
  upgradeLevel?: number;
  /** If currently upgrading, when it started and how long */
  upgradeStartedAtMs?: number;
  upgradeDurationSeconds?: number;
  /** V15 (audit Wave D / A4): persistent hazard damage 0-0.85. Penalizes the
   *  revenue of services this building enables until auto-repair (a
   *  repair-cost money sink in game-engine) works it back to 0. */
  damagePct?: number;
}

// ─── Research ───────────────────────────────────────────────────────────────

export type ResearchCategory =
  | 'rocketry'
  | 'spacecraft'
  | 'sensors'
  | 'ai_chips'
  | 'satellite_components'
  | 'solar_arrays'
  | 'mining'
  | 'infrastructure'
  | 'propulsion'
  | 'crew'
  | 'services'
  | 'ships'
  | 'terraforming'
  | 'materials'
  | 'defense'
  | 'exploration'
  | 'economy';

export interface ResearchDefinition {
  id: string;
  name: string;
  category: ResearchCategory;
  description: string;
  effect: string;
  baseCostMoney: number;
  baseTimeMonths: number;
  prerequisites: string[];
  tier: number;
  unlocks: string[];
  /** Real-time seconds to research (wall clock). Tier 1 ≈ 10 min, max ≈ 24 hr */
  realResearchSeconds: number;
  /** Resource costs for research (optional, primarily tier 3+) */
  resourceCost?: Record<string, number>;
}

export interface ActiveResearch {
  definitionId: string;
  startDate: GameDate;
  progressMonths: number;
  totalMonths: number;
  /** Unix ms timestamp when research started (real clock) */
  startedAtMs: number;
  /** Real-time seconds required */
  realDurationSeconds: number;
}

// ─── Services ───────────────────────────────────────────────────────────────

export type ServiceType =
  | 'sensor_service'
  | 'telecom_service'
  | 'ai_datacenter'
  | 'launch_payload'
  | 'mining_output'
  | 'tourism'
  | 'fabrication_output';

export interface ServiceDefinition {
  id: string;
  name: string;
  type: ServiceType;
  description: string;
  revenuePerMonth: number;
  requiredBuildings: string[];
  requiredResearch: string[];
  operatingCostPerMonth: number;
  tier: number;
}

export interface ServiceInstance {
  definitionId: string;
  locationId: string;
  linkedBuildingIds: string[];
  startDate: GameDate;
  revenueMultiplier: number;
}

// ─── Solar System ───────────────────────────────────────────────────────────

export type LocationType =
  | 'earth_surface'
  | 'earth_orbit'
  | 'moon'
  | 'mars'
  | 'asteroid_belt'
  | 'jupiter'
  | 'saturn'
  | 'outer_system'
  | 'mercury'
  | 'venus'
  | 'uranus'
  | 'neptune';

export interface SolarSystemLocation {
  id: string;
  name: string;
  type: LocationType;
  description: string;
  distanceFromEarthAU: number;
  deltaVFromLEO: number;
  travelTimeMonths: number;
  unlockCost: number;
  requiredResearch: string[];
  availableBuildings: string[];
  tier: number;
}

// ─── Reports / Mail ─────────────────────────────────────────────────────────

export type ReportType = 'probe_discovery' | 'system_alert' | 'milestone';

export interface GameReport {
  id: string;
  type: ReportType;
  title: string;
  body: string;
  createdAt: number; // timestamp ms
  read: boolean;
  locationId?: string;
  rewards?: {
    money?: number;
    resources?: Record<string, number>;
    miningBonus?: { locationId: string; resourceId: string; bonusPct: number; durationMonths: number };
  };
}

// ─── Events ─────────────────────────────────────────────────────────────────

export type GameEventType =
  | 'build_complete'
  | 'research_complete'
  | 'service_started'
  | 'location_unlocked'
  | 'milestone'
  | 'random_event'
  | 'npc_activity';

export interface GameEvent {
  id: string;
  date: GameDate;
  type: GameEventType;
  title: string;
  description: string;
}

// ─── Stats ──────────────────────────────────────────────────────────────────

export interface GameStats {
  rocketsLaunched: number;
  satellitesDeployed: number;
  stationsBuilt: number;
  researchCompleted: number;
  missionsToMoon: number;
  missionsToMars: number;
  missionsToOuterPlanets: number;
}

// ─── Game State ─────────────────────────────────────────────────────────────

export interface GameState {
  version: number;
  createdAt: number;
  lastTickAt: number;

  money: number;
  totalEarned: number;
  totalSpent: number;

  gameDate: GameDate;
  tickSpeed: TickSpeed;

  buildings: BuildingInstance[];
  completedResearch: string[];
  activeResearch: ActiveResearch | null;
  activeResearch2?: ActiveResearch | null; // Second queue, unlocked via 'parallel_research'
  activeServices: ServiceInstance[];
  unlockedLocations: string[];
  resources: Record<string, number>; // ResourceId → quantity

  /** Active mining bonuses from survey probe discoveries */
  miningBonuses?: { locationId: string; resourceId: string; bonusPct: number; expiresAtMonth: number }[];

  eventLog: GameEvent[];
  reports?: GameReport[];
  stats: GameStats;

  // Multiplayer (synced to server)
  companyName?: string;
  lastSyncAt?: number;

  // NPC companies (NPCCompanyState defined in npc-companies.ts)
  // Using inline shape to avoid circular import issues with webpack
  npcCompanies?: {
    id: string;
    name: string;
    strategy: 'aggressive' | 'balanced' | 'conservative';
    money: number;
    totalEarned: number;
    totalSpent: number;
    currentTier: number;
    completedResearch: string[];
    activeServiceIds: string[];
    unlockedLocations: string[];
    resources: Record<string, number>;
    buildingCount: number;
    monthsPlayed: number;
    progressionSpeed: number;
    riskTolerance: number;
    miningFocus: number;
    sellThreshold: number;
  }[];
  npcMarketPressure?: Record<string, number>;

  // Random events & economy
  activeEffects?: { eventId: string; label: string; expiresAtMonth: number; revenueMultiplier: number; costMultiplier: number }[];
  pendingChoice?: { eventId: string; eventName: string; eventIcon: string; eventDescription: string; choices: { label: string; description: string }[] } | null;
  incomeHistory?: number[];

  // Contracts
  availableContracts?: string[];
  activeContracts?: string[];
  completedContracts?: string[];
  lastContractRefresh?: number;

  // Competitive milestones
  claimedMilestones?: Record<string, string>;

  // Refining / Production
  activeRefining?: { recipeId: string; startedAtMs: number; durationSeconds: number } | null;
  craftedProducts?: Record<string, number>; // Product inventory (steel_ingots, etc.)

  // Workforce
  workforce?: {
    engineers: number;
    scientists: number;
    miners: number;
    operators: number;
    // Phase III additions (all optional; game-engine falls back to 0/defaults)
    pilots?: number;
    negotiators?: number;
    securitys?: number;
    medics?: number;
    morale?: number;
    fatigue?: number;
    trainingLevel?: number;
    trainingBudgetPerCrew?: number;
  };

  // Ships
  ships?: {
    instanceId: string;
    definitionId: string;
    name: string;
    status: 'idle' | 'in_transit' | 'loading' | 'mining' | 'refining' | 'building' | 'surveying' | 'expedition';
    currentLocation: string;
    isBuilt: boolean;
    buildStartedAtMs?: number;
    buildDurationSeconds?: number;
    route?: {
      from: string;
      to: string;
      departedAtMs: number;
      arrivalAtMs: number;
      cargo: Record<string, number>;
    };
    miningOperation?: {
      resourceId: string;
      startedAtMs: number;
      locationId: string;
    };
    surveyExpedition?: {
      targetLocation: string;
      startedAtMs: number;
      durationSeconds: number;
    };
    /** V15 (audit Wave D / A4): persistent hull damage 0-0.85. Penalizes
     *  mining rate until auto-repair (money sink) restores the hull. */
    hullDamagePct?: number;
  }[];

  // Prestige (deprecated — kept for migration; see legacy-system.ts)
  prestige?: { level: number; legacyPoints: number; permanentBonuses: { revenueMultiplier: number; buildSpeedMultiplier: number; researchSpeedMultiplier: number; miningMultiplier: number; startingMoney: number } };

  // Legacy system (replaces prestige — permanent bonuses without resets)
  legacy?: {
    completedMilestones: string[];
    stretchLevels: Record<string, number>;
    trackers: {
      totalResourcesMined: number;
      totalContractsCompleted: number;
      totalShipsBuilt: number;
      totalBuildingsCompleted: number;
    };
    legacyPower: number;
    displayTier: 'Pioneer' | 'Colonist' | 'Admiral' | 'Architect' | 'Legend';
  };

  // Corporation tier (1-7, company evolution)
  corporationTier?: number;

  // Weekly events
  currentWeekId?: number;
  weeklyProgress?: Record<string, number>; // metric → value this week

  // Market events
  activeMarketEvents?: { eventId: string; name: string; icon: string; affectedResources: string[]; priceMultiplier: number; startedAtMs: number; expiresAtMs: number }[];

  // Tick counter (for sub-month tick tracking)
  tickCount?: number;

  // Achievements
  earnedAchievements?: string[];
  playerTitle?: string | null;

  // Speed boosts (earned from contracts, leagues, mini-activities).
  // 'mining' added in audit Wave B so mini-activity mining_boost rewards
  // (audit §1c mini-activities) have a mechanical home.
  availableBoosts?: { id: string; type: 'construction' | 'research' | 'mining'; multiplier: number; durationSeconds: number; source: string; label: string }[];
  activeBoosts?: { boostId: string; type: 'construction' | 'research' | 'mining'; multiplier: number; activatedAtMs: number; expiresAtMs: number; label: string }[];

  // Dynamic service pricing (from server — multiplier per service ID)
  servicePriceMultipliers?: Record<string, number>;

  // One Wallet (audit A1): highest server ledger seq already applied into
  // this state's money/resources. Sent with every sync as the ack cursor;
  // the server only returns (and re-returns) entries beyond it, making
  // reconciliation idempotent under sync retries. Lives in GameState so the
  // cursor persists/saves atomically with the balance it describes.
  serverLedgerAck?: number;

  // Timed competitive events
  activeTimedEvents?: {
    templateId: string;
    name: string;
    icon: string;
    category: string;
    description: string;
    targetLabel: string;
    target: number;
    startedAtMs: number;
    expiresAtMs: number;
    rewardAmount: number;
    boostReward?: 'construction' | 'research' | null;
    completed?: boolean;
    completedAtMs?: number;
  }[];
  lastTimedEventSpawnMs?: number;

  // Mini-activities — rotating slot system
  miniActivityCooldowns?: Record<string, number>; // activityId → lastExecutedAtMs
  miniActivitySlots?: string[]; // Currently visible activity IDs (max 4)
  miniActivityLastSpawnMs?: number; // When the last activity was added to slots

  // Personal Megastructures
  megastructures?: {
    definitionId: string;
    currentPhase: number;
    completedPhases: number;
    totalPhases: number;
    status: 'building' | 'paused' | 'complete';
    phaseStartedAtMs?: number;
    phaseDurationSeconds?: number;
    startedAtMs: number;
    completedAtMs?: number;
  }[];

  // Reputation
  reputation?: number;

  // Victory conditions
  earnedVictories?: string[];

  // Specialization
  specialization?: {
    primary: { path: 'launch_magnate' | 'mining_baron' | 'data_overlord' | 'tourism_mogul' | 'fleet_commander' | 'fabrication_savant'; tier: number } | null;
    secondary: { path: 'launch_magnate' | 'mining_baron' | 'data_overlord' | 'tourism_mogul' | 'fleet_commander' | 'fabrication_savant'; tier: number } | null;
    respecCount: number;
  };

  // Daily task session metrics (reset daily, tracked client-side, synced to server)
  dailyMetrics?: {
    date: string; // YYYY-MM-DD
    units_mined: number;
    research_completed: number;
    revenue_earned: number;
    buildings_built: number;
    contracts_completed: number;
    research_started: number;
    rockets_launched: number;
    market_orders_filled: number;
    trade_volume: number;
    buildings_upgraded: number;
    satellites_deployed: number;
    cargo_delivered: number;
    iron_mined: number;
    titanium_mined: number;
    platinum_group_mined: number;
  };

  // Tutorial
  tutorialStep?: number; // 0 = not started, 1-5 = in progress, 6 = completed
  tutorialDismissed?: boolean;

  // Subsidiaries
  subsidiaries?: {
    id: string;
    type: 'sub_launch' | 'sub_mining' | 'sub_telecom' | 'sub_tourism' | 'sub_fabrication' | 'sub_research';
    createdAtMs: number;
    operations: number;
    synergy: number;
    efficiency: number;
  }[];

  // Commanders (hired crew that grant passive bonuses)
  hiredCommanders?: { definitionId: string; hiredAtMs: number }[];
  commanderPool?: { definitionIds: string[]; refreshedAtMs: number };

  // Faction standing (reputation -100 to +100 per faction)
  factionReputation?: Record<string, number>;

  // Delivery contracts — NPC-issued binding resource-delivery agreements
  availableDeliveries?: DeliveryContractState[];
  activeDeliveries?: DeliveryContractState[];
  completedDeliveries?: DeliveryContractState[];
  deliveryPoolRefreshedAtMs?: number;

  // Protected Frontier — new-player onramp shield
  frontierStatus?: 'active' | 'graduated' | 'none';
  frontierEnteredAtMs?: number;
  frontierGraduatedAtMs?: number;

  // Quarterly corporate reports (Wave 8) — QuarterlyReport shape defined in
  // quarterly-reports.ts. Using an inline shape here (matching the
  // npcCompanies precedent above) to avoid circular import issues with
  // webpack. History of automatic public quarterly readouts, one per
  // completed in-game quarter (3 game-months), oldest first.
  quarterlyReports?: {
    id: string;
    quarterIndex: number;
    quarterNumber: number;
    gameYear: number;
    quarterOfYear: number;
    generatedAtMs: number;
    gameDate: GameDate;
    revenue: number;
    costs: number;
    profit: number;
    netWorth: number;
    fleetCount: number;
    buildingCount: number;
    corporationTier: number;
    notableEvents: string[];
    growthRatePct: number | null;
  }[];

  // Starting archetype — the path the player picked at game creation
  startingArchetype?: 'cape_heritage' | 'meridian_signals' | 'tracking_consortium';

  // Modules (Phase IV) — purchased modules + fitted modules per ship
  moduleInventory?: {
    instanceId: string;
    definitionId: string;
    acquiredAtMs: number;
  }[];
  /** Map of shipInstanceId → list of module instanceIds fitted to that ship. */
  fittedModules?: Record<string, string[]>;

  // Corporate governance (Phase VI) — shared treasury + dividend history
  /** Corporate shared wallet. Separate from personal money once multiplayer
   *  alliances exist; mirrors player money in single-player. */
  corporateTreasury?: number;
  dividendHistory?: {
    id: string;
    declaredAtMs: number;
    perShareAmount: number;
    totalPayout: number;
    declaringUserId?: string;
    treasuryBefore: number;
  }[];

  // Exploration (Phase VII) — per-corp discovery database + active claims
  knownAnomalies?: {
    id: string;
    kind: 'rich_deposit' | 'ancient_artifact' | 'derelict_ship' | 'uncharted_asteroid' | 'hazard_zone' | 'alien_signal' | 'gravitational_lens';
    locationId: string;
    discoveredByShipId?: string;
    discoveredAtMs: number;
    fadesAtMs: number;
    claimed: boolean;
    claimedByCorp?: string;
    claimedAtMs?: number;
    title: string;
    summary: string;
    rewards: {
      money?: number;
      miningBonus?: { resourceId: string; bonusPct: number; durationMonths: number };
      unlocksResearchId?: string;
      moduleId?: string;
    };
  }[];
  claimStakes?: {
    id: string;
    anomalyId: string;
    stakedAtMs: number;
    expiresAtMs: number;
    holderProfileId?: string;
  }[];

  // Market depth (Phase V) — open futures positions
  futuresContracts?: {
    id: string;
    holderProfileId?: string;
    resourceSlug: string;
    quantity: number;
    strikePrice: number;
    direction: 'long' | 'short';
    marginLocked: number;
    openedAtMs: number;
    expiresAtMs: number;
    settledAtMs?: number;
    settlementPnL?: number;
    status: 'open' | 'settled' | 'liquidated';
  }[];

  // Interstellar era (V13, Wave 10) — expeditions, colonies, trade routes.
  // Shapes defined below (ExpeditionState etc.) alongside DeliveryContractState;
  // engine logic lives in expeditions.ts. Campaign-loop content per
  // docs/SESSION_DESIGN.md ("Interstellar expansion — Campaign (end-game)").
  expeditions?: ExpeditionState[];
  interstellarColonies?: InterstellarColonyState[];
  interstellarTradeRoutes?: InterstellarTradeRouteState[];

  // ─── Audit Wave B (V14) — server-computed bonuses that reach the tick ────
  // All fields additive + optional; solo/logged-out players never set them
  // and every consumer falls back to neutral values.

  /** Audit A2: alliance bonus aggregate (member count + tier + research +
   *  perks + projects), computed by sync/route.ts and piped through
   *  server-effects.ts. Multiplied into the tick next to tier bonuses. */
  allianceBonuses?: {
    revenueBonus: number;
    miningBonus: number;
    researchBonus: number;
    buildSpeedBonus: number;
    tradeBonus?: number;
  };

  /** Audit A7: per-zone standing (governor / stakeholder) from the server
   *  zone-influence tables. Drives getStakeholderServiceBonus on services in
   *  the zone and the governor tax revenue line. */
  zoneStandings?: {
    zoneSlug: string;
    sharePct: number;
    isGovernor: boolean;
    taxBaseMonthly: number;
  }[];

  /** Audit A8: persisted espionage rewards (EspionageMission.reward) become
   *  consumable perks: market_discount cuts the broker fee (applied
   *  server-side in market/trade), headhunt_voucher discounts the next hire
   *  (workforce.getHireCost). */
  activeIntelPerks?: {
    type: 'market_discount' | 'headhunt_voucher';
    discount: number;
    expiresAtMs: number;
    resources?: string[];
  }[];

  /** Audit §1b "Leagues": seasons whose promotion boost has already been
   *  granted (dedupe cursor for server-effects league boost grants). */
  claimedLeagueBoostSeasonIds?: string[];

  // Hazards (Phase II) — recent hazard log
  recentHazards?: {
    id: string;
    type: 'solar_storm' | 'micrometeorite' | 'pirate_raid' | 'equipment_failure';
    /** V15 (Wave D): severity class of the strike. */
    severity?: 'minor' | 'major' | 'severe';
    locationId: string;
    occurredAtMs: number;
    affectedShipInstanceId?: string;
    affectedBuildingInstanceId?: string;
    targetName?: string;
    damagePct: number;
    mitigatedPct: number;
    destroyed: boolean;
    insurancePayout: number;
    summary: string;
  }[];

  // ─── Audit Waves D+E (V15) — risk pillar + market integrity state ─────────
  // All fields additive + optional with save-migration defaults in
  // save-load.ts; every consumer falls back to a neutral value.

  /** Wave D (A4): corporate hazard insurance policy. While true, monthly
   *  premiums are charged (economic-sinks.calculateInsurancePremium — a real
   *  recurring sink) and destroyed assets pay out their insured value.
   *  Defaults ON (player-protective now that hazards can destroy); toggled
   *  via economic-sinks.setInsuranceActive (UI wave surfaces the switch).
   *  Premiums are waived inside the Protected Frontier. */
  insuranceActive?: boolean;

  /** Wave D (A4 warning cadence): severe hazards forecast for next
   *  game-month at the player's asset locations. Refreshed each month-end;
   *  surfaced in the event log now and as map overlays in the UI wave. */
  hazardWarnings?: {
    id: string;
    type: 'solar_storm' | 'micrometeorite' | 'pirate_raid' | 'equipment_failure';
    severity: 'minor' | 'major' | 'severe';
    locationId: string;
    forecastMonthIndex: number;
    issuedAtMs: number;
    summary: string;
  }[];

  /** Wave E (A5-i/A5-iv): market flows awaiting transmission to the shared
   *  market via sync — mined units (supply pressure) and net NPC trade flow.
   *  Drained after each successful sync (market-pressure.ts). */
  pendingMarketFlows?: {
    mined: Record<string, number>;
    npc: Record<string, number>;
  };

  /** Wave E (C5 §7): cash-reserve requirement status for T5+ corporations.
   *  Below a 3-month expense runway, services run at reduced efficiency.
   *  Computed at month-end; multiplier applied to service revenue. */
  reserveStatus?: {
    status: 'healthy' | 'warning' | 'critical';
    efficiencyMultiplier: number;
    requiredReserve: number;
  };
}

export interface DeliveryContractState {
  id: string;
  issuerKind: 'faction' | 'player';
  issuerFactionId?: string;
  issuerPlayerName?: string;
  title: string;
  resourceId: string;
  quantity: number;
  paymentMoney: number;
  deadlineAtMs: number;
  reputationOnComplete: number;
  reputationOnDefault: number;
  status: 'open' | 'accepted' | 'completed' | 'defaulted' | 'cancelled';
  offeredAtMs: number;
  acceptedAtMs?: number;
  completedAtMs?: number;
  defaultedAtMs?: number;
}

// ─── Interstellar era (Wave 10 — expeditions.ts) ────────────────────────────
// Per CLAUDE.md "Long-horizon expansion": solar-system gameplay is the
// mid-game; interstellar exploration / colonization / trade is the end-game.
// These types are defined here (like DeliveryContractState) so GameState can
// reference them without circular imports; all logic lives in expeditions.ts.

export type ExpeditionPhase =
  | 'outbound'     // in jump-transit to the target system
  | 'exploring'    // arrived; surveying — the colonize-or-return decision window
  | 'returning'    // in jump-transit back to Sol
  | 'colonizing'   // ship committed to founding a colony (terminal for the ship)
  | 'completed'    // returned to Sol; findings + cargo delivered
  | 'lost';        // destroyed en route by hazards (insurance may have paid out)

export interface ExpeditionHazardEntry {
  monthIndex: number;       // expedition month the hazard struck
  type: 'radiation_burst' | 'debris_impact' | 'systems_failure';
  damagePct: number;        // 0-1 hull integrity lost after mitigation
  mitigatedPct: number;     // 0-1 fraction of raw damage absorbed
  summary: string;
}

export interface ExpeditionOutcome {
  surveyDataPayout: number;                 // $ credited on return
  resourceSamples: Record<string, number>;  // cargo delivered to inventory on return
  colonySuitability: number;                // 0-1 — scales colony founding results
  firstContactFactionId?: string;           // faction met on arrival (lore hook)
  summary: string;
}

export interface ExpeditionState {
  id: string;
  targetSystemId: string;          // key into INTERSTELLAR_SYSTEMS
  shipInstanceId: string;          // committed ship (status 'expedition' while away)
  shipDefinitionId: string;
  crew: number;                    // workforce committed (returned on completion, lost with the ship)
  /** Which workforce pools the crew was drawn from (returned to the same pools). */
  crewBreakdown?: Record<string, number>;
  phase: ExpeditionPhase;
  launchedAtMs: number;
  /** Total game-months elapsed since game start (quarterly-reports convention) at launch. */
  launchGameMonth: number;
  /** Game-months of one-way transit (distanceLy × GAME_MONTHS_PER_LY). */
  outboundMonths: number;
  /** Game-months spent surveying at the destination before auto-return. */
  exploreMonths: number;
  /** Expedition-months processed so far (advanced by processExpeditionTick). */
  monthsElapsed: number;
  /** Deterministic RNG seed fixed at launch — hazards & outcomes are replayable. */
  seed: number;
  /** Upfront mitigation choices (CLAUDE.md: loss must be insurable/mitigable). */
  insured: boolean;
  insurancePremiumPaid: number;
  extraShielding: boolean;
  totalCost: number;               // full launch cost (basis for insurance payout)
  hullIntegrity: number;           // 1.0 → 0; expedition lost at ≤ 0
  hazardLog: ExpeditionHazardEntry[];
  outcome?: ExpeditionOutcome;     // rolled on arrival (start of 'exploring')
  colonyId?: string;               // set if this expedition founded a colony
  completedAtMs?: number;
}

export interface InterstellarColonyState {
  id: string;
  systemId: string;
  name: string;
  foundedAtMs: number;
  foundedGameMonth: number;
  /** Colonists on site. Grows monthly, capped by infrastructure. */
  population: number;
  /** 1-5. Each level raises production + population cap. */
  infrastructureLevel: number;
  upgradeInProgress?: { targetLevel: number; completesAtGameMonth: number } | null;
  /** ResourceIds this colony produces (drawn from the system's knownResources + exotic_fuel). */
  localResources: string[];
  /** Local warehouse — production accrues here; trade routes ship it to Sol. */
  stockpile: Record<string, number>;
  /** Total game-months processed for this colony (production cadence bookkeeping). */
  lastProcessedGameMonth: number;
  /** 0-1 from the founding expedition's survey — scales production. */
  suitability: number;
}

export interface InterstellarTradeRouteState {
  id: string;
  colonyId: string;
  systemId: string;
  resourceId: string;
  establishedAtMs: number;
  establishedGameMonth: number;
  /** One-way shipment transit in game-months (same physics as expeditions). */
  transitMonths: number;
  /** Game-months between departures. */
  cycleMonths: number;
  nextDepartureGameMonth: number;
  /** Shipments currently in transit toward Sol. */
  inTransit: { quantity: number; departedGameMonth: number; arrivesGameMonth: number }[];
  /** $ deducted per departure — logistics cost money (CLAUDE.md spatial strategy). */
  logisticsFeePerShipment: number;
  status: 'active' | 'suspended';
  totalDelivered: number;
}

// ─── UI Tabs ────────────────────────────────────────────────────────────────

export type GameTab = 'dashboard' | 'build' | 'research' | 'map' | 'services' | 'fleet' | 'crafting' | 'workforce' | 'market' | 'intelligence' | 'contracts' | 'alliance' | 'bounties' | 'leaderboard' | 'rivals' | 'leagues' | 'bidding' | 'seasons' | 'territory' | 'speedruns' | 'espionage' | 'megaproject' | 'megastructures' | 'reports' | 'commanders' | 'factions' | 'spatial' | 'diplomacy' | 'modules' | 'discoveries' | 'interstellar' | 'subsidiaries' | 'specialization' | 'victory' | 'futures' | 'economy';
