export interface BusinessModelTemplate {
  id: string;
  name: string;
  sector: string;
  description: string;
  revenueModel: string;
  keyMetrics: { label: string; benchmark: string; description: string }[];
  costStructure: { category: string; percentage: number; description: string }[];
  unitEconomics: { metric: string; value: string; notes: string }[];
  fundingBenchmarks: { stage: string; typical: string }[];
  breakEvenEstimate: string;
  icon: string;
}

export const BUSINESS_MODELS: BusinessModelTemplate[] = [
  {
    id: 'launch-service',
    name: 'Launch-as-a-Service',
    sector: 'launch',
    description: 'Providing dedicated or rideshare launch services to orbit. Revenue per launch, scaling through reusability and cadence.',
    revenueModel: 'Price per launch (dedicated) or price per kg (rideshare). Dedicated small-sat: $6M-$12M/launch. Rideshare: $5,000-$15,000/kg.',
    keyMetrics: [
      { label: 'Price per kg to LEO', benchmark: '$2,500-$15,000', description: 'Key competitive metric. Falcon 9 rideshare ~$5,000/kg.' },
      { label: 'Launch cadence', benchmark: '4-12 launches/year at maturity', description: 'Revenue scaling depends on production rate and turnaround time.' },
      { label: 'Success rate', benchmark: '>95% required', description: 'Insurance and customer confidence require high reliability.' },
      { label: 'Vehicle reusability', benchmark: '10+ flights/booster', description: 'Key to unit economics. SpaceX averages 15+ reuses per booster.' },
    ],
    costStructure: [
      { category: 'Vehicle Production', percentage: 35, description: 'First stage, second stage, fairing manufacturing' },
      { category: 'Propellant & Operations', percentage: 15, description: 'Fuel, launch operations, range costs' },
      { category: 'Recovery & Refurbishment', percentage: 10, description: 'Landing, transport, inspection, refurb' },
      { category: 'Insurance', percentage: 8, description: 'Launch insurance and third-party liability' },
      { category: 'R&D', percentage: 20, description: 'Ongoing vehicle improvements and next-gen development' },
      { category: 'SG&A', percentage: 12, description: 'Sales, regulatory, admin, facilities' },
    ],
    unitEconomics: [
      { metric: 'Revenue per launch (dedicated)', value: '$60M-$70M', notes: 'Falcon 9 list price ~$67M' },
      { metric: 'COGS per launch (reusable)', value: '$15M-$28M', notes: 'Significant reduction with reuse' },
      { metric: 'Gross margin (reusable)', value: '50-70%', notes: 'First flights have lower margin due to new hardware' },
      { metric: 'Break-even cadence', value: '4-6 launches/year', notes: 'With fully reusable first stage' },
    ],
    fundingBenchmarks: [
      { stage: 'Seed', typical: '$5M-$15M' },
      { stage: 'Series A', typical: '$30M-$80M' },
      { stage: 'Series B', typical: '$100M-$300M' },
      { stage: 'To first launch', typical: '$300M-$1B+' },
    ],
    breakEvenEstimate: '5-8 years from founding, 2-3 years after first commercial launch',
    icon: '\u{1F680}',
  },
  {
    id: 'earth-observation',
    name: 'Earth Observation Data Service',
    sector: 'earth_observation',
    description: 'Operating an imaging constellation and selling data/analytics. Subscription + per-image pricing.',
    revenueModel: 'Subscription tiers ($5K-$500K/year) + per-tasking fees ($500-$5,000/image). Government contracts for assured access.',
    keyMetrics: [
      { label: 'Revisit rate', benchmark: 'Daily for 100+ satellites', description: 'Key differentiator. Higher revisit = more value.' },
      { label: 'Resolution', benchmark: '0.3m-5m optical, 1m SAR', description: 'Sub-meter drives premium pricing.' },
      { label: 'ARR per satellite', benchmark: '$2M-$10M/year', description: 'Revenue generated per satellite in constellation.' },
      { label: 'Net revenue retention', benchmark: '110-130%', description: 'Upsell to higher tiers and additional areas of interest.' },
    ],
    costStructure: [
      { category: 'Satellite Manufacturing', percentage: 25, description: 'Build cost amortized over satellite life' },
      { category: 'Launch', percentage: 15, description: 'Rideshare deployment costs' },
      { category: 'Ground Stations', percentage: 10, description: 'Downlink network operations' },
      { category: 'Cloud/Processing', percentage: 15, description: 'Data processing, storage, distribution' },
      { category: 'R&D', percentage: 20, description: 'Analytics, AI/ML, next-gen sensors' },
      { category: 'SG&A', percentage: 15, description: 'Sales, marketing, government BD' },
    ],
    unitEconomics: [
      { metric: 'Satellite cost', value: '$1M-$15M each', notes: 'SmallSats ~$1-3M, larger high-res ~$10-15M' },
      { metric: 'Annual operating cost per sat', value: '$500K-$2M', notes: 'Ground ops, cloud, insurance' },
      { metric: 'Average contract value', value: '$50K-$2M/year', notes: 'Mix of SMB, enterprise, and government' },
      { metric: 'CAC', value: '$5K-$50K', notes: 'Government contracts have higher BD costs' },
    ],
    fundingBenchmarks: [
      { stage: 'Seed', typical: '$3M-$10M' },
      { stage: 'Series A', typical: '$15M-$50M' },
      { stage: 'Series B', typical: '$50M-$150M' },
      { stage: 'To first satellite', typical: '$15M-$40M' },
    ],
    breakEvenEstimate: '4-6 years from first satellite, typically after 10+ satellites on orbit',
    icon: '\u{1F6F0}\uFE0F',
  },
  {
    id: 'satellite-communications',
    name: 'Satellite Communications / Broadband',
    sector: 'communications',
    description: 'Operating a communications constellation for broadband, IoT, or enterprise connectivity.',
    revenueModel: 'Consumer subscriptions ($50-$120/month), enterprise plans ($500-$50K/month), government contracts, maritime/aviation wholesale.',
    keyMetrics: [
      { label: 'ARPU (consumer)', benchmark: '$80-$120/month', description: 'Average revenue per consumer subscriber.' },
      { label: 'Subscribers per satellite', benchmark: '5,000-20,000', description: 'Depends on capacity and beam design.' },
      { label: 'Capacity utilization', benchmark: '40-70%', description: 'Higher utilization improves unit economics.' },
      { label: 'Churn rate', benchmark: '1-3% monthly', description: 'Lower in areas without terrestrial alternatives.' },
    ],
    costStructure: [
      { category: 'Constellation Build', percentage: 30, description: 'Satellite manufacturing amortized over life' },
      { category: 'Launch', percentage: 15, description: 'Deployment and replenishment launches' },
      { category: 'Ground Network', percentage: 15, description: 'Gateway stations, PoPs, interconnects' },
      { category: 'User Terminals', percentage: 15, description: 'Subsidized customer equipment' },
      { category: 'Operations', percentage: 10, description: 'NOC, TT&C, spectrum management' },
      { category: 'SG&A', percentage: 15, description: 'Customer acquisition, billing, support' },
    ],
    unitEconomics: [
      { metric: 'Satellite cost', value: '$250K-$1M each (LEO)', notes: 'Mass production drives down cost' },
      { metric: 'User terminal cost', value: '$300-$2,500', notes: 'Often subsidized. Starlink Dish ~$599' },
      { metric: 'ARPU', value: '$80-$120/month consumer', notes: 'Enterprise 10-100x higher' },
      { metric: 'CAC', value: '$200-$800', notes: 'Including terminal subsidy and marketing' },
    ],
    fundingBenchmarks: [
      { stage: 'Seed', typical: '$5M-$20M' },
      { stage: 'Series A', typical: '$50M-$200M' },
      { stage: 'Series B+', typical: '$200M-$1B+' },
      { stage: 'Full constellation', typical: '$5B-$15B' },
    ],
    breakEvenEstimate: '5-10 years. Requires significant subscriber base (500K+) to cover constellation cost.',
    icon: '\u{1F4E1}',
  },
  {
    id: 'ground-station-network',
    name: 'Ground Station Network-as-a-Service',
    sector: 'ground_segment',
    description: 'Operating a global ground station network and selling antenna time to satellite operators.',
    revenueModel: 'Per-pass pricing ($5-$50/pass), monthly subscriptions, enterprise dedicated capacity.',
    keyMetrics: [
      { label: 'Antenna utilization', benchmark: '30-60%', description: 'Key driver of profitability.' },
      { label: 'Stations worldwide', benchmark: '10-50+ for global coverage', description: 'More stations = lower latency to downlink.' },
      { label: 'Customers per station', benchmark: '20-100+', description: 'Multi-tenant model spreads costs.' },
      { label: 'Revenue per antenna', benchmark: '$200K-$1M/year', description: 'Depends on size and band.' },
    ],
    costStructure: [
      { category: 'Station Infrastructure', percentage: 25, description: 'Antennas, radomes, facilities' },
      { category: 'Connectivity', percentage: 15, description: 'Fiber backhaul, internet transit' },
      { category: 'Operations', percentage: 20, description: 'Site staff, maintenance, monitoring' },
      { category: 'Software Platform', percentage: 15, description: 'Scheduling, API, customer portal' },
      { category: 'Site Leases', percentage: 10, description: 'Land/rooftop leases at remote locations' },
      { category: 'SG&A', percentage: 15, description: 'Sales, marketing, admin' },
    ],
    unitEconomics: [
      { metric: 'Station build cost', value: '$200K-$2M per site', notes: 'Depends on antenna size and band' },
      { metric: 'Per-pass price', value: '$5-$50', notes: 'Volume discounts for committed capacity' },
      { metric: 'Monthly subscription', value: '$2K-$20K', notes: 'Guaranteed passes per day' },
      { metric: 'Gross margin', value: '50-70%', notes: 'High operating leverage once deployed' },
    ],
    fundingBenchmarks: [
      { stage: 'Seed', typical: '$2M-$5M' },
      { stage: 'Series A', typical: '$10M-$30M' },
      { stage: 'Series B', typical: '$30M-$80M' },
    ],
    breakEvenEstimate: '2-4 years from first station deployment. Individual stations break even at 40%+ utilization.',
    icon: '\u{1F4E1}',
  },
  {
    id: 'space-tourism',
    name: 'Space Tourism Operator',
    sector: 'space_tourism',
    description: 'Providing suborbital or orbital space experiences for paying customers.',
    revenueModel: 'Per-seat pricing. Suborbital: $250K-$450K/seat. Orbital: $25M-$55M/seat. Space station stays: $35K-$55K/night.',
    keyMetrics: [
      { label: 'Revenue per flight', benchmark: '$1.5M-$250M', description: 'Suborbital (~6 pax) vs orbital (~4 pax).' },
      { label: 'Flight cadence', benchmark: '12-52 flights/year', description: 'Suborbital can achieve weekly cadence.' },
      { label: 'Load factor', benchmark: '85-100%', description: 'High demand keeping most flights full.' },
      { label: 'Safety record', benchmark: '100% crew safety', description: 'Single incident can halt operations for years.' },
    ],
    costStructure: [
      { category: 'Vehicle Operations', percentage: 30, description: 'Propellant, turnaround, maintenance' },
      { category: 'Vehicle Amortization', percentage: 20, description: 'Build cost spread over vehicle life' },
      { category: 'Training & Experience', percentage: 10, description: 'Customer training, pre-flight preparation' },
      { category: 'Insurance', percentage: 15, description: 'High passenger liability premiums' },
      { category: 'Facilities', percentage: 10, description: 'Spaceport, customer center, operations' },
      { category: 'SG&A', percentage: 15, description: 'Marketing, sales (high-net-worth targeting)' },
    ],
    unitEconomics: [
      { metric: 'Ticket price (suborbital)', value: '$250K-$450K', notes: 'Virgin Galactic ~$450K, Blue Origin ~$300K' },
      { metric: 'Cost per suborbital flight', value: '$500K-$2M', notes: 'Operating costs per flight' },
      { metric: 'Ticket price (orbital)', value: '$25M-$55M', notes: 'SpaceX Crew Dragon private missions' },
      { metric: 'Addressable market', value: '~2.5M people globally', notes: 'UHNW individuals + bucket-list spenders' },
    ],
    fundingBenchmarks: [
      { stage: 'Seed', typical: '$10M-$30M' },
      { stage: 'Series A', typical: '$50M-$200M' },
      { stage: 'To first flight', typical: '$500M-$1B+' },
    ],
    breakEvenEstimate: 'Suborbital: 3-5 years at 30+ flights/year. Orbital: requires ~10 flights/year.',
    icon: '\u{1F9D1}\u200D\u{1F680}',
  },
  {
    id: 'in-space-manufacturing',
    name: 'In-Space Manufacturing',
    sector: 'in_space',
    description: 'Manufacturing products in microgravity (fiber optics, pharmaceuticals, semiconductors) and returning them to Earth.',
    revenueModel: 'Price per unit of manufactured product. ZBLAN fiber: $1M-$3M/km. Bioprinted organs: $100K-$500K/unit.',
    keyMetrics: [
      { label: 'Yield per mission', benchmark: '$5M-$50M in product value', description: 'Revenue generated per ISS or free-flyer mission.' },
      { label: 'Mission cadence', benchmark: '4-12 missions/year', description: 'Depends on platform access and production speed.' },
      { label: 'Product quality premium', benchmark: '10-1000x terrestrial', description: 'Microgravity products command massive premiums.' },
      { label: 'Return mass cost', benchmark: '$10K-$50K/kg', description: 'Key constraint on product viability.' },
    ],
    costStructure: [
      { category: 'Platform Access', percentage: 30, description: 'ISS rack time or free-flyer costs' },
      { category: 'Launch/Return', percentage: 25, description: 'Up-mass and down-mass transportation' },
      { category: 'Manufacturing Equipment', percentage: 15, description: 'Space-rated production hardware' },
      { category: 'R&D', percentage: 20, description: 'Process development and optimization' },
      { category: 'SG&A', percentage: 10, description: 'Customer development, IP protection' },
    ],
    unitEconomics: [
      { metric: 'ISS rack rent', value: '$7.5M-$12M/year', notes: 'Per Express Rack equivalent' },
      { metric: 'ZBLAN fiber value', value: '$1M-$3M per km', notes: 'vs $150/km terrestrial equivalent' },
      { metric: 'Up-mass cost', value: '$3K-$10K/kg', notes: 'SpaceX Dragon rideshare rates' },
      { metric: 'Down-mass cost', value: '$10K-$50K/kg', notes: 'Limited return capacity premium' },
    ],
    fundingBenchmarks: [
      { stage: 'Seed', typical: '$3M-$10M' },
      { stage: 'Series A', typical: '$15M-$50M' },
      { stage: 'To first production', typical: '$30M-$80M' },
    ],
    breakEvenEstimate: '4-7 years. First revenues from ISS experiments, scaling with dedicated free-flyer platforms.',
    icon: '\u{1F3ED}',
  },
  {
    id: 'debris-removal',
    name: 'Active Debris Removal / SSA Service',
    sector: 'debris_removal',
    description: 'Providing space situational awareness data and active debris removal services.',
    revenueModel: 'SSA subscriptions ($10K-$500K/year), debris removal per-object contracts ($5M-$30M), government programs.',
    keyMetrics: [
      { label: 'Objects tracked', benchmark: '100K+', description: 'More objects tracked = higher value proposition.' },
      { label: 'Conjunction alerts/day', benchmark: '100-1000', description: 'Drives subscription value for operators.' },
      { label: 'Debris removals/year', benchmark: '2-10 missions', description: 'Ramping up from demonstrations.' },
      { label: 'Government contracts', benchmark: '60-80% of revenue', description: 'Military SSA spending growing rapidly.' },
    ],
    costStructure: [
      { category: 'Sensor Network', percentage: 25, description: 'Radar, optical, and space-based sensors' },
      { category: 'Data Processing', percentage: 15, description: 'AI/ML catalog maintenance, orbit determination' },
      { category: 'Removal Vehicle Build', percentage: 20, description: 'Spacecraft for ADR missions' },
      { category: 'Launch', percentage: 15, description: 'Deploying removal vehicles' },
      { category: 'R&D', percentage: 15, description: 'Capture mechanisms, guidance systems' },
      { category: 'SG&A', percentage: 10, description: 'Government BD, commercial sales' },
    ],
    unitEconomics: [
      { metric: 'SSA subscription', value: '$10K-$500K/year', notes: 'Per-customer based on fleet size' },
      { metric: 'Debris removal contract', value: '$5M-$30M per object', notes: 'Government-funded initially' },
      { metric: 'Sensor site cost', value: '$500K-$5M', notes: 'Varies by sensor type' },
      { metric: 'Removal vehicle cost', value: '$10M-$50M', notes: 'Including launch' },
    ],
    fundingBenchmarks: [
      { stage: 'Seed', typical: '$3M-$8M' },
      { stage: 'Series A', typical: '$15M-$50M' },
      { stage: 'Series B', typical: '$50M-$100M' },
    ],
    breakEvenEstimate: 'SSA: 2-4 years. ADR: 5-8 years (requires government anchor contracts).',
    icon: '\u{1F9F9}',
  },
  {
    id: 'satellite-iot',
    name: 'Satellite IoT / M2M',
    sector: 'iot',
    description: 'Providing IoT connectivity via satellite for remote assets (agriculture, maritime, logistics, energy).',
    revenueModel: 'Per-device per-month ($1-$15/device). Enterprise fleet pricing. Data plans by volume.',
    keyMetrics: [
      { label: 'Connected devices', benchmark: '100K-5M+', description: 'Scale is key to profitability.' },
      { label: 'ARPU per device', benchmark: '$3-$15/month', description: 'Low ARPU requires massive scale.' },
      { label: 'Data per message', benchmark: '10-100 bytes', description: 'Small messages, very high volume.' },
      { label: 'Latency', benchmark: '15 min - 2 hours', description: 'Acceptable for most IoT use cases.' },
    ],
    costStructure: [
      { category: 'Constellation', percentage: 25, description: 'Small satellites, often 3U-6U CubeSats' },
      { category: 'Launch', percentage: 10, description: 'Rideshare deployments' },
      { category: 'Ground & Cloud', percentage: 20, description: 'Ground stations, data routing, APIs' },
      { category: 'Device Modules', percentage: 15, description: 'Satellite modems for customer devices' },
      { category: 'R&D', percentage: 15, description: 'Protocol development, power optimization' },
      { category: 'SG&A', percentage: 15, description: 'Channel partnerships, enterprise sales' },
    ],
    unitEconomics: [
      { metric: 'Satellite cost', value: '$300K-$1M each', notes: 'CubeSat-class, mass produced' },
      { metric: 'Module cost', value: '$10-$50', notes: 'Satellite modem per device' },
      { metric: 'Monthly ARPU', value: '$3-$15', notes: 'Scale matters enormously' },
      { metric: 'Break-even devices', value: '500K-2M connected', notes: 'High fixed costs, low marginal' },
    ],
    fundingBenchmarks: [
      { stage: 'Seed', typical: '$2M-$5M' },
      { stage: 'Series A', typical: '$10M-$30M' },
      { stage: 'Series B', typical: '$30M-$80M' },
    ],
    breakEvenEstimate: '3-5 years with 500K+ connected devices. Channel partnerships accelerate adoption.',
    icon: '\u{1F4F6}',
  },
];
