import prisma from './db';

export interface CompanyData {
  slug: string;
  name: string;
  description: string;
  country: string;
  headquarters?: string;
  founded?: number;
  website?: string;
  logoUrl?: string;
  isPublic: boolean;
  ticker?: string;
  exchange?: string;
  marketCap?: number;
  isPreIPO?: boolean;
  expectedIPODate?: string;
  lastFundingRound?: string;
  lastFundingAmount?: number;
  lastFundingDate?: string;
  totalFunding?: number;
  nextFundingRound?: string;
  valuation?: number;
  focusAreas: string[];
  subSectors?: string[];
  employeeCount?: number;
  revenueEstimate?: number;
}

// Initial company data
const SPACE_COMPANIES: CompanyData[] = [
  // US Public Companies
  {
    slug: 'rocket-lab',
    name: 'Rocket Lab USA',
    description: 'End-to-end space company providing launch services, spacecraft manufacturing, and on-orbit management.',
    country: 'USA',
    headquarters: 'Long Beach, CA',
    founded: 2006,
    website: 'https://www.rocketlabusa.com',
    isPublic: true,
    ticker: 'RKLB',
    exchange: 'NASDAQ',
    marketCap: 11.2,
    focusAreas: ['launch_provider', 'spacecraft', 'satellite_components'],
    subSectors: ['small_launch', 'electron', 'neutron', 'photon'],
    employeeCount: 2000,
  },
  {
    slug: 'intuitive-machines',
    name: 'Intuitive Machines',
    description: 'Space exploration company focused on lunar access and services.',
    country: 'USA',
    headquarters: 'Houston, TX',
    founded: 2013,
    website: 'https://www.intuitivemachines.com',
    isPublic: true,
    ticker: 'LUNR',
    exchange: 'NASDAQ',
    marketCap: 1.8,
    focusAreas: ['lunar_services', 'lunar_landers', 'space_infrastructure'],
    subSectors: ['clps', 'nova_c', 'lunar_data'],
    employeeCount: 400,
  },
  {
    slug: 'ast-spacemobile',
    name: 'AST SpaceMobile',
    description: 'Building the first space-based cellular broadband network accessible by standard smartphones.',
    country: 'USA',
    headquarters: 'Midland, TX',
    founded: 2017,
    website: 'https://ast-science.com',
    isPublic: true,
    ticker: 'ASTS',
    exchange: 'NASDAQ',
    marketCap: 7.5,
    focusAreas: ['space_broadband', 'satellites', 'telecommunications'],
    subSectors: ['direct_to_cell', 'bluebird_satellites'],
    employeeCount: 350,
  },
  {
    slug: 'planet-labs',
    name: 'Planet Labs PBC',
    description: 'Earth imaging company operating the largest fleet of Earth observation satellites.',
    country: 'USA',
    headquarters: 'San Francisco, CA',
    founded: 2010,
    website: 'https://www.planet.com',
    isPublic: true,
    ticker: 'PL',
    exchange: 'NYSE',
    marketCap: 1.2,
    focusAreas: ['earth_observation', 'satellites', 'geospatial_data'],
    subSectors: ['dove_satellites', 'skysat', 'analytics'],
    employeeCount: 700,
  },
  {
    slug: 'redwire-space',
    name: 'Redwire Corporation',
    description: 'Space infrastructure company providing critical components and systems for space missions.',
    country: 'USA',
    headquarters: 'Jacksonville, FL',
    founded: 2020,
    website: 'https://redwirespace.com',
    isPublic: true,
    ticker: 'RDW',
    exchange: 'NYSE',
    marketCap: 0.85,
    focusAreas: ['space_infrastructure', 'spacecraft_components', 'in_space_manufacturing'],
    subSectors: ['solar_arrays', '3d_printing', 'sensors'],
    employeeCount: 700,
  },
  {
    slug: 'blacksky',
    name: 'BlackSky Technology',
    description: 'Real-time geospatial intelligence company providing satellite imagery and analytics.',
    country: 'USA',
    headquarters: 'Herndon, VA',
    founded: 2014,
    website: 'https://www.blacksky.com',
    isPublic: true,
    ticker: 'BKSY',
    exchange: 'NYSE',
    marketCap: 0.45,
    focusAreas: ['earth_observation', 'geospatial_intelligence', 'satellites'],
    subSectors: ['real_time_imagery', 'ai_analytics', 'spectra'],
    employeeCount: 300,
  },
  {
    slug: 'spire-global',
    name: 'Spire Global',
    description: 'Space-to-cloud data and analytics company providing maritime, aviation, and weather tracking.',
    country: 'USA',
    headquarters: 'Vienna, VA',
    founded: 2012,
    website: 'https://spire.com',
    isPublic: true,
    ticker: 'SPIR',
    exchange: 'NYSE',
    marketCap: 0.35,
    focusAreas: ['satellites', 'data_analytics', 'weather'],
    subSectors: ['maritime_tracking', 'aviation', 'rf_sensing'],
    employeeCount: 500,
  },
  {
    slug: 'lockheed-martin',
    name: 'Lockheed Martin',
    description: 'Global aerospace, defense, and security company with major space systems division.',
    country: 'USA',
    headquarters: 'Bethesda, MD',
    founded: 1995,
    website: 'https://www.lockheedmartin.com',
    isPublic: true,
    ticker: 'LMT',
    exchange: 'NYSE',
    marketCap: 135,
    focusAreas: ['defense', 'satellites', 'spacecraft', 'launch_provider'],
    subSectors: ['orion', 'gps_satellites', 'missile_defense', 'space_systems'],
    employeeCount: 116000,
    revenueEstimate: 67000,
  },
  {
    slug: 'northrop-grumman',
    name: 'Northrop Grumman',
    description: 'Aerospace and defense company providing space systems, launch vehicles, and satellites.',
    country: 'USA',
    headquarters: 'Falls Church, VA',
    founded: 1994,
    website: 'https://www.northropgrumman.com',
    isPublic: true,
    ticker: 'NOC',
    exchange: 'NYSE',
    marketCap: 75,
    focusAreas: ['defense', 'launch_provider', 'satellites', 'spacecraft'],
    subSectors: ['antares', 'cygnus', 'james_webb', 'missile_systems'],
    employeeCount: 95000,
    revenueEstimate: 40000,
  },
  {
    slug: 'honeywell',
    name: 'Honeywell Aerospace',
    description: 'Diversified technology company with major aerospace division supplying avionics and propulsion systems.',
    country: 'USA',
    headquarters: 'Charlotte, NC',
    founded: 1906,
    website: 'https://aerospace.honeywell.com',
    isPublic: true,
    ticker: 'HON',
    exchange: 'NASDAQ',
    marketCap: 145,
    focusAreas: ['aerospace_components', 'avionics', 'propulsion'],
    subSectors: ['navigation', 'satellite_communications', 'space_sensors'],
    employeeCount: 97000,
    revenueEstimate: 36000,
  },
  {
    slug: 'heico',
    name: 'HEICO Corporation',
    description: 'Aerospace and electronics company providing components for commercial and defense markets.',
    country: 'USA',
    headquarters: 'Hollywood, FL',
    founded: 1957,
    website: 'https://www.heico.com',
    isPublic: true,
    ticker: 'HEI',
    exchange: 'NYSE',
    marketCap: 32,
    focusAreas: ['aerospace_components', 'electronics', 'defense'],
    subSectors: ['replacement_parts', 'electronic_technologies'],
    employeeCount: 9500,
    revenueEstimate: 3000,
  },

  // US Private Companies
  {
    slug: 'spacex',
    name: 'SpaceX',
    description: 'Leading private aerospace company developing rockets and spacecraft for orbital and interplanetary missions.',
    country: 'USA',
    headquarters: 'Hawthorne, CA',
    founded: 2002,
    website: 'https://www.spacex.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD - Starlink spinoff possible',
    lastFundingRound: 'Series N',
    lastFundingAmount: 750,
    lastFundingDate: '2024',
    totalFunding: 10000,
    valuation: 210,
    focusAreas: ['launch_provider', 'spacecraft', 'space_broadband', 'interplanetary'],
    subSectors: ['falcon_9', 'falcon_heavy', 'starship', 'starlink', 'dragon'],
    employeeCount: 13000,
    revenueEstimate: 9000,
  },
  {
    slug: 'blue-origin',
    name: 'Blue Origin',
    description: 'Aerospace company developing reusable launch vehicles and space tourism services.',
    country: 'USA',
    headquarters: 'Kent, WA',
    founded: 2000,
    website: 'https://www.blueorigin.com',
    isPublic: false,
    isPreIPO: false,
    lastFundingRound: 'Private (Bezos funded)',
    totalFunding: 15000,
    valuation: 28,
    focusAreas: ['launch_provider', 'space_tourism', 'lunar_services'],
    subSectors: ['new_shepard', 'new_glenn', 'blue_moon', 'be4_engine'],
    employeeCount: 11000,
  },
  {
    slug: 'sierra-space',
    name: 'Sierra Space',
    description: 'Commercial space company developing Dream Chaser spaceplane and orbital platforms.',
    country: 'USA',
    headquarters: 'Louisville, CO',
    founded: 2021,
    website: 'https://www.sierraspace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: '2025-2026',
    lastFundingRound: 'Series B',
    lastFundingAmount: 1400,
    lastFundingDate: '2023',
    totalFunding: 2000,
    valuation: 5.3,
    focusAreas: ['spacecraft', 'space_stations', 'cargo_transport'],
    subSectors: ['dream_chaser', 'orbital_reef', 'life_habitat'],
    employeeCount: 1500,
  },
  {
    slug: 'axiom-space',
    name: 'Axiom Space',
    description: 'Building the world\'s first commercial space station and providing ISS missions.',
    country: 'USA',
    headquarters: 'Houston, TX',
    founded: 2016,
    website: 'https://www.axiomspace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: '2026-2027',
    lastFundingRound: 'Series C',
    lastFundingAmount: 350,
    lastFundingDate: '2023',
    totalFunding: 600,
    valuation: 3.5,
    focusAreas: ['space_stations', 'space_tourism', 'astronaut_training'],
    subSectors: ['axiom_station', 'private_missions', 'spacesuits'],
    employeeCount: 700,
  },
  {
    slug: 'vast-space',
    name: 'Vast',
    description: 'Developing artificial gravity space stations for long-duration human spaceflight.',
    country: 'USA',
    headquarters: 'Long Beach, CA',
    founded: 2021,
    website: 'https://www.vastspace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series A',
    lastFundingAmount: 300,
    lastFundingDate: '2023',
    totalFunding: 400,
    valuation: 1.2,
    focusAreas: ['space_stations', 'artificial_gravity', 'life_support'],
    subSectors: ['haven_1', 'rotating_stations'],
    employeeCount: 200,
  },
  {
    slug: 'relativity-space',
    name: 'Relativity Space',
    description: 'Aerospace company using 3D printing to manufacture rockets.',
    country: 'USA',
    headquarters: 'Long Beach, CA',
    founded: 2015,
    website: 'https://www.relativityspace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: '2026-2027',
    lastFundingRound: 'Series E',
    lastFundingAmount: 650,
    lastFundingDate: '2023',
    totalFunding: 1300,
    valuation: 4.2,
    focusAreas: ['launch_provider', 'manufacturing'],
    subSectors: ['terran_r', '3d_printing', 'stargate'],
    employeeCount: 1000,
  },
  {
    slug: 'varda-space',
    name: 'Varda Space Industries',
    description: 'In-space manufacturing company producing pharmaceuticals and materials in microgravity.',
    country: 'USA',
    headquarters: 'El Segundo, CA',
    founded: 2020,
    website: 'https://www.varda.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 90,
    lastFundingDate: '2024',
    totalFunding: 150,
    valuation: 0.5,
    focusAreas: ['in_space_manufacturing', 'pharmaceuticals'],
    subSectors: ['reentry_capsules', 'microgravity_production'],
    employeeCount: 80,
  },
  {
    slug: 'orbit-fab',
    name: 'Orbit Fab',
    description: 'In-space refueling infrastructure company building gas stations in space.',
    country: 'USA',
    headquarters: 'San Francisco, CA',
    founded: 2018,
    website: 'https://www.orbitfab.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series A',
    lastFundingAmount: 28,
    lastFundingDate: '2022',
    totalFunding: 35,
    valuation: 0.15,
    focusAreas: ['space_infrastructure', 'refueling', 'satellite_services'],
    subSectors: ['fuel_depots', 'rapidv_interface'],
    employeeCount: 50,
  },
  {
    slug: 'ula',
    name: 'United Launch Alliance',
    description: 'Joint venture of Lockheed Martin and Boeing providing launch services.',
    country: 'USA',
    headquarters: 'Centennial, CO',
    founded: 2006,
    website: 'https://www.ulalaunch.com',
    isPublic: false,
    isPreIPO: false,
    valuation: 3,
    focusAreas: ['launch_provider', 'national_security'],
    subSectors: ['vulcan', 'atlas_v', 'delta_iv'],
    employeeCount: 3000,
  },

  // International - Japan
  {
    slug: 'mitsubishi-heavy',
    name: 'Mitsubishi Heavy Industries',
    description: 'Japanese industrial conglomerate with major aerospace and launch vehicle division.',
    country: 'JPN',
    headquarters: 'Tokyo, Japan',
    founded: 1884,
    website: 'https://www.mhi.com',
    isPublic: true,
    ticker: '7011',
    exchange: 'TSE',
    marketCap: 45,
    focusAreas: ['launch_provider', 'spacecraft', 'defense'],
    subSectors: ['h3_rocket', 'h2a', 'satellites'],
    employeeCount: 77000,
    revenueEstimate: 35000,
  },

  // International - China
  {
    slug: 'casc',
    name: 'China Aerospace Science and Technology Corporation',
    description: 'Chinese state-owned aerospace and defense company, main contractor for Chinese space program.',
    country: 'CHN',
    headquarters: 'Beijing, China',
    founded: 1999,
    website: 'http://english.spacechina.com',
    isPublic: false,
    isPreIPO: false,
    focusAreas: ['launch_provider', 'spacecraft', 'satellites', 'lunar_services'],
    subSectors: ['long_march', 'shenzhou', 'tianzhou', 'change'],
    employeeCount: 170000,
  },
  {
    slug: 'casic',
    name: 'China Aerospace Science and Industry Corporation',
    description: 'Chinese state-owned aerospace company focusing on missiles, rockets, and satellites.',
    country: 'CHN',
    headquarters: 'Beijing, China',
    founded: 1999,
    isPublic: false,
    isPreIPO: false,
    focusAreas: ['launch_provider', 'missiles', 'satellites'],
    subSectors: ['kuaizhou', 'commercial_rockets'],
    employeeCount: 150000,
  },
  {
    slug: 'galactic-energy',
    name: 'Galactic Energy',
    description: 'Chinese private rocket company developing commercial launch vehicles.',
    country: 'CHN',
    headquarters: 'Beijing, China',
    founded: 2018,
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series C',
    totalFunding: 200,
    valuation: 0.8,
    focusAreas: ['launch_provider'],
    subSectors: ['ceres_1', 'pallas_1'],
    employeeCount: 500,
  },
  {
    slug: 'landspace',
    name: 'LandSpace',
    description: 'Chinese private aerospace company that achieved first methane rocket orbital flight.',
    country: 'CHN',
    headquarters: 'Huzhou, China',
    founded: 2015,
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series D',
    totalFunding: 300,
    valuation: 1.0,
    focusAreas: ['launch_provider'],
    subSectors: ['zhuque_2', 'methane_engines'],
    employeeCount: 800,
  },
  {
    slug: 'ispace-china',
    name: 'iSpace (China)',
    description: 'Chinese private rocket startup focused on small satellite launches.',
    country: 'CHN',
    headquarters: 'Beijing, China',
    founded: 2016,
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    totalFunding: 170,
    focusAreas: ['launch_provider'],
    subSectors: ['hyperbola'],
    employeeCount: 400,
  },

  // International - Russia
  {
    slug: 'roscosmos',
    name: 'Roscosmos State Corporation',
    description: 'Russian governmental body responsible for space program and aerospace research.',
    country: 'RUS',
    headquarters: 'Moscow, Russia',
    founded: 2015,
    website: 'https://www.roscosmos.ru',
    isPublic: false,
    isPreIPO: false,
    focusAreas: ['launch_provider', 'spacecraft', 'space_stations', 'satellites'],
    subSectors: ['soyuz', 'proton', 'angara', 'iss_operations'],
    employeeCount: 170000,
  },
  {
    slug: 'energia',
    name: 'RSC Energia',
    description: 'Russian spacecraft manufacturer responsible for Soyuz and Progress vehicles.',
    country: 'RUS',
    headquarters: 'Korolev, Russia',
    founded: 1946,
    isPublic: false,
    isPreIPO: false,
    focusAreas: ['spacecraft', 'space_stations'],
    subSectors: ['soyuz_spacecraft', 'progress', 'nauka_module'],
    employeeCount: 22000,
  },
  {
    slug: 'khrunichev',
    name: 'Khrunichev State Research and Production Space Center',
    description: 'Russian rocket manufacturer producing Proton and Angara launch vehicles.',
    country: 'RUS',
    headquarters: 'Moscow, Russia',
    founded: 1916,
    isPublic: false,
    isPreIPO: false,
    focusAreas: ['launch_provider'],
    subSectors: ['proton', 'angara', 'briz_upper_stage'],
    employeeCount: 40000,
  },

  // International - Europe
  {
    slug: 'arianespace',
    name: 'Arianespace',
    description: 'European launch service provider operating Ariane, Soyuz, and Vega rockets.',
    country: 'FRA',
    headquarters: 'Évry-Courcouronnes, France',
    founded: 1980,
    website: 'https://www.arianespace.com',
    isPublic: false,
    isPreIPO: false,
    focusAreas: ['launch_provider'],
    subSectors: ['ariane_6', 'vega_c', 'commercial_launches'],
    employeeCount: 400,
  },
  {
    slug: 'airbus-defence-space',
    name: 'Airbus Defence and Space',
    description: 'European aerospace company building satellites, launchers, and space systems.',
    country: 'FRA',
    headquarters: 'Toulouse, France',
    founded: 2014,
    website: 'https://www.airbus.com/space',
    isPublic: true,
    ticker: 'AIR',
    exchange: 'EPA',
    marketCap: 120,
    focusAreas: ['satellites', 'spacecraft', 'launch_provider'],
    subSectors: ['telecom_satellites', 'earth_observation', 'orion_esm'],
    employeeCount: 35000,
    revenueEstimate: 12000,
  },

  // Additional US Public Companies
  {
    slug: 'l3harris',
    name: 'L3Harris Technologies',
    description: 'Defense and aerospace company providing space-based ISR, communications, and missile tracking systems.',
    country: 'USA',
    headquarters: 'Melbourne, FL',
    founded: 2019,
    website: 'https://www.l3harris.com',
    isPublic: true,
    ticker: 'LHX',
    exchange: 'NYSE',
    marketCap: 46,
    focusAreas: ['defense', 'satellites', 'communications'],
    subSectors: ['space_sensors', 'missile_warning', 'gps_payloads', 'responsive_space'],
    employeeCount: 50000,
    revenueEstimate: 20000,
  },
  {
    slug: 'rtx',
    name: 'RTX Corporation',
    description: 'Aerospace and defense conglomerate with Raytheon missile and Collins Aerospace space divisions.',
    country: 'USA',
    headquarters: 'Arlington, VA',
    founded: 2020,
    website: 'https://www.rtx.com',
    isPublic: true,
    ticker: 'RTX',
    exchange: 'NYSE',
    marketCap: 155,
    focusAreas: ['defense', 'satellites', 'propulsion'],
    subSectors: ['missile_defense', 'space_sensors', 'satellite_communications'],
    employeeCount: 185000,
    revenueEstimate: 69000,
  },
  {
    slug: 'boeing',
    name: 'Boeing',
    description: 'Aerospace giant with major space division including Starliner, SLS, and satellite programs.',
    country: 'USA',
    headquarters: 'Arlington, VA',
    founded: 1916,
    website: 'https://www.boeing.com',
    isPublic: true,
    ticker: 'BA',
    exchange: 'NYSE',
    marketCap: 130,
    focusAreas: ['spacecraft', 'launch_provider', 'defense', 'satellites'],
    subSectors: ['starliner', 'sls', 'wgs_satellites', 'phantom_works'],
    employeeCount: 170000,
    revenueEstimate: 78000,
  },
  {
    slug: 'momentus',
    name: 'Momentus',
    description: 'In-space transportation company providing last-mile delivery and hosted payload services.',
    country: 'USA',
    headquarters: 'San Jose, CA',
    founded: 2017,
    website: 'https://momentus.space',
    isPublic: true,
    ticker: 'MNTS',
    exchange: 'NASDAQ',
    marketCap: 0.05,
    focusAreas: ['in_space_services', 'satellite_services'],
    subSectors: ['orbital_transfer', 'vigoride', 'last_mile_delivery'],
    employeeCount: 90,
  },
  {
    slug: 'astra',
    name: 'Astra Space',
    description: 'Space technology company pivoting from launch to spacecraft power and propulsion systems.',
    country: 'USA',
    headquarters: 'Alameda, CA',
    founded: 2016,
    website: 'https://astra.com',
    isPublic: true,
    ticker: 'ASTR',
    exchange: 'NASDAQ',
    marketCap: 0.08,
    focusAreas: ['propulsion', 'spacecraft_components'],
    subSectors: ['electric_propulsion', 'power_modules'],
    employeeCount: 200,
  },
  {
    slug: 'mynaric',
    name: 'Mynaric',
    description: 'Laser communications company providing optical inter-satellite link terminals for space networks.',
    country: 'DEU',
    headquarters: 'Munich, Germany',
    founded: 2009,
    website: 'https://mynaric.com',
    isPublic: true,
    ticker: 'MYNA',
    exchange: 'NASDAQ',
    marketCap: 0.15,
    focusAreas: ['communications', 'satellites'],
    subSectors: ['laser_comms', 'optical_ground_stations', 'condor_terminal'],
    employeeCount: 350,
  },
  {
    slug: 'ses',
    name: 'SES S.A.',
    description: 'Global satellite operator with GEO and MEO fleets providing video and data connectivity worldwide.',
    country: 'LUX',
    headquarters: 'Betzdorf, Luxembourg',
    founded: 1985,
    website: 'https://www.ses.com',
    isPublic: true,
    ticker: 'SESG',
    exchange: 'EPA',
    marketCap: 5.8,
    focusAreas: ['satellites', 'communications'],
    subSectors: ['o3b_mpower', 'astra_geo', 'video_distribution', 'government_services'],
    employeeCount: 2200,
    revenueEstimate: 2000,
  },
  {
    slug: 'telesat',
    name: 'Telesat',
    description: 'Canadian satellite operator developing Lightspeed LEO constellation for global broadband.',
    country: 'CAN',
    headquarters: 'Ottawa, Canada',
    founded: 1969,
    website: 'https://www.telesat.com',
    isPublic: true,
    ticker: 'TSAT',
    exchange: 'NASDAQ',
    marketCap: 0.8,
    focusAreas: ['satellites', 'communications'],
    subSectors: ['lightspeed_leo', 'geo_fleet', 'broadband'],
    employeeCount: 500,
    revenueEstimate: 700,
  },
  {
    slug: 'iridium',
    name: 'Iridium Communications',
    description: 'Operates the only truly global satellite communications network with 66 cross-linked LEO satellites.',
    country: 'USA',
    headquarters: 'McLean, VA',
    founded: 2000,
    website: 'https://www.iridium.com',
    isPublic: true,
    ticker: 'IRDM',
    exchange: 'NASDAQ',
    marketCap: 3.5,
    focusAreas: ['satellites', 'communications'],
    subSectors: ['iridium_next', 'iot', 'voice', 'broadband', 'direct_to_device'],
    employeeCount: 600,
    revenueEstimate: 800,
  },
  {
    slug: 'viasat',
    name: 'Viasat',
    description: 'Global communications company providing satellite broadband, in-flight connectivity, and defense systems.',
    country: 'USA',
    headquarters: 'Carlsbad, CA',
    founded: 1986,
    website: 'https://www.viasat.com',
    isPublic: true,
    ticker: 'VSAT',
    exchange: 'NASDAQ',
    marketCap: 2.8,
    focusAreas: ['satellites', 'communications', 'defense'],
    subSectors: ['viasat_3', 'in_flight_wifi', 'government_systems'],
    employeeCount: 7000,
    revenueEstimate: 3500,
  },

  // Additional US Private Companies
  {
    slug: 'firefly-aerospace',
    name: 'Firefly Aerospace',
    description: 'Launch and spacecraft company developing Alpha rocket and Blue Ghost lunar lander.',
    country: 'USA',
    headquarters: 'Cedar Park, TX',
    founded: 2014,
    website: 'https://fireflyspace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: '2026-2027',
    lastFundingRound: 'Series C',
    lastFundingAmount: 175,
    lastFundingDate: '2024',
    totalFunding: 400,
    nextFundingRound: 'Series D or IPO',
    valuation: 2.5,
    focusAreas: ['launch_provider', 'lunar_services', 'spacecraft'],
    subSectors: ['alpha', 'mlv', 'blue_ghost', 'elytra'],
    employeeCount: 600,
  },
  {
    slug: 'stoke-space',
    name: 'Stoke Space',
    description: 'Developing fully reusable rockets with a novel second-stage recovery approach.',
    country: 'USA',
    headquarters: 'Kent, WA',
    founded: 2019,
    website: 'https://www.stokespace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 100,
    lastFundingDate: '2024',
    totalFunding: 175,
    nextFundingRound: 'Series C',
    valuation: 1.0,
    focusAreas: ['launch_provider'],
    subSectors: ['full_reusability', 'second_stage_recovery'],
    employeeCount: 250,
  },
  {
    slug: 'impulse-space',
    name: 'Impulse Space',
    description: 'In-space transportation company building orbital maneuvering vehicles and Mars landers.',
    country: 'USA',
    headquarters: 'Redondo Beach, CA',
    founded: 2021,
    website: 'https://www.impulsespace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 150,
    lastFundingDate: '2024',
    totalFunding: 225,
    nextFundingRound: 'Series C',
    valuation: 1.2,
    focusAreas: ['in_space_services', 'propulsion'],
    subSectors: ['mira', 'helios', 'mars_lander'],
    employeeCount: 150,
  },
  {
    slug: 'astranis',
    name: 'Astranis',
    description: 'Building small, low-cost broadband satellites that serve individual countries or regions.',
    country: 'USA',
    headquarters: 'San Francisco, CA',
    founded: 2015,
    website: 'https://www.astranis.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: '2026-2027',
    lastFundingRound: 'Series C',
    lastFundingAmount: 200,
    lastFundingDate: '2023',
    totalFunding: 500,
    nextFundingRound: 'Pre-IPO or Series D',
    valuation: 3.2,
    focusAreas: ['satellites', 'communications'],
    subSectors: ['micro_geo', 'broadband', 'omega_satellites'],
    employeeCount: 400,
  },
  {
    slug: 'k2-space',
    name: 'K2 Space',
    description: 'Building very large, low-cost satellites for commercial and government customers.',
    country: 'USA',
    headquarters: 'Los Angeles, CA',
    founded: 2022,
    website: 'https://www.k2space.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series A',
    lastFundingAmount: 50,
    lastFundingDate: '2024',
    totalFunding: 70,
    nextFundingRound: 'Series B',
    valuation: 0.3,
    focusAreas: ['satellites', 'spacecraft'],
    subSectors: ['large_spacecraft', 'modular_satellites'],
    employeeCount: 80,
  },
  {
    slug: 'apex-space',
    name: 'Apex',
    description: 'Satellite bus manufacturer building standardized spacecraft platforms for faster delivery.',
    country: 'USA',
    headquarters: 'Los Angeles, CA',
    founded: 2022,
    website: 'https://www.apex.aero',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 95,
    lastFundingDate: '2024',
    totalFunding: 120,
    nextFundingRound: 'Series C',
    valuation: 0.75,
    focusAreas: ['satellites', 'manufacturing'],
    subSectors: ['satellite_buses', 'aries', 'nova'],
    employeeCount: 120,
  },
  {
    slug: 'true-anomaly',
    name: 'True Anomaly',
    description: 'Space security company developing spacecraft and software for orbital domain awareness.',
    country: 'USA',
    headquarters: 'Denver, CO',
    founded: 2022,
    website: 'https://www.trueanomaly.space',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 100,
    lastFundingDate: '2024',
    totalFunding: 155,
    nextFundingRound: 'Series C',
    valuation: 0.8,
    focusAreas: ['defense', 'space_infrastructure'],
    subSectors: ['space_domain_awareness', 'jackal_spacecraft', 'orbital_security'],
    employeeCount: 180,
  },
  {
    slug: 'capella-space',
    name: 'Capella Space',
    description: 'Synthetic aperture radar satellite company providing all-weather Earth observation imagery.',
    country: 'USA',
    headquarters: 'San Francisco, CA',
    founded: 2016,
    website: 'https://www.capellaspace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series C',
    lastFundingAmount: 97,
    lastFundingDate: '2023',
    totalFunding: 230,
    nextFundingRound: 'Series D',
    valuation: 1.0,
    focusAreas: ['earth_observation', 'satellites', 'defense'],
    subSectors: ['sar_imagery', 'acadia_satellites', 'analytics'],
    employeeCount: 200,
  },
  {
    slug: 'hawkeye360',
    name: 'HawkEye 360',
    description: 'Radio frequency geospatial analytics company using satellite clusters for signal detection.',
    country: 'USA',
    headquarters: 'Herndon, VA',
    founded: 2015,
    website: 'https://www.he360.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series D',
    lastFundingAmount: 68,
    lastFundingDate: '2023',
    totalFunding: 300,
    nextFundingRound: 'Pre-IPO',
    valuation: 1.3,
    focusAreas: ['earth_observation', 'defense', 'satellites'],
    subSectors: ['rf_analytics', 'maritime_surveillance', 'spectrum_monitoring'],
    employeeCount: 200,
  },
  {
    slug: 'umbra-space',
    name: 'Umbra',
    description: 'SAR satellite company providing high-resolution radar imagery on-demand.',
    country: 'USA',
    headquarters: 'Santa Barbara, CA',
    founded: 2015,
    website: 'https://umbra.space',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series C',
    lastFundingAmount: 70,
    lastFundingDate: '2024',
    totalFunding: 160,
    nextFundingRound: 'Series D',
    valuation: 0.6,
    focusAreas: ['earth_observation', 'satellites'],
    subSectors: ['sar_satellites', 'canopy_platform'],
    employeeCount: 130,
  },
  {
    slug: 'muon-space',
    name: 'Muon Space',
    description: 'Climate monitoring satellite company building multi-sensor constellations for environmental data.',
    country: 'USA',
    headquarters: 'Mountain View, CA',
    founded: 2021,
    website: 'https://www.muonspace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 57,
    lastFundingDate: '2024',
    totalFunding: 82,
    nextFundingRound: 'Series C',
    valuation: 0.4,
    focusAreas: ['earth_observation', 'satellites'],
    subSectors: ['climate_monitoring', 'multi_sensor', 'wildfire_detection'],
    employeeCount: 90,
  },
  {
    slug: 'astrobotic',
    name: 'Astrobotic Technology',
    description: 'Lunar logistics company delivering payloads to the Moon for NASA CLPS program.',
    country: 'USA',
    headquarters: 'Pittsburgh, PA',
    founded: 2007,
    website: 'https://www.astrobotic.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series C',
    lastFundingAmount: 100,
    lastFundingDate: '2023',
    totalFunding: 350,
    nextFundingRound: 'Pre-IPO',
    valuation: 0.8,
    focusAreas: ['lunar_services', 'spacecraft'],
    subSectors: ['peregrine', 'griffin', 'cubeRover', 'lunaGrid'],
    employeeCount: 300,
  },
  {
    slug: 'york-space',
    name: 'York Space Systems',
    description: 'Spacecraft manufacturer producing standardized satellite platforms for defense and commercial markets.',
    country: 'USA',
    headquarters: 'Denver, CO',
    founded: 2015,
    website: 'https://www.yorkspacesystems.com',
    isPublic: false,
    isPreIPO: false,
    lastFundingRound: 'Growth Equity',
    lastFundingAmount: 100,
    lastFundingDate: '2022',
    totalFunding: 150,
    valuation: 0.7,
    focusAreas: ['satellites', 'defense', 'manufacturing'],
    subSectors: ['s_class_platform', 'sda_satellites'],
    employeeCount: 250,
  },
  {
    slug: 'cesiumastro',
    name: 'CesiumAstro',
    description: 'Communications systems company providing active phased array antennas for space and airborne platforms.',
    country: 'USA',
    headquarters: 'Austin, TX',
    founded: 2017,
    website: 'https://www.cesiumastro.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series C',
    lastFundingAmount: 65,
    lastFundingDate: '2024',
    totalFunding: 130,
    nextFundingRound: 'Series D',
    valuation: 0.5,
    focusAreas: ['communications', 'defense', 'satellites'],
    subSectors: ['phased_arrays', 'multi_beam', 'software_defined_radio'],
    employeeCount: 200,
  },
  {
    slug: 'phantom-space',
    name: 'Phantom Space',
    description: 'Vertically integrated space company developing launch vehicles, satellites, and space tugs.',
    country: 'USA',
    headquarters: 'Tucson, AZ',
    founded: 2019,
    website: 'https://www.phantomspace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series A',
    lastFundingAmount: 28,
    lastFundingDate: '2022',
    totalFunding: 40,
    nextFundingRound: 'Series B',
    valuation: 0.2,
    focusAreas: ['launch_provider', 'satellites', 'in_space_services'],
    subSectors: ['daytona_rocket', 'satellite_factory', 'vitruvian_tug'],
    employeeCount: 100,
  },
  {
    slug: 'abl-space',
    name: 'ABL Space Systems',
    description: 'Launch vehicle company developing RS1 rocket with containerized ground system for rapid deployment.',
    country: 'USA',
    headquarters: 'El Segundo, CA',
    founded: 2017,
    website: 'https://www.ablspacesystems.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 200,
    lastFundingDate: '2022',
    totalFunding: 300,
    nextFundingRound: 'Series C',
    valuation: 2.4,
    focusAreas: ['launch_provider'],
    subSectors: ['rs1_rocket', 'e2_engine', 'gls_ground_system'],
    employeeCount: 300,
  },
  {
    slug: 'terran-orbital',
    name: 'Terran Orbital',
    description: 'Satellite manufacturer specializing in small satellites for defense, intelligence, and commercial markets.',
    country: 'USA',
    headquarters: 'Boca Raton, FL',
    founded: 2013,
    website: 'https://terranorbital.com',
    isPublic: false,
    isPreIPO: false,
    lastFundingRound: 'Acquired by Lockheed Martin',
    lastFundingDate: '2024',
    valuation: 0.45,
    focusAreas: ['satellites', 'defense', 'manufacturing'],
    subSectors: ['cubesats', 'espa_class', 'sda_tranche'],
    employeeCount: 500,
  },
  {
    slug: 'astroscale',
    name: 'Astroscale',
    description: 'On-orbit servicing and debris removal company developing commercial solutions for space sustainability.',
    country: 'JPN',
    headquarters: 'Tokyo, Japan',
    founded: 2013,
    website: 'https://astroscale.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: '2025-2026',
    lastFundingRound: 'Series G',
    lastFundingAmount: 76,
    lastFundingDate: '2024',
    totalFunding: 400,
    nextFundingRound: 'IPO',
    valuation: 1.5,
    focusAreas: ['in_space_services', 'space_infrastructure'],
    subSectors: ['debris_removal', 'life_extension', 'elsa_d', 'adras_j'],
    employeeCount: 350,
  },
  {
    slug: 'ispace-japan',
    name: 'ispace',
    description: 'Japanese lunar exploration company developing commercial lunar landers and rovers.',
    country: 'JPN',
    headquarters: 'Tokyo, Japan',
    founded: 2010,
    website: 'https://ispace-inc.com',
    isPublic: true,
    ticker: '9348',
    exchange: 'TSE',
    marketCap: 0.6,
    focusAreas: ['lunar_services', 'spacecraft'],
    subSectors: ['hakuto_r', 'lunar_lander', 'micro_rover'],
    employeeCount: 250,
  },

  // European Private Companies
  {
    slug: 'orbex',
    name: 'Orbex',
    description: 'European launch company developing Prime rocket for small satellite launches from Scotland.',
    country: 'GBR',
    headquarters: 'Forres, Scotland',
    founded: 2015,
    website: 'https://orbex.space',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series C',
    lastFundingAmount: 52,
    lastFundingDate: '2023',
    totalFunding: 100,
    nextFundingRound: 'Series D',
    valuation: 0.3,
    focusAreas: ['launch_provider'],
    subSectors: ['prime_rocket', 'bio_propane', 'sutherland_spaceport'],
    employeeCount: 130,
  },
  {
    slug: 'rocket-factory-augsburg',
    name: 'Rocket Factory Augsburg',
    description: 'German micro-launcher company developing the RFA ONE orbital launch vehicle.',
    country: 'DEU',
    headquarters: 'Augsburg, Germany',
    founded: 2018,
    website: 'https://www.rfa.space',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 40,
    lastFundingDate: '2023',
    totalFunding: 80,
    nextFundingRound: 'Series C',
    valuation: 0.25,
    focusAreas: ['launch_provider'],
    subSectors: ['rfa_one', 'helix_engine'],
    employeeCount: 200,
  },
  {
    slug: 'isar-aerospace',
    name: 'Isar Aerospace',
    description: 'European launch company building Spectrum rocket for dedicated small and medium satellite launches.',
    country: 'DEU',
    headquarters: 'Ottobrunn, Germany',
    founded: 2018,
    website: 'https://www.isaraerospace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series C',
    lastFundingAmount: 165,
    lastFundingDate: '2023',
    totalFunding: 310,
    nextFundingRound: 'Pre-IPO',
    valuation: 1.2,
    focusAreas: ['launch_provider'],
    subSectors: ['spectrum_rocket', 'aquila_engine'],
    employeeCount: 350,
  },
  {
    slug: 'iceye',
    name: 'ICEYE',
    description: 'Finnish-origin SAR satellite company operating the largest synthetic aperture radar constellation.',
    country: 'EUR',
    headquarters: 'Espoo, Finland',
    founded: 2014,
    website: 'https://www.iceye.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series E',
    lastFundingAmount: 93,
    lastFundingDate: '2024',
    totalFunding: 380,
    nextFundingRound: 'Pre-IPO',
    valuation: 1.6,
    focusAreas: ['earth_observation', 'satellites', 'defense'],
    subSectors: ['sar_constellation', 'flood_monitoring', 'defense_isr'],
    employeeCount: 600,
  },

  // India
  {
    slug: 'skyroot-aerospace',
    name: 'Skyroot Aerospace',
    description: 'Indian private rocket company that became India\'s first private firm to launch a rocket to space.',
    country: 'IND',
    headquarters: 'Hyderabad, India',
    founded: 2018,
    website: 'https://www.skyroot.in',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series C',
    lastFundingAmount: 27,
    lastFundingDate: '2024',
    totalFunding: 80,
    nextFundingRound: 'Series D',
    valuation: 0.35,
    focusAreas: ['launch_provider'],
    subSectors: ['vikram_rockets', '3d_printed_engines'],
    employeeCount: 300,
  },
  {
    slug: 'agnikul-cosmos',
    name: 'Agnikul Cosmos',
    description: 'Indian launch startup building 3D-printed rocket engines and customizable small launch vehicles.',
    country: 'IND',
    headquarters: 'Chennai, India',
    founded: 2017,
    website: 'https://agnikul.in',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 26,
    lastFundingDate: '2024',
    totalFunding: 50,
    nextFundingRound: 'Series C',
    valuation: 0.2,
    focusAreas: ['launch_provider', 'manufacturing'],
    subSectors: ['agnibaan', '3d_printed_engines', 'semi_cryo'],
    employeeCount: 200,
  },
  {
    slug: 'pixxel',
    name: 'Pixxel',
    description: 'Indian hyperspectral earth observation satellite company providing detailed environmental analytics.',
    country: 'IND',
    headquarters: 'Bangalore, India',
    founded: 2019,
    website: 'https://www.pixxel.space',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 36,
    lastFundingDate: '2023',
    totalFunding: 70,
    nextFundingRound: 'Series C',
    valuation: 0.3,
    focusAreas: ['earth_observation', 'satellites'],
    subSectors: ['hyperspectral', 'firefly_constellation', 'aurora_platform'],
    employeeCount: 150,
  },

  // South Korea
  {
    slug: 'innospace',
    name: 'Innospace',
    description: 'South Korean launch company developing hybrid rockets for small satellite access to space.',
    country: 'KOR',
    headquarters: 'Sejong City, South Korea',
    founded: 2017,
    website: 'https://www.innospace.co.kr',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 30,
    lastFundingDate: '2023',
    totalFunding: 60,
    nextFundingRound: 'Series C',
    valuation: 0.2,
    focusAreas: ['launch_provider'],
    subSectors: ['hanbit_tlv', 'hybrid_rocket'],
    employeeCount: 100,
  },

  // Israel
  {
    slug: 'spaceil',
    name: 'SpaceIL',
    description: 'Israeli nonprofit developing lunar landers, originating from the Google Lunar XPRIZE competition.',
    country: 'ISR',
    headquarters: 'Ramat Gan, Israel',
    founded: 2011,
    website: 'https://www.spaceil.com',
    isPublic: false,
    isPreIPO: false,
    lastFundingRound: 'Donation/Grant',
    totalFunding: 100,
    focusAreas: ['lunar_services', 'spacecraft'],
    subSectors: ['beresheet', 'lunar_lander'],
    employeeCount: 50,
  },

  // New Zealand
  {
    slug: 'rocket-lab-nz',
    name: 'Dawn Aerospace',
    description: 'New Zealand-Netherlands company developing reusable suborbital rocket planes and green propulsion.',
    country: 'NZL',
    headquarters: 'Christchurch, New Zealand',
    founded: 2015,
    website: 'https://www.dawnaerospace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series A',
    lastFundingAmount: 25,
    lastFundingDate: '2022',
    totalFunding: 35,
    nextFundingRound: 'Series B',
    valuation: 0.12,
    focusAreas: ['launch_provider', 'propulsion'],
    subSectors: ['mk_ii_aurora', 'green_propulsion', 'reusable_spaceplane'],
    employeeCount: 60,
  },

  // Australia
  {
    slug: 'gilmour-space',
    name: 'Gilmour Space Technologies',
    description: 'Australian launch company developing Eris rocket for small-to-medium satellite payloads.',
    country: 'AUS',
    headquarters: 'Gold Coast, Australia',
    founded: 2012,
    website: 'https://www.gspace.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series C',
    lastFundingAmount: 47,
    lastFundingDate: '2023',
    totalFunding: 100,
    nextFundingRound: 'Pre-IPO',
    valuation: 0.35,
    focusAreas: ['launch_provider'],
    subSectors: ['eris_rocket', 'hybrid_propulsion'],
    employeeCount: 180,
  },

  // UAE
  {
    slug: 'bayanat',
    name: 'Bayanat',
    description: 'UAE-based AI and geospatial intelligence company with satellite imaging and analytics capabilities.',
    country: 'ARE',
    headquarters: 'Abu Dhabi, UAE',
    founded: 2020,
    website: 'https://bayanat.ai',
    isPublic: false,
    isPreIPO: false,
    lastFundingRound: 'Strategic Investment',
    totalFunding: 200,
    valuation: 1.0,
    focusAreas: ['earth_observation', 'satellites', 'defense'],
    subSectors: ['geospatial_ai', 'satellite_analytics', 'smart_city'],
    employeeCount: 300,
  },

  // Additional notable US private
  {
    slug: 'space-perspective',
    name: 'Space Perspective',
    description: 'Space tourism company offering stratospheric balloon flights to the edge of space.',
    country: 'USA',
    headquarters: 'Titusville, FL',
    founded: 2019,
    website: 'https://spaceperspective.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 64,
    lastFundingDate: '2024',
    totalFunding: 115,
    nextFundingRound: 'Series C',
    valuation: 0.5,
    focusAreas: ['space_tourism'],
    subSectors: ['spaceship_neptune', 'stratospheric_balloon'],
    employeeCount: 100,
  },
  {
    slug: 'privateer',
    name: 'Privateer Space',
    description: 'Space sustainability company building data platform for space traffic coordination and debris tracking.',
    country: 'USA',
    headquarters: 'Maui, HI',
    founded: 2021,
    website: 'https://www.privateer.com',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series A',
    lastFundingAmount: 56,
    lastFundingDate: '2023',
    totalFunding: 80,
    nextFundingRound: 'Series B',
    valuation: 0.3,
    focusAreas: ['space_infrastructure', 'in_space_services'],
    subSectors: ['wayfinder_platform', 'space_traffic', 'debris_tracking'],
    employeeCount: 60,
  },
  {
    slug: 'epsilon3',
    name: 'Epsilon3',
    description: 'Operating system for spacecraft and launch vehicle operations, replacing paper procedures with software.',
    country: 'USA',
    headquarters: 'Los Angeles, CA',
    founded: 2021,
    website: 'https://www.epsilon3.io',
    isPublic: false,
    isPreIPO: true,
    expectedIPODate: 'TBD',
    lastFundingRound: 'Series B',
    lastFundingAmount: 34,
    lastFundingDate: '2024',
    totalFunding: 50,
    nextFundingRound: 'Series C',
    valuation: 0.2,
    focusAreas: ['space_infrastructure', 'manufacturing'],
    subSectors: ['mission_operations', 'procedure_automation', 'test_management'],
    employeeCount: 50,
  },
  {
    slug: 'spaceflight-industries',
    name: 'Spaceflight Inc.',
    description: 'Rideshare launch service provider arranging shared launches for small satellite operators.',
    country: 'USA',
    headquarters: 'Seattle, WA',
    founded: 2010,
    website: 'https://spaceflight.com',
    isPublic: false,
    isPreIPO: false,
    lastFundingRound: 'Series B',
    lastFundingAmount: 150,
    lastFundingDate: '2021',
    totalFunding: 200,
    valuation: 0.5,
    focusAreas: ['launch_provider', 'in_space_services'],
    subSectors: ['rideshare', 'sherpa_tug', 'mission_management'],
    employeeCount: 100,
  },

  // Additional notable Canada
  {
    slug: 'mda-space',
    name: 'MDA Space',
    description: 'Canadian space technology company building Canadarm systems, radar satellites, and ground stations.',
    country: 'CAN',
    headquarters: 'Brampton, Canada',
    founded: 1969,
    website: 'https://mda.space',
    isPublic: true,
    ticker: 'MDA',
    exchange: 'TSX',
    marketCap: 3.5,
    focusAreas: ['satellites', 'spacecraft', 'space_infrastructure'],
    subSectors: ['canadarm3', 'radarsat', 'ground_systems', 'satellite_servicing'],
    employeeCount: 3000,
    revenueEstimate: 700,
  },
];

export async function initializeCompanies(): Promise<number> {
  let count = 0;

  for (const company of SPACE_COMPANIES) {
    try {
      await prisma.spaceCompany.upsert({
        where: { slug: company.slug },
        update: {
          name: company.name,
          description: company.description,
          country: company.country,
          headquarters: company.headquarters,
          founded: company.founded,
          website: company.website,
          logoUrl: company.logoUrl,
          isPublic: company.isPublic,
          ticker: company.ticker,
          exchange: company.exchange,
          marketCap: company.marketCap,
          isPreIPO: company.isPreIPO || false,
          expectedIPODate: company.expectedIPODate,
          lastFundingRound: company.lastFundingRound,
          lastFundingAmount: company.lastFundingAmount,
          lastFundingDate: company.lastFundingDate,
          totalFunding: company.totalFunding,
          nextFundingRound: company.nextFundingRound,
          valuation: company.valuation,
          focusAreas: JSON.stringify(company.focusAreas),
          subSectors: company.subSectors ? JSON.stringify(company.subSectors) : null,
          employeeCount: company.employeeCount,
          revenueEstimate: company.revenueEstimate,
        },
        create: {
          slug: company.slug,
          name: company.name,
          description: company.description,
          country: company.country,
          headquarters: company.headquarters,
          founded: company.founded,
          website: company.website,
          logoUrl: company.logoUrl,
          isPublic: company.isPublic,
          ticker: company.ticker,
          exchange: company.exchange,
          marketCap: company.marketCap,
          isPreIPO: company.isPreIPO || false,
          expectedIPODate: company.expectedIPODate,
          lastFundingRound: company.lastFundingRound,
          lastFundingAmount: company.lastFundingAmount,
          lastFundingDate: company.lastFundingDate,
          totalFunding: company.totalFunding,
          nextFundingRound: company.nextFundingRound,
          valuation: company.valuation,
          focusAreas: JSON.stringify(company.focusAreas),
          subSectors: company.subSectors ? JSON.stringify(company.subSectors) : null,
          employeeCount: company.employeeCount,
          revenueEstimate: company.revenueEstimate,
        },
      });
      count++;
    } catch (err) {
      console.error(`Failed to add company ${company.name}:`, err);
    }
  }

  return count;
}

export async function getCompanies(options?: {
  country?: string;
  isPublic?: boolean;
  focusArea?: string;
  limit?: number;
  offset?: number;
}) {
  const { country, isPublic, focusArea, limit = 50, offset = 0 } = options || {};

  const where: Record<string, unknown> = {};

  if (country) {
    where.country = country;
  }

  if (isPublic !== undefined) {
    where.isPublic = isPublic;
  }

  if (focusArea) {
    where.focusAreas = { contains: focusArea };
  }

  const companies = await prisma.spaceCompany.findMany({
    where,
    orderBy: [
      { marketCap: 'desc' },
      { valuation: 'desc' },
      { name: 'asc' },
    ],
    take: limit,
    skip: offset,
  });

  const total = await prisma.spaceCompany.count({ where });

  return { companies, total };
}

export async function getPublicCompanies() {
  return prisma.spaceCompany.findMany({
    where: { isPublic: true },
    orderBy: { marketCap: 'desc' },
  });
}

export async function getPrivateCompanies() {
  return prisma.spaceCompany.findMany({
    where: { isPublic: false },
    orderBy: [{ valuation: 'desc' }, { name: 'asc' }],
  });
}

export async function getCompanyBySlug(slug: string) {
  return prisma.spaceCompany.findUnique({ where: { slug } });
}

export async function getCompanyStats() {
  const total = await prisma.spaceCompany.count();
  const publicCount = await prisma.spaceCompany.count({ where: { isPublic: true } });
  const privateCount = await prisma.spaceCompany.count({ where: { isPublic: false } });
  const preIPOCount = await prisma.spaceCompany.count({ where: { isPreIPO: true } });

  const countries = await prisma.spaceCompany.groupBy({
    by: ['country'],
    _count: { country: true },
  });

  // Calculate total market cap from public companies
  const marketCapAgg = await prisma.spaceCompany.aggregate({
    where: { isPublic: true },
    _sum: { marketCap: true },
  });

  return {
    total,
    publicCount,
    privateCount,
    preIPOCount,
    countriesCount: countries.length,
    totalMarketCap: marketCapAgg._sum.marketCap || 0,
    byCountry: Object.fromEntries(countries.map((c) => [c.country, c._count.country])),
  };
}
