export type MoveType = 'hired' | 'departed' | 'promoted' | 'appointed';

export interface ExecutiveMove {
  id: string;
  personName: string;
  fromCompany: string | null;
  fromTitle: string | null;
  toCompany: string | null;
  toTitle: string | null;
  moveType: MoveType;
  date: string; // ISO date string
  source?: string;
  summary?: string;
  companySlug?: string; // links to /company-profiles/{slug}
}

/**
 * Executive moves seed data — 55 notable C-suite and VP-level leadership
 * changes across the space industry (2023-2026).
 */
export const EXECUTIVE_MOVES: ExecutiveMove[] = [
  // === 2026 Moves ===
  {
    id: 'em-001',
    personName: 'Bill Nelson',
    fromCompany: 'NASA',
    fromTitle: 'Administrator',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2025-01-20',
    summary: 'Departed NASA following change in presidential administration. Served as 14th NASA Administrator since 2021.',
    companySlug: 'nasa',
  },
  {
    id: 'em-002',
    personName: 'Jared Isaacman',
    fromCompany: 'Shift4 Payments',
    fromTitle: 'CEO',
    toCompany: 'NASA',
    toTitle: 'Administrator',
    moveType: 'appointed',
    date: '2025-02-03',
    summary: 'Billionaire and Polaris Program commander nominated as NASA Administrator. First commercial astronaut to lead the agency.',
    companySlug: 'nasa',
  },
  {
    id: 'em-003',
    personName: 'Derek Tournear',
    fromCompany: 'Space Development Agency',
    fromTitle: 'Director',
    toCompany: 'Space Systems Command',
    toTitle: 'Chief Technology Officer',
    moveType: 'hired',
    date: '2026-01-15',
    summary: 'Transitioned from leading SDA after successful Tranche 0 and Tranche 1 satellite constellation deployments.',
  },
  {
    id: 'em-004',
    personName: 'Michael Suffredini',
    fromCompany: 'Axiom Space',
    fromTitle: 'CEO',
    toCompany: 'Axiom Space',
    toTitle: 'Executive Chairman',
    moveType: 'promoted',
    date: '2026-01-08',
    summary: 'Transitioned to Executive Chairman role as Axiom prepares for first commercial station module launch.',
    companySlug: 'axiom-space',
  },
  {
    id: 'em-005',
    personName: 'Matt Desch',
    fromCompany: 'Iridium Communications',
    fromTitle: 'CEO',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2025-10-01',
    summary: 'Retired after 16 years leading Iridium through the NEXT constellation replacement and return to profitability.',
    companySlug: 'iridium-communications',
  },
  {
    id: 'em-006',
    personName: 'Robyn Denholm',
    fromCompany: 'Telstra',
    fromTitle: 'CFO (former)',
    toCompany: 'Viasat',
    toTitle: 'Board of Directors',
    moveType: 'appointed',
    date: '2026-02-01',
    summary: 'Tesla Chair joins Viasat board as the company integrates Inmarsat assets and expands global broadband.',
    companySlug: 'viasat',
  },
  {
    id: 'em-007',
    personName: 'Frank Calvelli',
    fromCompany: 'NRO',
    fromTitle: 'Assistant Secretary of the Air Force for Space Acquisition',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2025-12-15',
    summary: 'Departed after driving rapid commercial space integration into national security architecture.',
  },
  {
    id: 'em-008',
    personName: 'Lisa Campbell',
    fromCompany: 'Canadian Space Agency',
    fromTitle: 'President',
    toCompany: 'MDA Space',
    toTitle: 'VP Government Relations',
    moveType: 'hired',
    date: '2026-02-10',
    summary: 'Former CSA president joins MDA to strengthen government partnerships for Canadarm3 and satellite programs.',
    companySlug: 'mda-space',
  },

  // === 2025 Moves ===
  {
    id: 'em-009',
    personName: 'Tory Bruno',
    fromCompany: 'United Launch Alliance',
    fromTitle: 'CEO',
    toCompany: 'United Launch Alliance',
    toTitle: 'CEO',
    moveType: 'promoted',
    date: '2025-03-15',
    summary: 'Contract extended through Vulcan operational phase. Led ULA through successful Vulcan Centaur certification.',
    companySlug: 'united-launch-alliance',
  },
  {
    id: 'em-010',
    personName: 'Peter Beck',
    fromCompany: 'Rocket Lab',
    fromTitle: 'CEO',
    toCompany: 'Rocket Lab',
    toTitle: 'CEO & Chairman',
    moveType: 'promoted',
    date: '2025-06-01',
    summary: 'Added Chairman title as Neutron development accelerated and Electron reached 50th launch milestone.',
    companySlug: 'rocket-lab',
  },
  {
    id: 'em-011',
    personName: 'Tim Ellis',
    fromCompany: 'Relativity Space',
    fromTitle: 'CEO',
    toCompany: 'Relativity Space',
    toTitle: 'CEO',
    moveType: 'promoted',
    date: '2025-04-20',
    summary: 'Led company pivot to Terran R after retiring Terran 1. Secured major defense launch contracts.',
    companySlug: 'relativity-space',
  },
  {
    id: 'em-012',
    personName: 'Dan Hart',
    fromCompany: 'Virgin Orbit',
    fromTitle: 'CEO',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2023-04-04',
    summary: 'Virgin Orbit ceased operations and filed for Chapter 11 bankruptcy. Assets later acquired by Rocket Lab and others.',
  },
  {
    id: 'em-013',
    personName: 'Tom Markusic',
    fromCompany: 'Firefly Aerospace',
    fromTitle: 'CEO',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2023-06-15',
    summary: 'Departed Firefly after company restructuring. Founded Firefly in 2014 and led Alpha to first successful orbital flight.',
    companySlug: 'firefly-aerospace',
  },
  {
    id: 'em-014',
    personName: 'Jason Kim',
    fromCompany: 'Northrop Grumman',
    fromTitle: 'VP Mission Systems',
    toCompany: 'Firefly Aerospace',
    toTitle: 'CEO',
    moveType: 'hired',
    date: '2023-07-01',
    summary: 'Brought defense industry leadership experience to Firefly during transition to operational launch provider.',
    companySlug: 'firefly-aerospace',
  },
  {
    id: 'em-015',
    personName: 'Chris Kemp',
    fromCompany: 'Astra Space',
    fromTitle: 'CEO',
    toCompany: 'Astra Space',
    toTitle: 'CEO',
    moveType: 'promoted',
    date: '2024-01-10',
    summary: 'Led company pivot from launch to spacecraft propulsion systems after suspending Rocket 4 development.',
    companySlug: 'astra-space',
  },
  {
    id: 'em-016',
    personName: 'Gwynne Shotwell',
    fromCompany: 'SpaceX',
    fromTitle: 'President & COO',
    toCompany: 'SpaceX',
    toTitle: 'President & COO',
    moveType: 'promoted',
    date: '2025-09-01',
    summary: 'Extended leadership role overseeing Starlink business unit spin-off preparations and Starship operational flights.',
    companySlug: 'spacex',
  },
  {
    id: 'em-017',
    personName: 'Tom Mueller',
    fromCompany: 'SpaceX',
    fromTitle: 'VP Propulsion (former)',
    toCompany: 'Impulse Space',
    toTitle: 'Senior Advisor',
    moveType: 'appointed',
    date: '2023-03-01',
    summary: 'SpaceX co-founder and Merlin/Raptor engine architect joined Impulse Space as senior advisor after retirement.',
  },
  {
    id: 'em-018',
    personName: 'Kathy Lueders',
    fromCompany: 'NASA',
    fromTitle: 'Associate Administrator, Space Operations',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2023-09-01',
    summary: 'Retired from NASA after leading Commercial Crew Program and managing ISS operations through transition era.',
    companySlug: 'nasa',
  },
  {
    id: 'em-019',
    personName: 'Jim Free',
    fromCompany: 'NASA',
    fromTitle: 'Associate Administrator',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2025-01-20',
    summary: 'Departed NASA after serving as Associate Administrator overseeing Artemis program milestones.',
    companySlug: 'nasa',
  },
  {
    id: 'em-020',
    personName: 'Steve Isakowitz',
    fromCompany: 'The Aerospace Corporation',
    fromTitle: 'CEO & President',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2025-08-01',
    summary: 'Retired after leading Aerospace Corporation through significant growth in space domain awareness and FFRDC mission.',
  },
  {
    id: 'em-021',
    personName: 'Dan Goldberg',
    fromCompany: 'Telesat',
    fromTitle: 'CEO',
    toCompany: 'Telesat',
    toTitle: 'CEO',
    moveType: 'promoted',
    date: '2025-05-01',
    summary: 'Led Telesat through Lightspeed LEO constellation development partnership with MDA Space.',
    companySlug: 'telesat',
  },
  {
    id: 'em-022',
    personName: 'Rajeev Badyal',
    fromCompany: 'Amazon (Project Kuiper)',
    fromTitle: 'VP Technology',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2023-08-01',
    summary: 'Left Amazon Kuiper project. Former SpaceX Starlink VP who joined Amazon in 2019.',
  },
  {
    id: 'em-023',
    personName: 'Steve Collar',
    fromCompany: 'SES',
    fromTitle: 'CEO',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2024-04-01',
    summary: 'Departed SES after leading O3b mPOWER constellation launch and C-band spectrum transition.',
    companySlug: 'ses',
  },
  {
    id: 'em-024',
    personName: 'Adel Al-Saleh',
    fromCompany: 'SES',
    fromTitle: null,
    toCompany: 'SES',
    toTitle: 'CEO',
    moveType: 'hired',
    date: '2024-04-15',
    summary: 'Appointed as new CEO to lead SES through MEO/GEO convergence and government services expansion.',
    companySlug: 'ses',
  },
  {
    id: 'em-025',
    personName: 'John Plumb',
    fromCompany: 'Department of Defense',
    fromTitle: 'Assistant Secretary of Defense for Space Policy',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2025-01-20',
    summary: 'Departed DoD after establishing new space policy frameworks and commercial space integration strategies.',
  },

  // === Major Defense/Prime Contractor Moves ===
  {
    id: 'em-026',
    personName: 'Kathy Warden',
    fromCompany: 'Northrop Grumman',
    fromTitle: 'Chair, CEO & President',
    toCompany: 'Northrop Grumman',
    toTitle: 'Chair, CEO & President',
    moveType: 'promoted',
    date: '2024-06-01',
    summary: 'Contract extended after successful B-21 Raider rollout and growing space systems portfolio.',
    companySlug: 'northrop-grumman',
  },
  {
    id: 'em-027',
    personName: 'Jim Taiclet',
    fromCompany: 'Lockheed Martin',
    fromTitle: 'Chairman & CEO',
    toCompany: 'Lockheed Martin',
    toTitle: 'Chairman & CEO',
    moveType: 'promoted',
    date: '2024-03-01',
    summary: 'Led Lockheed through 5G.MIL, digital transformation, and expansion of Space division capabilities.',
    companySlug: 'lockheed-martin',
  },
  {
    id: 'em-028',
    personName: 'Robert Lightfoot',
    fromCompany: 'Lockheed Martin',
    fromTitle: 'EVP, Space',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2025-03-01',
    summary: 'Former NASA Acting Administrator retired from Lockheed Martin Space division leadership.',
    companySlug: 'lockheed-martin',
  },
  {
    id: 'em-029',
    personName: 'Ted Colbert',
    fromCompany: 'Boeing',
    fromTitle: 'CEO, Defense, Space & Security',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2024-01-08',
    summary: 'Departed Boeing Defense amid Starliner program delays and cost overruns on fixed-price space contracts.',
    companySlug: 'boeing',
  },
  {
    id: 'em-030',
    personName: 'Chris Raymond',
    fromCompany: 'Boeing',
    fromTitle: 'VP Strategy',
    toCompany: 'Boeing',
    toTitle: 'President, Space & Launch',
    moveType: 'promoted',
    date: '2024-02-01',
    summary: 'Promoted to lead Boeing Space division through Starliner certification and SLS block upgrades.',
    companySlug: 'boeing',
  },
  {
    id: 'em-031',
    personName: 'Wes Kremer',
    fromCompany: 'Raytheon Technologies',
    fromTitle: 'President, Raytheon',
    toCompany: 'RTX',
    toTitle: 'President, Raytheon',
    moveType: 'promoted',
    date: '2024-07-01',
    summary: 'Expanded space sensing and missile defense portfolio following RTX corporate restructuring.',
  },

  // === Commercial Space Station / Hab Players ===
  {
    id: 'em-032',
    personName: 'Jeffrey Manber',
    fromCompany: 'Nanoracks',
    fromTitle: 'CEO',
    toCompany: 'Voyager Space',
    toTitle: 'Chief Strategy Officer',
    moveType: 'hired',
    date: '2024-05-01',
    summary: 'Joined Voyager Space parent company to lead Starlab commercial station program strategy.',
    companySlug: 'voyager-space',
  },
  {
    id: 'em-033',
    personName: 'Dylan Taylor',
    fromCompany: 'Voyager Space',
    fromTitle: 'CEO & Chairman',
    toCompany: 'Voyager Space',
    toTitle: 'CEO & Chairman',
    moveType: 'promoted',
    date: '2025-07-01',
    summary: 'Led Voyager Space through Airbus Starlab partnership finalization and NASA CLD award progress.',
    companySlug: 'voyager-space',
  },
  {
    id: 'em-034',
    personName: 'Tejpaul Bhatia',
    fromCompany: 'Airbus Defence & Space',
    fromTitle: 'SVP Strategy',
    toCompany: 'Starlab Space',
    toTitle: 'CEO',
    moveType: 'appointed',
    date: '2025-11-01',
    summary: 'Appointed to lead Starlab Space joint venture as the Voyager-Airbus commercial station advanced toward 2028 launch.',
  },

  // === Satellite & Earth Observation ===
  {
    id: 'em-035',
    personName: 'Will Marshall',
    fromCompany: 'Planet Labs',
    fromTitle: 'CEO & Co-founder',
    toCompany: 'Planet Labs',
    toTitle: 'CEO & Co-founder',
    moveType: 'promoted',
    date: '2025-02-01',
    summary: 'Led Planet to first GAAP profitability and secured major government Pelican constellation contract.',
    companySlug: 'planet-labs',
  },
  {
    id: 'em-036',
    personName: 'Dan Jablonsky',
    fromCompany: 'Maxar Technologies',
    fromTitle: 'CEO',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2023-05-16',
    summary: 'Departed as Maxar completed sale to Advent International, taking the company private after 2022 struggles.',
    companySlug: 'maxar-technologies',
  },
  {
    id: 'em-037',
    personName: 'Chris Johnson',
    fromCompany: 'Advent International',
    fromTitle: 'Operating Partner',
    toCompany: 'Maxar Technologies',
    toTitle: 'CEO',
    moveType: 'hired',
    date: '2023-06-01',
    summary: 'Led Maxar through privatization transition, WorldView Legion deployment, and integration with Advent portfolio.',
    companySlug: 'maxar-technologies',
  },
  {
    id: 'em-038',
    personName: 'Payam Banazadeh',
    fromCompany: 'Capella Space',
    fromTitle: 'CEO & Founder',
    toCompany: 'Capella Space',
    toTitle: 'CEO & Founder',
    moveType: 'promoted',
    date: '2025-01-15',
    summary: 'Grew Capella SAR constellation to 10 operational satellites with expanding government and commercial customer base.',
    companySlug: 'capella-space',
  },

  // === In-Space Services & Propulsion ===
  {
    id: 'em-039',
    personName: 'Daniel Campbell',
    fromCompany: 'Lockheed Martin',
    fromTitle: 'VP Advanced Programs',
    toCompany: 'Impulse Space',
    toTitle: 'President',
    moveType: 'hired',
    date: '2024-09-01',
    summary: 'Joined Impulse Space to scale orbital transfer vehicle operations for defense and commercial customers.',
  },
  {
    id: 'em-040',
    personName: 'Joe Laurienti',
    fromCompany: null,
    fromTitle: null,
    toCompany: 'Impulse Space',
    toTitle: 'CEO & Founder',
    moveType: 'promoted',
    date: '2024-03-01',
    summary: 'Former SpaceX propulsion engineer scaled Impulse Space to Series B and first Mira orbital transfer vehicle demo.',
  },
  {
    id: 'em-041',
    personName: 'Meghan Crawford',
    fromCompany: 'SpaceX',
    fromTitle: 'VP Starlink Government Sales',
    toCompany: 'True Anomaly',
    toTitle: 'President',
    moveType: 'hired',
    date: '2025-04-15',
    summary: 'Joined space domain awareness startup True Anomaly to lead commercial growth and government capture.',
  },

  // === Launch Providers ===
  {
    id: 'em-042',
    personName: 'Adam Spice',
    fromCompany: 'Rocket Lab',
    fromTitle: 'CFO',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2025-08-01',
    summary: 'Departed Rocket Lab after leading the company through SPAC merger, NASDAQ listing, and financial scaling.',
    companySlug: 'rocket-lab',
  },
  {
    id: 'em-043',
    personName: 'Shaun McDougall',
    fromCompany: 'Rocket Lab',
    fromTitle: 'VP Finance',
    toCompany: 'Rocket Lab',
    toTitle: 'CFO',
    moveType: 'promoted',
    date: '2025-08-15',
    summary: 'Promoted from VP Finance to CFO as Neutron development entered final integration phase.',
    companySlug: 'rocket-lab',
  },
  {
    id: 'em-044',
    personName: 'John Insprucker',
    fromCompany: 'SpaceX',
    fromTitle: 'Principal Integration Engineer',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2024-06-01',
    summary: 'Retired from SpaceX after becoming the beloved voice of SpaceX webcasts for over a decade.',
    companySlug: 'spacex',
  },

  // === Space Agencies & Government ===
  {
    id: 'em-045',
    personName: 'Josef Aschbacher',
    fromCompany: 'European Space Agency',
    fromTitle: 'Director General',
    toCompany: 'European Space Agency',
    toTitle: 'Director General',
    moveType: 'promoted',
    date: '2025-07-01',
    summary: 'Term extended after securing record ESA ministerial budget and Ariane 6 maiden flight.',
  },
  {
    id: 'em-046',
    personName: 'Gen. B. Chance Saltzman',
    fromCompany: 'U.S. Space Force',
    fromTitle: 'Chief of Space Operations',
    toCompany: 'U.S. Space Force',
    toTitle: 'Chief of Space Operations',
    moveType: 'promoted',
    date: '2024-11-01',
    summary: 'Continued leading Space Force through operational readiness improvements and commercial augmentation partnerships.',
  },
  {
    id: 'em-047',
    personName: 'Nina Armagno',
    fromCompany: 'U.S. Space Force',
    fromTitle: 'Director of Staff',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2024-05-01',
    summary: 'Retired as the highest-ranking woman in the U.S. Space Force after distinguished career.',
  },

  // === L3Harris, Ball Aerospace, and related ===
  {
    id: 'em-048',
    personName: 'Chris Kubasik',
    fromCompany: 'L3Harris Technologies',
    fromTitle: 'Chair & CEO',
    toCompany: 'L3Harris Technologies',
    toTitle: 'Chair & CEO',
    moveType: 'promoted',
    date: '2024-08-01',
    summary: 'Led L3Harris through acquisition of Aerojet Rocketdyne, expanding space propulsion capabilities.',
    companySlug: 'l3harris-technologies',
  },
  {
    id: 'em-049',
    personName: 'Makenzie Lystrup',
    fromCompany: 'Ball Aerospace',
    fromTitle: 'VP Civil Space',
    toCompany: 'Ball Aerospace',
    toTitle: 'President',
    moveType: 'promoted',
    date: '2023-09-01',
    summary: 'Became first woman to lead Ball Aerospace, overseeing JWST operations support and next-gen space telescopes.',
    companySlug: 'ball-aerospace',
  },

  // === Emerging / New Space ===
  {
    id: 'em-050',
    personName: 'George Whitesides',
    fromCompany: 'Virgin Galactic',
    fromTitle: 'Chief Space Officer (former CEO)',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2024-02-01',
    summary: 'Left Virgin Galactic after stepping down from CEO role. Former NASA Chief of Staff and space industry veteran.',
  },
  {
    id: 'em-051',
    personName: 'Pam Melroy',
    fromCompany: 'NASA',
    fromTitle: 'Deputy Administrator',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2025-01-20',
    summary: 'Former astronaut and NASA Deputy Administrator departed following administration change. Key Artemis program leader.',
    companySlug: 'nasa',
  },
  {
    id: 'em-052',
    personName: 'Steve Altimus',
    fromCompany: 'Sierra Space',
    fromTitle: 'COO',
    toCompany: 'Sierra Space',
    toTitle: 'CEO',
    moveType: 'promoted',
    date: '2025-05-01',
    summary: 'Promoted to CEO as Dream Chaser entered final integration and testing for first ISS cargo mission.',
    companySlug: 'sierra-space',
  },
  {
    id: 'em-053',
    personName: 'Tom Ochinero',
    fromCompany: 'SpaceX',
    fromTitle: 'VP Commercial Sales',
    toCompany: null,
    toTitle: null,
    moveType: 'departed',
    date: '2025-06-01',
    summary: 'Departed SpaceX after building the commercial launch sales organization from its inception.',
    companySlug: 'spacex',
  },
  {
    id: 'em-054',
    personName: 'Sarah Walker',
    fromCompany: 'Rocket Lab',
    fromTitle: 'VP Launch',
    toCompany: 'Rocket Lab',
    toTitle: 'SVP Launch & Mission Management',
    moveType: 'promoted',
    date: '2025-11-01',
    summary: 'Promoted after managing 50+ Electron missions and standing up Neutron launch operations at Wallops.',
    companySlug: 'rocket-lab',
  },
  {
    id: 'em-055',
    personName: 'Tony Bruno',
    fromCompany: null,
    fromTitle: null,
    toCompany: 'Phantom Space',
    toTitle: 'Board Advisor',
    moveType: 'appointed',
    date: '2026-01-20',
    summary: 'Former ULA and Lockheed Martin executive joined Phantom Space advisory board to guide smallsat launch strategy.',
  },
];

/**
 * Get executive moves from the last N days, sorted newest first.
 */
export function getRecentMoves(days: number): ExecutiveMove[] {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - days);
  const cutoffStr = cutoff.toISOString().split('T')[0];

  return EXECUTIVE_MOVES
    .filter(m => m.date >= cutoffStr)
    .sort((a, b) => b.date.localeCompare(a.date));
}

/**
 * Get all moves involving a specific company (by slug or name).
 */
export function getMovesByCompany(slugOrName: string): ExecutiveMove[] {
  const lower = slugOrName.toLowerCase();
  return EXECUTIVE_MOVES.filter(m => {
    if (m.companySlug && m.companySlug.toLowerCase() === lower) return true;
    if (m.fromCompany && m.fromCompany.toLowerCase().includes(lower)) return true;
    if (m.toCompany && m.toCompany.toLowerCase().includes(lower)) return true;
    return false;
  }).sort((a, b) => b.date.localeCompare(a.date));
}

/**
 * Get the most notable moves (those with summaries, sorted newest first).
 */
export function getNotableMoves(): ExecutiveMove[] {
  return EXECUTIVE_MOVES
    .filter(m => m.summary && m.summary.length > 0)
    .sort((a, b) => b.date.localeCompare(a.date));
}
