// Launch-vehicle reference catalogue — curated specs and career records.
// Extracted from the /launch-vehicles page on 2026-08-28 so /rockets/[slug]
// pages can share one source of truth. Career counts are hand-maintained;
// live per-rocket launch stats come from SpaceEvent (src/lib/rockets.ts).

export type VehicleStatus = 'Operational' | 'In Development' | 'Retired';

/** Date the hand-maintained career records below were last audited against
 *  public flight logs. Per-vehicle `asOf` overrides this where a vehicle's
 *  count was verified on a different date. (2026-09-01 fact-check audit.) */
export const VEHICLE_RECORDS_AS_OF = '2026-09-01';

export interface LaunchVehicle {
  id: string;
  name: string;
  manufacturer: string;
  country: string;
  status: VehicleStatus;
  heightM: number;
  diameterM: number;
  massKg: number;
  payloadLeoKg: number;
  payloadGtoKg: number | null;
  payloadSsoKg: number | null;
  payloadTliKg: number | null;
  costMillions: number | null;
  costPerKgLeo: number | null;
  totalLaunches: number;
  successes: number;
  failures: number;
  partialFailures: number;
  successRate: number;
  consecutiveSuccesses: number;
  /** When this vehicle's career record was last verified (defaults to VEHICLE_RECORDS_AS_OF). */
  asOf?: string;
  reusable: boolean;
  stages: number;
  engines: string;
  propellant: string;
  fairingDiameterM: number;
  firstFlight: string;
  lastFlight: string | null;
  description: string;
}

// ────────────────────────────────────────
// Vehicle Seed Data (real specs)
// ────────────────────────────────────────


export const LAUNCH_VEHICLES: LaunchVehicle[] = [
  {
    id: 'falcon-9',
    name: 'Falcon 9 Block 5',
    manufacturer: 'SpaceX',
    country: 'United States',
    status: 'Operational',
    heightM: 70,
    diameterM: 3.7,
    massKg: 549054,
    payloadLeoKg: 22800,
    payloadGtoKg: 8300,
    payloadSsoKg: 15600,
    payloadTliKg: null,
    // 2026-09-01 audit: list price $74M (SatBase, Feb 2026); ~680 flights = ~578
    // through 2025 + ~100 in 2026 by Aug 22; streak counted since the Jul 2024
    // Starlink 9-3 upper-stage failure.
    costMillions: 74,
    costPerKgLeo: 3246,
    totalLaunches: 680,
    successes: 677,
    failures: 2,
    partialFailures: 1,
    successRate: 99.6,
    consecutiveSuccesses: 330,
    asOf: '2026-08-22',
    reusable: true,
    stages: 2,
    engines: '9x Merlin 1D + 1x Merlin Vacuum',
    propellant: 'RP-1 / LOX',
    fairingDiameterM: 5.2,
    firstFlight: '2018-05-11',
    lastFlight: null,
    description: 'The workhorse of the global launch industry. First orbital-class rocket to achieve propulsive landing and routine reuse of the first stage. Dominates the global commercial launch market with 134 flights in 2024 and 165 in 2025. Boosters have been certified for up to 40 flights each. Block 5 variant first flew May 2018 (original Falcon 9 v1.0 debuted June 2010).',
  },
  {
    id: 'falcon-heavy',
    name: 'Falcon Heavy',
    manufacturer: 'SpaceX',
    country: 'United States',
    status: 'Operational',
    heightM: 70,
    diameterM: 12.2,
    massKg: 1420788,
    payloadLeoKg: 63800,
    payloadGtoKg: 26700,
    payloadSsoKg: null,
    payloadTliKg: 16800,
    // 2026-09-01 audit: 13 flights — #13 launched the Roman Space Telescope (late Aug 2026).
    costMillions: 97,
    costPerKgLeo: 1520,
    totalLaunches: 13,
    successes: 13,
    failures: 0,
    partialFailures: 0,
    successRate: 100,
    consecutiveSuccesses: 13,
    asOf: '2026-09-01',
    reusable: true,
    stages: 2,
    engines: '27x Merlin 1D + 1x Merlin Vacuum',
    propellant: 'RP-1 / LOX',
    fairingDiameterM: 5.2,
    firstFlight: '2018-02-06',
    lastFlight: null,
    description: 'The most powerful operational rocket by payload capacity to LEO. Uses three Falcon 9 first-stage cores strapped together. Side boosters are routinely recovered; center core recovery has been demonstrated.',
  },
  {
    id: 'starship',
    name: 'Starship / Super Heavy',
    manufacturer: 'SpaceX',
    country: 'United States',
    status: 'Operational',
    heightM: 121,
    diameterM: 9,
    massKg: 5000000,
    payloadLeoKg: 150000,
    payloadGtoKg: 21000,
    payloadSsoKg: null,
    payloadTliKg: 50000,
    // 2026-09-01 audit: these cost figures are SpaceX's aspirational internal
    // target at mature flight rates, NOT an offered price — see description.
    costMillions: 10,
    costPerKgLeo: 67,
    totalLaunches: 0,
    successes: 0,
    failures: 0,
    partialFailures: 0,
    successRate: 0,
    consecutiveSuccesses: 0,
    reusable: true,
    stages: 2,
    engines: '33x Raptor (booster) + 6x Raptor (ship)',
    propellant: 'CH4 / LOX (Methalox)',
    fairingDiameterM: 8,
    firstFlight: '2023-04-20',
    lastFlight: null,
    // 2026-09-01 audit: Flight 13 (Jul 24, 2026) deployed 20 Starlink V3 — ship
    // splashed down in the Indian Ocean (expended by design), booster destroyed
    // on its landing burn; first ship-catch attempt is planned for Flight 14.
    description: 'The largest and most powerful rocket ever flown, designed for full and rapid reusability. Reached operational status in 2026: Flight 13 (July 24, 2026) deployed the first 20 Starlink V3 satellites, with the ship splashing down in the Indian Ocean (expended by design) and the booster lost during its landing burn; the first tower-catch attempt of the ship is planned for Flight 14. The cost figures shown are SpaceX\'s aspirational internal target at mature flight rates — a target, not an offered price. Intended to also enable Mars colonization, point-to-point Earth transport, and dramatically reduce cost per kg to orbit. See live launch data for current flight-rate and reliability figures rather than a fixed count here.',
  },
  {
    id: 'electron',
    name: 'Electron',
    manufacturer: 'Rocket Lab',
    country: 'United States',
    status: 'Operational',
    heightM: 18,
    diameterM: 1.2,
    massKg: 12550,
    payloadLeoKg: 300,
    payloadGtoKg: null,
    payloadSsoKg: 200,
    payloadTliKg: null,
    costMillions: 7.5,
    costPerKgLeo: 25000,
    // 2026-09-01 audit: 93 launches / ~89 successes as of Aug 20, 2026; every
    // flight since the Sep 2023 failure has succeeded (streak = 40 + 12 new).
    totalLaunches: 93,
    successes: 89,
    failures: 4,
    partialFailures: 0,
    successRate: 95.7,
    consecutiveSuccesses: 52,
    asOf: '2026-08-20',
    reusable: false,
    stages: 2,
    engines: '9x Rutherford + 1x Rutherford Vacuum',
    propellant: 'RP-1 / LOX',
    fairingDiameterM: 1.2,
    firstFlight: '2017-05-25',
    lastFlight: null,
    description: 'The leading dedicated small-satellite launcher, with 93 launches as of August 2026. Uses electric turbopump-fed engines and carbon composite structure. Rocket Lab achieved a record 21 Electron launches in 2025 with 100% mission success, cementing its position as the second most frequently launched US rocket.',
  },
  {
    id: 'neutron',
    name: 'Neutron',
    manufacturer: 'Rocket Lab',
    country: 'United States',
    status: 'In Development',
    heightM: 43,
    diameterM: 7,
    massKg: 480000,
    payloadLeoKg: 13000,
    payloadGtoKg: 1500,
    payloadSsoKg: null,
    payloadTliKg: null,
    costMillions: 50,
    costPerKgLeo: 3846,
    totalLaunches: 0,
    successes: 0,
    failures: 0,
    partialFailures: 0,
    successRate: 0,
    consecutiveSuccesses: 0,
    reusable: true,
    stages: 2,
    engines: '9x Archimedes + 1x Archimedes Vacuum',
    propellant: 'CH4 / LOX (Methalox)',
    fairingDiameterM: 5,
    firstFlight: '2026 (target)',
    lastFlight: null,
    description: 'Rocket Lab\'s medium-lift reusable launch vehicle, targeting the mega-constellation deployment market. Features a unique "Hungry Hippo" fairing design integrated into the first stage, Archimedes methalox engines, and propulsive landing capability. Maiden flight expected in 2026 from Wallops Island, Virginia.',
  },
  {
    id: 'vulcan-centaur',
    name: 'Vulcan Centaur',
    manufacturer: 'ULA',
    country: 'United States',
    status: 'Operational',
    heightM: 61.6,
    diameterM: 5.4,
    massKg: 546700,
    payloadLeoKg: 27200,
    payloadGtoKg: 12350,
    payloadSsoKg: null,
    payloadTliKg: 8900,
    costMillions: 110,
    costPerKgLeo: 4044,
    // 2026-09-01 audit: 4th flight was USSF-87 (Feb 12, 2026) — a second GEM
    // 63XL SRB anomaly; orbit was achieved (counted a success, matching the
    // Cert-2 treatment below) but the Space Force paused NSSL Vulcan launches.
    totalLaunches: 4,
    successes: 4,
    failures: 0,
    partialFailures: 0,
    successRate: 100,
    consecutiveSuccesses: 4,
    asOf: '2026-09-01',
    reusable: false,
    stages: 2,
    engines: '2x BE-4 + 1-2x RL-10C',
    propellant: 'CH4 / LOX (booster) + LH2 / LOX (upper)',
    fairingDiameterM: 5.4,
    firstFlight: '2024-01-08',
    lastFlight: null,
    description: 'ULA\'s next-generation launch vehicle replacing both Atlas V and Delta IV Heavy. Uses Blue Origin BE-4 methalox engines on the first stage and the proven Centaur V upper stage with RL-10C engines. Two flights have experienced GEM 63XL SRB anomalies while still reaching their intended orbits: the Cert-2 mission (October 2024, certified a success by ULA and the U.S. Space Force) and USSF-87 (February 12, 2026), after which the Space Force paused Vulcan national-security launches pending the SRB investigation. Designed for national security missions.',
  },
  {
    id: 'atlas-v',
    name: 'Atlas V',
    manufacturer: 'ULA',
    country: 'United States',
    status: 'Operational',
    heightM: 58.3,
    diameterM: 3.81,
    massKg: 590000,
    payloadLeoKg: 18850,
    payloadGtoKg: 8900,
    payloadSsoKg: null,
    payloadTliKg: null,
    costMillions: 110,
    costPerKgLeo: 5836,
    // 2026-09-01 audit: ~103 flights as of Aug 2026 (2025-26 Kuiper missions);
    // consecutive successes counted since the June 2007 NROL-30 partial
    // failure — the earlier "101 consecutive" contradicted the 1 partial.
    totalLaunches: 103,
    successes: 102,
    failures: 0,
    partialFailures: 1,
    successRate: 99.0,
    consecutiveSuccesses: 93,
    asOf: '2026-08',
    reusable: false,
    stages: 2,
    engines: '1x RD-180 + 1-5x AJ-60A SRBs + 1-2x RL-10A',
    propellant: 'RP-1 / LOX (booster) + LH2 / LOX (upper)',
    fairingDiameterM: 5.4,
    firstFlight: '2002-08-21',
    lastFlight: null,
    description: 'One of the most reliable launch vehicles ever built: roughly 103 flights as of August 2026 with a single partial failure (NROL-30, June 2007) and an unbroken success streak since. Used Russian RD-180 engines. No new orders; flying out its remaining launches (primarily Amazon Kuiper) before retirement, succeeded by Vulcan Centaur.',
  },
  {
    id: 'new-glenn',
    name: 'New Glenn',
    manufacturer: 'Blue Origin',
    country: 'United States',
    status: 'Operational',
    heightM: 98,
    diameterM: 7,
    massKg: 1500000,
    payloadLeoKg: 45000,
    payloadGtoKg: 13000,
    payloadSsoKg: null,
    payloadTliKg: null,
    costMillions: 68,
    costPerKgLeo: 1511,
    // 2026-09-01 audit: NG-3 (Apr 19, 2026) lost AST BlueBird 7 to a
    // second-stage failure; a May 28, 2026 pad explosion then destroyed a
    // vehicle (not counted — never launched) and damaged LC-36.
    totalLaunches: 3,
    successes: 2,
    failures: 1,
    partialFailures: 0,
    successRate: 67,
    consecutiveSuccesses: 0,
    asOf: '2026-09-01',
    reusable: true,
    stages: 2,
    engines: '7x BE-4 + 2x BE-3U',
    propellant: 'CH4 / LOX (booster) + LH2 / LOX (upper)',
    fairingDiameterM: 7,
    firstFlight: '2025-01-16',
    lastFlight: null,
    description: 'Blue Origin\'s orbital heavy-lift launch vehicle with a reusable first stage. Features the largest payload fairing in production at 7 meters diameter. Named after astronaut John Glenn. Successfully landed its first stage booster on the second flight in November 2025, but the third flight (NG-3, April 19, 2026) suffered a second-stage failure that lost AST SpaceMobile\'s BlueBird 7, and a pad explosion on May 28, 2026 destroyed another vehicle and damaged Launch Complex 36 — as of August 2026 the fleet is effectively grounded pending an engine fix.',
  },
  {
    id: 'ariane-6',
    name: 'Ariane 6',
    manufacturer: 'ArianeGroup',
    country: 'France / ESA',
    status: 'Operational',
    heightM: 56,
    diameterM: 5.4,
    massKg: 530000,
    payloadLeoKg: 21650,
    payloadGtoKg: 11500,
    payloadSsoKg: 14900,
    payloadTliKg: null,
    costMillions: 77,
    costPerKgLeo: 3557,
    totalLaunches: 6,
    successes: 5,
    failures: 0,
    partialFailures: 1,
    successRate: 83.3,
    consecutiveSuccesses: 5,
    reusable: false,
    stages: 2,
    engines: '1x Vulcain 2.1 + 0/2/4x P120C SRBs + 1x Vinci',
    propellant: 'LH2 / LOX + HTPB (SRBs)',
    fairingDiameterM: 5.4,
    firstFlight: '2024-07-09',
    lastFlight: null,
    description: 'Europe\'s newest heavy-lift launcher replacing Ariane 5. Available in A62 (2 SRBs) and A64 (4 SRBs) configurations. The Vinci upper stage engine features a restart capability for complex mission profiles. First A64 variant launched in February 2026 with Amazon Kuiper satellites.',
  },
  {
    id: 'vega-c',
    name: 'Vega-C',
    manufacturer: 'Avio',
    country: 'Italy / ESA',
    status: 'Operational',
    heightM: 34.8,
    diameterM: 3.4,
    massKg: 210000,
    payloadLeoKg: 2300,
    payloadGtoKg: null,
    payloadSsoKg: 1500,
    payloadTliKg: null,
    costMillions: 37,
    costPerKgLeo: 16087,
    totalLaunches: 7,
    successes: 6,
    failures: 1,
    partialFailures: 0,
    successRate: 85.7,
    consecutiveSuccesses: 5,
    reusable: false,
    stages: 4,
    engines: 'P120C + Zefiro-40 + Zefiro-9 + AVUM+',
    propellant: 'HTPB (solid) + UDMH/N2O4 (AVUM+)',
    fairingDiameterM: 3.3,
    firstFlight: '2022-07-13',
    lastFlight: null,
    description: 'ESA\'s upgraded small-to-medium launch vehicle with improved performance over the original Vega. Uses the P120C solid motor shared with Ariane 6 as its first stage. Returned to flight in December 2024 after a two-year stand-down, completing four successful missions in 2025.',
  },
  {
    id: 'h3',
    name: 'H3',
    manufacturer: 'JAXA / MHI',
    country: 'Japan',
    status: 'Operational',
    heightM: 63,
    diameterM: 5.2,
    massKg: 574000,
    payloadLeoKg: 16500,
    payloadGtoKg: 6500,
    payloadSsoKg: 12000,
    payloadTliKg: null,
    costMillions: 51,
    costPerKgLeo: 3091,
    totalLaunches: 9,
    successes: 7,
    failures: 2,
    partialFailures: 0,
    successRate: 77.8,
    consecutiveSuccesses: 0,
    reusable: false,
    stages: 2,
    engines: '2x LE-9 + 0/2x SRB-3 + 1x LE-5B-3',
    propellant: 'LH2 / LOX + HTPB (SRBs)',
    fairingDiameterM: 5.2,
    firstFlight: '2023-03-07',
    lastFlight: null,
    description: 'Japan\'s next-generation flagship launch vehicle replacing the H-IIA. Features the expander-bleed cycle LE-9 engine, designed for improved reliability and reduced cost. Suffered a second-stage anomaly on its December 2025 flight after five consecutive successes.',
  },
  {
    id: 'pslv',
    name: 'PSLV',
    manufacturer: 'ISRO',
    country: 'India',
    status: 'Operational',
    heightM: 44,
    diameterM: 2.8,
    massKg: 320000,
    payloadLeoKg: 3800,
    payloadGtoKg: 1425,
    payloadSsoKg: 1750,
    payloadTliKg: null,
    costMillions: 21,
    costPerKgLeo: 5526,
    totalLaunches: 65,
    successes: 62,
    failures: 2,
    partialFailures: 1,
    successRate: 95.2,
    consecutiveSuccesses: 55,
    reusable: false,
    stages: 4,
    engines: 'S139 + Vikas + PS3 + PS4',
    propellant: 'HTPB + UDMH/N2O4 + HTPB + MMH/MON-3',
    fairingDiameterM: 3.2,
    firstFlight: '1993-09-20',
    lastFlight: null,
    description: 'India\'s highly reliable workhorse launcher with over 65 missions. Known for cost-effective rideshare and dedicated small satellite missions. Holds the record for deploying 104 satellites in a single mission (PSLV-C37).',
  },
  {
    id: 'lvm3',
    name: 'LVM3 (GSLV Mk III)',
    manufacturer: 'ISRO',
    country: 'India',
    status: 'Operational',
    heightM: 43.4,
    diameterM: 4,
    massKg: 640000,
    payloadLeoKg: 10000,
    payloadGtoKg: 4000,
    payloadSsoKg: null,
    payloadTliKg: null,
    costMillions: 47,
    costPerKgLeo: 4700,
    totalLaunches: 9,
    successes: 9,
    failures: 0,
    partialFailures: 0,
    successRate: 100,
    consecutiveSuccesses: 9,
    reusable: false,
    stages: 3,
    engines: '2x S200 SRBs + 2x Vikas + 1x CE-20',
    propellant: 'HTPB (SRBs) + UDMH/N2O4 + LH2/LOX',
    fairingDiameterM: 5,
    firstFlight: '2017-06-05',
    lastFlight: null,
    description: 'India\'s heaviest launch vehicle, used for Chandrayaan-3 lunar mission and OneWeb constellation deployment. Features indigenous CE-20 cryogenic upper stage engine. Also designated for the Gaganyaan crewed program.',
  },
  {
    id: 'long-march-5',
    name: 'Long March 5',
    manufacturer: 'CALT / CASC',
    country: 'China',
    status: 'Operational',
    heightM: 56.97,
    diameterM: 5,
    massKg: 869000,
    payloadLeoKg: 25000,
    payloadGtoKg: 14000,
    payloadSsoKg: null,
    payloadTliKg: 8200,
    costMillions: 100,
    costPerKgLeo: 4000,
    totalLaunches: 15,
    successes: 14,
    failures: 1,
    partialFailures: 0,
    successRate: 93.3,
    consecutiveSuccesses: 13,
    reusable: false,
    stages: 2,
    engines: '2x YF-77 + 4x boosters (2x YF-100 each) + 2x YF-75D',
    propellant: 'LH2 / LOX (core) + RP-1/LOX (boosters)',
    fairingDiameterM: 5.2,
    firstFlight: '2016-11-03',
    lastFlight: null,
    description: 'China\'s most powerful operational rocket, used for the Tianhe space station modules, Chang\'e lunar missions, and Tianwen Mars probe. The Long March 5B variant is used for LEO heavy-lift.',
  },
  {
    id: 'long-march-2d',
    name: 'Long March 2D',
    manufacturer: 'SAST / CASC',
    country: 'China',
    status: 'Operational',
    heightM: 41.06,
    diameterM: 3.35,
    massKg: 232250,
    payloadLeoKg: 3500,
    payloadGtoKg: null,
    payloadSsoKg: 1300,
    payloadTliKg: null,
    costMillions: 30,
    costPerKgLeo: 8571,
    totalLaunches: 105,
    successes: 104,
    failures: 1,
    partialFailures: 0,
    successRate: 99.0,
    consecutiveSuccesses: 100,
    reusable: false,
    stages: 2,
    engines: '4x YF-21C + 1x YF-24C',
    propellant: 'UDMH / N2O4',
    fairingDiameterM: 3.35,
    firstFlight: '1992-08-09',
    lastFlight: null,
    description: 'China\'s highly reliable medium-lift workhorse, primarily used for Earth observation and SSO missions. Reached its 100th mission milestone in September 2025, one of the most frequently launched Chinese vehicles.',
  },
  {
    id: 'long-march-3b',
    name: 'Long March 3B/E',
    manufacturer: 'CALT / CASC',
    country: 'China',
    status: 'Operational',
    heightM: 56.33,
    diameterM: 3.35,
    massKg: 458970,
    payloadLeoKg: 11500,
    payloadGtoKg: 5500,
    payloadSsoKg: null,
    payloadTliKg: null,
    costMillions: 70,
    costPerKgLeo: 6087,
    totalLaunches: 97,
    successes: 93,
    failures: 3,
    partialFailures: 1,
    successRate: 95.9,
    consecutiveSuccesses: 50,
    reusable: false,
    stages: 3,
    engines: '4x YF-21C + 4x YF-25 (boosters) + 1x YF-24E + 2x YF-75',
    propellant: 'UDMH/N2O4 + LH2/LOX (3rd stage)',
    fairingDiameterM: 4.2,
    firstFlight: '1996-02-15',
    lastFlight: null,
    description: 'China\'s primary GTO launch vehicle, used extensively for BeiDou navigation satellite deployment. Features four strap-on liquid boosters and a cryogenic third stage.',
  },
  {
    id: 'ceres-1',
    name: 'Ceres-1',
    manufacturer: 'Galactic Energy',
    country: 'China',
    status: 'Operational',
    heightM: 20,
    diameterM: 1.4,
    massKg: 33000,
    payloadLeoKg: 400,
    payloadGtoKg: null,
    payloadSsoKg: 230,
    payloadTliKg: null,
    costMillions: 5,
    costPerKgLeo: 12500,
    totalLaunches: 23,
    successes: 21,
    failures: 2,
    partialFailures: 0,
    successRate: 91.3,
    consecutiveSuccesses: 2,
    reusable: false,
    stages: 4,
    engines: '4x solid stages + liquid kick stage',
    propellant: 'Solid (HTPB) + Liquid kick',
    fairingDiameterM: 1.4,
    firstFlight: '2020-11-07',
    lastFlight: null,
    description: 'China\'s leading commercial small launch vehicle from Galactic Energy. One of the first privately developed Chinese rockets to reach orbit. Provides cost-effective dedicated small-sat access to SSO.',
  },
  {
    id: 'soyuz-2',
    name: 'Soyuz-2.1b',
    manufacturer: 'RKTs Progress',
    country: 'Russia',
    status: 'Operational',
    heightM: 46.3,
    diameterM: 10.3,
    massKg: 312000,
    payloadLeoKg: 8200,
    payloadGtoKg: 3250,
    payloadSsoKg: 4850,
    payloadTliKg: null,
    costMillions: 48,
    costPerKgLeo: 5854,
    totalLaunches: 74,
    successes: 72,
    failures: 2,
    partialFailures: 0,
    successRate: 97.3,
    consecutiveSuccesses: 48,
    reusable: false,
    stages: 3,
    engines: '4x RD-107A + 1x RD-108A + 1x RD-0124',
    propellant: 'RP-1 / LOX',
    fairingDiameterM: 4.11,
    firstFlight: '2006-12-27',
    lastFlight: null,
    description: 'The modern variant of the legendary R-7 derived Soyuz family, the most launched rocket design in history. Used for ISS crew transport (with Soyuz-2.1a for crewed flights), Glonass navigation, and commercial payloads.',
  },
  {
    id: 'proton-m',
    name: 'Proton-M',
    manufacturer: 'Khrunichev',
    country: 'Russia',
    status: 'Operational',
    heightM: 58.2,
    diameterM: 7.4,
    massKg: 705000,
    payloadLeoKg: 23700,
    payloadGtoKg: 6920,
    payloadSsoKg: null,
    payloadTliKg: null,
    costMillions: 65,
    costPerKgLeo: 2743,
    totalLaunches: 115,
    successes: 104,
    failures: 10,
    partialFailures: 1,
    successRate: 90.4,
    consecutiveSuccesses: 15,
    reusable: false,
    stages: 4,
    engines: '6x RD-275M + 3x RD-0210/0211 + 1x RD-0212 + various upper stages',
    propellant: 'UDMH / N2O4',
    fairingDiameterM: 5,
    firstFlight: '2001-04-07',
    lastFlight: null,
    description: 'Russia\'s heavy-lift workhorse used primarily for GTO communications satellites and interplanetary missions. Uses hypergolic propellants throughout. Being phased out in favor of the Angara A5.',
  },
  {
    id: 'angara-a5',
    name: 'Angara A5',
    manufacturer: 'Khrunichev',
    country: 'Russia',
    status: 'Operational',
    heightM: 64,
    diameterM: 8.86,
    massKg: 773000,
    payloadLeoKg: 24500,
    payloadGtoKg: 5400,
    payloadSsoKg: null,
    payloadTliKg: null,
    costMillions: 100,
    costPerKgLeo: 4082,
    totalLaunches: 5,
    successes: 5,
    failures: 0,
    partialFailures: 0,
    successRate: 100,
    consecutiveSuccesses: 5,
    reusable: false,
    stages: 3,
    engines: '5x RD-191 (URM) + 1x RD-0124A + upper stages',
    propellant: 'RP-1 / LOX + LH2/LOX (upper)',
    fairingDiameterM: 5.1,
    firstFlight: '2014-12-23',
    lastFlight: null,
    description: 'Russia\'s new modular heavy-lift vehicle intended to replace the Proton-M. Built from Universal Rocket Modules (URMs). Unlike Proton, uses environmentally cleaner RP-1/LOX propellant. Launching from Vostochny Cosmodrome.',
  },
  {
    id: 'firefly-alpha',
    name: 'Firefly Alpha',
    manufacturer: 'Firefly Aerospace',
    country: 'United States',
    status: 'Operational',
    heightM: 29,
    diameterM: 1.82,
    massKg: 54000,
    payloadLeoKg: 1030,
    payloadGtoKg: null,
    payloadSsoKg: 630,
    payloadTliKg: null,
    costMillions: 15,
    costPerKgLeo: 14563,
    totalLaunches: 8,
    successes: 6,
    failures: 1,
    partialFailures: 1,
    successRate: 75.0,
    consecutiveSuccesses: 5,
    reusable: false,
    stages: 2,
    engines: '4x Reaver 1 + 1x Lightning 1',
    propellant: 'RP-1 / LOX',
    fairingDiameterM: 2,
    firstFlight: '2021-09-02',
    lastFlight: null,
    description: 'A small launch vehicle designed for dedicated small satellite missions. Uses tap-off cycle engines with carbon fiber composite structures. Also developing the medium-lift MLV in partnership with Northrop Grumman.',
  },
  {
    id: 'terran-r',
    name: 'Terran R',
    manufacturer: 'Relativity Space',
    country: 'United States',
    status: 'In Development',
    heightM: 66,
    diameterM: 5,
    massKg: 290000,
    payloadLeoKg: 20000,
    payloadGtoKg: 5000,
    payloadSsoKg: null,
    payloadTliKg: null,
    costMillions: null,
    costPerKgLeo: null,
    totalLaunches: 0,
    successes: 0,
    failures: 0,
    partialFailures: 0,
    successRate: 0,
    consecutiveSuccesses: 0,
    reusable: true,
    stages: 2,
    engines: '7x Aeon R (1st) + 1x Aeon Vac (2nd)',
    propellant: 'CH4 / LOX (Methalox)',
    fairingDiameterM: 5,
    firstFlight: '2026 (target)',
    lastFlight: null,
    description: 'A medium-to-heavy lift reusable launch vehicle incorporating 3D-printed manufacturing. Following the retirement of Terran 1 after its test flight, Relativity shifted focus entirely to Terran R for the medium-lift reusable market.',
  },
  {
    id: 'epsilon-s',
    name: 'Epsilon S',
    manufacturer: 'IHI Aerospace / JAXA',
    country: 'Japan',
    status: 'In Development',
    heightM: 27.5,
    diameterM: 2.6,
    massKg: 96000,
    payloadLeoKg: 1500,
    payloadGtoKg: null,
    payloadSsoKg: 600,
    payloadTliKg: null,
    costMillions: 30,
    costPerKgLeo: 20000,
    totalLaunches: 0,
    successes: 0,
    failures: 0,
    partialFailures: 0,
    successRate: 0,
    consecutiveSuccesses: 0,
    reusable: false,
    stages: 3,
    engines: 'SRB-3 + M-35 + KM-V2c',
    propellant: 'Solid (HTPB composite)',
    fairingDiameterM: 2.6,
    firstFlight: '2024 (engine test failure, delayed)',
    lastFlight: null,
    description: 'Japan\'s upgraded solid-fuel small satellite launcher, enhanced from the Epsilon series. Shares the SRB-3 booster with H3. Development delayed by a third-stage static fire test failure in 2023.',
  },
  {
    id: 'long-march-6a',
    name: 'Long March 6A',
    manufacturer: 'SAST / CASC',
    country: 'China',
    status: 'Operational',
    heightM: 50,
    diameterM: 3.35,
    massKg: 530000,
    payloadLeoKg: 7000,
    payloadGtoKg: null,
    payloadSsoKg: 4000,
    payloadTliKg: null,
    costMillions: 35,
    costPerKgLeo: 5000,
    totalLaunches: 3,
    successes: 3,
    failures: 0,
    partialFailures: 0,
    successRate: 100,
    consecutiveSuccesses: 3,
    reusable: false,
    stages: 2,
    engines: '1x YF-100K + 4x solid boosters + 1x YF-115',
    propellant: 'RP-1 / LOX + HTPB (SRBs)',
    fairingDiameterM: 4.2,
    firstFlight: '2022-03-29',
    lastFlight: null,
    description: 'China\'s newest medium-lift hybrid vehicle combining liquid core stage with solid strap-on boosters. Designed for SSO constellation deployment with high launch cadence.',
  },
];
