// AI Report Generation Engine
// Uses Anthropic Claude to generate comprehensive space industry research reports
// Gathers data from existing SpaceNexus sources (company profiles, news, funding, events)

import Anthropic from '@anthropic-ai/sdk';
import prisma from '@/lib/db';
import { logger } from '@/lib/logger';
import {
  SPACE_SECTORS,
  buildSectorOverviewPrompt,
  buildCompanyDeepDivePrompt,
  buildCompetitiveAnalysisPrompt,
  buildMarketEntryBriefPrompt,
} from '@/lib/report-templates';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ReportSectionContent {
  id: string;
  title: string;
  content: string;
}

export interface GeneratedReport {
  title: string;
  subtitle: string;
  generatedAt: string;
  reportType: string;
  executive_summary: string;
  methodology: string;
  sections: ReportSectionContent[];
}

export interface GenerateOptions {
  maxTokens?: number;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const MOCK_ENABLED = !process.env.ANTHROPIC_API_KEY;

function getSampleReport(reportType: string, title: string): GeneratedReport {
  return {
    title,
    subtitle: 'Sample report generated with mock data',
    generatedAt: new Date().toISOString(),
    reportType,
    executive_summary:
      'This is a sample report generated without an AI connection. Configure ANTHROPIC_API_KEY to enable full AI-powered report generation with real data analysis and insights.',
    methodology:
      'Sample data only. Connect ANTHROPIC_API_KEY for AI-powered analysis using SpaceNexus database of 100+ company profiles, funding rounds, news articles, and market intelligence.',
    sections: [
      {
        id: 'exec-summary',
        title: 'Executive Summary',
        content:
          '**This is a sample report.** When ANTHROPIC_API_KEY is configured, this section will contain a comprehensive executive summary generated by Claude AI based on real SpaceNexus data.\n\n- Key finding 1: The space economy continues to grow at 7-9% CAGR\n- Key finding 2: Private investment reached $15B+ in the latest fiscal year\n- Key finding 3: Regulatory frameworks are evolving to support commercial space activities\n- Key finding 4: Consolidation activity is accelerating across multiple sectors',
      },
      {
        id: 'market-overview',
        title: 'Market Overview',
        content:
          'The global space economy is valued at approximately **$546 billion** and growing. Key segments include:\n\n| Segment | Size (2025) | Growth Rate |\n|---------|------------|-------------|\n| Satellite Services | $144B | 4.2% |\n| Launch Services | $8.5B | 12.3% |\n| Ground Equipment | $145B | 5.1% |\n| Government Budgets | $110B | 6.8% |\n\n> *Note: This is sample data. Full reports include AI-generated analysis from real SpaceNexus data sources.*',
      },
      {
        id: 'key-players',
        title: 'Key Players',
        content:
          'Major companies operating in this sector include:\n\n1. **SpaceX** — Market leader in launch services with reusable Falcon 9 and Starship programs\n2. **Rocket Lab** — Leading small launch provider expanding into satellite manufacturing\n3. **Planet Labs** — Largest commercial Earth observation constellation\n4. **Aerojet Rocketdyne (L3Harris)** — Major propulsion system supplier\n5. **Maxar Technologies** — Leading provider of Earth intelligence and space infrastructure\n\n> *Full reports include comprehensive company-level data from the SpaceNexus intelligence database.*',
      },
      {
        id: 'trends',
        title: 'Key Trends',
        content:
          '### Emerging Trends\n\n- **Mega-constellation deployment** — Thousands of satellites being launched for broadband connectivity\n- **In-space servicing** — Growing market for satellite life extension and debris removal\n- **Defense space spending** — Government investment in space resilience and rapid capability development\n- **Commercial space stations** — Transition from ISS to commercial LEO destinations\n- **Space sustainability** — Increasing focus on debris mitigation and responsible operations',
      },
      {
        id: 'outlook',
        title: 'Strategic Outlook',
        content:
          '### Forward-Looking Assessment\n\nThe sector is positioned for continued growth driven by:\n\n1. Declining launch costs enabling new applications\n2. Growing government demand for commercial solutions\n3. Emerging use cases in IoT, direct-to-device, and edge computing\n4. Increasing international participation and competition\n\n**Key risks** include regulatory uncertainty, spectrum congestion, and orbital debris accumulation.\n\n> *Configure ANTHROPIC_API_KEY for complete AI-powered analysis with actionable recommendations.*',
      },
    ],
  };
}

// ---------------------------------------------------------------------------
// Data gathering helpers
// ---------------------------------------------------------------------------

async function gatherSectorData(sector: string): Promise<string> {
  // Map sector ID to relevant database fields
  const sectorMapping: Record<string, string[]> = {
    'launch-services': ['launch', 'propulsion'],
    'satellite-manufacturing': ['satellite', 'manufacturing'],
    'earth-observation': ['satellite', 'analytics', 'earth-observation'],
    'satellite-communications': ['satellite', 'communications'],
    'space-defense': ['defense'],
    'in-space-services': ['infrastructure', 'in-space'],
    'ground-segment': ['ground-segment', 'infrastructure'],
    'space-analytics': ['analytics'],
    'cislunar-economy': ['cislunar', 'lunar'],
    'space-manufacturing': ['manufacturing'],
    'space-tourism': ['human-spaceflight', 'tourism'],
    'smallsat-constellation': ['satellite', 'constellation', 'smallsat'],
    'propulsion': ['propulsion', 'launch'],
    'space-debris': ['debris', 'sustainability'],
    'spectrum-management': ['spectrum', 'rf', 'communications'],
  };

  const sectorTags = sectorMapping[sector] || [sector];

  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const db = prisma as any;

    const [companies, recentNews, recentFunding, recentEvents, listings] = await Promise.all([
      // Companies in this sector
      db.companyProfile.findMany({
        where: {
          OR: [
            { sector: { in: sectorTags } },
            { tags: { hasSome: sectorTags } },
          ],
        },
        take: 30,
        orderBy: { tier: 'asc' },
        select: {
          name: true,
          slug: true,
          sector: true,
          status: true,
          tier: true,
          employeeRange: true,
          headquarters: true,
          totalFunding: true,
          lastFundingRound: true,
          valuation: true,
          revenueEstimate: true,
          ownershipType: true,
          isPublic: true,
          marketCap: true,
          description: true,
          tags: true,
          foundedYear: true,
        },
      }).catch(() => []),

      // Recent news
      db.newsArticle.findMany({
        where: {
          publishedAt: {
            gte: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000), // last 90 days
          },
          OR: sectorTags.map((tag: string) => ({
            OR: [
              { title: { contains: tag, mode: 'insensitive' } },
              { category: { contains: tag, mode: 'insensitive' } },
            ],
          })),
        },
        take: 15,
        orderBy: { publishedAt: 'desc' },
        select: {
          title: true,
          summary: true,
          source: true,
          category: true,
          publishedAt: true,
        },
      }).catch(() => []),

      // Recent funding in sector
      db.fundingRound.findMany({
        where: {
          date: {
            gte: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000), // last year
          },
          company: {
            OR: [
              { sector: { in: sectorTags } },
              { tags: { hasSome: sectorTags } },
            ],
          },
        },
        take: 20,
        orderBy: { date: 'desc' },
        select: {
          amount: true,
          currency: true,
          seriesLabel: true,
          roundType: true,
          leadInvestor: true,
          date: true,
          company: {
            select: { name: true },
          },
        },
      }).catch(() => []),

      // Recent company events
      db.companyEvent.findMany({
        where: {
          date: {
            gte: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000), // last 6 months
          },
          company: {
            OR: [
              { sector: { in: sectorTags } },
              { tags: { hasSome: sectorTags } },
            ],
          },
        },
        take: 15,
        orderBy: [{ importance: 'desc' }, { date: 'desc' }],
        select: {
          title: true,
          type: true,
          importance: true,
          date: true,
          company: {
            select: { name: true },
          },
        },
      }).catch(() => []),

      // Marketplace listings in sector
      db.serviceListing.findMany({
        where: {
          status: 'active',
          category: { in: sectorTags },
        },
        take: 10,
        select: {
          name: true,
          category: true,
          subcategory: true,
          pricingType: true,
          priceMin: true,
          priceMax: true,
          company: {
            select: { name: true },
          },
        },
      }).catch(() => []),
    ]);

    // Format context data
    const parts: string[] = [];

    if (companies.length > 0) {
      parts.push('### Companies in this Sector');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      parts.push(companies.map((c: any) => {
        const funding = c.totalFunding ? `$${(c.totalFunding / 1e6).toFixed(1)}M funding` : 'Funding undisclosed';
        const valuation = c.valuation ? `$${(c.valuation / 1e9).toFixed(2)}B valuation` : '';
        const revenue = c.revenueEstimate ? `$${(c.revenueEstimate / 1e6).toFixed(0)}M est. revenue` : '';
        return `- **${c.name}** (Tier ${c.tier}) — ${c.description?.slice(0, 100) || 'No description'}. ${funding}${valuation ? ', ' + valuation : ''}${revenue ? ', ' + revenue : ''}. Founded ${c.foundedYear || 'N/A'}. ${c.employeeRange || 'N/A'} employees. ${c.headquarters || ''}`;
      }).join('\n'));
    }

    if (recentFunding.length > 0) {
      parts.push('\n### Recent Funding Activity (Past 12 Months)');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      parts.push(recentFunding.map((f: any) => {
        const amt = f.amount ? `$${(f.amount / 1e6).toFixed(1)}M` : 'Undisclosed amount';
        return `- ${f.company.name}: ${f.seriesLabel || f.roundType || 'Round'} — ${amt}${f.leadInvestor ? `, led by ${f.leadInvestor}` : ''} (${new Date(f.date).toLocaleDateString()})`;
      }).join('\n'));
    }

    if (recentNews.length > 0) {
      parts.push('\n### Recent News (Past 90 Days)');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      parts.push(recentNews.map((n: any) =>
        `- [${n.category}] ${n.title} — ${n.source} (${new Date(n.publishedAt).toLocaleDateString()})`
      ).join('\n'));
    }

    if (recentEvents.length > 0) {
      parts.push('\n### Key Company Events (Past 6 Months)');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      parts.push(recentEvents.map((e: any) =>
        `- ${e.company.name}: ${e.title} [${e.type}] (Importance: ${e.importance}/10)`
      ).join('\n'));
    }

    if (listings.length > 0) {
      parts.push('\n### Marketplace Listings');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      parts.push(listings.map((l: any) => {
        const price = l.priceMin && l.priceMax
          ? `$${l.priceMin.toLocaleString()}-$${l.priceMax.toLocaleString()}`
          : l.priceMin ? `From $${l.priceMin.toLocaleString()}` : 'RFQ';
        return `- ${l.company.name}: ${l.name} (${l.category}/${l.subcategory || 'general'}) — ${price}`;
      }).join('\n'));
    }

    if (parts.length === 0) {
      return 'Limited data available in database for this sector. Please generate analysis based on your general knowledge of the space industry.';
    }

    return parts.join('\n');
  } catch (error) {
    logger.error('Failed to gather sector data', {
      sector,
      error: error instanceof Error ? error.message : String(error),
    });
    return 'Database query failed. Please generate analysis based on general space industry knowledge.';
  }
}

async function gatherCompanyData(companySlug: string): Promise<{ name: string; contextData: string }> {
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const db = prisma as any;

    const company = await db.companyProfile.findUnique({
      where: { slug: companySlug },
      include: {
        fundingRounds: {
          orderBy: { date: 'desc' },
          take: 10,
        },
        events: {
          orderBy: [{ importance: 'desc' }, { date: 'desc' }],
          take: 20,
        },
        scores: true,
        satelliteAssets: {
          take: 10,
        },
        facilities: {
          take: 10,
        },
        newsArticles: {
          orderBy: { publishedAt: 'desc' },
          take: 10,
          select: {
            title: true,
            summary: true,
            source: true,
            publishedAt: true,
          },
        },
        serviceListings: {
          where: { status: 'active' },
          take: 10,
          select: {
            name: true,
            category: true,
            pricingType: true,
            priceMin: true,
            priceMax: true,
          },
        },
      },
    }).catch(() => null);

    if (!company) {
      return {
        name: companySlug,
        contextData: `Company with slug "${companySlug}" not found in database. Generate a report based on general industry knowledge for a company with this identifier.`,
      };
    }

    const parts: string[] = [];

    // Company basics
    parts.push('### Company Profile');
    parts.push(`- **Name**: ${company.name}`);
    if (company.legalName) parts.push(`- **Legal Name**: ${company.legalName}`);
    if (company.ticker) parts.push(`- **Ticker**: ${company.ticker} (${company.exchange || 'N/A'})`);
    parts.push(`- **Status**: ${company.status}`);
    parts.push(`- **Sector**: ${company.sector || 'N/A'}`);
    if (company.subsector) parts.push(`- **Subsector**: ${company.subsector}`);
    parts.push(`- **Tier**: ${company.tier}`);
    if (company.foundedYear) parts.push(`- **Founded**: ${company.foundedYear}`);
    if (company.headquarters) parts.push(`- **HQ**: ${company.headquarters}`);
    if (company.employeeRange) parts.push(`- **Employees**: ${company.employeeRange}`);
    if (company.ceo) parts.push(`- **CEO**: ${company.ceo}`);
    if (company.cto) parts.push(`- **CTO**: ${company.cto}`);
    if (company.ownershipType) parts.push(`- **Ownership**: ${company.ownershipType}`);
    if (company.parentCompany) parts.push(`- **Parent Company**: ${company.parentCompany}`);
    if (company.description) parts.push(`- **Description**: ${company.description}`);
    if (company.longDescription) parts.push(`- **Detailed Overview**: ${company.longDescription}`);
    if (company.tags?.length) parts.push(`- **Tags**: ${company.tags.join(', ')}`);

    // Financial data
    parts.push('\n### Financial Data');
    if (company.totalFunding) parts.push(`- **Total Funding**: $${(company.totalFunding / 1e6).toFixed(1)}M`);
    if (company.lastFundingRound) parts.push(`- **Last Round**: ${company.lastFundingRound}`);
    if (company.valuation) parts.push(`- **Valuation**: $${(company.valuation / 1e9).toFixed(2)}B`);
    if (company.revenueEstimate) parts.push(`- **Revenue Estimate**: $${(company.revenueEstimate / 1e6).toFixed(0)}M`);
    if (company.isPublic && company.marketCap) parts.push(`- **Market Cap**: $${(company.marketCap / 1e9).toFixed(2)}B`);

    // Funding rounds
    if (company.fundingRounds?.length > 0) {
      parts.push('\n### Funding History');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      company.fundingRounds.forEach((f: any) => {
        const amt = f.amount ? `$${(f.amount / 1e6).toFixed(1)}M` : 'Undisclosed';
        parts.push(`- ${f.seriesLabel || f.roundType || 'Round'}: ${amt}${f.leadInvestor ? ` (led by ${f.leadInvestor})` : ''} — ${new Date(f.date).toLocaleDateString()}`);
        if (f.investors?.length) parts.push(`  Investors: ${f.investors.join(', ')}`);
      });
    }

    // Events / milestones
    if (company.events?.length > 0) {
      parts.push('\n### Key Events & Milestones');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      company.events.forEach((e: any) => {
        parts.push(`- [${e.type}] ${e.title} (${new Date(e.date).toLocaleDateString()}) — Importance: ${e.importance}/10`);
        if (e.description) parts.push(`  ${e.description.slice(0, 200)}`);
      });
    }

    // Scores
    if (company.scores?.length > 0) {
      parts.push('\n### Company Scores');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      company.scores.forEach((s: any) => {
        parts.push(`- ${s.scoreType}: ${s.score}/100`);
      });
    }

    // Recent news
    if (company.newsArticles?.length > 0) {
      parts.push('\n### Recent News');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      company.newsArticles.forEach((n: any) => {
        parts.push(`- ${n.title} — ${n.source} (${new Date(n.publishedAt).toLocaleDateString()})`);
      });
    }

    // Satellite assets
    if (company.satelliteAssets?.length > 0) {
      parts.push('\n### Satellite Assets');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      company.satelliteAssets.forEach((s: any) => {
        parts.push(`- ${s.name || s.noradId}: ${s.orbitType || 'Unknown orbit'}${s.status ? ` (${s.status})` : ''}`);
      });
    }

    // Service listings
    if (company.serviceListings?.length > 0) {
      parts.push('\n### Marketplace Listings');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      company.serviceListings.forEach((l: any) => {
        const price = l.priceMin && l.priceMax
          ? `$${l.priceMin.toLocaleString()}-$${l.priceMax.toLocaleString()}`
          : 'RFQ';
        parts.push(`- ${l.name} (${l.category}) — ${price}`);
      });
    }

    return {
      name: company.name,
      contextData: parts.join('\n'),
    };
  } catch (error) {
    logger.error('Failed to gather company data', {
      companySlug,
      error: error instanceof Error ? error.message : String(error),
    });
    return {
      name: companySlug,
      contextData: 'Database query failed. Generate analysis based on general knowledge.',
    };
  }
}

async function gatherMultiCompanyData(companySlugs: string[]): Promise<{ names: string[]; contextData: string }> {
  const results = await Promise.all(companySlugs.map((slug) => gatherCompanyData(slug)));
  const names = results.map((r) => r.name);
  const contextData = results.map((r, i) => `## Company ${i + 1}: ${r.name}\n${r.contextData}`).join('\n\n---\n\n');
  return { names, contextData };
}

async function gatherMarketEntryData(topic: string): Promise<string> {
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const db = prisma as any;

    // Extract keywords from topic for searching
    const keywords = topic
      .toLowerCase()
      .split(/\s+/)
      .filter((w: string) => w.length > 3 && !['the', 'and', 'for', 'with', 'from', 'into', 'that', 'this'].includes(w));

    const [relatedCompanies, relatedNews, relatedListings] = await Promise.all([
      // Find companies related to the topic
      db.companyProfile.findMany({
        where: {
          OR: keywords.slice(0, 5).map((kw: string) => ({
            OR: [
              { description: { contains: kw, mode: 'insensitive' } },
              { name: { contains: kw, mode: 'insensitive' } },
              { sector: { contains: kw, mode: 'insensitive' } },
            ],
          })),
        },
        take: 20,
        orderBy: { tier: 'asc' },
        select: {
          name: true,
          sector: true,
          tier: true,
          totalFunding: true,
          employeeRange: true,
          description: true,
          status: true,
        },
      }).catch(() => []),

      // Related news
      db.newsArticle.findMany({
        where: {
          publishedAt: {
            gte: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000),
          },
          OR: keywords.slice(0, 3).map((kw: string) => ({
            title: { contains: kw, mode: 'insensitive' },
          })),
        },
        take: 10,
        orderBy: { publishedAt: 'desc' },
        select: {
          title: true,
          source: true,
          category: true,
          publishedAt: true,
        },
      }).catch(() => []),

      // Related marketplace listings
      db.serviceListing.findMany({
        where: {
          status: 'active',
          OR: keywords.slice(0, 3).map((kw: string) => ({
            OR: [
              { name: { contains: kw, mode: 'insensitive' } },
              { description: { contains: kw, mode: 'insensitive' } },
            ],
          })),
        },
        take: 10,
        select: {
          name: true,
          category: true,
          pricingType: true,
          priceMin: true,
          priceMax: true,
          company: { select: { name: true } },
        },
      }).catch(() => []),
    ]);

    const parts: string[] = [];

    if (relatedCompanies.length > 0) {
      parts.push('### Existing Players in Related Space');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      parts.push(relatedCompanies.map((c: any) => {
        const funding = c.totalFunding ? `$${(c.totalFunding / 1e6).toFixed(1)}M funding` : '';
        return `- **${c.name}** (Tier ${c.tier}, ${c.sector || 'N/A'}) — ${c.description?.slice(0, 120) || 'N/A'}${funding ? `. ${funding}` : ''}`;
      }).join('\n'));
    }

    if (relatedNews.length > 0) {
      parts.push('\n### Related Recent News');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      parts.push(relatedNews.map((n: any) =>
        `- ${n.title} — ${n.source} (${new Date(n.publishedAt).toLocaleDateString()})`
      ).join('\n'));
    }

    if (relatedListings.length > 0) {
      parts.push('\n### Related Marketplace Listings');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      parts.push(relatedListings.map((l: any) => {
        const price = l.priceMin ? `From $${l.priceMin.toLocaleString()}` : 'RFQ';
        return `- ${l.company.name}: ${l.name} (${l.category}) — ${price}`;
      }).join('\n'));
    }

    if (parts.length === 0) {
      return 'Limited direct data found for this topic in the database. Generate analysis based on general space industry knowledge and publicly available information.';
    }

    return parts.join('\n');
  } catch (error) {
    logger.error('Failed to gather market entry data', {
      topic,
      error: error instanceof Error ? error.message : String(error),
    });
    return 'Database query failed. Generate analysis based on general space industry knowledge.';
  }
}

// ---------------------------------------------------------------------------
// AI call helper
// ---------------------------------------------------------------------------

async function callClaude(
  systemPrompt: string,
  userPrompt: string,
  maxTokens: number = 8000
): Promise<GeneratedReport> {
  const anthropic = new Anthropic();

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-5-20250929',
    max_tokens: maxTokens,
    system: systemPrompt,
    messages: [{ role: 'user', content: userPrompt }],
  });

  const textBlock = response.content.find((block) => block.type === 'text');
  if (!textBlock || textBlock.type !== 'text') {
    throw new Error('AI response contained no text');
  }

  // Extract JSON from response
  const jsonMatch = textBlock.text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    throw new Error('No JSON found in AI response');
  }

  const parsed = JSON.parse(jsonMatch[0]);

  if (!parsed.sections || !Array.isArray(parsed.sections)) {
    throw new Error('Invalid report structure in AI response');
  }

  return {
    title: parsed.title || 'Intelligence Report',
    subtitle: parsed.subtitle || '',
    generatedAt: new Date().toISOString(),
    reportType: '',
    executive_summary: parsed.executive_summary || '',
    methodology: parsed.methodology || '',
    sections: parsed.sections.map((s: { id?: string; title?: string; content?: string }) => ({
      id: s.id || '',
      title: s.title || '',
      content: s.content || '',
    })),
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are a senior space industry analyst producing professional intelligence reports for SpaceNexus, a leading space industry intelligence platform. Your reports are read by space industry executives, investors, engineers, and government program managers.

Write in a professional, analytical tone. Be specific and data-driven. Always return valid JSON in the exact format requested.`;

/**
 * Generate a Sector Overview report
 */
export async function generateSectorReport(
  sector: string,
  options: GenerateOptions = {}
): Promise<GeneratedReport> {
  const sectorLabel = SPACE_SECTORS.find((s) => s.value === sector)?.label || sector;

  logger.info('Generating sector overview report', { sector, sectorLabel });

  if (MOCK_ENABLED) {
    logger.warn('ANTHROPIC_API_KEY not set — returning sample sector report');
    return getSampleReport('sector-overview', `Sector Overview: ${sectorLabel}`);
  }

  const contextData = await gatherSectorData(sector);
  const prompt = buildSectorOverviewPrompt(sector, sectorLabel, contextData);

  const report = await callClaude(SYSTEM_PROMPT, prompt, options.maxTokens || 8000);
  report.reportType = 'sector-overview';
  return report;
}

/**
 * Generate a Company Deep Dive report
 */
export async function generateCompanyDeepDive(
  companySlug: string,
  options: GenerateOptions = {}
): Promise<GeneratedReport> {
  logger.info('Generating company deep dive report', { companySlug });

  if (MOCK_ENABLED) {
    logger.warn('ANTHROPIC_API_KEY not set — returning sample company report');
    return getSampleReport('company-deep-dive', `Company Deep Dive: ${companySlug}`);
  }

  const { name, contextData } = await gatherCompanyData(companySlug);
  const prompt = buildCompanyDeepDivePrompt(name, contextData);

  const report = await callClaude(SYSTEM_PROMPT, prompt, options.maxTokens || 8000);
  report.reportType = 'company-deep-dive';
  return report;
}

/**
 * Generate a Competitive Analysis report
 */
export async function generateCompetitiveAnalysis(
  companySlugs: string[],
  options: GenerateOptions = {}
): Promise<GeneratedReport> {
  logger.info('Generating competitive analysis report', { companySlugs });

  if (MOCK_ENABLED) {
    logger.warn('ANTHROPIC_API_KEY not set — returning sample competitive report');
    return getSampleReport('competitive-analysis', `Competitive Analysis: ${companySlugs.join(' vs ')}`);
  }

  const { names, contextData } = await gatherMultiCompanyData(companySlugs);
  const prompt = buildCompetitiveAnalysisPrompt(names, contextData);

  const report = await callClaude(SYSTEM_PROMPT, prompt, options.maxTokens || 10000);
  report.reportType = 'competitive-analysis';
  return report;
}

/**
 * Generate a Market Entry Brief
 */
export async function generateMarketEntryBrief(
  topic: string,
  options: GenerateOptions = {}
): Promise<GeneratedReport> {
  logger.info('Generating market entry brief', { topic });

  if (MOCK_ENABLED) {
    logger.warn('ANTHROPIC_API_KEY not set — returning sample market entry brief');
    return getSampleReport('market-entry-brief', `Market Entry Brief: ${topic}`);
  }

  const contextData = await gatherMarketEntryData(topic);
  const prompt = buildMarketEntryBriefPrompt(topic, contextData);

  const report = await callClaude(SYSTEM_PROMPT, prompt, options.maxTokens || 10000);
  report.reportType = 'market-entry-brief';
  return report;
}
