export interface SpaceEvent {
  id: string;
  name: string;
  type: 'conference' | 'webinar' | 'expo' | 'workshop' | 'networking' | 'launch_event' | 'hackathon';
  startDate: string; // ISO date
  endDate?: string;
  location: string;
  venue?: string;
  virtual: boolean;
  description: string;
  website: string;
  attendeeCount?: number;
  cost?: string;
  organizer: string;
  tags: string[];
  recurring: boolean;
  highlight: boolean;
}

export const SPACE_EVENTS: SpaceEvent[] = [
  // ── January 2026 ──
  {
    id: 'aiaa-scitech-2026',
    name: 'AIAA SciTech Forum 2026',
    type: 'conference',
    startDate: '2026-01-19',
    endDate: '2026-01-23',
    location: 'Orlando, FL, USA',
    venue: 'Orange County Convention Center',
    virtual: false,
    description: 'The largest annual aerospace sciences meeting in the world. Covers aerodynamics, structures, propulsion, and space systems with over 4,000 technical papers presented.',
    website: 'https://www.aiaa.org/scitech',
    attendeeCount: 6000,
    cost: '$700-$1,200',
    organizer: 'AIAA',
    tags: ['research', 'engineering', 'aerodynamics', 'propulsion'],
    recurring: true,
    highlight: true,
  },

  // ── February 2026 ──
  {
    id: 'smallsat-symposium-2026',
    name: 'SmallSat Symposium 2026',
    type: 'conference',
    startDate: '2026-02-02',
    endDate: '2026-02-05',
    location: 'Mountain View, CA, USA',
    venue: 'Computer History Museum',
    virtual: false,
    description: 'Premier Silicon Valley event for the small satellite industry. Features business-focused sessions on emerging trends, investment, and technology in the smallsat ecosystem.',
    website: 'https://www.smallsatsymposium.com',
    attendeeCount: 2500,
    cost: '$1,200-$2,400',
    organizer: 'Satnews Publishers',
    tags: ['smallsat', 'investment', 'startups', 'silicon-valley'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'spacecom-2026',
    name: 'SpaceCom 2026',
    type: 'expo',
    startDate: '2026-02-24',
    endDate: '2026-02-25',
    location: 'Orlando, FL, USA',
    venue: 'Orange County Convention Center',
    virtual: false,
    description: 'Conference connecting space technology innovators with industry leaders from energy, maritime, agriculture, and other terrestrial sectors seeking space-derived solutions.',
    website: 'https://spacecomexpo.com',
    attendeeCount: 3000,
    cost: '$500-$1,500',
    organizer: 'SpaceCom',
    tags: ['commercial-space', 'cross-industry', 'applications', 'networking'],
    recurring: true,
    highlight: false,
  },

  // ── March 2026 ──
  {
    id: 'satellite-2026',
    name: 'SATELLITE 2026',
    type: 'conference',
    startDate: '2026-03-09',
    endDate: '2026-03-12',
    location: 'Washington, DC, USA',
    venue: 'Walter E. Washington Convention Center',
    virtual: false,
    description: 'The premier global event for satellite communications, space, and connectivity. Features 300+ exhibitors, keynotes from industry leaders, and extensive networking opportunities.',
    website: 'https://www.satshow.com',
    attendeeCount: 15000,
    cost: 'Free exhibit hall, $1,200-$3,500 conference',
    organizer: 'Via Satellite / Access Intelligence',
    tags: ['satcom', 'connectivity', 'broadband', 'government', 'defense'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'space-foundation-space-symposium-preview',
    name: 'Space Foundation Discovery Series',
    type: 'webinar',
    startDate: '2026-03-18',
    location: 'Virtual',
    virtual: true,
    description: 'Monthly virtual event series from the Space Foundation featuring industry thought leaders discussing current space topics and previewing the Space Symposium.',
    website: 'https://www.spacefoundation.org',
    cost: 'Free',
    organizer: 'Space Foundation',
    tags: ['education', 'industry-trends', 'virtual'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'isc-2026-spring',
    name: 'International Space Commerce Conference',
    type: 'conference',
    startDate: '2026-03-24',
    endDate: '2026-03-25',
    location: 'Washington, DC, USA',
    virtual: false,
    description: 'Focused on the commercial space economy, this event brings together investors, entrepreneurs, and government stakeholders to discuss space commerce opportunities.',
    website: 'https://spaceinvestsummit.com',
    attendeeCount: 800,
    cost: '$800-$2,000',
    organizer: 'Space Investment Summit',
    tags: ['investment', 'commercial-space', 'finance', 'startups'],
    recurring: true,
    highlight: false,
  },

  // ── April 2026 ──
  {
    id: 'space-symposium-2026',
    name: '41st Space Symposium',
    type: 'conference',
    startDate: '2026-04-06',
    endDate: '2026-04-09',
    location: 'Colorado Springs, CO, USA',
    venue: 'The Broadmoor',
    virtual: false,
    description: 'The premier assembly of the global space community. Features senior military, government, and industry leaders. Includes the Symposium exhibit center with 200+ exhibitors and the iconic Space Warfighter Luncheon.',
    website: 'https://www.spacesymposium.org',
    attendeeCount: 15000,
    cost: '$1,500-$4,000',
    organizer: 'Space Foundation',
    tags: ['defense', 'government', 'commercial-space', 'policy', 'networking'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'cubesat-workshop-2026',
    name: 'CubeSat Developers Workshop',
    type: 'workshop',
    startDate: '2026-04-22',
    endDate: '2026-04-24',
    location: 'San Luis Obispo, CA, USA',
    venue: 'Cal Poly San Luis Obispo',
    virtual: false,
    description: 'Annual workshop bringing together CubeSat developers from academia, industry, and government. Features technical presentations, poster sessions, and hands-on demonstrations.',
    website: 'https://www.cubesat.org/workshop',
    attendeeCount: 800,
    cost: '$200-$500',
    organizer: 'Cal Poly CubeSat Lab',
    tags: ['cubesat', 'academic', 'engineering', 'hands-on'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'nsrc-2026',
    name: 'Next-Generation Suborbital Researchers Conference',
    type: 'conference',
    startDate: '2026-04-14',
    endDate: '2026-04-16',
    location: 'Broomfield, CO, USA',
    virtual: false,
    description: 'Conference focused on using commercial suborbital vehicles for research, education, and technology development in microgravity.',
    website: 'https://nsrc.swri.org',
    attendeeCount: 400,
    cost: '$400-$800',
    organizer: 'Southwest Research Institute',
    tags: ['suborbital', 'research', 'microgravity', 'science'],
    recurring: true,
    highlight: false,
  },

  // ── May 2026 ──
  {
    id: 'space-tech-expo-2026',
    name: 'Space Tech Expo 2026',
    type: 'expo',
    startDate: '2026-05-19',
    endDate: '2026-05-21',
    location: 'Long Beach, CA, USA',
    venue: 'Long Beach Convention Center',
    virtual: false,
    description: 'Leading trade show for the space industry supply chain. Features 300+ exhibitors showcasing spacecraft components, testing equipment, manufacturing technologies, and subsystems.',
    website: 'https://www.spacetechexpo.com',
    attendeeCount: 8000,
    cost: 'Free exhibit hall, $500-$1,500 conference',
    organizer: 'Smarter Shows',
    tags: ['supply-chain', 'manufacturing', 'components', 'testing'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'geoint-2026',
    name: 'GEOINT Symposium 2026',
    type: 'conference',
    startDate: '2026-05-03',
    endDate: '2026-05-06',
    location: 'San Diego, CA, USA',
    venue: 'San Diego Convention Center',
    virtual: false,
    description: 'Largest annual gathering of the geospatial intelligence community. Hosted by USGIF, features intelligence community leaders, defense contractors, and technology providers.',
    website: 'https://geoint.usgif.org',
    attendeeCount: 5000,
    cost: '$800-$2,000',
    organizer: 'USGIF',
    tags: ['geoint', 'defense', 'remote-sensing', 'intelligence'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'global-space-exploration-2026',
    name: 'Global Space Exploration Conference (GLEX)',
    type: 'conference',
    startDate: '2026-05-11',
    endDate: '2026-05-15',
    location: 'Beijing, China',
    virtual: false,
    description: 'International conference on human and robotic space exploration featuring space agencies from around the world discussing lunar, Mars, and deep space missions.',
    website: 'https://www.iafastro.org/events/glex',
    attendeeCount: 2000,
    cost: '$500-$1,200',
    organizer: 'IAF',
    tags: ['exploration', 'lunar', 'mars', 'international', 'agencies'],
    recurring: true,
    highlight: false,
  },

  // ── June 2026 ──
  {
    id: 'ssib-2026',
    name: 'State of the Space Industrial Base 2026',
    type: 'conference',
    startDate: '2026-06-15',
    endDate: '2026-06-17',
    location: 'Colorado Springs, CO, USA',
    virtual: false,
    description: 'Annual workshop convening senior leaders from the U.S. Space Force, intelligence community, and commercial space to assess and strengthen the space industrial base.',
    website: 'https://spaceindustrialbase.com',
    attendeeCount: 500,
    cost: 'By invitation',
    organizer: 'USSF / Defense Innovation Unit',
    tags: ['defense', 'industrial-base', 'policy', 'government'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'aiaa-aviation-2026',
    name: 'AIAA Aviation Forum 2026',
    type: 'conference',
    startDate: '2026-06-15',
    endDate: '2026-06-19',
    location: 'Dallas, TX, USA',
    venue: 'Kay Bailey Hutchison Convention Center',
    virtual: false,
    description: 'AIAA annual aviation and aeronautics forum. Covers advanced air mobility, hypersonics, point-to-point suborbital, and space access technologies.',
    website: 'https://www.aiaa.org/aviation',
    attendeeCount: 4000,
    cost: '$600-$1,100',
    organizer: 'AIAA',
    tags: ['aviation', 'hypersonics', 'propulsion', 'research'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'paris-air-forum-2026',
    name: 'Paris Air Forum 2026',
    type: 'conference',
    startDate: '2026-06-22',
    endDate: '2026-06-23',
    location: 'Paris, France',
    virtual: false,
    description: 'High-level discussion forum for aerospace executives covering topics from sustainability and defense to space exploration and new mobility.',
    website: 'https://www.parisairforum.com',
    attendeeCount: 1500,
    cost: '$800-$2,000',
    organizer: 'La Tribune / Paris Air Forum',
    tags: ['aerospace', 'europe', 'executive', 'policy'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'newspace-europe-2026',
    name: 'NewSpace Europe 2026',
    type: 'conference',
    startDate: '2026-06-08',
    endDate: '2026-06-09',
    location: 'Luxembourg City, Luxembourg',
    virtual: false,
    description: 'European NewSpace conference focusing on the growing European commercial space ecosystem, featuring startups, investors, and policy makers from across the continent.',
    website: 'https://newspace-europe.lu',
    attendeeCount: 1000,
    cost: '$500-$1,200',
    organizer: 'Luxembourg Space Agency / ESA',
    tags: ['newspace', 'europe', 'startups', 'investment', 'policy'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'nasa-space-apps-2026',
    name: 'NASA International Space Apps Challenge',
    type: 'hackathon',
    startDate: '2026-06-27',
    endDate: '2026-06-28',
    location: 'Worldwide (200+ locations)',
    virtual: true,
    description: 'Global hackathon using NASA open data. Teams tackle challenges in Earth science, space exploration, and technology development over 48 hours. Open to all skill levels.',
    website: 'https://www.spaceappschallenge.org',
    attendeeCount: 30000,
    cost: 'Free',
    organizer: 'NASA',
    tags: ['hackathon', 'open-data', 'education', 'community', 'global'],
    recurring: true,
    highlight: true,
  },

  // ── July 2026 ──
  {
    id: 'farnborough-2026',
    name: 'Farnborough International Airshow 2026',
    type: 'expo',
    startDate: '2026-07-20',
    endDate: '2026-07-24',
    location: 'Farnborough, Hampshire, UK',
    venue: 'Farnborough Airport',
    virtual: false,
    description: 'One of the world\'s largest aerospace trade shows, alternating years with the Paris Air Show. Major defense and space contracts are announced, with dedicated Space Zone exhibition area.',
    website: 'https://www.farnboroughairshow.com',
    attendeeCount: 80000,
    cost: '$100-$500 (trade days)',
    organizer: 'Farnborough International',
    tags: ['airshow', 'defense', 'commercial-space', 'UK', 'trade-show'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'isdc-2026',
    name: 'International Space Development Conference 2026',
    type: 'conference',
    startDate: '2026-07-09',
    endDate: '2026-07-12',
    location: 'Los Angeles, CA, USA',
    virtual: false,
    description: 'Annual conference hosted by the National Space Society featuring tracks on settlement, policy, commercial development, and education. Open to space enthusiasts and professionals alike.',
    website: 'https://isdc.nss.org',
    attendeeCount: 1500,
    cost: '$200-$600',
    organizer: 'National Space Society',
    tags: ['advocacy', 'settlement', 'education', 'policy', 'community'],
    recurring: true,
    highlight: false,
  },

  // ── August 2026 ──
  {
    id: 'smallsat-2026',
    name: 'SmallSat Conference 2026',
    type: 'conference',
    startDate: '2026-08-01',
    endDate: '2026-08-06',
    location: 'Logan, UT, USA',
    venue: 'Utah State University',
    virtual: false,
    description: 'The premier technical conference for small satellite missions and technologies. Hosted at Utah State University, it brings together engineers, program managers, and researchers from around the world.',
    website: 'https://smallsat.org',
    attendeeCount: 4000,
    cost: '$200-$800',
    organizer: 'AIAA / Utah State University',
    tags: ['smallsat', 'technical', 'academic', 'engineering', 'missions'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'space-intelligence-forum-2026',
    name: 'Space Intelligence Forum',
    type: 'conference',
    startDate: '2026-08-18',
    endDate: '2026-08-19',
    location: 'Washington, DC, USA',
    virtual: false,
    description: 'Focused on the intersection of space and intelligence operations. Covers space-based ISR, electronic warfare, SSA, and cyber threats to space systems.',
    website: 'https://www.defensenews.com/events',
    attendeeCount: 600,
    cost: '$1,000-$2,500',
    organizer: 'Defense News',
    tags: ['intelligence', 'defense', 'cybersecurity', 'ISR'],
    recurring: true,
    highlight: false,
  },

  // ── September 2026 ──
  {
    id: 'amos-2026',
    name: 'AMOS Conference 2026',
    type: 'conference',
    startDate: '2026-09-15',
    endDate: '2026-09-18',
    location: 'Maui, HI, USA',
    venue: 'Wailea Beach Resort',
    virtual: false,
    description: 'Advanced Maui Optical and Space Surveillance Technologies Conference. The premier forum for space domain awareness, space surveillance technologies, and orbital debris research.',
    website: 'https://amostech.com',
    attendeeCount: 1500,
    cost: '$800-$2,000',
    organizer: 'Maui Economic Development Board',
    tags: ['SSA', 'surveillance', 'debris', 'optical', 'defense'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'wsb-week-2026',
    name: 'World Satellite Business Week 2026',
    type: 'conference',
    startDate: '2026-09-14',
    endDate: '2026-09-18',
    location: 'Paris, France',
    venue: 'Westin Paris - Vendome',
    virtual: false,
    description: 'Premier business event for the global satellite industry. C-suite executives gather to discuss market trends, M&A, investment, and strategic direction of the satellite sector.',
    website: 'https://www.worldsatellitebusinessweek.com',
    attendeeCount: 3000,
    cost: '$3,000-$6,000',
    organizer: 'Euroconsult',
    tags: ['business', 'satcom', 'investment', 'executive', 'europe'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'iac-launch-week-2026',
    name: 'International Astronautical Congress Pre-Events',
    type: 'networking',
    startDate: '2026-09-28',
    endDate: '2026-09-30',
    location: 'Milan, Italy',
    virtual: false,
    description: 'Pre-congress networking events, space agency bilateral meetings, and startup pitches leading into IAC 2026. Multiple side events across the city.',
    website: 'https://www.iafastro.org/events/iac/iac-2026',
    cost: 'Varies',
    organizer: 'Various',
    tags: ['networking', 'international', 'startups', 'agencies'],
    recurring: false,
    highlight: false,
  },

  // ── October 2026 ──
  {
    id: 'iac-2026',
    name: 'International Astronautical Congress (IAC) 2026',
    type: 'conference',
    startDate: '2026-10-01',
    endDate: '2026-10-05',
    location: 'Milan, Italy',
    venue: 'MiCo - Milano Convention Centre',
    virtual: false,
    description: 'The world\'s premier space event, gathering 10,000+ space professionals, agencies, and companies from 80+ countries. Features technical sessions, plenaries, Global Networking Forum, and the IAF exhibition.',
    website: 'https://www.iafastro.org/events/iac/iac-2026',
    attendeeCount: 10000,
    cost: '$500-$1,500',
    organizer: 'International Astronautical Federation (IAF)',
    tags: ['international', 'agencies', 'research', 'industry', 'networking'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'satellite-innovation-2026',
    name: 'Satellite Innovation 2026',
    type: 'conference',
    startDate: '2026-10-13',
    endDate: '2026-10-14',
    location: 'Mountain View, CA, USA',
    venue: 'Computer History Museum',
    virtual: false,
    description: 'Focused on innovation in the satellite sector. Features startup demos, investor matchmaking, and panels on next-gen constellations, ground systems, and analytics.',
    website: 'https://www.satinnovation.com',
    attendeeCount: 1500,
    cost: '$1,200-$2,500',
    organizer: 'Satnews Publishers',
    tags: ['innovation', 'startups', 'investment', 'silicon-valley'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'world-space-week-2026',
    name: 'World Space Week 2026',
    type: 'launch_event',
    startDate: '2026-10-04',
    endDate: '2026-10-10',
    location: 'Worldwide',
    virtual: true,
    description: 'UN-declared annual celebration of space science and technology. Thousands of events worldwide including lectures, exhibitions, screenings, and educational activities.',
    website: 'https://www.worldspaceweek.org',
    attendeeCount: 100000,
    cost: 'Free',
    organizer: 'World Space Week Association / UN',
    tags: ['education', 'outreach', 'global', 'community'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'aiaa-ascend-2026',
    name: 'AIAA ASCEND 2026',
    type: 'conference',
    startDate: '2026-10-19',
    endDate: '2026-10-21',
    location: 'Las Vegas, NV, USA',
    venue: 'Caesars Forum',
    virtual: false,
    description: 'AIAA\'s space conference bringing together space professionals for technical sessions, networking, and exhibition. Covers commercial space, exploration, national security, and sustainability.',
    website: 'https://www.aiaa.org/ascend',
    attendeeCount: 3500,
    cost: '$700-$1,400',
    organizer: 'AIAA',
    tags: ['commercial-space', 'exploration', 'defense', 'sustainability'],
    recurring: true,
    highlight: false,
  },

  // ── November 2026 ──
  {
    id: 'milsatcom-2026',
    name: 'Global MilSatCom 2026',
    type: 'conference',
    startDate: '2026-11-03',
    endDate: '2026-11-05',
    location: 'London, UK',
    venue: 'QEII Centre',
    virtual: false,
    description: 'The world\'s most established military satellite communications conference. Features senior military and government officials discussing next-gen MILSATCOM architectures, resilience, and commercial integration.',
    website: 'https://www.globalmilsatcom.com',
    attendeeCount: 800,
    cost: '$2,000-$4,000',
    organizer: 'SMi Group',
    tags: ['milsatcom', 'defense', 'government', 'UK', 'communications'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'space-tech-expo-europe-2026',
    name: 'Space Tech Expo Europe 2026',
    type: 'expo',
    startDate: '2026-11-17',
    endDate: '2026-11-19',
    location: 'Bremen, Germany',
    venue: 'Messe Bremen',
    virtual: false,
    description: 'European edition of Space Tech Expo. Major supply chain trade show for European space industry with focus on satellite manufacturing, launch systems, and ground equipment.',
    website: 'https://www.spacetechexpo-europe.com',
    attendeeCount: 5000,
    cost: 'Free exhibit hall, $500-$1,200 conference',
    organizer: 'Smarter Shows',
    tags: ['supply-chain', 'europe', 'manufacturing', 'components'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'dubai-airshow-2026-space',
    name: 'Dubai Airshow 2026 - Space Pavilion',
    type: 'expo',
    startDate: '2026-11-16',
    endDate: '2026-11-20',
    location: 'Dubai, UAE',
    venue: 'DWC - Al Maktoum International',
    virtual: false,
    description: 'Biennial aerospace event in the Middle East. The dedicated Space Pavilion features growing presence of space startups, agencies, and defense programs from the Gulf region and beyond.',
    website: 'https://www.dubaiairshow.aero',
    attendeeCount: 50000,
    cost: '$100-$1,000',
    organizer: 'Dubai Airshow',
    tags: ['airshow', 'middle-east', 'defense', 'commercial-space'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'space-startup-pitch-2026',
    name: 'Space Venture Finance Symposium',
    type: 'networking',
    startDate: '2026-11-10',
    endDate: '2026-11-11',
    location: 'San Francisco, CA, USA',
    virtual: false,
    description: 'Dedicated space venture event connecting startups with investors. Features pitch competitions, fireside chats with successful founders, and closed-door investor meetings.',
    website: 'https://spaceinvestsummit.com',
    attendeeCount: 500,
    cost: '$1,000-$3,000',
    organizer: 'Space Capital / Space Investment Summit',
    tags: ['investment', 'startups', 'VC', 'pitch', 'finance'],
    recurring: true,
    highlight: false,
  },

  // ── December 2026 ──
  {
    id: 'agu-fall-2026',
    name: 'AGU Fall Meeting 2026',
    type: 'conference',
    startDate: '2026-12-07',
    endDate: '2026-12-11',
    location: 'San Francisco, CA, USA',
    venue: 'Moscone Center',
    virtual: true,
    description: 'Largest Earth and space science conference in the world. Features planetary science, heliophysics, and space weather sessions relevant to the space industry alongside 25,000+ geoscientists.',
    website: 'https://www.agu.org/Fall-Meeting',
    attendeeCount: 25000,
    cost: '$500-$800',
    organizer: 'American Geophysical Union',
    tags: ['science', 'earth-observation', 'planetary', 'space-weather', 'academic'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'aiaa-propulsion-2026',
    name: 'AIAA Propulsion & Energy Forum 2026',
    type: 'conference',
    startDate: '2026-12-14',
    endDate: '2026-12-18',
    location: 'Cincinnati, OH, USA',
    virtual: false,
    description: 'Leading conference on propulsion and energy systems for aerospace. Covers chemical, electric, and nuclear propulsion, in-space manufacturing energy needs, and green propellant development.',
    website: 'https://www.aiaa.org/propulsion-energy',
    attendeeCount: 2500,
    cost: '$600-$1,100',
    organizer: 'AIAA',
    tags: ['propulsion', 'energy', 'research', 'engineering'],
    recurring: true,
    highlight: false,
  },

  // ── Additional recurring/specialty events (various months) ──
  {
    id: 'pld-launch-summit-2026',
    name: 'European Launch Summit 2026',
    type: 'conference',
    startDate: '2026-03-17',
    endDate: '2026-03-18',
    location: 'Madrid, Spain',
    virtual: false,
    description: 'Summit focused on European launch capabilities and the emerging micro-launcher sector. Features PLD Space, Isar Aerospace, RFA, and other European launch providers.',
    website: 'https://www.europeanlauncher.com',
    attendeeCount: 600,
    cost: '$500-$1,200',
    organizer: 'European Launch Industry',
    tags: ['launch', 'europe', 'micro-launchers', 'policy'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'space-workforce-summit-2026',
    name: 'Space Workforce 2030 Summit',
    type: 'conference',
    startDate: '2026-05-28',
    endDate: '2026-05-29',
    location: 'Houston, TX, USA',
    virtual: true,
    description: 'Focus on talent pipeline, STEM education, diversity in aerospace, and workforce development for the growing space economy. Hybrid format available.',
    website: 'https://www.spaceworkforce2030.org',
    attendeeCount: 1000,
    cost: '$300-$800',
    organizer: 'Space Workforce 2030',
    tags: ['workforce', 'STEM', 'diversity', 'education', 'talent'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'space-sustainability-forum-2026',
    name: 'Space Sustainability Forum',
    type: 'conference',
    startDate: '2026-06-02',
    endDate: '2026-06-03',
    location: 'London, UK',
    virtual: true,
    description: 'Conference on orbital debris mitigation, space traffic management, sustainable operations, and end-of-life disposal. Brings together regulators, operators, and technology providers.',
    website: 'https://spacesustainabilityforum.com',
    attendeeCount: 700,
    cost: '$600-$1,500',
    organizer: 'Space Sustainability Coalition',
    tags: ['sustainability', 'debris', 'regulation', 'STM'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'lunar-surface-innovation-2026',
    name: 'Lunar Surface Innovation Consortium Workshop',
    type: 'workshop',
    startDate: '2026-04-29',
    endDate: '2026-04-30',
    location: 'Laurel, MD, USA',
    venue: 'Johns Hopkins APL',
    virtual: true,
    description: 'Workshop on lunar surface technologies: ISRU, construction, power, communications, and science. Features NASA updates on Artemis surface systems.',
    website: 'https://lsic.jhuapl.edu',
    attendeeCount: 500,
    cost: 'Free',
    organizer: 'Johns Hopkins APL / NASA',
    tags: ['lunar', 'artemis', 'ISRU', 'technology', 'NASA'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'space-ops-workshop-2026',
    name: 'International SpaceOps Workshop',
    type: 'workshop',
    startDate: '2026-08-24',
    endDate: '2026-08-28',
    location: 'Montreal, Canada',
    virtual: false,
    description: 'Biennial conference on space mission operations. Covers ground systems, flight dynamics, autonomous operations, mission control, and multi-mission operations.',
    website: 'https://www.spaceops.org',
    attendeeCount: 1200,
    cost: '$400-$900',
    organizer: 'AIAA / International SpaceOps Committee',
    tags: ['operations', 'ground-systems', 'mission-control', 'international'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'space-cyber-2026',
    name: 'Space Cybersecurity Symposium',
    type: 'conference',
    startDate: '2026-09-08',
    endDate: '2026-09-09',
    location: 'Washington, DC, USA',
    virtual: false,
    description: 'Focused on cybersecurity threats to space systems. Covers satellite hacking, ground station security, supply chain integrity, and national security implications.',
    website: 'https://www.spacecybersymposium.com',
    attendeeCount: 400,
    cost: '$800-$2,000',
    organizer: 'Space ISAC',
    tags: ['cybersecurity', 'defense', 'national-security', 'infrastructure'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'space-apps-webinar-series',
    name: 'Space Applications Webinar Series',
    type: 'webinar',
    startDate: '2026-04-15',
    location: 'Virtual',
    virtual: true,
    description: 'Monthly webinar series covering commercial applications of space technology across agriculture, climate monitoring, disaster response, and urban planning.',
    website: 'https://www.spacefoundation.org/events',
    cost: 'Free',
    organizer: 'Space Foundation',
    tags: ['applications', 'commercial', 'education', 'virtual'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'newspace-india-2026',
    name: 'NewSpace India Summit 2026',
    type: 'conference',
    startDate: '2026-07-15',
    endDate: '2026-07-16',
    location: 'Bangalore, India',
    virtual: false,
    description: 'India\'s premier commercial space conference, highlighting the rapidly growing Indian NewSpace ecosystem. Features ISRO updates, startup showcases, and international collaboration.',
    website: 'https://newspaceindia.com',
    attendeeCount: 2000,
    cost: '$200-$600',
    organizer: 'IN-SPACe / ISRO',
    tags: ['india', 'newspace', 'startups', 'ISRO', 'asia'],
    recurring: true,
    highlight: false,
  },
];

// ── ICS Generation Helper ──

export function generateICS(event: SpaceEvent): string {
  const formatDate = (dateStr: string) => dateStr.replace(/-/g, '');
  const start = formatDate(event.startDate) + 'T090000Z';
  const end = formatDate(event.endDate || event.startDate) + 'T180000Z';
  const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

  // Escape special characters for ICS
  const escapeICS = (str: string) =>
    str.replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n');

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//SpaceNexus//Space Events//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `DTSTART:${start}`,
    `DTEND:${end}`,
    `DTSTAMP:${now}`,
    `UID:${event.id}@spacenexus.us`,
    `SUMMARY:${escapeICS(event.name)}`,
    `DESCRIPTION:${escapeICS(event.description)}`,
    `LOCATION:${escapeICS(event.location)}${event.venue ? ' - ' + escapeICS(event.venue) : ''}`,
    `URL:${event.website}`,
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');
}

// ── Export all events as a combined ICS ──

export function generateMultiEventICS(events: SpaceEvent[]): string {
  const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  const formatDate = (dateStr: string) => dateStr.replace(/-/g, '');

  const escapeICS = (str: string) =>
    str.replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n');

  const vevents = events.map((event) => {
    const start = formatDate(event.startDate) + 'T090000Z';
    const end = formatDate(event.endDate || event.startDate) + 'T180000Z';
    return [
      'BEGIN:VEVENT',
      `DTSTART:${start}`,
      `DTEND:${end}`,
      `DTSTAMP:${now}`,
      `UID:${event.id}@spacenexus.us`,
      `SUMMARY:${escapeICS(event.name)}`,
      `DESCRIPTION:${escapeICS(event.description)}`,
      `LOCATION:${escapeICS(event.location)}${event.venue ? ' - ' + escapeICS(event.venue) : ''}`,
      `URL:${event.website}`,
      'END:VEVENT',
    ].join('\r\n');
  });

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//SpaceNexus//Space Events//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:SpaceNexus Space Events',
    ...vevents,
    'END:VCALENDAR',
  ].join('\r\n');
}

// ── Type/filter helpers ──

export const EVENT_TYPES: { value: SpaceEvent['type']; label: string; color: string }[] = [
  { value: 'conference', label: 'Conference', color: 'bg-cyan-500' },
  { value: 'expo', label: 'Expo / Trade Show', color: 'bg-purple-500' },
  { value: 'workshop', label: 'Workshop', color: 'bg-amber-500' },
  { value: 'webinar', label: 'Webinar', color: 'bg-emerald-500' },
  { value: 'networking', label: 'Networking', color: 'bg-rose-500' },
  { value: 'launch_event', label: 'Launch Event', color: 'bg-orange-500' },
  { value: 'hackathon', label: 'Hackathon', color: 'bg-indigo-500' },
];

export const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

export function getEventTypeColor(type: SpaceEvent['type']): string {
  return EVENT_TYPES.find(t => t.value === type)?.color || 'bg-slate-500';
}

export function getEventTypeLabel(type: SpaceEvent['type']): string {
  return EVENT_TYPES.find(t => t.value === type)?.label || type;
}
