export interface SpaceEvent {
  id: string;
  name: string;
  type: 'conference' | 'webinar' | 'expo' | 'workshop' | 'networking' | 'launch_event' | 'hackathon' | 'hearing' | 'tradeshow';
  startDate: string; // ISO date
  endDate?: string;
  location: string;
  venue?: string;
  country: string;
  virtual: boolean;
  description: string;
  website: string;
  registrationUrl?: string;
  attendeeCount?: number;
  cost?: string;
  costType: 'free' | 'paid';
  organizer: string;
  tags: string[];
  recurring: boolean;
  highlight: boolean;
  speakers?: string[];
  exhibitors?: number;
}

export const SPACE_EVENTS: SpaceEvent[] = [
  // ══════════════════════════════════════════
  // ── January 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'aiaa-scitech-2026',
    name: 'AIAA SciTech Forum 2026',
    type: 'conference',
    startDate: '2026-01-19',
    endDate: '2026-01-23',
    location: 'Orlando, FL, USA',
    venue: 'Orange County Convention Center',
    country: 'USA',
    virtual: false,
    description: 'The largest annual aerospace sciences meeting in the world. Covers aerodynamics, structures, propulsion, and space systems with over 4,000 technical papers presented.',
    website: 'https://www.aiaa.org/scitech',
    attendeeCount: 6000,
    cost: '$700-$1,200',
    costType: 'paid',
    organizer: 'AIAA',
    tags: ['research', 'engineering', 'aerodynamics', 'propulsion'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'spacecom-2027',
    name: 'SpaceCom 2027',
    type: 'expo',
    startDate: '2027-01-25',
    endDate: '2027-01-27',
    location: 'Orlando, FL, USA',
    venue: 'Orange County Convention Center',
    country: 'USA',
    virtual: false,
    description: 'Conference connecting space technology innovators with industry leaders from energy, maritime, agriculture, and other terrestrial sectors seeking space-derived solutions.',
    website: 'https://spacecomexpo.com',
    attendeeCount: 3500,
    cost: '$500-$1,500',
    costType: 'paid',
    organizer: 'SpaceCom',
    tags: ['commercial-space', 'cross-industry', 'applications', 'networking'],
    recurring: true,
    highlight: true,
  },

  // ══════════════════════════════════════════
  // ── February 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'smallsat-symposium-2026',
    name: 'SmallSat Symposium 2026',
    type: 'conference',
    startDate: '2026-02-02',
    endDate: '2026-02-05',
    location: 'Mountain View, CA, USA',
    venue: 'Computer History Museum',
    country: 'USA',
    virtual: false,
    description: 'Premier Silicon Valley event for the small satellite industry. Features business-focused sessions on emerging trends, investment, and technology in the smallsat ecosystem.',
    website: 'https://www.smallsatsymposium.com',
    attendeeCount: 2500,
    cost: '$1,200-$2,400',
    costType: 'paid',
    organizer: 'Satnews Publishers',
    tags: ['smallsat', 'investment', 'startups', 'silicon-valley'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'spacecom-2026',
    name: 'SpaceCom 2026',
    type: 'expo',
    startDate: '2026-02-24',
    endDate: '2026-02-25',
    location: 'Orlando, FL, USA',
    venue: 'Orange County Convention Center',
    country: 'USA',
    virtual: false,
    description: 'Conference connecting space technology innovators with industry leaders from energy, maritime, agriculture, and other terrestrial sectors seeking space-derived solutions.',
    website: 'https://spacecomexpo.com',
    attendeeCount: 3000,
    cost: '$500-$1,500',
    costType: 'paid',
    organizer: 'SpaceCom',
    tags: ['commercial-space', 'cross-industry', 'applications', 'networking'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'spacenews-webinar-feb-2026',
    name: 'SpaceNews Webinar: LEO Economy Outlook',
    type: 'webinar',
    startDate: '2026-02-12',
    location: 'Virtual',
    country: 'Virtual',
    virtual: true,
    description: 'Monthly SpaceNews webinar examining the business landscape of LEO constellations, broadband economics, and emerging use cases for low Earth orbit infrastructure.',
    website: 'https://spacenews.com/webinars',
    cost: 'Free',
    costType: 'free',
    organizer: 'SpaceNews',
    tags: ['LEO', 'broadband', 'business', 'virtual'],
    recurring: true,
    highlight: false,
  },

  // ══════════════════════════════════════════
  // ── March 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'satellite-2026',
    name: 'SATELLITE 2026',
    type: 'conference',
    startDate: '2026-03-09',
    endDate: '2026-03-12',
    location: 'Washington, DC, USA',
    venue: 'Walter E. Washington Convention Center',
    country: 'USA',
    virtual: false,
    description: 'The premier global event for satellite communications, space, and connectivity. Features 300+ exhibitors, keynotes from industry leaders, and extensive networking opportunities.',
    website: 'https://www.satshow.com',
    registrationUrl: 'https://www.satshow.com/register',
    attendeeCount: 15000,
    cost: 'Free exhibit hall, $1,200-$3,500 conference',
    costType: 'paid',
    organizer: 'Via Satellite / Access Intelligence',
    tags: ['satcom', 'connectivity', 'broadband', 'government', 'defense'],
    exhibitors: 350,
    recurring: true,
    highlight: true,
  },
  {
    id: 'space-foundation-discovery-march',
    name: 'Space Foundation Discovery Series',
    type: 'webinar',
    startDate: '2026-03-18',
    location: 'Virtual',
    country: 'Virtual',
    virtual: true,
    description: 'Monthly virtual event series from the Space Foundation featuring industry thought leaders discussing current space topics and previewing the Space Symposium.',
    website: 'https://www.spacefoundation.org',
    cost: 'Free',
    costType: 'free',
    organizer: 'Space Foundation',
    tags: ['education', 'industry-trends', 'virtual'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'isc-2026-spring',
    name: 'International Space Commerce Conference',
    type: 'conference',
    startDate: '2026-03-24',
    endDate: '2026-03-25',
    location: 'Washington, DC, USA',
    country: 'USA',
    virtual: false,
    description: 'Focused on the commercial space economy, this event brings together investors, entrepreneurs, and government stakeholders to discuss space commerce opportunities.',
    website: 'https://spaceinvestsummit.com',
    attendeeCount: 800,
    cost: '$800-$2,000',
    costType: 'paid',
    organizer: 'Space Investment Summit',
    tags: ['investment', 'commercial-space', 'finance', 'startups'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'pld-launch-summit-2026',
    name: 'European Launch Summit 2026',
    type: 'conference',
    startDate: '2026-03-17',
    endDate: '2026-03-18',
    location: 'Madrid, Spain',
    country: 'Spain',
    virtual: false,
    description: 'Summit focused on European launch capabilities and the emerging micro-launcher sector. Features PLD Space, Isar Aerospace, RFA, and other European launch providers.',
    website: 'https://www.europeanlauncher.com',
    attendeeCount: 600,
    cost: '$500-$1,200',
    costType: 'paid',
    organizer: 'European Launch Industry',
    tags: ['launch', 'europe', 'micro-launchers', 'policy'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'via-satellite-webinar-march-2026',
    name: 'Via Satellite Webinar: Next-Gen Ground Systems',
    type: 'webinar',
    startDate: '2026-03-25',
    location: 'Virtual',
    country: 'Virtual',
    virtual: true,
    description: 'Via Satellite monthly webinar exploring modernization of satellite ground systems, virtualization, multi-orbit management, and software-defined ground infrastructure.',
    website: 'https://www.satellitetoday.com/webinars',
    cost: 'Free',
    costType: 'free',
    organizer: 'Via Satellite',
    tags: ['ground-systems', 'satcom', 'technology', 'virtual'],
    recurring: true,
    highlight: false,
  },

  // ══════════════════════════════════════════
  // ── April 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'space-symposium-2026',
    name: '41st Space Symposium',
    type: 'conference',
    startDate: '2026-04-06',
    endDate: '2026-04-09',
    location: 'Colorado Springs, CO, USA',
    venue: 'The Broadmoor',
    country: 'USA',
    virtual: false,
    description: 'The premier assembly of the global space community. Features senior military, government, and industry leaders. Includes the Symposium exhibit center with 200+ exhibitors and the iconic Space Warfighter Luncheon.',
    website: 'https://www.spacesymposium.org',
    registrationUrl: 'https://www.spacesymposium.org/register',
    attendeeCount: 15000,
    cost: '$1,500-$4,000',
    costType: 'paid',
    organizer: 'Space Foundation',
    tags: ['defense', 'government', 'commercial-space', 'policy', 'networking'],
    exhibitors: 200,
    speakers: ['Gen. Chance Saltzman', 'Space Force leadership', 'NASA Administrator'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'cubesat-workshop-2026',
    name: 'CubeSat Developers Workshop',
    type: 'workshop',
    startDate: '2026-04-22',
    endDate: '2026-04-24',
    location: 'San Luis Obispo, CA, USA',
    venue: 'Cal Poly San Luis Obispo',
    country: 'USA',
    virtual: false,
    description: 'Annual workshop bringing together CubeSat developers from academia, industry, and government. Features technical presentations, poster sessions, and hands-on demonstrations.',
    website: 'https://www.cubesat.org/workshop',
    attendeeCount: 800,
    cost: '$200-$500',
    costType: 'paid',
    organizer: 'Cal Poly CubeSat Lab',
    tags: ['cubesat', 'academic', 'engineering', 'hands-on'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'nsrc-2026',
    name: 'Next-Generation Suborbital Researchers Conference',
    type: 'conference',
    startDate: '2026-04-14',
    endDate: '2026-04-16',
    location: 'Broomfield, CO, USA',
    country: 'USA',
    virtual: false,
    description: 'Conference focused on using commercial suborbital vehicles for research, education, and technology development in microgravity.',
    website: 'https://nsrc.swri.org',
    attendeeCount: 400,
    cost: '$400-$800',
    costType: 'paid',
    organizer: 'Southwest Research Institute',
    tags: ['suborbital', 'research', 'microgravity', 'science'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'space-apps-webinar-april',
    name: 'Space Applications Webinar: Precision Agriculture',
    type: 'webinar',
    startDate: '2026-04-15',
    location: 'Virtual',
    country: 'Virtual',
    virtual: true,
    description: 'Monthly webinar covering commercial applications of space technology. This edition focuses on precision agriculture, crop monitoring via satellite, and climate-smart farming.',
    website: 'https://www.spacefoundation.org/events',
    cost: 'Free',
    costType: 'free',
    organizer: 'Space Foundation',
    tags: ['applications', 'agriculture', 'education', 'virtual'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'faa-commercial-space-2026',
    name: 'FAA Commercial Space Transportation Conference',
    type: 'hearing',
    startDate: '2026-04-28',
    endDate: '2026-04-29',
    location: 'Washington, DC, USA',
    country: 'USA',
    virtual: true,
    description: 'Annual FAA conference on commercial launch and reentry licensing, safety regulations, spaceport operations, and the evolving regulatory framework for commercial space transportation.',
    website: 'https://www.faa.gov/space',
    attendeeCount: 600,
    cost: 'Free',
    costType: 'free',
    organizer: 'Federal Aviation Administration',
    tags: ['regulation', 'licensing', 'safety', 'government', 'policy'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'lunar-surface-innovation-2026',
    name: 'Lunar Surface Innovation Consortium Workshop',
    type: 'workshop',
    startDate: '2026-04-29',
    endDate: '2026-04-30',
    location: 'Laurel, MD, USA',
    venue: 'Johns Hopkins APL',
    country: 'USA',
    virtual: true,
    description: 'Workshop on lunar surface technologies: ISRU, construction, power, communications, and science. Features NASA updates on Artemis surface systems.',
    website: 'https://lsic.jhuapl.edu',
    attendeeCount: 500,
    cost: 'Free',
    costType: 'free',
    organizer: 'Johns Hopkins APL / NASA',
    tags: ['lunar', 'artemis', 'ISRU', 'technology', 'NASA'],
    recurring: true,
    highlight: false,
  },

  // ══════════════════════════════════════════
  // ── May 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'space-tech-expo-2026',
    name: 'Space Tech Expo 2026',
    type: 'tradeshow',
    startDate: '2026-05-19',
    endDate: '2026-05-21',
    location: 'Long Beach, CA, USA',
    venue: 'Long Beach Convention Center',
    country: 'USA',
    virtual: false,
    description: 'Leading trade show for the space industry supply chain. Features 300+ exhibitors showcasing spacecraft components, testing equipment, manufacturing technologies, and subsystems.',
    website: 'https://www.spacetechexpo.com',
    registrationUrl: 'https://www.spacetechexpo.com/register',
    attendeeCount: 8000,
    cost: 'Free exhibit hall, $500-$1,500 conference',
    costType: 'paid',
    organizer: 'Smarter Shows',
    tags: ['supply-chain', 'manufacturing', 'components', 'testing'],
    exhibitors: 350,
    recurring: true,
    highlight: true,
  },
  {
    id: 'geoint-2026',
    name: 'GEOINT Symposium 2026',
    type: 'conference',
    startDate: '2026-05-03',
    endDate: '2026-05-06',
    location: 'San Diego, CA, USA',
    venue: 'San Diego Convention Center',
    country: 'USA',
    virtual: false,
    description: 'Largest annual gathering of the geospatial intelligence community. Hosted by USGIF, features intelligence community leaders, defense contractors, and technology providers.',
    website: 'https://geoint.usgif.org',
    attendeeCount: 5000,
    cost: '$800-$2,000',
    costType: 'paid',
    organizer: 'USGIF',
    tags: ['geoint', 'defense', 'remote-sensing', 'intelligence'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'global-space-exploration-2026',
    name: 'Global Space Exploration Conference (GLEX)',
    type: 'conference',
    startDate: '2026-05-11',
    endDate: '2026-05-15',
    location: 'Beijing, China',
    country: 'China',
    virtual: false,
    description: 'International conference on human and robotic space exploration featuring space agencies from around the world discussing lunar, Mars, and deep space missions.',
    website: 'https://www.iafastro.org/events/glex',
    attendeeCount: 2000,
    cost: '$500-$1,200',
    costType: 'paid',
    organizer: 'IAF',
    tags: ['exploration', 'lunar', 'mars', 'international', 'agencies'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'space-workforce-summit-2026',
    name: 'Space Workforce 2030 Summit',
    type: 'conference',
    startDate: '2026-05-28',
    endDate: '2026-05-29',
    location: 'Houston, TX, USA',
    country: 'USA',
    virtual: true,
    description: 'Focus on talent pipeline, STEM education, diversity in aerospace, and workforce development for the growing space economy. Hybrid format available.',
    website: 'https://www.spaceworkforce2030.org',
    attendeeCount: 1000,
    cost: '$300-$800',
    costType: 'paid',
    organizer: 'Space Workforce 2030',
    tags: ['workforce', 'STEM', 'diversity', 'education', 'talent'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'spacenews-webinar-may-2026',
    name: 'SpaceNews Webinar: Satellite Direct-to-Device',
    type: 'webinar',
    startDate: '2026-05-14',
    location: 'Virtual',
    country: 'Virtual',
    virtual: true,
    description: 'Monthly SpaceNews webinar examining the emerging direct-to-device satellite connectivity market, 5G-NTN standards, and competitive dynamics between operators.',
    website: 'https://spacenews.com/webinars',
    cost: 'Free',
    costType: 'free',
    organizer: 'SpaceNews',
    tags: ['D2D', 'connectivity', 'broadband', 'virtual'],
    recurring: true,
    highlight: false,
  },

  // ══════════════════════════════════════════
  // ── June 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'ssib-2026',
    name: 'State of the Space Industrial Base 2026',
    type: 'conference',
    startDate: '2026-06-15',
    endDate: '2026-06-17',
    location: 'Colorado Springs, CO, USA',
    country: 'USA',
    virtual: false,
    description: 'Annual workshop convening senior leaders from the U.S. Space Force, intelligence community, and commercial space to assess and strengthen the space industrial base.',
    website: 'https://spaceindustrialbase.com',
    attendeeCount: 500,
    cost: 'By invitation',
    costType: 'paid',
    organizer: 'USSF / Defense Innovation Unit',
    tags: ['defense', 'industrial-base', 'policy', 'government'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'aiaa-aviation-2026',
    name: 'AIAA Aviation Forum 2026',
    type: 'conference',
    startDate: '2026-06-15',
    endDate: '2026-06-19',
    location: 'Dallas, TX, USA',
    venue: 'Kay Bailey Hutchison Convention Center',
    country: 'USA',
    virtual: false,
    description: 'AIAA annual aviation and aeronautics forum. Covers advanced air mobility, hypersonics, point-to-point suborbital, and space access technologies.',
    website: 'https://www.aiaa.org/aviation',
    attendeeCount: 4000,
    cost: '$600-$1,100',
    costType: 'paid',
    organizer: 'AIAA',
    tags: ['aviation', 'hypersonics', 'propulsion', 'research'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'copuos-2026',
    name: 'UN COPUOS 69th Session',
    type: 'hearing',
    startDate: '2026-06-08',
    endDate: '2026-06-19',
    location: 'Vienna, Austria',
    venue: 'Vienna International Centre',
    country: 'Austria',
    virtual: true,
    description: 'The 69th session of the UN Committee on the Peaceful Uses of Outer Space. Addresses long-term sustainability of space activities, space debris, space traffic management, and international cooperation.',
    website: 'https://www.unoosa.org/oosa/en/ourwork/copuos/index.html',
    attendeeCount: 500,
    cost: 'Free (delegation-based)',
    costType: 'free',
    organizer: 'United Nations / UNOOSA',
    tags: ['policy', 'international', 'regulation', 'sustainability', 'UN'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'paris-air-forum-2026',
    name: 'Paris Air Forum 2026',
    type: 'conference',
    startDate: '2026-06-22',
    endDate: '2026-06-23',
    location: 'Paris, France',
    country: 'France',
    virtual: false,
    description: 'High-level discussion forum for aerospace executives covering topics from sustainability and defense to space exploration and new mobility.',
    website: 'https://www.parisairforum.com',
    attendeeCount: 1500,
    cost: '$800-$2,000',
    costType: 'paid',
    organizer: 'La Tribune / Paris Air Forum',
    tags: ['aerospace', 'europe', 'executive', 'policy'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'newspace-europe-2026',
    name: 'NewSpace Europe 2026',
    type: 'conference',
    startDate: '2026-06-08',
    endDate: '2026-06-09',
    location: 'Luxembourg City, Luxembourg',
    country: 'Luxembourg',
    virtual: false,
    description: 'European NewSpace conference focusing on the growing European commercial space ecosystem, featuring startups, investors, and policy makers from across the continent.',
    website: 'https://newspace-europe.lu',
    attendeeCount: 1000,
    cost: '$500-$1,200',
    costType: 'paid',
    organizer: 'Luxembourg Space Agency / ESA',
    tags: ['newspace', 'europe', 'startups', 'investment', 'policy'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'nasa-space-apps-2026',
    name: 'NASA International Space Apps Challenge',
    type: 'hackathon',
    startDate: '2026-06-27',
    endDate: '2026-06-28',
    location: 'Worldwide (200+ locations)',
    country: 'Worldwide',
    virtual: true,
    description: 'Global hackathon using NASA open data. Teams tackle challenges in Earth science, space exploration, and technology development over 48 hours. Open to all skill levels.',
    website: 'https://www.spaceappschallenge.org',
    attendeeCount: 30000,
    cost: 'Free',
    costType: 'free',
    organizer: 'NASA',
    tags: ['hackathon', 'open-data', 'education', 'community', 'global'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'space-sustainability-forum-2026',
    name: 'Space Sustainability Forum',
    type: 'conference',
    startDate: '2026-06-02',
    endDate: '2026-06-03',
    location: 'London, UK',
    country: 'UK',
    virtual: true,
    description: 'Conference on orbital debris mitigation, space traffic management, sustainable operations, and end-of-life disposal. Brings together regulators, operators, and technology providers.',
    website: 'https://spacesustainabilityforum.com',
    attendeeCount: 700,
    cost: '$600-$1,500',
    costType: 'paid',
    organizer: 'Space Sustainability Coalition',
    tags: ['sustainability', 'debris', 'regulation', 'STM'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'wrc-27-prep-meeting-1',
    name: 'WRC-27 Preparatory Meeting (CPM27-1)',
    type: 'hearing',
    startDate: '2026-06-29',
    endDate: '2026-07-03',
    location: 'Geneva, Switzerland',
    venue: 'ITU Headquarters',
    country: 'Switzerland',
    virtual: true,
    description: 'First preparatory conference meeting for WRC-27. Addresses spectrum allocation for satellite services, 5G/NTN coexistence, and NGSO/GSO sharing frameworks critical for the space industry.',
    website: 'https://www.itu.int/en/ITU-R/conferences/wrc/Pages/default.aspx',
    attendeeCount: 800,
    cost: 'Free (delegation-based)',
    costType: 'free',
    organizer: 'International Telecommunication Union (ITU)',
    tags: ['spectrum', 'regulation', 'ITU', 'international', 'policy'],
    recurring: false,
    highlight: false,
  },

  // ══════════════════════════════════════════
  // ── July 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'farnborough-2026',
    name: 'Farnborough International Airshow 2026',
    type: 'tradeshow',
    startDate: '2026-07-20',
    endDate: '2026-07-24',
    location: 'Farnborough, Hampshire, UK',
    venue: 'Farnborough Airport',
    country: 'UK',
    virtual: false,
    description: 'One of the world\'s largest aerospace trade shows, alternating years with the Paris Air Show. Major defense and space contracts are announced, with dedicated Space Zone exhibition area.',
    website: 'https://www.farnboroughairshow.com',
    registrationUrl: 'https://www.farnboroughairshow.com/register',
    attendeeCount: 80000,
    cost: '$100-$500 (trade days)',
    costType: 'paid',
    organizer: 'Farnborough International',
    tags: ['airshow', 'defense', 'commercial-space', 'UK', 'trade-show'],
    exhibitors: 1500,
    recurring: true,
    highlight: true,
  },
  {
    id: 'isdc-2026',
    name: 'International Space Development Conference 2026',
    type: 'conference',
    startDate: '2026-07-09',
    endDate: '2026-07-12',
    location: 'Los Angeles, CA, USA',
    country: 'USA',
    virtual: false,
    description: 'Annual conference hosted by the National Space Society featuring tracks on settlement, policy, commercial development, and education. Open to space enthusiasts and professionals alike.',
    website: 'https://isdc.nss.org',
    attendeeCount: 1500,
    cost: '$200-$600',
    costType: 'paid',
    organizer: 'National Space Society',
    tags: ['advocacy', 'settlement', 'education', 'policy', 'community'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'newspace-india-2026',
    name: 'NewSpace India Summit 2026',
    type: 'conference',
    startDate: '2026-07-15',
    endDate: '2026-07-16',
    location: 'Bangalore, India',
    country: 'India',
    virtual: false,
    description: 'India\'s premier commercial space conference, highlighting the rapidly growing Indian NewSpace ecosystem. Features ISRO updates, startup showcases, and international collaboration.',
    website: 'https://newspaceindia.com',
    attendeeCount: 2000,
    cost: '$200-$600',
    costType: 'paid',
    organizer: 'IN-SPACe / ISRO',
    tags: ['india', 'newspace', 'startups', 'ISRO', 'asia'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'spacenews-webinar-jul-2026',
    name: 'SpaceNews Webinar: Cislunar Economy',
    type: 'webinar',
    startDate: '2026-07-09',
    location: 'Virtual',
    country: 'Virtual',
    virtual: true,
    description: 'Monthly SpaceNews webinar on the emerging cislunar economy, commercial lunar services, Gateway logistics, and the business case for beyond-LEO operations.',
    website: 'https://spacenews.com/webinars',
    cost: 'Free',
    costType: 'free',
    organizer: 'SpaceNews',
    tags: ['cislunar', 'lunar', 'business', 'virtual'],
    recurring: true,
    highlight: false,
  },

  // ══════════════════════════════════════════
  // ── August 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'smallsat-2026',
    name: 'SmallSat Conference 2026',
    type: 'conference',
    startDate: '2026-08-01',
    endDate: '2026-08-06',
    location: 'Logan, UT, USA',
    venue: 'Utah State University',
    country: 'USA',
    virtual: false,
    description: 'The premier technical conference for small satellite missions and technologies. Hosted at Utah State University, it brings together engineers, program managers, and researchers from around the world.',
    website: 'https://smallsat.org',
    registrationUrl: 'https://smallsat.org/registration',
    attendeeCount: 4000,
    cost: '$200-$800',
    costType: 'paid',
    organizer: 'AIAA / Utah State University',
    tags: ['smallsat', 'technical', 'academic', 'engineering', 'missions'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'space-intelligence-forum-2026',
    name: 'Space Intelligence Forum',
    type: 'conference',
    startDate: '2026-08-18',
    endDate: '2026-08-19',
    location: 'Washington, DC, USA',
    country: 'USA',
    virtual: false,
    description: 'Focused on the intersection of space and intelligence operations. Covers space-based ISR, electronic warfare, SSA, and cyber threats to space systems.',
    website: 'https://www.defensenews.com/events',
    attendeeCount: 600,
    cost: '$1,000-$2,500',
    costType: 'paid',
    organizer: 'Defense News',
    tags: ['intelligence', 'defense', 'cybersecurity', 'ISR'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'space-ops-workshop-2026',
    name: 'International SpaceOps Workshop',
    type: 'workshop',
    startDate: '2026-08-24',
    endDate: '2026-08-28',
    location: 'Montreal, Canada',
    country: 'Canada',
    virtual: false,
    description: 'Biennial conference on space mission operations. Covers ground systems, flight dynamics, autonomous operations, mission control, and multi-mission operations.',
    website: 'https://www.spaceops.org',
    attendeeCount: 1200,
    cost: '$400-$900',
    costType: 'paid',
    organizer: 'AIAA / International SpaceOps Committee',
    tags: ['operations', 'ground-systems', 'mission-control', 'international'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'responsive-space-2026',
    name: 'Responsive Space Conference',
    type: 'conference',
    startDate: '2026-08-11',
    endDate: '2026-08-13',
    location: 'Albuquerque, NM, USA',
    venue: 'Kirtland Air Force Base',
    country: 'USA',
    virtual: false,
    description: 'Annual conference on operationally responsive space capabilities. Covers rapid launch, on-orbit servicing, resilient architectures, and rapid reconstitution for national security.',
    website: 'https://responsivespace.com',
    attendeeCount: 500,
    cost: '$600-$1,200',
    costType: 'paid',
    organizer: 'AFRL / SDA',
    tags: ['responsive-space', 'defense', 'rapid-launch', 'national-security'],
    recurring: true,
    highlight: false,
  },

  // ══════════════════════════════════════════
  // ── September 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'amos-2026',
    name: 'AMOS Conference 2026',
    type: 'conference',
    startDate: '2026-09-15',
    endDate: '2026-09-18',
    location: 'Maui, HI, USA',
    venue: 'Wailea Beach Resort',
    country: 'USA',
    virtual: false,
    description: 'Advanced Maui Optical and Space Surveillance Technologies Conference. The premier forum for space domain awareness, space surveillance technologies, and orbital debris research.',
    website: 'https://amostech.com',
    registrationUrl: 'https://amostech.com/register',
    attendeeCount: 1500,
    cost: '$800-$2,000',
    costType: 'paid',
    organizer: 'Maui Economic Development Board',
    tags: ['SSA', 'surveillance', 'debris', 'optical', 'defense'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'wsb-week-2026',
    name: 'World Satellite Business Week 2026',
    type: 'conference',
    startDate: '2026-09-14',
    endDate: '2026-09-18',
    location: 'Paris, France',
    venue: 'Westin Paris - Vendome',
    country: 'France',
    virtual: false,
    description: 'Premier business event for the global satellite industry. C-suite executives gather to discuss market trends, M&A, investment, and strategic direction of the satellite sector.',
    website: 'https://www.worldsatellitebusinessweek.com',
    attendeeCount: 3000,
    cost: '$3,000-$6,000',
    costType: 'paid',
    organizer: 'Euroconsult',
    tags: ['business', 'satcom', 'investment', 'executive', 'europe'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'iac-launch-week-2026',
    name: 'International Astronautical Congress Pre-Events',
    type: 'networking',
    startDate: '2026-09-28',
    endDate: '2026-09-30',
    location: 'Milan, Italy',
    country: 'Italy',
    virtual: false,
    description: 'Pre-congress networking events, space agency bilateral meetings, and startup pitches leading into IAC 2026. Multiple side events across the city.',
    website: 'https://www.iafastro.org/events/iac/iac-2026',
    cost: 'Varies',
    costType: 'paid',
    organizer: 'Various',
    tags: ['networking', 'international', 'startups', 'agencies'],
    recurring: false,
    highlight: false,
  },
  {
    id: 'space-cyber-2026',
    name: 'Space Cybersecurity Symposium',
    type: 'conference',
    startDate: '2026-09-08',
    endDate: '2026-09-09',
    location: 'Washington, DC, USA',
    country: 'USA',
    virtual: false,
    description: 'Focused on cybersecurity threats to space systems. Covers satellite hacking, ground station security, supply chain integrity, and national security implications.',
    website: 'https://www.spacecybersymposium.com',
    attendeeCount: 400,
    cost: '$800-$2,000',
    costType: 'paid',
    organizer: 'Space ISAC',
    tags: ['cybersecurity', 'defense', 'national-security', 'infrastructure'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'via-satellite-webinar-sep-2026',
    name: 'Via Satellite Webinar: Spectrum & Interference',
    type: 'webinar',
    startDate: '2026-09-24',
    location: 'Virtual',
    country: 'Virtual',
    virtual: true,
    description: 'Via Satellite monthly webinar addressing spectrum management challenges, NGSO-GSO interference mitigation, and WRC-27 preparatory activities impacting the satellite industry.',
    website: 'https://www.satellitetoday.com/webinars',
    cost: 'Free',
    costType: 'free',
    organizer: 'Via Satellite',
    tags: ['spectrum', 'regulation', 'satcom', 'virtual'],
    recurring: true,
    highlight: false,
  },

  // ══════════════════════════════════════════
  // ── October 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'iac-2026',
    name: 'International Astronautical Congress (IAC) 2026',
    type: 'conference',
    startDate: '2026-10-01',
    endDate: '2026-10-05',
    location: 'Milan, Italy',
    venue: 'MiCo - Milano Convention Centre',
    country: 'Italy',
    virtual: false,
    description: 'The world\'s premier space event, gathering 10,000+ space professionals, agencies, and companies from 80+ countries. Features technical sessions, plenaries, Global Networking Forum, and the IAF exhibition.',
    website: 'https://www.iafastro.org/events/iac/iac-2026',
    registrationUrl: 'https://www.iafastro.org/events/iac/iac-2026/registration',
    attendeeCount: 10000,
    cost: '$500-$1,500',
    costType: 'paid',
    organizer: 'International Astronautical Federation (IAF)',
    tags: ['international', 'agencies', 'research', 'industry', 'networking'],
    exhibitors: 400,
    recurring: true,
    highlight: true,
  },
  {
    id: 'satellite-innovation-2026',
    name: 'Satellite Innovation 2026',
    type: 'conference',
    startDate: '2026-10-13',
    endDate: '2026-10-14',
    location: 'Mountain View, CA, USA',
    venue: 'Computer History Museum',
    country: 'USA',
    virtual: false,
    description: 'Focused on innovation in the satellite sector. Features startup demos, investor matchmaking, and panels on next-gen constellations, ground systems, and analytics.',
    website: 'https://www.satinnovation.com',
    attendeeCount: 1500,
    cost: '$1,200-$2,500',
    costType: 'paid',
    organizer: 'Satnews Publishers',
    tags: ['innovation', 'startups', 'investment', 'silicon-valley'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'world-space-week-2026',
    name: 'World Space Week 2026',
    type: 'launch_event',
    startDate: '2026-10-04',
    endDate: '2026-10-10',
    location: 'Worldwide',
    country: 'Worldwide',
    virtual: true,
    description: 'UN-declared annual celebration of space science and technology. Thousands of events worldwide including lectures, exhibitions, screenings, and educational activities.',
    website: 'https://www.worldspaceweek.org',
    attendeeCount: 100000,
    cost: 'Free',
    costType: 'free',
    organizer: 'World Space Week Association / UN',
    tags: ['education', 'outreach', 'global', 'community'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'aiaa-ascend-2026',
    name: 'AIAA ASCEND 2026',
    type: 'conference',
    startDate: '2026-10-19',
    endDate: '2026-10-21',
    location: 'Las Vegas, NV, USA',
    venue: 'Caesars Forum',
    country: 'USA',
    virtual: false,
    description: 'AIAA\'s space conference bringing together space professionals for technical sessions, networking, and exhibition. Covers commercial space, exploration, national security, and sustainability.',
    website: 'https://www.aiaa.org/ascend',
    attendeeCount: 3500,
    cost: '$700-$1,400',
    costType: 'paid',
    organizer: 'AIAA',
    tags: ['commercial-space', 'exploration', 'defense', 'sustainability'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'space-foundation-discovery-oct',
    name: 'Space Foundation Discovery: Artemis Update',
    type: 'webinar',
    startDate: '2026-10-22',
    location: 'Virtual',
    country: 'Virtual',
    virtual: true,
    description: 'Special edition Discovery Series webinar providing updates on the Artemis program, commercial lunar payload services, and Gateway construction milestones.',
    website: 'https://www.spacefoundation.org',
    cost: 'Free',
    costType: 'free',
    organizer: 'Space Foundation',
    tags: ['artemis', 'lunar', 'NASA', 'virtual'],
    recurring: true,
    highlight: false,
  },

  // ══════════════════════════════════════════
  // ── November 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'milsatcom-2026',
    name: 'Global MilSatCom 2026',
    type: 'conference',
    startDate: '2026-11-03',
    endDate: '2026-11-05',
    location: 'London, UK',
    venue: 'QEII Centre',
    country: 'UK',
    virtual: false,
    description: 'The world\'s most established military satellite communications conference. Features senior military and government officials discussing next-gen MILSATCOM architectures, resilience, and commercial integration.',
    website: 'https://www.globalmilsatcom.com',
    attendeeCount: 800,
    cost: '$2,000-$4,000',
    costType: 'paid',
    organizer: 'SMi Group',
    tags: ['milsatcom', 'defense', 'government', 'UK', 'communications'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'space-tech-expo-europe-2026',
    name: 'Space Tech Expo Europe 2026',
    type: 'tradeshow',
    startDate: '2026-11-17',
    endDate: '2026-11-19',
    location: 'Bremen, Germany',
    venue: 'Messe Bremen',
    country: 'Germany',
    virtual: false,
    description: 'European edition of Space Tech Expo. Major supply chain trade show for European space industry with focus on satellite manufacturing, launch systems, and ground equipment.',
    website: 'https://www.spacetechexpo-europe.com',
    registrationUrl: 'https://www.spacetechexpo-europe.com/register',
    attendeeCount: 5000,
    cost: 'Free exhibit hall, $500-$1,200 conference',
    costType: 'paid',
    organizer: 'Smarter Shows',
    tags: ['supply-chain', 'europe', 'manufacturing', 'components'],
    exhibitors: 250,
    recurring: true,
    highlight: false,
  },
  {
    id: 'dubai-airshow-2026-space',
    name: 'Dubai Airshow 2026 - Space Pavilion',
    type: 'tradeshow',
    startDate: '2026-11-16',
    endDate: '2026-11-20',
    location: 'Dubai, UAE',
    venue: 'DWC - Al Maktoum International',
    country: 'UAE',
    virtual: false,
    description: 'Biennial aerospace event in the Middle East. The dedicated Space Pavilion features growing presence of space startups, agencies, and defense programs from the Gulf region and beyond.',
    website: 'https://www.dubaiairshow.aero',
    attendeeCount: 50000,
    cost: '$100-$1,000',
    costType: 'paid',
    organizer: 'Dubai Airshow',
    tags: ['airshow', 'middle-east', 'defense', 'commercial-space'],
    exhibitors: 1200,
    recurring: true,
    highlight: false,
  },
  {
    id: 'space-startup-pitch-2026',
    name: 'Space Venture Finance Symposium',
    type: 'networking',
    startDate: '2026-11-10',
    endDate: '2026-11-11',
    location: 'San Francisco, CA, USA',
    country: 'USA',
    virtual: false,
    description: 'Dedicated space venture event connecting startups with investors. Features pitch competitions, fireside chats with successful founders, and closed-door investor meetings.',
    website: 'https://spaceinvestsummit.com',
    attendeeCount: 500,
    cost: '$1,000-$3,000',
    costType: 'paid',
    organizer: 'Space Capital / Space Investment Summit',
    tags: ['investment', 'startups', 'VC', 'pitch', 'finance'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'spacenews-webinar-nov-2026',
    name: 'SpaceNews Webinar: Year in Review',
    type: 'webinar',
    startDate: '2026-11-19',
    location: 'Virtual',
    country: 'Virtual',
    virtual: true,
    description: 'SpaceNews annual year-in-review webinar examining the biggest stories, deals, launches, and policy shifts of 2026 in the global space industry.',
    website: 'https://spacenews.com/webinars',
    cost: 'Free',
    costType: 'free',
    organizer: 'SpaceNews',
    tags: ['review', 'analysis', 'industry-trends', 'virtual'],
    recurring: true,
    highlight: false,
  },

  // ══════════════════════════════════════════
  // ── December 2026 ──
  // ══════════════════════════════════════════
  {
    id: 'agu-fall-2026',
    name: 'AGU Fall Meeting 2026',
    type: 'conference',
    startDate: '2026-12-07',
    endDate: '2026-12-11',
    location: 'San Francisco, CA, USA',
    venue: 'Moscone Center',
    country: 'USA',
    virtual: true,
    description: 'Largest Earth and space science conference in the world. Features planetary science, heliophysics, and space weather sessions relevant to the space industry alongside 25,000+ geoscientists.',
    website: 'https://www.agu.org/Fall-Meeting',
    attendeeCount: 25000,
    cost: '$500-$800',
    costType: 'paid',
    organizer: 'American Geophysical Union',
    tags: ['science', 'earth-observation', 'planetary', 'space-weather', 'academic'],
    recurring: true,
    highlight: false,
  },
  {
    id: 'aiaa-propulsion-2026',
    name: 'AIAA Propulsion & Energy Forum 2026',
    type: 'conference',
    startDate: '2026-12-14',
    endDate: '2026-12-18',
    location: 'Cincinnati, OH, USA',
    country: 'USA',
    virtual: false,
    description: 'Leading conference on propulsion and energy systems for aerospace. Covers chemical, electric, and nuclear propulsion, in-space manufacturing energy needs, and green propellant development.',
    website: 'https://www.aiaa.org/propulsion-energy',
    attendeeCount: 2500,
    cost: '$600-$1,100',
    costType: 'paid',
    organizer: 'AIAA',
    tags: ['propulsion', 'energy', 'research', 'engineering'],
    recurring: true,
    highlight: false,
  },

  // ══════════════════════════════════════════
  // ── 2027 Events ──
  // ══════════════════════════════════════════
  {
    id: 'aiaa-scitech-2027',
    name: 'AIAA SciTech Forum 2027',
    type: 'conference',
    startDate: '2027-01-18',
    endDate: '2027-01-22',
    location: 'Grapevine, TX, USA',
    venue: 'Gaylord Texan Resort',
    country: 'USA',
    virtual: false,
    description: 'The largest annual aerospace sciences meeting returns for 2027. Over 4,500 technical papers covering aerodynamics, structures, propulsion, space systems, and emerging technologies.',
    website: 'https://www.aiaa.org/scitech',
    attendeeCount: 6500,
    cost: '$750-$1,300',
    costType: 'paid',
    organizer: 'AIAA',
    tags: ['research', 'engineering', 'aerodynamics', 'propulsion'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'satellite-2027',
    name: 'SATELLITE 2027',
    type: 'conference',
    startDate: '2027-03-08',
    endDate: '2027-03-11',
    location: 'Washington, DC, USA',
    venue: 'Walter E. Washington Convention Center',
    country: 'USA',
    virtual: false,
    description: 'The premier global event for satellite communications, space, and connectivity returns for its 2027 edition with expanded focus on direct-to-device and non-terrestrial networks.',
    website: 'https://www.satshow.com',
    attendeeCount: 16000,
    cost: 'Free exhibit hall, $1,200-$3,500 conference',
    costType: 'paid',
    organizer: 'Via Satellite / Access Intelligence',
    tags: ['satcom', 'connectivity', 'broadband', 'government', 'defense'],
    exhibitors: 375,
    recurring: true,
    highlight: true,
  },
  {
    id: 'space-symposium-2027',
    name: '42nd Space Symposium',
    type: 'conference',
    startDate: '2027-04-05',
    endDate: '2027-04-08',
    location: 'Colorado Springs, CO, USA',
    venue: 'The Broadmoor',
    country: 'USA',
    virtual: false,
    description: 'The premier assembly of the global space community returns for its 42nd year with expanded international pavilions and dedicated tracks on cislunar economy and space traffic management.',
    website: 'https://www.spacesymposium.org',
    attendeeCount: 16000,
    cost: '$1,600-$4,200',
    costType: 'paid',
    organizer: 'Space Foundation',
    tags: ['defense', 'government', 'commercial-space', 'policy', 'networking'],
    exhibitors: 220,
    recurring: true,
    highlight: true,
  },
  {
    id: 'space-tech-expo-2027',
    name: 'Space Tech Expo 2027',
    type: 'tradeshow',
    startDate: '2027-05-18',
    endDate: '2027-05-20',
    location: 'Long Beach, CA, USA',
    venue: 'Long Beach Convention Center',
    country: 'USA',
    virtual: false,
    description: 'The space industry supply chain trade show returns with expanded sections on in-space manufacturing, advanced materials, and additive manufacturing for spacecraft.',
    website: 'https://www.spacetechexpo.com',
    attendeeCount: 9000,
    cost: 'Free exhibit hall, $500-$1,500 conference',
    costType: 'paid',
    organizer: 'Smarter Shows',
    tags: ['supply-chain', 'manufacturing', 'components', 'testing'],
    exhibitors: 375,
    recurring: true,
    highlight: true,
  },
  {
    id: 'paris-air-show-2027',
    name: 'Paris Air Show 2027',
    type: 'tradeshow',
    startDate: '2027-06-16',
    endDate: '2027-06-22',
    location: 'Paris Le Bourget, France',
    venue: 'Parc des Expositions du Bourget',
    country: 'France',
    virtual: false,
    description: 'The world\'s oldest and largest air show (biennial). A landmark event for the global aerospace industry with massive space exhibition halls, major contract signings, and defense program reveals.',
    website: 'https://www.siae.fr',
    registrationUrl: 'https://www.siae.fr/en/registration',
    attendeeCount: 300000,
    cost: '$50-$500 (trade), varies public',
    costType: 'paid',
    organizer: 'SIAE / GIFAS',
    tags: ['airshow', 'defense', 'commercial-space', 'france', 'trade-show', 'europe'],
    exhibitors: 2400,
    recurring: true,
    highlight: true,
  },
  {
    id: 'smallsat-2027',
    name: 'SmallSat Conference 2027',
    type: 'conference',
    startDate: '2027-08-02',
    endDate: '2027-08-07',
    location: 'Logan, UT, USA',
    venue: 'Utah State University',
    country: 'USA',
    virtual: false,
    description: 'The premier technical conference for small satellite missions returns for 2027 with expanded tracks on mega-constellation operations, on-orbit servicing, and space debris.',
    website: 'https://smallsat.org',
    attendeeCount: 4500,
    cost: '$200-$850',
    costType: 'paid',
    organizer: 'AIAA / Utah State University',
    tags: ['smallsat', 'technical', 'academic', 'engineering', 'missions'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'iac-2027',
    name: 'International Astronautical Congress (IAC) 2027',
    type: 'conference',
    startDate: '2027-10-06',
    endDate: '2027-10-10',
    location: 'Baku, Azerbaijan',
    country: 'Azerbaijan',
    virtual: false,
    description: 'The world\'s premier space event heads to Baku for IAC 2027. Expected to bring together 10,000+ delegates from 90+ countries for the 78th Congress.',
    website: 'https://www.iafastro.org/events/iac',
    attendeeCount: 10000,
    cost: '$500-$1,500',
    costType: 'paid',
    organizer: 'International Astronautical Federation (IAF)',
    tags: ['international', 'agencies', 'research', 'industry', 'networking'],
    exhibitors: 420,
    recurring: true,
    highlight: true,
  },
  {
    id: 'wrc-27',
    name: 'World Radiocommunication Conference 2027 (WRC-27)',
    type: 'hearing',
    startDate: '2027-11-17',
    endDate: '2027-12-15',
    location: 'Dubai, UAE',
    venue: 'Dubai World Trade Centre',
    country: 'UAE',
    virtual: false,
    description: 'ITU World Radiocommunication Conference setting global spectrum allocation rules for the next 4 years. Critical decisions on satellite spectrum sharing, NGSO constellations, and 5G-NTN coexistence.',
    website: 'https://www.itu.int/en/ITU-R/conferences/wrc/2027',
    attendeeCount: 4000,
    cost: 'Free (delegation-based)',
    costType: 'free',
    organizer: 'International Telecommunication Union (ITU)',
    tags: ['spectrum', 'regulation', 'ITU', 'international', 'policy', 'WRC'],
    recurring: true,
    highlight: true,
  },
  {
    id: 'amos-2027',
    name: 'AMOS Conference 2027',
    type: 'conference',
    startDate: '2027-09-14',
    endDate: '2027-09-17',
    location: 'Maui, HI, USA',
    venue: 'Wailea Beach Resort',
    country: 'USA',
    virtual: false,
    description: 'The premier forum for space domain awareness returns. Expanded tracks on cislunar surveillance, autonomous SDA, and commercial SSA data fusion.',
    website: 'https://amostech.com',
    attendeeCount: 1800,
    cost: '$800-$2,000',
    costType: 'paid',
    organizer: 'Maui Economic Development Board',
    tags: ['SSA', 'surveillance', 'debris', 'optical', 'defense'],
    recurring: true,
    highlight: true,
  },
];

// ── ICS Generation Helper ──

export function generateICS(event: SpaceEvent): string {
  const formatDate = (dateStr: string) => dateStr.replace(/-/g, '');
  const start = formatDate(event.startDate) + 'T090000Z';
  const end = formatDate(event.endDate || event.startDate) + 'T180000Z';
  const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

  const escapeICS = (str: string) =>
    str.replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n');

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//SpaceNexus//Space Events//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `DTSTART:${start}`,
    `DTEND:${end}`,
    `DTSTAMP:${now}`,
    `UID:${event.id}@spacenexus.us`,
    `SUMMARY:${escapeICS(event.name)}`,
    `DESCRIPTION:${escapeICS(event.description)}`,
    `LOCATION:${escapeICS(event.location)}${event.venue ? ' - ' + escapeICS(event.venue) : ''}`,
    `URL:${event.website}`,
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');
}

// ── Export all events as a combined ICS ──

export function generateMultiEventICS(events: SpaceEvent[]): string {
  const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  const formatDate = (dateStr: string) => dateStr.replace(/-/g, '');

  const escapeICS = (str: string) =>
    str.replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n');

  const vevents = events.map((event) => {
    const start = formatDate(event.startDate) + 'T090000Z';
    const end = formatDate(event.endDate || event.startDate) + 'T180000Z';
    return [
      'BEGIN:VEVENT',
      `DTSTART:${start}`,
      `DTEND:${end}`,
      `DTSTAMP:${now}`,
      `UID:${event.id}@spacenexus.us`,
      `SUMMARY:${escapeICS(event.name)}`,
      `DESCRIPTION:${escapeICS(event.description)}`,
      `LOCATION:${escapeICS(event.location)}${event.venue ? ' - ' + escapeICS(event.venue) : ''}`,
      `URL:${event.website}`,
      'END:VEVENT',
    ].join('\r\n');
  });

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//SpaceNexus//Space Events//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:SpaceNexus Space Events',
    ...vevents,
    'END:VCALENDAR',
  ].join('\r\n');
}

// ── Google Calendar link generator ──

export function generateGoogleCalendarUrl(event: SpaceEvent): string {
  const formatGoogleDate = (dateStr: string) => dateStr.replace(/-/g, '');
  const start = formatGoogleDate(event.startDate);
  const end = formatGoogleDate(event.endDate || event.startDate);
  // Google Calendar uses all-day event format: YYYYMMDD/YYYYMMDD (end is exclusive, add one day)
  const endDate = new Date(event.endDate || event.startDate);
  endDate.setDate(endDate.getDate() + 1);
  const endStr = endDate.toISOString().split('T')[0].replace(/-/g, '');

  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: event.name,
    dates: `${start}/${endStr}`,
    details: `${event.description}\n\n${event.website}`,
    location: event.venue ? `${event.venue}, ${event.location}` : event.location,
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

// ── Type/filter helpers ──

export const EVENT_TYPES: { value: SpaceEvent['type']; label: string; color: string }[] = [
  { value: 'conference', label: 'Conference', color: 'bg-cyan-500' },
  { value: 'tradeshow', label: 'Trade Show', color: 'bg-green-500' },
  { value: 'expo', label: 'Expo', color: 'bg-purple-500' },
  { value: 'workshop', label: 'Workshop', color: 'bg-amber-500' },
  { value: 'webinar', label: 'Webinar', color: 'bg-violet-500' },
  { value: 'networking', label: 'Networking', color: 'bg-rose-500' },
  { value: 'launch_event', label: 'Launch Event', color: 'bg-orange-500' },
  { value: 'hackathon', label: 'Hackathon', color: 'bg-indigo-500' },
  { value: 'hearing', label: 'Hearing / Policy', color: 'bg-teal-500' },
];

export const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

export function getEventTypeColor(type: SpaceEvent['type']): string {
  return EVENT_TYPES.find(t => t.value === type)?.color || 'bg-slate-500';
}

export function getEventTypeLabel(type: SpaceEvent['type']): string {
  return EVENT_TYPES.find(t => t.value === type)?.label || type;
}

// ── Query helpers ──

export function getAllEvents(): SpaceEvent[] {
  return [...SPACE_EVENTS].sort((a, b) => a.startDate.localeCompare(b.startDate));
}

export function getUpcomingEvents(days: number = 90): SpaceEvent[] {
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  const cutoff = new Date(now);
  cutoff.setDate(cutoff.getDate() + days);

  return SPACE_EVENTS
    .filter((e) => {
      const end = new Date((e.endDate || e.startDate) + 'T23:59:59');
      const start = new Date(e.startDate + 'T00:00:00');
      return end >= now && start <= cutoff;
    })
    .sort((a, b) => a.startDate.localeCompare(b.startDate));
}

export function getEventsByType(type: SpaceEvent['type']): SpaceEvent[] {
  return SPACE_EVENTS
    .filter((e) => e.type === type)
    .sort((a, b) => a.startDate.localeCompare(b.startDate));
}

export function getEventsByMonth(year: number, month: number): SpaceEvent[] {
  return SPACE_EVENTS
    .filter((e) => {
      const d = new Date(e.startDate + 'T00:00:00');
      return d.getFullYear() === year && d.getMonth() === month;
    })
    .sort((a, b) => a.startDate.localeCompare(b.startDate));
}

export function getEventCountries(): string[] {
  const countries = new Set<string>();
  SPACE_EVENTS.forEach((e) => countries.add(e.country));
  return Array.from(countries).sort();
}
