import prisma from './db';
import { SpectrumAllocation, SpectrumFiling, SpectrumService, SpectrumFilingStatus } from '@/types';

// Seed data for spectrum allocations
export const SPECTRUM_ALLOCATIONS_SEED = [
  {
    slug: 'l-band',
    bandName: 'L-band',
    frequencyMin: 1000,
    frequencyMax: 2000,
    bandwidth: 1000,
    service: 'mobile_satellite',
    region: 'Global',
    allocationType: 'primary',
    assignedTo: 'Iridium / Inmarsat',
    filingStatus: 'assigned',
    numberOfFilings: 14,
    ituReference: 'RR 5.351A',
    fccReference: null,
    coordinationRequired: true,
    description: 'Primary mobile satellite band. Used by Iridium, Inmarsat, and Globalstar for voice and low-data-rate services.',
  },
  {
    slug: 's-band',
    bandName: 'S-band',
    frequencyMin: 2000,
    frequencyMax: 4000,
    bandwidth: 2000,
    service: 'earth_exploration',
    region: 'Global',
    allocationType: 'shared',
    assignedTo: null,
    filingStatus: 'filed',
    numberOfFilings: 22,
    ituReference: 'RR 5.391',
    fccReference: null,
    coordinationRequired: true,
    description: 'Used for Earth exploration satellite service and space research. Shared with terrestrial mobile services in many regions.',
  },
  {
    slug: 'c-band',
    bandName: 'C-band',
    frequencyMin: 4000,
    frequencyMax: 8000,
    bandwidth: 4000,
    service: 'fixed_satellite',
    region: 'Global',
    allocationType: 'primary',
    assignedTo: 'SES / Intelsat (transitioning)',
    filingStatus: 'congested',
    numberOfFilings: 87,
    ituReference: 'RR 5.418',
    fccReference: 'FCC 20-22',
    coordinationRequired: true,
    description: 'Heavily congested band undergoing transition. FCC C-band auction reallocated 3.7-3.98 GHz to 5G. Legacy satellite operators being relocated.',
  },
  {
    slug: 'x-band',
    bandName: 'X-band',
    frequencyMin: 8000,
    frequencyMax: 12000,
    bandwidth: 4000,
    service: 'earth_exploration',
    region: 'Region 2',
    allocationType: 'primary',
    assignedTo: 'Military / Government',
    filingStatus: 'assigned',
    numberOfFilings: 31,
    ituReference: 'RR 5.461',
    fccReference: null,
    coordinationRequired: true,
    description: 'Primarily reserved for military communications, radar, and Earth exploration satellite services. Limited commercial access.',
  },
  {
    slug: 'ku-band',
    bandName: 'Ku-band',
    frequencyMin: 12000,
    frequencyMax: 18000,
    bandwidth: 6000,
    service: 'fixed_satellite',
    region: 'Global',
    allocationType: 'primary',
    assignedTo: 'OneWeb / SES / Eutelsat',
    filingStatus: 'assigned',
    numberOfFilings: 64,
    ituReference: 'RR 5.484A',
    fccReference: 'FCC 17-122',
    coordinationRequired: true,
    description: 'Workhorse band for DTH television and VSAT services. Increasingly used by NGSO constellations like OneWeb.',
  },
  {
    slug: 'ka-band',
    bandName: 'Ka-band',
    frequencyMin: 26000,
    frequencyMax: 40000,
    bandwidth: 14000,
    service: 'fixed_satellite',
    region: 'Global',
    allocationType: 'primary',
    assignedTo: 'SpaceX / Amazon / Telesat',
    filingStatus: 'coordinating',
    numberOfFilings: 112,
    ituReference: 'RR 5.516B',
    fccReference: 'FCC 22-91',
    coordinationRequired: true,
    description: 'High-throughput band critical for next-gen broadband constellations. Active coordination between Starlink, Kuiper, and Lightspeed systems.',
  },
  {
    slug: 'v-band',
    bandName: 'V-band',
    frequencyMin: 40000,
    frequencyMax: 75000,
    bandwidth: 35000,
    service: 'inter_satellite',
    region: 'Global',
    allocationType: 'primary',
    assignedTo: null,
    filingStatus: 'available',
    numberOfFilings: 18,
    ituReference: 'RR 5.555',
    fccReference: null,
    coordinationRequired: false,
    description: 'Emerging band with large bandwidth availability. SpaceX has filed for V-band NGSO operations. High atmospheric attenuation limits ground use.',
  },
  {
    slug: 'q-band',
    bandName: 'Q-band',
    frequencyMin: 33000,
    frequencyMax: 50000,
    bandwidth: 17000,
    service: 'fixed_satellite',
    region: 'Global',
    allocationType: 'secondary',
    assignedTo: null,
    filingStatus: 'available',
    numberOfFilings: 7,
    ituReference: 'RR 5.547',
    fccReference: null,
    coordinationRequired: false,
    description: 'Largely unallocated band with potential for future high-capacity satellite links. Research and experimental use ongoing.',
  },
];

// Seed data for spectrum filings
const filingDate = (year: number, month: number, day: number) => new Date(year, month - 1, day);

export const SPECTRUM_FILINGS_SEED = [
  {
    filingId: 'SAT-LOI-2021-0002',
    operator: 'SpaceX',
    system: 'Starlink Gen2 V-band',
    agency: 'FCC',
    bandName: 'V-band',
    frequencyMin: 40000,
    frequencyMax: 50200,
    orbitType: 'NGSO',
    numberOfSatellites: 7500,
    status: 'approved',
    filingDate: filingDate(2021, 1, 15),
    grantDate: filingDate(2023, 12, 1),
    expiryDate: filingDate(2032, 12, 1),
    description: 'SpaceX Gen2 filing for V-band downlinks to support high-throughput Starlink services at scale.',
    country: 'USA',
  },
  {
    filingId: 'SAT-MPL-2020-0064',
    operator: 'SpaceX',
    system: 'Starlink Ka-band',
    agency: 'FCC',
    bandName: 'Ka-band',
    frequencyMin: 27500,
    frequencyMax: 29500,
    orbitType: 'NGSO',
    numberOfSatellites: 4408,
    status: 'approved',
    filingDate: filingDate(2020, 4, 17),
    grantDate: filingDate(2021, 4, 27),
    expiryDate: filingDate(2030, 4, 27),
    description: 'Ka-band authorization for Starlink broadband constellation. Includes gateway and user terminal links.',
    country: 'USA',
  },
  {
    filingId: 'SAT-LOI-2019-0034',
    operator: 'Amazon (Kuiper)',
    system: 'Project Kuiper',
    agency: 'FCC',
    bandName: 'Ka-band',
    frequencyMin: 28600,
    frequencyMax: 30000,
    orbitType: 'NGSO',
    numberOfSatellites: 3236,
    status: 'approved',
    filingDate: filingDate(2019, 7, 4),
    grantDate: filingDate(2020, 7, 30),
    expiryDate: filingDate(2029, 7, 30),
    description: 'Amazon Project Kuiper Ka-band LEO constellation for global broadband. Must deploy 50% by 2026.',
    country: 'USA',
  },
  {
    filingId: 'SAT-LOI-2016-0041',
    operator: 'OneWeb',
    system: 'OneWeb Phase 2',
    agency: 'FCC',
    bandName: 'Ku-band',
    frequencyMin: 12750,
    frequencyMax: 14500,
    orbitType: 'NGSO',
    numberOfSatellites: 648,
    status: 'coordinating',
    filingDate: filingDate(2016, 5, 27),
    grantDate: null,
    expiryDate: null,
    description: 'OneWeb Phase 2 expansion filing for Ku-band spectrum. Coordination ongoing with incumbent GEO operators.',
    country: 'UK',
  },
  {
    filingId: 'SAT-LOI-2022-0078',
    operator: 'Telesat',
    system: 'Lightspeed',
    agency: 'FCC',
    bandName: 'Ka-band',
    frequencyMin: 28350,
    frequencyMax: 29100,
    orbitType: 'NGSO',
    numberOfSatellites: 298,
    status: 'pending',
    filingDate: filingDate(2022, 9, 14),
    grantDate: null,
    expiryDate: null,
    description: 'Telesat Lightspeed Ka-band filing for enterprise and government broadband LEO constellation.',
    country: 'Canada',
  },
  {
    filingId: 'SAT-APL-2023-0015',
    operator: 'AST SpaceMobile',
    system: 'SpaceMobile',
    agency: 'FCC',
    bandName: 'L-band',
    frequencyMin: 1910,
    frequencyMax: 1990,
    orbitType: 'NGSO',
    numberOfSatellites: 168,
    status: 'pending',
    filingDate: filingDate(2023, 3, 10),
    grantDate: null,
    expiryDate: null,
    description: 'Direct-to-cellular satellite service using standard mobile phone frequencies. Coordination with terrestrial carriers required.',
    country: 'USA',
  },
  // ── Additional filings ──
  {
    filingId: 'SAT-LOI-2017-0030',
    operator: 'SES',
    system: 'O3b mPOWER',
    agency: 'FCC',
    bandName: 'Ka-band',
    frequencyMin: 27500,
    frequencyMax: 30000,
    orbitType: 'NGSO',
    numberOfSatellites: 11,
    status: 'approved',
    filingDate: filingDate(2017, 9, 1),
    grantDate: filingDate(2018, 6, 22),
    expiryDate: filingDate(2033, 6, 22),
    description: 'SES O3b mPOWER next-gen MEO constellation with software-defined beams for high-throughput broadband. 11 satellites providing terabit-class capacity.',
    country: 'Luxembourg',
  },
  {
    filingId: 'SAT-LOA-2015-0061',
    operator: 'Iridium',
    system: 'Iridium NEXT',
    agency: 'FCC',
    bandName: 'L-band',
    frequencyMin: 1616,
    frequencyMax: 1626,
    orbitType: 'NGSO',
    numberOfSatellites: 66,
    status: 'approved',
    filingDate: filingDate(2015, 8, 12),
    grantDate: filingDate(2016, 1, 15),
    expiryDate: filingDate(2031, 1, 15),
    description: 'Iridium NEXT constellation replacement. 66 operational satellites plus 9 on-orbit spares providing global L-band voice and data services.',
    country: 'USA',
  },
  {
    filingId: 'SAT-MOD-2018-0042',
    operator: 'Globalstar',
    system: 'Globalstar Band n53',
    agency: 'FCC',
    bandName: 'S-band',
    frequencyMin: 2483,
    frequencyMax: 2500,
    orbitType: 'NGSO',
    numberOfSatellites: 24,
    status: 'approved',
    filingDate: filingDate(2018, 4, 20),
    grantDate: filingDate(2020, 11, 10),
    expiryDate: filingDate(2030, 11, 10),
    description: 'Globalstar S-band/L-band authorization including Band n53 terrestrial component for Apple satellite SOS service integration.',
    country: 'USA',
  },
  {
    filingId: 'SAT-LOI-2023-0089',
    operator: 'Lynk Global',
    system: 'Lynk Direct-to-Cell',
    agency: 'FCC',
    bandName: 'L-band',
    frequencyMin: 1710,
    frequencyMax: 1780,
    orbitType: 'NGSO',
    numberOfSatellites: 1000,
    status: 'pending',
    filingDate: filingDate(2023, 6, 15),
    grantDate: null,
    expiryDate: null,
    description: 'Lynk Global direct-to-standard-cell-phone satellite constellation. Spectrum sharing agreements with MNOs for emergency and commercial messaging.',
    country: 'USA',
  },
  {
    filingId: 'SAT-LOI-2020-0087',
    operator: 'Viasat',
    system: 'ViaSat-3',
    agency: 'FCC',
    bandName: 'Ka-band',
    frequencyMin: 28350,
    frequencyMax: 28600,
    orbitType: 'GSO',
    numberOfSatellites: 3,
    status: 'approved',
    filingDate: filingDate(2020, 12, 3),
    grantDate: filingDate(2021, 8, 18),
    expiryDate: filingDate(2036, 8, 18),
    description: 'ViaSat-3 GEO Ka-band ultra-high capacity satellite system. Three satellites providing over 1 Tbps combined capacity for global broadband.',
    country: 'USA',
  },
  {
    filingId: 'SAT-LOI-2021-0095',
    operator: 'EchoStar (Hughes)',
    system: 'Hughes NGSO',
    agency: 'FCC',
    bandName: 'V-band',
    frequencyMin: 37500,
    frequencyMax: 42500,
    orbitType: 'NGSO',
    numberOfSatellites: 1440,
    status: 'pending',
    filingDate: filingDate(2021, 11, 22),
    grantDate: null,
    expiryDate: null,
    description: 'EchoStar/Hughes NGSO constellation filing for V-band LEO broadband service complementing existing Jupiter GEO fleet.',
    country: 'USA',
  },
  {
    filingId: 'SAT-LOI-2022-0104',
    operator: 'Rivada Space Networks',
    system: 'Rivada OuterNET',
    agency: 'FCC',
    bandName: 'Ka-band',
    frequencyMin: 27500,
    frequencyMax: 29100,
    orbitType: 'NGSO',
    numberOfSatellites: 600,
    status: 'pending',
    filingDate: filingDate(2022, 3, 8),
    grantDate: null,
    expiryDate: null,
    description: 'Rivada Space Networks 600-satellite Ka-band constellation with optical inter-satellite links for ultra-low-latency global connectivity.',
    country: 'Germany',
  },
  {
    filingId: 'SAT-LOI-2023-0112',
    operator: 'E-Space',
    system: 'E-Space Constellation',
    agency: 'ITU',
    bandName: 'V-band',
    frequencyMin: 40000,
    frequencyMax: 50000,
    orbitType: 'NGSO',
    numberOfSatellites: 116640,
    status: 'coordinating',
    filingDate: filingDate(2023, 1, 20),
    grantDate: null,
    expiryDate: null,
    description: 'Controversial 100,000+ satellite filing from E-Space via Rwanda ITU filings. Raised concerns about orbital debris, spectrum hoarding, and constellation scale.',
    country: 'Rwanda',
  },
  {
    filingId: 'SAT-MOD-2023-0056',
    operator: 'SpaceX',
    system: 'Starlink Direct-to-Cell',
    agency: 'FCC',
    bandName: 'L-band',
    frequencyMin: 1695,
    frequencyMax: 1780,
    orbitType: 'NGSO',
    numberOfSatellites: 7500,
    status: 'approved',
    filingDate: filingDate(2023, 10, 15),
    grantDate: filingDate(2024, 3, 14),
    expiryDate: filingDate(2033, 3, 14),
    description: 'SpaceX direct-to-cell Starlink service in partnership with T-Mobile. Uses existing cellular PCS bands via supplemental coverage from space (SCS) framework.',
    country: 'USA',
  },
  {
    filingId: 'SAT-LOI-2018-0073',
    operator: 'Planet Labs',
    system: 'PlanetScope',
    agency: 'FCC',
    bandName: 'X-band',
    frequencyMin: 8025,
    frequencyMax: 8400,
    orbitType: 'NGSO',
    numberOfSatellites: 200,
    status: 'approved',
    filingDate: filingDate(2018, 6, 10),
    grantDate: filingDate(2019, 2, 5),
    expiryDate: filingDate(2029, 2, 5),
    description: 'Planet Labs X-band downlink authorization for PlanetScope and SkySat Earth observation constellation data delivery.',
    country: 'USA',
  },
  {
    filingId: 'SAT-LOI-2023-0025',
    operator: 'Eutelsat OneWeb',
    system: 'OneWeb Gen 2',
    agency: 'ITU',
    bandName: 'Ku-band',
    frequencyMin: 10700,
    frequencyMax: 12750,
    orbitType: 'NGSO',
    numberOfSatellites: 2000,
    status: 'coordinating',
    filingDate: filingDate(2023, 4, 12),
    grantDate: null,
    expiryDate: null,
    description: 'Eutelsat OneWeb Gen 2 Ku/Ka-band expansion filing for enhanced broadband capacity post-merger with Eutelsat.',
    country: 'France',
  },
  {
    filingId: 'SAT-LOI-2022-0065',
    operator: 'Intelsat',
    system: 'Intelsat NGSO',
    agency: 'FCC',
    bandName: 'Ka-band',
    frequencyMin: 28350,
    frequencyMax: 29500,
    orbitType: 'NGSO',
    numberOfSatellites: 198,
    status: 'pending',
    filingDate: filingDate(2022, 7, 18),
    grantDate: null,
    expiryDate: null,
    description: 'Intelsat NGSO filing to supplement GEO fleet with LEO overlay constellation for enhanced mobility and latency-sensitive services.',
    country: 'USA',
  },
  {
    filingId: 'SAT-LOI-2022-0091',
    operator: 'Hanwha Systems',
    system: 'Hanwha LEO',
    agency: 'ITU',
    bandName: 'Ka-band',
    frequencyMin: 27500,
    frequencyMax: 29500,
    orbitType: 'NGSO',
    numberOfSatellites: 2000,
    status: 'coordinating',
    filingDate: filingDate(2022, 8, 5),
    grantDate: null,
    expiryDate: null,
    description: 'Hanwha Systems 2,000-satellite Ka-band LEO constellation for broadband and government services in Asia-Pacific.',
    country: 'South Korea',
  },
  {
    filingId: 'SAT-LOI-2021-0043',
    operator: 'Astra Space',
    system: 'Astra Broadband',
    agency: 'FCC',
    bandName: 'V-band',
    frequencyMin: 37500,
    frequencyMax: 42000,
    orbitType: 'NGSO',
    numberOfSatellites: 13620,
    status: 'expired',
    filingDate: filingDate(2021, 5, 14),
    grantDate: null,
    expiryDate: null,
    description: 'Astra Space V-band NGSO constellation filing. Application withdrawn after company pivoted away from launch vehicle development.',
    country: 'USA',
  },
  {
    filingId: 'SAT-LOI-2023-0071',
    operator: 'SpaceX',
    system: 'Starlink Ku-band Expansion',
    agency: 'FCC',
    bandName: 'Ku-band',
    frequencyMin: 10700,
    frequencyMax: 12700,
    orbitType: 'NGSO',
    numberOfSatellites: 7500,
    status: 'approved',
    filingDate: filingDate(2023, 2, 1),
    grantDate: filingDate(2023, 12, 1),
    expiryDate: filingDate(2032, 12, 1),
    description: 'Starlink Gen2 Ku-band downlink expansion authorization supporting user terminal services globally.',
    country: 'USA',
  },
  {
    filingId: 'SAT-LOI-2024-0018',
    operator: 'IRIS2 Consortium',
    system: 'IRIS2 EU Sovereign',
    agency: 'ITU',
    bandName: 'Ka-band',
    frequencyMin: 27500,
    frequencyMax: 30000,
    orbitType: 'NGSO',
    numberOfSatellites: 170,
    status: 'coordinating',
    filingDate: filingDate(2024, 3, 1),
    grantDate: null,
    expiryDate: null,
    description: 'EU IRIS2 sovereign connectivity constellation Ka/Ku-band filings. Multi-orbit system for secure government and commercial broadband services.',
    country: 'Luxembourg',
  },
];

// Initialize spectrum data
export async function initializeSpectrumData() {
  const results = {
    allocationsCreated: 0,
    filingsCreated: 0,
  };

  // Upsert spectrum allocations
  for (const allocationData of SPECTRUM_ALLOCATIONS_SEED) {
    const existing = await prisma.spectrumAllocation.findUnique({
      where: { slug: allocationData.slug },
    });

    if (!existing) {
      await prisma.spectrumAllocation.create({
        data: allocationData,
      });
      results.allocationsCreated++;
    }
  }

  // Upsert spectrum filings
  for (const filingData of SPECTRUM_FILINGS_SEED) {
    const existing = await prisma.spectrumFiling.findUnique({
      where: { filingId: filingData.filingId },
    });

    if (!existing) {
      await prisma.spectrumFiling.create({
        data: filingData,
      });
      results.filingsCreated++;
    }
  }

  return results;
}

// Query functions
export async function getSpectrumAllocations(): Promise<SpectrumAllocation[]> {
  const allocations = await prisma.spectrumAllocation.findMany({
    select: {
      id: true,
      slug: true,
      bandName: true,
      frequencyMin: true,
      frequencyMax: true,
      bandwidth: true,
      service: true,
      region: true,
      allocationType: true,
      assignedTo: true,
      filingStatus: true,
      numberOfFilings: true,
      ituReference: true,
      fccReference: true,
      coordinationRequired: true,
      description: true,
    },
    orderBy: { frequencyMin: 'asc' },
  });

  return allocations.map(a => ({
    ...a,
    service: a.service as SpectrumService,
    filingStatus: a.filingStatus as SpectrumFilingStatus,
  }));
}

export async function getSpectrumFilings(options?: {
  bandName?: string;
  status?: string;
  operator?: string;
}): Promise<SpectrumFiling[]> {
  const where: Record<string, unknown> = {};

  if (options?.bandName) {
    where.bandName = options.bandName;
  }
  if (options?.status) {
    where.status = options.status;
  }
  if (options?.operator) {
    where.operator = { contains: options.operator };
  }

  const filings = await prisma.spectrumFiling.findMany({
    where,
    select: {
      id: true,
      filingId: true,
      operator: true,
      system: true,
      agency: true,
      bandName: true,
      frequencyMin: true,
      frequencyMax: true,
      orbitType: true,
      numberOfSatellites: true,
      status: true,
      filingDate: true,
      grantDate: true,
      expiryDate: true,
      description: true,
      country: true,
    },
    orderBy: { filingDate: 'desc' },
  });

  return filings as SpectrumFiling[];
}

export async function getSpectrumStats() {
  const allocations = await prisma.spectrumAllocation.findMany({
    select: {
      bandName: true,
      filingStatus: true,
      numberOfFilings: true,
    },
  });
  const filings = await prisma.spectrumFiling.findMany({
    select: { status: true },
  });

  const totalBands = allocations.length;
  const congestedBands = allocations.filter(a => a.filingStatus === 'congested').length;
  const totalFilings = filings.length;
  const pendingFilings = filings.filter(f => f.status === 'pending').length;

  // Find the band with the most filings
  const topBand = allocations.reduce(
    (top, a) => (a.numberOfFilings > (top?.numberOfFilings ?? 0) ? a : top),
    allocations[0],
  );

  return {
    totalBands,
    congestedBands,
    totalFilings,
    pendingFilings,
    topBand: topBand
      ? {
          bandName: topBand.bandName,
          filingStatus: topBand.filingStatus as SpectrumFilingStatus,
          numberOfFilings: topBand.numberOfFilings,
        }
      : null,
  };
}
