import {
  SupplyChainCompany,
  SupplyRelationship,
  SupplyShortage,
  SupplyChainTier,
  SupplyCriticality,
  GeopoliticalRisk,
  ShortageSeverity,
} from '@/types';

// ============================================================
// Aerospace Supply Chain Companies (30-40 entries)
// ============================================================

export const SUPPLY_CHAIN_COMPANIES: SupplyChainCompany[] = [
  // Prime Contractors
  {
    id: 'spacex',
    slug: 'spacex',
    name: 'SpaceX',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['launch_vehicles', 'spacecraft', 'satellites', 'propulsion'],
    customers: ['nasa', 'dod', 'commercial'],
    suppliers: ['aerojet-rocketdyne', 'moog', 'honeywell', 'te-connectivity'],
    criticality: 'high',
    description: 'Leading launch provider and satellite manufacturer',
    headquarters: 'Hawthorne, CA',
    employeeCount: 13000,
  },
  {
    id: 'boeing',
    slug: 'boeing',
    name: 'Boeing Defense, Space & Security',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['spacecraft', 'satellites', 'launch_vehicles', 'space_station_modules'],
    customers: ['nasa', 'dod', 'commercial'],
    suppliers: ['aerojet-rocketdyne', 'l3harris', 'ball-aerospace', 'honeywell'],
    criticality: 'high',
    description: 'Major aerospace and defense prime contractor',
    headquarters: 'Arlington, VA',
    employeeCount: 140000,
  },
  {
    id: 'lockheed-martin',
    slug: 'lockheed-martin',
    name: 'Lockheed Martin Space',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['spacecraft', 'satellites', 'missiles', 'space_systems'],
    customers: ['nasa', 'dod', 'nro'],
    suppliers: ['aerojet-rocketdyne', 'l3harris', 'northrop-grumman', 'honeywell'],
    criticality: 'high',
    description: 'Premier space systems integrator',
    headquarters: 'Bethesda, MD',
    employeeCount: 116000,
  },
  {
    id: 'northrop-grumman',
    slug: 'northrop-grumman',
    name: 'Northrop Grumman Space Systems',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['satellites', 'launch_vehicles', 'propulsion', 'space_logistics'],
    customers: ['nasa', 'dod', 'commercial'],
    suppliers: ['aerojet-rocketdyne', 'moog', 'te-connectivity'],
    criticality: 'high',
    description: 'Space systems and solid rocket motor manufacturer',
    headquarters: 'Falls Church, VA',
    employeeCount: 90000,
  },
  {
    id: 'airbus-defence-space',
    slug: 'airbus-defence-space',
    name: 'Airbus Defence and Space',
    tier: 'prime',
    country: 'Europe',
    countryCode: 'EUR',
    products: ['satellites', 'launch_vehicles', 'space_systems', 'earth_observation'],
    customers: ['esa', 'commercial', 'european_governments'],
    suppliers: ['arianegroup', 'thales-alenia', 'safran'],
    criticality: 'high',
    description: 'European space systems prime contractor',
    headquarters: 'Leiden, Netherlands',
    employeeCount: 35000,
  },
  {
    id: 'ula',
    slug: 'ula',
    name: 'United Launch Alliance',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['launch_vehicles', 'propulsion_systems'],
    customers: ['nasa', 'dod', 'nro'],
    suppliers: ['aerojet-rocketdyne', 'blue-origin', 'moog'],
    criticality: 'high',
    description: 'Premier US government launch provider',
    headquarters: 'Centennial, CO',
    employeeCount: 3000,
  },
  {
    id: 'rocket-lab',
    slug: 'rocket-lab',
    name: 'Rocket Lab',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['launch_vehicles', 'spacecraft', 'space_systems'],
    customers: ['nasa', 'dod', 'commercial'],
    suppliers: ['rutherford-internal', 'maxar', 'sinclair-interplanetary'],
    criticality: 'medium',
    description: 'Small launch and space systems provider',
    headquarters: 'Long Beach, CA',
    employeeCount: 1800,
  },
  {
    id: 'blue-origin',
    slug: 'blue-origin',
    name: 'Blue Origin',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['launch_vehicles', 'propulsion', 'lunar_landers'],
    customers: ['nasa', 'ula', 'commercial'],
    suppliers: ['honeywell', 'moog', 'parker-hannifin'],
    criticality: 'medium',
    description: 'Vertical integration launch and propulsion company',
    headquarters: 'Kent, WA',
    employeeCount: 11000,
  },

  // Tier 1 Suppliers
  {
    id: 'aerojet-rocketdyne',
    slug: 'aerojet-rocketdyne',
    name: 'Aerojet Rocketdyne',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['rocket_engines', 'propulsion_systems', 'thrusters'],
    customers: ['spacex', 'boeing', 'lockheed-martin', 'northrop-grumman', 'ula'],
    suppliers: ['specialty-metals-inc', 'honeywell', 'moog'],
    criticality: 'high',
    description: 'Premier rocket propulsion manufacturer',
    headquarters: 'El Segundo, CA',
    employeeCount: 5000,
  },
  {
    id: 'l3harris',
    slug: 'l3harris',
    name: 'L3Harris Technologies',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['avionics', 'communication_systems', 'sensors', 'electronics'],
    customers: ['boeing', 'lockheed-martin', 'northrop-grumman', 'nasa'],
    suppliers: ['analog-devices', 'texas-instruments', 'xilinx'],
    criticality: 'high',
    description: 'Defense electronics and communication systems',
    headquarters: 'Melbourne, FL',
    employeeCount: 50000,
  },
  {
    id: 'ball-aerospace',
    slug: 'ball-aerospace',
    name: 'Ball Aerospace',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['spacecraft', 'instruments', 'sensors', 'antennas'],
    customers: ['nasa', 'boeing', 'lockheed-martin'],
    suppliers: ['honeywell', 'analog-devices', 'corning'],
    criticality: 'high',
    description: 'Space instruments and spacecraft manufacturer',
    headquarters: 'Boulder, CO',
    employeeCount: 5500,
  },
  {
    id: 'maxar',
    slug: 'maxar',
    name: 'Maxar Technologies',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['satellites', 'spacecraft_buses', 'robotics', 'earth_observation'],
    customers: ['nasa', 'commercial', 'government'],
    suppliers: ['honeywell', 'moog', 'cobham'],
    criticality: 'high',
    description: 'Satellite manufacturer and Earth observation provider',
    headquarters: 'Westminster, CO',
    employeeCount: 4500,
  },
  {
    id: 'honeywell-aerospace',
    slug: 'honeywell-aerospace',
    name: 'Honeywell Aerospace',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['avionics', 'guidance_systems', 'sensors', 'actuators'],
    customers: ['spacex', 'boeing', 'lockheed-martin', 'blue-origin'],
    suppliers: ['analog-devices', 'texas-instruments', 'specialty-materials'],
    criticality: 'high',
    description: 'Aerospace avionics and systems provider',
    headquarters: 'Phoenix, AZ',
    employeeCount: 40000,
  },
  {
    id: 'moog',
    slug: 'moog',
    name: 'Moog Inc.',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['actuators', 'valves', 'propulsion_components', 'flight_controls'],
    customers: ['spacex', 'boeing', 'northrop-grumman', 'ula', 'aerojet-rocketdyne'],
    suppliers: ['specialty-metals', 'parker-hannifin', 'te-connectivity'],
    criticality: 'high',
    description: 'Precision motion control components',
    headquarters: 'East Aurora, NY',
    employeeCount: 13000,
  },
  {
    id: 'thales-alenia',
    slug: 'thales-alenia',
    name: 'Thales Alenia Space',
    tier: 'tier1',
    country: 'France',
    countryCode: 'FRA',
    products: ['satellites', 'space_systems', 'communication_payloads'],
    customers: ['airbus-defence-space', 'esa', 'commercial'],
    suppliers: ['safran', 'stmicroelectronics', 'sodern'],
    criticality: 'high',
    description: 'European satellite systems manufacturer',
    headquarters: 'Cannes, France',
    employeeCount: 8500,
  },
  {
    id: 'arianegroup',
    slug: 'arianegroup',
    name: 'ArianeGroup',
    tier: 'tier1',
    country: 'France',
    countryCode: 'FRA',
    products: ['launch_vehicles', 'propulsion_systems', 'solid_motors'],
    customers: ['airbus-defence-space', 'esa'],
    suppliers: ['safran', 'mt-aerospace', 'avio'],
    criticality: 'high',
    description: 'European launch vehicle manufacturer',
    headquarters: 'Paris, France',
    employeeCount: 9000,
  },
  {
    id: 'safran',
    slug: 'safran',
    name: 'Safran',
    tier: 'tier1',
    country: 'France',
    countryCode: 'FRA',
    products: ['propulsion', 'navigation_systems', 'optronics'],
    customers: ['arianegroup', 'thales-alenia', 'airbus-defence-space'],
    suppliers: ['stmicroelectronics', 'specialty-metals-eu'],
    criticality: 'high',
    description: 'French aerospace propulsion and systems',
    headquarters: 'Paris, France',
    employeeCount: 83000,
  },

  // Tier 2 Suppliers
  {
    id: 'te-connectivity',
    slug: 'te-connectivity',
    name: 'TE Connectivity',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['connectors', 'sensors', 'wiring_harnesses'],
    customers: ['spacex', 'boeing', 'northrop-grumman', 'honeywell'],
    suppliers: ['copper-suppliers', 'polymer-suppliers'],
    criticality: 'medium',
    description: 'Electronic connectors and sensors',
    headquarters: 'Schaffhausen, Switzerland',
    employeeCount: 85000,
  },
  {
    id: 'analog-devices',
    slug: 'analog-devices',
    name: 'Analog Devices',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['semiconductors', 'signal_processing', 'power_management'],
    customers: ['l3harris', 'honeywell', 'ball-aerospace'],
    suppliers: ['tsmc', 'globalfoundries'],
    criticality: 'high',
    description: 'High-performance semiconductors',
    headquarters: 'Wilmington, MA',
    employeeCount: 24000,
  },
  {
    id: 'texas-instruments',
    slug: 'texas-instruments',
    name: 'Texas Instruments',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['semiconductors', 'analog_chips', 'embedded_processors'],
    customers: ['l3harris', 'honeywell', 'raytheon'],
    suppliers: ['internal-fabs', 'specialty-materials'],
    criticality: 'medium',
    description: 'Semiconductor manufacturer',
    headquarters: 'Dallas, TX',
    employeeCount: 30000,
  },
  {
    id: 'parker-hannifin',
    slug: 'parker-hannifin',
    name: 'Parker Hannifin',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['hydraulics', 'seals', 'fluid_systems', 'thermal_management'],
    customers: ['blue-origin', 'moog', 'aerojet-rocketdyne'],
    suppliers: ['specialty-polymers', 'metal-suppliers'],
    criticality: 'medium',
    description: 'Motion and control technologies',
    headquarters: 'Cleveland, OH',
    employeeCount: 58000,
  },
  {
    id: 'curtiss-wright',
    slug: 'curtiss-wright',
    name: 'Curtiss-Wright',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['electronics', 'actuation_systems', 'sensors'],
    customers: ['boeing', 'lockheed-martin', 'general-dynamics'],
    suppliers: ['semiconductor-suppliers', 'metal-suppliers'],
    criticality: 'medium',
    description: 'Defense and aerospace systems',
    headquarters: 'Davidson, NC',
    employeeCount: 8500,
  },
  {
    id: 'cobham-advanced',
    slug: 'cobham-advanced',
    name: 'Cobham Advanced Electronic Solutions',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['rf_components', 'microwave_devices', 'space_electronics'],
    customers: ['maxar', 'l3harris', 'northrop-grumman'],
    suppliers: ['specialty-semiconductors', 'rare-earth-suppliers'],
    criticality: 'medium',
    description: 'Space-qualified electronic components',
    headquarters: 'Lowell, MA',
    employeeCount: 3500,
  },
  {
    id: 'stmicroelectronics',
    slug: 'stmicroelectronics',
    name: 'STMicroelectronics',
    tier: 'tier2',
    country: 'Europe',
    countryCode: 'EUR',
    products: ['semiconductors', 'mems', 'power_devices'],
    customers: ['thales-alenia', 'safran', 'airbus-defence-space'],
    suppliers: ['global-wafer', 'specialty-materials'],
    criticality: 'medium',
    description: 'European semiconductor manufacturer',
    headquarters: 'Geneva, Switzerland',
    employeeCount: 50000,
  },

  // Tier 3 Suppliers (Critical Materials)
  {
    id: 'mp-materials',
    slug: 'mp-materials',
    name: 'MP Materials',
    tier: 'tier3',
    country: 'United States',
    countryCode: 'USA',
    products: ['rare_earth_elements', 'neodymium', 'praseodymium'],
    customers: ['honeywell', 'general-motors', 'defense-contractors'],
    suppliers: ['mining-operations'],
    criticality: 'high',
    description: 'Only US rare earth mine and processor',
    headquarters: 'Las Vegas, NV',
    employeeCount: 500,
  },
  {
    id: 'lynas-rare-earths',
    slug: 'lynas-rare-earths',
    name: 'Lynas Rare Earths',
    tier: 'tier3',
    country: 'Australia',
    countryCode: 'AUS',
    products: ['rare_earth_elements', 'neodymium', 'praseodymium', 'dysprosium'],
    customers: ['western-defense-contractors', 'electronics-manufacturers'],
    suppliers: ['mining-operations'],
    criticality: 'high',
    description: 'Non-China rare earth producer',
    headquarters: 'Perth, Australia',
    employeeCount: 1000,
  },
  {
    id: 'china-northern-rare-earth',
    slug: 'china-northern-rare-earth',
    name: 'China Northern Rare Earth',
    tier: 'tier3',
    country: 'China',
    countryCode: 'CHN',
    products: ['rare_earth_elements', 'all_17_ree'],
    customers: ['global-manufacturers'],
    suppliers: ['bayan-obo-mine'],
    criticality: 'high',
    description: 'World largest rare earth producer (60% global)',
    headquarters: 'Baotou, Inner Mongolia',
    employeeCount: 25000,
  },
  {
    id: 'ati-specialty',
    slug: 'ati-specialty',
    name: 'ATI Specialty Materials',
    tier: 'tier3',
    country: 'United States',
    countryCode: 'USA',
    products: ['titanium', 'nickel_alloys', 'specialty_steels'],
    customers: ['boeing', 'aerojet-rocketdyne', 'pratt-whitney'],
    suppliers: ['titanium-sponge-suppliers', 'nickel-suppliers'],
    criticality: 'high',
    description: 'Specialty metals for aerospace',
    headquarters: 'Pittsburgh, PA',
    employeeCount: 7000,
  },
  {
    id: 'materion',
    slug: 'materion',
    name: 'Materion Corporation',
    tier: 'tier3',
    country: 'United States',
    countryCode: 'USA',
    products: ['beryllium', 'precision_alloys', 'advanced_materials'],
    customers: ['boeing', 'lockheed-martin', 'defense-contractors'],
    suppliers: ['beryllium-mining', 'alloy-suppliers'],
    criticality: 'high',
    description: 'Only Western beryllium producer',
    headquarters: 'Mayfield Heights, OH',
    employeeCount: 2500,
  },
  {
    id: 'vsmpo-avisma',
    slug: 'vsmpo-avisma',
    name: 'VSMPO-AVISMA',
    tier: 'tier3',
    country: 'Russia',
    countryCode: 'RUS',
    products: ['titanium', 'titanium_alloys'],
    customers: ['boeing', 'airbus', 'embraer'],
    suppliers: ['russian-titanium-mines'],
    criticality: 'high',
    description: 'World largest titanium producer (sanctioned)',
    headquarters: 'Verkhnaya Salda, Russia',
    employeeCount: 20000,
  },
  {
    id: 'tsmc',
    slug: 'tsmc',
    name: 'Taiwan Semiconductor Manufacturing Company',
    tier: 'tier3',
    country: 'Taiwan',
    countryCode: 'TWN',
    products: ['semiconductors', 'advanced_nodes', 'space_grade_chips'],
    customers: ['analog-devices', 'nvidia', 'qualcomm', 'defense-contractors'],
    suppliers: ['asml', 'applied-materials', 'lam-research'],
    criticality: 'high',
    description: 'World leading advanced semiconductor fab',
    headquarters: 'Hsinchu, Taiwan',
    employeeCount: 65000,
  },
  {
    id: 'samsung-foundry',
    slug: 'samsung-foundry',
    name: 'Samsung Foundry',
    tier: 'tier3',
    country: 'South Korea',
    countryCode: 'KOR',
    products: ['semiconductors', 'memory', 'logic_chips'],
    customers: ['qualcomm', 'nvidia', 'defense-customers'],
    suppliers: ['asml', 'applied-materials'],
    criticality: 'high',
    description: 'Major semiconductor foundry',
    headquarters: 'Hwaseong, South Korea',
    employeeCount: 110000,
  },
  {
    id: 'smic',
    slug: 'smic',
    name: 'Semiconductor Manufacturing International Corporation',
    tier: 'tier3',
    country: 'China',
    countryCode: 'CHN',
    products: ['semiconductors', 'mature_nodes'],
    customers: ['chinese-manufacturers', 'huawei'],
    suppliers: ['chinese-equipment'],
    criticality: 'medium',
    description: 'China largest chip foundry (restricted)',
    headquarters: 'Shanghai, China',
    employeeCount: 19000,
  },
  {
    id: 'glencore-cobalt',
    slug: 'glencore-cobalt',
    name: 'Glencore (Cobalt Division)',
    tier: 'tier3',
    country: 'DR Congo',
    countryCode: 'COD',
    products: ['cobalt', 'copper'],
    customers: ['battery-manufacturers', 'alloy-producers'],
    suppliers: ['drc-mining'],
    criticality: 'high',
    description: 'Major cobalt supplier (70% global from DRC)',
    headquarters: 'Baar, Switzerland',
    employeeCount: 135000,
  },
  {
    id: 'sqm-lithium',
    slug: 'sqm-lithium',
    name: 'SQM (Sociedad Quimica y Minera)',
    tier: 'tier3',
    country: 'Chile',
    countryCode: 'CHL',
    products: ['lithium', 'potassium', 'iodine'],
    customers: ['battery-manufacturers', 'aerospace'],
    suppliers: ['atacama-salt-flats'],
    criticality: 'medium',
    description: 'Major lithium producer',
    headquarters: 'Santiago, Chile',
    employeeCount: 16000,
  },
];

// ============================================================
// Supply Relationships
// ============================================================

export const SUPPLY_RELATIONSHIPS: SupplyRelationship[] = [
  // SpaceX relationships
  {
    id: 'rel-1',
    supplierId: 'aerojet-rocketdyne',
    supplierName: 'Aerojet Rocketdyne',
    customerId: 'spacex',
    customerName: 'SpaceX',
    products: ['thrusters', 'attitude_control'],
    annualValue: 50000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  {
    id: 'rel-2',
    supplierId: 'honeywell-aerospace',
    supplierName: 'Honeywell Aerospace',
    customerId: 'spacex',
    customerName: 'SpaceX',
    products: ['avionics', 'sensors'],
    annualValue: 30000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  // Boeing relationships
  {
    id: 'rel-3',
    supplierId: 'aerojet-rocketdyne',
    supplierName: 'Aerojet Rocketdyne',
    customerId: 'boeing',
    customerName: 'Boeing',
    products: ['rs-25_engines', 'propulsion_systems'],
    annualValue: 200000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  {
    id: 'rel-4',
    supplierId: 'l3harris',
    supplierName: 'L3Harris Technologies',
    customerId: 'boeing',
    customerName: 'Boeing',
    products: ['communication_systems', 'sensors'],
    annualValue: 150000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  // Critical material dependencies
  {
    id: 'rel-5',
    supplierId: 'china-northern-rare-earth',
    supplierName: 'China Northern Rare Earth',
    customerId: 'honeywell-aerospace',
    customerName: 'Honeywell Aerospace',
    products: ['rare_earth_magnets', 'neodymium'],
    annualValue: 20000000,
    geopoliticalRisk: 'high',
    isCritical: true,
    notes: 'Critical dependency on Chinese rare earths',
  },
  {
    id: 'rel-6',
    supplierId: 'tsmc',
    supplierName: 'TSMC',
    customerId: 'analog-devices',
    customerName: 'Analog Devices',
    products: ['advanced_semiconductors'],
    annualValue: 100000000,
    geopoliticalRisk: 'medium',
    isCritical: true,
    notes: 'Taiwan geopolitical risk',
  },
  {
    id: 'rel-7',
    supplierId: 'vsmpo-avisma',
    supplierName: 'VSMPO-AVISMA',
    customerId: 'boeing',
    customerName: 'Boeing',
    products: ['titanium_forgings'],
    annualValue: 300000000,
    geopoliticalRisk: 'high',
    isCritical: true,
    notes: 'Russian titanium - seeking alternatives post-sanctions',
  },
  // European supply chain
  {
    id: 'rel-8',
    supplierId: 'arianegroup',
    supplierName: 'ArianeGroup',
    customerId: 'airbus-defence-space',
    customerName: 'Airbus Defence and Space',
    products: ['ariane_stages', 'propulsion'],
    annualValue: 500000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  {
    id: 'rel-9',
    supplierId: 'safran',
    supplierName: 'Safran',
    customerId: 'arianegroup',
    customerName: 'ArianeGroup',
    products: ['vulcain_engine_components'],
    annualValue: 200000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  // Material supply chains
  {
    id: 'rel-10',
    supplierId: 'materion',
    supplierName: 'Materion Corporation',
    customerId: 'lockheed-martin',
    customerName: 'Lockheed Martin',
    products: ['beryllium_structures'],
    annualValue: 50000000,
    geopoliticalRisk: 'none',
    isCritical: true,
    notes: 'Sole Western supplier of aerospace-grade beryllium',
  },
  {
    id: 'rel-11',
    supplierId: 'ati-specialty',
    supplierName: 'ATI Specialty Materials',
    customerId: 'aerojet-rocketdyne',
    customerName: 'Aerojet Rocketdyne',
    products: ['nickel_superalloys', 'titanium'],
    annualValue: 80000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  {
    id: 'rel-12',
    supplierId: 'glencore-cobalt',
    supplierName: 'Glencore (Cobalt)',
    customerId: 'ati-specialty',
    customerName: 'ATI Specialty Materials',
    products: ['cobalt_for_superalloys'],
    annualValue: 30000000,
    geopoliticalRisk: 'high',
    isCritical: true,
    notes: 'DRC cobalt supply concerns',
  },
];

// ============================================================
// Supply Shortages and Risk Alerts
// ============================================================

export const SUPPLY_SHORTAGES: SupplyShortage[] = [
  {
    id: 'shortage-1',
    material: 'Radiation-Hardened Semiconductors',
    category: 'semiconductors',
    affectedProducts: ['satellite_avionics', 'deep_space_electronics', 'missile_guidance'],
    severity: 'critical',
    alternativeSuppliers: ['cobham-advanced', 'bae-systems-rad-hard'],
    notes: 'Limited global capacity for rad-hard chips. Lead times 18-24 months.',
    estimatedResolution: '2027',
    impactedCompanies: ['lockheed-martin', 'northrop-grumman', 'boeing', 'ball-aerospace'],
    geopoliticalFactors: ['US_CHIPS_Act', 'Defense_Priority'],
  },
  {
    id: 'shortage-2',
    material: 'Rare Earth Elements (Heavy)',
    category: 'rare_earth',
    affectedProducts: ['permanent_magnets', 'guidance_systems', 'electric_propulsion'],
    severity: 'critical',
    alternativeSuppliers: ['lynas-rare-earths', 'mp-materials'],
    notes: 'China controls 90%+ of heavy rare earth processing. Critical for defense.',
    estimatedResolution: '2028+',
    impactedCompanies: ['honeywell-aerospace', 'l3harris', 'general-dynamics'],
    geopoliticalFactors: ['China_Export_Controls', 'US_Stockpile_Efforts'],
  },
  {
    id: 'shortage-3',
    material: 'Aerospace-Grade Titanium',
    category: 'specialty_metals',
    affectedProducts: ['rocket_structures', 'satellite_frames', 'engine_components'],
    severity: 'high',
    alternativeSuppliers: ['ati-specialty', 'timet', 'kobe-steel'],
    notes: 'Russian sanctions impacted 30% of global aerospace titanium. Supply diversifying.',
    estimatedResolution: '2026',
    impactedCompanies: ['boeing', 'airbus-defence-space', 'spacex'],
    geopoliticalFactors: ['Russia_Sanctions', 'Supply_Diversification'],
  },
  {
    id: 'shortage-4',
    material: 'Beryllium',
    category: 'specialty_metals',
    affectedProducts: ['satellite_structures', 'optical_mounts', 'heat_shields'],
    severity: 'high',
    alternativeSuppliers: ['materion'],
    notes: 'Single Western supplier (Materion). Critical for James Webb-class optics.',
    estimatedResolution: 'Ongoing',
    impactedCompanies: ['ball-aerospace', 'lockheed-martin', 'boeing'],
    geopoliticalFactors: ['Single_Source_Risk', 'Strategic_Stockpile'],
  },
  {
    id: 'shortage-5',
    material: 'Space-Grade Solar Cells',
    category: 'power',
    affectedProducts: ['satellite_power', 'space_station_arrays', 'lunar_systems'],
    severity: 'medium',
    alternativeSuppliers: ['spectrolab', 'solaero', 'azur-space'],
    notes: 'High efficiency III-V cells in short supply. New capacity coming online.',
    estimatedResolution: '2025',
    impactedCompanies: ['maxar', 'northrop-grumman', 'lockheed-martin'],
  },
  {
    id: 'shortage-6',
    material: 'Gallium',
    category: 'semiconductors',
    affectedProducts: ['rf_components', 'power_electronics', 'led_systems'],
    severity: 'high',
    alternativeSuppliers: ['limited_non_china'],
    notes: 'China controls 80% of gallium. Export restrictions announced 2023.',
    estimatedResolution: '2027',
    impactedCompanies: ['l3harris', 'analog-devices', 'raytheon'],
    geopoliticalFactors: ['China_Export_Ban', 'Strategic_Material'],
  },
  {
    id: 'shortage-7',
    material: 'Cobalt',
    category: 'specialty_metals',
    affectedProducts: ['superalloys', 'batteries', 'high_temp_components'],
    severity: 'medium',
    alternativeSuppliers: ['glencore-cobalt', 'australian-mines'],
    notes: '70% from DRC with ethical and supply concerns. Recycling increasing.',
    estimatedResolution: '2026',
    impactedCompanies: ['aerojet-rocketdyne', 'pratt-whitney', 'ge-aerospace'],
    geopoliticalFactors: ['DRC_Instability', 'ESG_Concerns'],
  },
  {
    id: 'shortage-8',
    material: 'Advanced Composites (CFRP)',
    category: 'structures',
    affectedProducts: ['rocket_fairings', 'satellite_structures', 'pressure_vessels'],
    severity: 'medium',
    alternativeSuppliers: ['toray', 'hexcel', 'sgl-carbon'],
    notes: 'Aerospace carbon fiber demand exceeding supply. New capacity ramping.',
    estimatedResolution: '2025',
    impactedCompanies: ['spacex', 'rocket-lab', 'boeing'],
  },
  {
    id: 'shortage-9',
    material: 'Tantalum Capacitors',
    category: 'avionics',
    affectedProducts: ['electronics', 'power_systems', 'filters'],
    severity: 'medium',
    alternativeSuppliers: ['kemet', 'vishay', 'avx'],
    notes: 'Space-grade tantalum capacitors in tight supply. Lead times extended.',
    estimatedResolution: '2025',
    impactedCompanies: ['l3harris', 'honeywell-aerospace', 'collins-aerospace'],
    geopoliticalFactors: ['DRC_Tantalum_Mining'],
  },
  {
    id: 'shortage-10',
    material: 'Hydrazine',
    category: 'propulsion',
    affectedProducts: ['satellite_propulsion', 'attitude_control', 'spacecraft_thrusters'],
    severity: 'low',
    alternativeSuppliers: ['arch-chemicals', 'lonza'],
    notes: 'Limited production capacity. Green propellant alternatives emerging.',
    estimatedResolution: '2025',
    impactedCompanies: ['maxar', 'lockheed-martin', 'ball-aerospace'],
  },
  {
    id: 'shortage-11',
    material: 'Germanium',
    category: 'sensors',
    affectedProducts: ['infrared_optics', 'fiber_optics', 'solar_cells'],
    severity: 'high',
    alternativeSuppliers: ['limited_non_china'],
    notes: 'China export restrictions on germanium effective Aug 2023.',
    estimatedResolution: '2027',
    impactedCompanies: ['ball-aerospace', 'l3harris', 'raytheon'],
    geopoliticalFactors: ['China_Export_Ban'],
  },
  {
    id: 'shortage-12',
    material: 'Rocket-Grade Aluminum Alloys',
    category: 'structures',
    affectedProducts: ['rocket_tanks', 'spacecraft_structures'],
    severity: 'low',
    alternativeSuppliers: ['arconic', 'constellium', 'aleris'],
    notes: 'Supply adequate but lead times extended for large forgings.',
    estimatedResolution: '2025',
    impactedCompanies: ['spacex', 'ula', 'blue-origin'],
  },
];

// ============================================================
// Helper Functions
// ============================================================

export function getCompanyById(id: string): SupplyChainCompany | undefined {
  return SUPPLY_CHAIN_COMPANIES.find((c) => c.id === id);
}

export function getCompaniesByTier(tier: SupplyChainTier): SupplyChainCompany[] {
  return SUPPLY_CHAIN_COMPANIES.filter((c) => c.tier === tier);
}

export function getCompaniesByCountry(countryCode: string): SupplyChainCompany[] {
  return SUPPLY_CHAIN_COMPANIES.filter((c) => c.countryCode === countryCode);
}

export function getCompanySuppliers(companyId: string): SupplyChainCompany[] {
  const company = getCompanyById(companyId);
  if (!company) return [];
  return company.suppliers
    .map((s) => SUPPLY_CHAIN_COMPANIES.find((c) => c.id === s))
    .filter((c): c is SupplyChainCompany => c !== undefined);
}

export function getCompanyCustomers(companyId: string): SupplyChainCompany[] {
  const company = getCompanyById(companyId);
  if (!company) return [];
  return company.customers
    .map((c) => SUPPLY_CHAIN_COMPANIES.find((co) => co.id === c))
    .filter((c): c is SupplyChainCompany => c !== undefined);
}

export function getRelationshipsForCompany(companyId: string): SupplyRelationship[] {
  return SUPPLY_RELATIONSHIPS.filter(
    (r) => r.supplierId === companyId || r.customerId === companyId
  );
}

export function getHighRiskRelationships(): SupplyRelationship[] {
  return SUPPLY_RELATIONSHIPS.filter((r) => r.geopoliticalRisk === 'high');
}

export function getShortagesByCategory(category: string): SupplyShortage[] {
  return SUPPLY_SHORTAGES.filter((s) => s.category === category);
}

export function getCriticalShortages(): SupplyShortage[] {
  return SUPPLY_SHORTAGES.filter((s) => s.severity === 'critical');
}

export function getSupplyChainStats() {
  const companies = SUPPLY_CHAIN_COMPANIES;
  const relationships = SUPPLY_RELATIONSHIPS;
  const shortages = SUPPLY_SHORTAGES;

  return {
    totalCompanies: companies.length,
    primeContractors: companies.filter((c) => c.tier === 'prime').length,
    tier1Suppliers: companies.filter((c) => c.tier === 'tier1').length,
    tier2Suppliers: companies.filter((c) => c.tier === 'tier2').length,
    tier3Suppliers: companies.filter((c) => c.tier === 'tier3').length,
    totalRelationships: relationships.length,
    highRiskRelationships: relationships.filter((r) => r.geopoliticalRisk === 'high').length,
    criticalRelationships: relationships.filter((r) => r.isCritical).length,
    totalShortages: shortages.length,
    criticalShortages: shortages.filter((s) => s.severity === 'critical').length,
    highSeverityShortages: shortages.filter((s) => s.severity === 'high').length,
    countriesWithHighRisk: ['CHN', 'RUS', 'COD'],
    usCompanies: companies.filter((c) => c.countryCode === 'USA').length,
    europeanCompanies: companies.filter((c) => ['EUR', 'FRA', 'DEU', 'GBR'].includes(c.countryCode)).length,
  };
}
