import {
  SupplyChainCompany,
  SupplyRelationship,
  SupplyShortage,
  SupplyChainTier,
  SupplyCriticality,
  GeopoliticalRisk,
  ShortageSeverity,
} from '@/types';

// ============================================================
// Aerospace Supply Chain Companies (30-40 entries)
// ============================================================

export const SUPPLY_CHAIN_COMPANIES: SupplyChainCompany[] = [
  // Prime Contractors
  {
    id: 'spacex',
    slug: 'spacex',
    name: 'SpaceX',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['launch_vehicles', 'spacecraft', 'satellites', 'propulsion'],
    customers: ['nasa', 'dod', 'commercial'],
    suppliers: ['aerojet-rocketdyne', 'moog', 'honeywell', 'te-connectivity'],
    criticality: 'high',
    description: 'Leading launch provider and satellite manufacturer',
    headquarters: 'Hawthorne, CA',
    employeeCount: 13000,
  },
  {
    id: 'boeing',
    slug: 'boeing',
    name: 'Boeing Defense, Space & Security',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['spacecraft', 'satellites', 'launch_vehicles', 'space_station_modules'],
    customers: ['nasa', 'dod', 'commercial'],
    suppliers: ['aerojet-rocketdyne', 'l3harris', 'ball-aerospace', 'honeywell'],
    criticality: 'high',
    description: 'Major aerospace and defense prime contractor',
    headquarters: 'Arlington, VA',
    employeeCount: 140000,
  },
  {
    id: 'lockheed-martin',
    slug: 'lockheed-martin',
    name: 'Lockheed Martin Space',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['spacecraft', 'satellites', 'missiles', 'space_systems'],
    customers: ['nasa', 'dod', 'nro'],
    suppliers: ['aerojet-rocketdyne', 'l3harris', 'northrop-grumman', 'honeywell'],
    criticality: 'high',
    description: 'Premier space systems integrator',
    headquarters: 'Bethesda, MD',
    employeeCount: 116000,
  },
  {
    id: 'northrop-grumman',
    slug: 'northrop-grumman',
    name: 'Northrop Grumman Space Systems',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['satellites', 'launch_vehicles', 'propulsion', 'space_logistics'],
    customers: ['nasa', 'dod', 'commercial'],
    suppliers: ['aerojet-rocketdyne', 'moog', 'te-connectivity'],
    criticality: 'high',
    description: 'Space systems and solid rocket motor manufacturer',
    headquarters: 'Falls Church, VA',
    employeeCount: 90000,
  },
  {
    id: 'airbus-defence-space',
    slug: 'airbus-defence-space',
    name: 'Airbus Defence and Space',
    tier: 'prime',
    country: 'Europe',
    countryCode: 'EUR',
    products: ['satellites', 'launch_vehicles', 'space_systems', 'earth_observation'],
    customers: ['esa', 'commercial', 'european_governments'],
    suppliers: ['arianegroup', 'thales-alenia', 'safran'],
    criticality: 'high',
    description: 'European space systems prime contractor',
    headquarters: 'Leiden, Netherlands',
    employeeCount: 35000,
  },
  {
    id: 'ula',
    slug: 'ula',
    name: 'United Launch Alliance',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['launch_vehicles', 'propulsion_systems'],
    customers: ['nasa', 'dod', 'nro'],
    suppliers: ['aerojet-rocketdyne', 'blue-origin', 'moog'],
    criticality: 'high',
    description: 'Premier US government launch provider',
    headquarters: 'Centennial, CO',
    employeeCount: 3000,
  },
  {
    id: 'rocket-lab',
    slug: 'rocket-lab',
    name: 'Rocket Lab',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['launch_vehicles', 'spacecraft', 'space_systems'],
    customers: ['nasa', 'dod', 'commercial'],
    suppliers: ['rutherford-internal', 'maxar', 'sinclair-interplanetary'],
    criticality: 'medium',
    description: 'Small launch and space systems provider',
    headquarters: 'Long Beach, CA',
    employeeCount: 1800,
  },
  {
    id: 'blue-origin',
    slug: 'blue-origin',
    name: 'Blue Origin',
    tier: 'prime',
    country: 'United States',
    countryCode: 'USA',
    products: ['launch_vehicles', 'propulsion', 'lunar_landers'],
    customers: ['nasa', 'ula', 'commercial'],
    suppliers: ['honeywell', 'moog', 'parker-hannifin'],
    criticality: 'medium',
    description: 'Vertical integration launch and propulsion company',
    headquarters: 'Kent, WA',
    employeeCount: 11000,
  },

  // Tier 1 Suppliers
  {
    id: 'aerojet-rocketdyne',
    slug: 'aerojet-rocketdyne',
    name: 'Aerojet Rocketdyne',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['rocket_engines', 'propulsion_systems', 'thrusters'],
    customers: ['spacex', 'boeing', 'lockheed-martin', 'northrop-grumman', 'ula'],
    suppliers: ['specialty-metals-inc', 'honeywell', 'moog'],
    criticality: 'high',
    description: 'Premier rocket propulsion manufacturer',
    headquarters: 'El Segundo, CA',
    employeeCount: 5000,
  },
  {
    id: 'l3harris',
    slug: 'l3harris',
    name: 'L3Harris Technologies',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['avionics', 'communication_systems', 'sensors', 'electronics'],
    customers: ['boeing', 'lockheed-martin', 'northrop-grumman', 'nasa'],
    suppliers: ['analog-devices', 'texas-instruments', 'xilinx'],
    criticality: 'high',
    description: 'Defense electronics and communication systems',
    headquarters: 'Melbourne, FL',
    employeeCount: 50000,
  },
  {
    id: 'ball-aerospace',
    slug: 'ball-aerospace',
    name: 'Ball Aerospace',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['spacecraft', 'instruments', 'sensors', 'antennas'],
    customers: ['nasa', 'boeing', 'lockheed-martin'],
    suppliers: ['honeywell', 'analog-devices', 'corning'],
    criticality: 'high',
    description: 'Space instruments and spacecraft manufacturer',
    headquarters: 'Boulder, CO',
    employeeCount: 5500,
  },
  {
    id: 'maxar',
    slug: 'maxar',
    name: 'Maxar Technologies',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['satellites', 'spacecraft_buses', 'robotics', 'earth_observation'],
    customers: ['nasa', 'commercial', 'government'],
    suppliers: ['honeywell', 'moog', 'cobham'],
    criticality: 'high',
    description: 'Satellite manufacturer and Earth observation provider',
    headquarters: 'Westminster, CO',
    employeeCount: 4500,
  },
  {
    id: 'honeywell-aerospace',
    slug: 'honeywell-aerospace',
    name: 'Honeywell Aerospace',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['avionics', 'guidance_systems', 'sensors', 'actuators'],
    customers: ['spacex', 'boeing', 'lockheed-martin', 'blue-origin'],
    suppliers: ['analog-devices', 'texas-instruments', 'specialty-materials'],
    criticality: 'high',
    description: 'Aerospace avionics and systems provider',
    headquarters: 'Phoenix, AZ',
    employeeCount: 40000,
  },
  {
    id: 'moog',
    slug: 'moog',
    name: 'Moog Inc.',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['actuators', 'valves', 'propulsion_components', 'flight_controls'],
    customers: ['spacex', 'boeing', 'northrop-grumman', 'ula', 'aerojet-rocketdyne'],
    suppliers: ['specialty-metals', 'parker-hannifin', 'te-connectivity'],
    criticality: 'high',
    description: 'Precision motion control components',
    headquarters: 'East Aurora, NY',
    employeeCount: 13000,
  },
  {
    id: 'thales-alenia',
    slug: 'thales-alenia',
    name: 'Thales Alenia Space',
    tier: 'tier1',
    country: 'France',
    countryCode: 'FRA',
    products: ['satellites', 'space_systems', 'communication_payloads'],
    customers: ['airbus-defence-space', 'esa', 'commercial'],
    suppliers: ['safran', 'stmicroelectronics', 'sodern'],
    criticality: 'high',
    description: 'European satellite systems manufacturer',
    headquarters: 'Cannes, France',
    employeeCount: 8500,
  },
  {
    id: 'arianegroup',
    slug: 'arianegroup',
    name: 'ArianeGroup',
    tier: 'tier1',
    country: 'France',
    countryCode: 'FRA',
    products: ['launch_vehicles', 'propulsion_systems', 'solid_motors'],
    customers: ['airbus-defence-space', 'esa'],
    suppliers: ['safran', 'mt-aerospace', 'avio'],
    criticality: 'high',
    description: 'European launch vehicle manufacturer',
    headquarters: 'Paris, France',
    employeeCount: 9000,
  },
  {
    id: 'safran',
    slug: 'safran',
    name: 'Safran',
    tier: 'tier1',
    country: 'France',
    countryCode: 'FRA',
    products: ['propulsion', 'navigation_systems', 'optronics'],
    customers: ['arianegroup', 'thales-alenia', 'airbus-defence-space'],
    suppliers: ['stmicroelectronics', 'specialty-metals-eu'],
    criticality: 'high',
    description: 'French aerospace propulsion and systems',
    headquarters: 'Paris, France',
    employeeCount: 83000,
  },

  // Tier 2 Suppliers
  {
    id: 'te-connectivity',
    slug: 'te-connectivity',
    name: 'TE Connectivity',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['connectors', 'sensors', 'wiring_harnesses'],
    customers: ['spacex', 'boeing', 'northrop-grumman', 'honeywell'],
    suppliers: ['copper-suppliers', 'polymer-suppliers'],
    criticality: 'medium',
    description: 'Electronic connectors and sensors',
    headquarters: 'Schaffhausen, Switzerland',
    employeeCount: 85000,
  },
  {
    id: 'analog-devices',
    slug: 'analog-devices',
    name: 'Analog Devices',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['semiconductors', 'signal_processing', 'power_management'],
    customers: ['l3harris', 'honeywell', 'ball-aerospace'],
    suppliers: ['tsmc', 'globalfoundries'],
    criticality: 'high',
    description: 'High-performance semiconductors',
    headquarters: 'Wilmington, MA',
    employeeCount: 24000,
  },
  {
    id: 'texas-instruments',
    slug: 'texas-instruments',
    name: 'Texas Instruments',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['semiconductors', 'analog_chips', 'embedded_processors'],
    customers: ['l3harris', 'honeywell', 'raytheon'],
    suppliers: ['internal-fabs', 'specialty-materials'],
    criticality: 'medium',
    description: 'Semiconductor manufacturer',
    headquarters: 'Dallas, TX',
    employeeCount: 30000,
  },
  {
    id: 'parker-hannifin',
    slug: 'parker-hannifin',
    name: 'Parker Hannifin',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['hydraulics', 'seals', 'fluid_systems', 'thermal_management'],
    customers: ['blue-origin', 'moog', 'aerojet-rocketdyne'],
    suppliers: ['specialty-polymers', 'metal-suppliers'],
    criticality: 'medium',
    description: 'Motion and control technologies',
    headquarters: 'Cleveland, OH',
    employeeCount: 58000,
  },
  {
    id: 'curtiss-wright',
    slug: 'curtiss-wright',
    name: 'Curtiss-Wright',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['electronics', 'actuation_systems', 'sensors'],
    customers: ['boeing', 'lockheed-martin', 'general-dynamics'],
    suppliers: ['semiconductor-suppliers', 'metal-suppliers'],
    criticality: 'medium',
    description: 'Defense and aerospace systems',
    headquarters: 'Davidson, NC',
    employeeCount: 8500,
  },
  {
    id: 'cobham-advanced',
    slug: 'cobham-advanced',
    name: 'Cobham Advanced Electronic Solutions',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['rf_components', 'microwave_devices', 'space_electronics'],
    customers: ['maxar', 'l3harris', 'northrop-grumman'],
    suppliers: ['specialty-semiconductors', 'rare-earth-suppliers'],
    criticality: 'medium',
    description: 'Space-qualified electronic components',
    headquarters: 'Lowell, MA',
    employeeCount: 3500,
  },
  {
    id: 'stmicroelectronics',
    slug: 'stmicroelectronics',
    name: 'STMicroelectronics',
    tier: 'tier2',
    country: 'Europe',
    countryCode: 'EUR',
    products: ['semiconductors', 'mems', 'power_devices'],
    customers: ['thales-alenia', 'safran', 'airbus-defence-space'],
    suppliers: ['global-wafer', 'specialty-materials'],
    criticality: 'medium',
    description: 'European semiconductor manufacturer',
    headquarters: 'Geneva, Switzerland',
    employeeCount: 50000,
  },

  // Tier 3 Suppliers (Critical Materials)
  {
    id: 'mp-materials',
    slug: 'mp-materials',
    name: 'MP Materials',
    tier: 'tier3',
    country: 'United States',
    countryCode: 'USA',
    products: ['rare_earth_elements', 'neodymium', 'praseodymium'],
    customers: ['honeywell', 'general-motors', 'defense-contractors'],
    suppliers: ['mining-operations'],
    criticality: 'high',
    description: 'Only US rare earth mine and processor',
    headquarters: 'Las Vegas, NV',
    employeeCount: 500,
  },
  {
    id: 'lynas-rare-earths',
    slug: 'lynas-rare-earths',
    name: 'Lynas Rare Earths',
    tier: 'tier3',
    country: 'Australia',
    countryCode: 'AUS',
    products: ['rare_earth_elements', 'neodymium', 'praseodymium', 'dysprosium'],
    customers: ['western-defense-contractors', 'electronics-manufacturers'],
    suppliers: ['mining-operations'],
    criticality: 'high',
    description: 'Non-China rare earth producer',
    headquarters: 'Perth, Australia',
    employeeCount: 1000,
  },
  {
    id: 'china-northern-rare-earth',
    slug: 'china-northern-rare-earth',
    name: 'China Northern Rare Earth',
    tier: 'tier3',
    country: 'China',
    countryCode: 'CHN',
    products: ['rare_earth_elements', 'all_17_ree'],
    customers: ['global-manufacturers'],
    suppliers: ['bayan-obo-mine'],
    criticality: 'high',
    description: 'World largest rare earth producer (60% global)',
    headquarters: 'Baotou, Inner Mongolia',
    employeeCount: 25000,
  },
  {
    id: 'ati-specialty',
    slug: 'ati-specialty',
    name: 'ATI Specialty Materials',
    tier: 'tier3',
    country: 'United States',
    countryCode: 'USA',
    products: ['titanium', 'nickel_alloys', 'specialty_steels'],
    customers: ['boeing', 'aerojet-rocketdyne', 'pratt-whitney'],
    suppliers: ['titanium-sponge-suppliers', 'nickel-suppliers'],
    criticality: 'high',
    description: 'Specialty metals for aerospace',
    headquarters: 'Pittsburgh, PA',
    employeeCount: 7000,
  },
  {
    id: 'materion',
    slug: 'materion',
    name: 'Materion Corporation',
    tier: 'tier3',
    country: 'United States',
    countryCode: 'USA',
    products: ['beryllium', 'precision_alloys', 'advanced_materials'],
    customers: ['boeing', 'lockheed-martin', 'defense-contractors'],
    suppliers: ['beryllium-mining', 'alloy-suppliers'],
    criticality: 'high',
    description: 'Only Western beryllium producer',
    headquarters: 'Mayfield Heights, OH',
    employeeCount: 2500,
  },
  {
    id: 'vsmpo-avisma',
    slug: 'vsmpo-avisma',
    name: 'VSMPO-AVISMA',
    tier: 'tier3',
    country: 'Russia',
    countryCode: 'RUS',
    products: ['titanium', 'titanium_alloys'],
    customers: ['boeing', 'airbus', 'embraer'],
    suppliers: ['russian-titanium-mines'],
    criticality: 'high',
    description: 'World largest titanium producer (sanctioned)',
    headquarters: 'Verkhnaya Salda, Russia',
    employeeCount: 20000,
  },
  {
    id: 'tsmc',
    slug: 'tsmc',
    name: 'Taiwan Semiconductor Manufacturing Company',
    tier: 'tier3',
    country: 'Taiwan',
    countryCode: 'TWN',
    products: ['semiconductors', 'advanced_nodes', 'space_grade_chips'],
    customers: ['analog-devices', 'nvidia', 'qualcomm', 'defense-contractors'],
    suppliers: ['asml', 'applied-materials', 'lam-research'],
    criticality: 'high',
    description: 'World leading advanced semiconductor fab',
    headquarters: 'Hsinchu, Taiwan',
    employeeCount: 65000,
  },
  {
    id: 'samsung-foundry',
    slug: 'samsung-foundry',
    name: 'Samsung Foundry',
    tier: 'tier3',
    country: 'South Korea',
    countryCode: 'KOR',
    products: ['semiconductors', 'memory', 'logic_chips'],
    customers: ['qualcomm', 'nvidia', 'defense-customers'],
    suppliers: ['asml', 'applied-materials'],
    criticality: 'high',
    description: 'Major semiconductor foundry',
    headquarters: 'Hwaseong, South Korea',
    employeeCount: 110000,
  },
  {
    id: 'smic',
    slug: 'smic',
    name: 'Semiconductor Manufacturing International Corporation',
    tier: 'tier3',
    country: 'China',
    countryCode: 'CHN',
    products: ['semiconductors', 'mature_nodes'],
    customers: ['chinese-manufacturers', 'huawei'],
    suppliers: ['chinese-equipment'],
    criticality: 'medium',
    description: 'China largest chip foundry (restricted)',
    headquarters: 'Shanghai, China',
    employeeCount: 19000,
  },
  {
    id: 'glencore-cobalt',
    slug: 'glencore-cobalt',
    name: 'Glencore (Cobalt Division)',
    tier: 'tier3',
    country: 'DR Congo',
    countryCode: 'COD',
    products: ['cobalt', 'copper'],
    customers: ['battery-manufacturers', 'alloy-producers'],
    suppliers: ['drc-mining'],
    criticality: 'high',
    description: 'Major cobalt supplier (70% global from DRC)',
    headquarters: 'Baar, Switzerland',
    employeeCount: 135000,
  },
  {
    id: 'sqm-lithium',
    slug: 'sqm-lithium',
    name: 'SQM (Sociedad Quimica y Minera)',
    tier: 'tier3',
    country: 'Chile',
    countryCode: 'CHL',
    products: ['lithium', 'potassium', 'iodine'],
    customers: ['battery-manufacturers', 'aerospace'],
    suppliers: ['atacama-salt-flats'],
    criticality: 'medium',
    description: 'Major lithium producer',
    headquarters: 'Santiago, Chile',
    employeeCount: 16000,
  },

  // ── New Companies (Supply Chain Expansion) ──────────────────

  // Tier 1 — Large established space companies
  {
    id: 'axiom-space',
    slug: 'axiom-space',
    name: 'Axiom Space',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['space_station_modules', 'eva_suits', 'commercial_habitats'],
    customers: ['nasa', 'commercial', 'international-partners'],
    suppliers: ['collins-aerospace', 'honeywell-aerospace', 'thales-alenia'],
    criticality: 'high',
    description: 'Commercial space station developer (Axiom Station) and provider of ISS missions and next-gen EVA suits (AxEMU)',
    headquarters: 'Houston, TX',
    employeeCount: 1200,
  },
  {
    id: 'sierra-space',
    slug: 'sierra-space',
    name: 'Sierra Space',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['dream_chaser', 'life_habitat', 'inflatable_modules', 'docking_systems'],
    customers: ['nasa', 'commercial', 'ula'],
    suppliers: ['honeywell-aerospace', 'moog', 'collins-aerospace'],
    criticality: 'high',
    description: 'Developer of Dream Chaser spaceplane and LIFE inflatable habitat for Orbital Reef station',
    headquarters: 'Louisville, CO',
    employeeCount: 1500,
  },
  {
    id: 'mda-space',
    slug: 'mda-space',
    name: 'MDA Space',
    tier: 'tier1',
    country: 'Canada',
    countryCode: 'CAN',
    products: ['robotics', 'canadarm3', 'satellite_servicing', 'space_sensors'],
    customers: ['nasa', 'csa', 'commercial'],
    suppliers: ['maxon-motors', 'harmonic-drive', 'honeywell-aerospace'],
    criticality: 'high',
    description: 'Builder of Canadarm, Canadarm2, and Canadarm3 for Lunar Gateway. Premier space robotics company',
    headquarters: 'Brampton, Ontario',
    employeeCount: 3000,
  },
  {
    id: 'collins-aerospace',
    slug: 'collins-aerospace',
    name: 'Collins Aerospace (RTX)',
    tier: 'tier1',
    country: 'United States',
    countryCode: 'USA',
    products: ['eva_suits', 'life_support_systems', 'oxygen_generation', 'co2_removal', 'thermal_control'],
    customers: ['nasa', 'axiom-space', 'boeing', 'lockheed-martin'],
    suppliers: ['honeywell-aerospace', 'parker-hannifin', 'specialty-polymers'],
    criticality: 'high',
    description: 'Sole provider of next-gen EVA suits (xEMU/AxEMU) and ISS ECLSS components including OGS and CDRA',
    headquarters: 'Charlotte, NC',
    employeeCount: 70000,
  },

  // Tier 2 — Mid-size specialists
  {
    id: 'vast',
    slug: 'vast',
    name: 'Vast',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['space_stations', 'artificial_gravity_habitats'],
    customers: ['nasa', 'commercial'],
    suppliers: ['spacex', 'collins-aerospace', 'honeywell-aerospace'],
    criticality: 'medium',
    description: 'Developer of Haven-1 single-module station and multi-module artificial gravity station',
    headquarters: 'Long Beach, CA',
    employeeCount: 400,
  },
  {
    id: 'mynaric',
    slug: 'mynaric',
    name: 'Mynaric',
    tier: 'tier2',
    country: 'Europe',
    countryCode: 'EUR',
    products: ['optical_communication_terminals', 'laser_terminals', 'free_space_optics'],
    customers: ['sda', 'darpa', 'northrop-grumman', 'l3harris'],
    suppliers: ['laser-diode-suppliers', 'precision-optics-suppliers'],
    criticality: 'medium',
    description: 'Leading manufacturer of optical inter-satellite links (CONDOR, HAWK) for SDA Tranche programs',
    headquarters: 'Munich, Germany',
    employeeCount: 500,
  },
  {
    id: 'intuitive-machines',
    slug: 'intuitive-machines',
    name: 'Intuitive Machines',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['lunar_landers', 'lunar_rovers', 'lunar_communications', 'data_relay'],
    customers: ['nasa', 'commercial'],
    suppliers: ['spacex', 'honeywell-aerospace', 'aerojet-rocketdyne'],
    criticality: 'medium',
    description: 'CLPS lunar lander provider (Nova-C, Nova-D). First commercial lunar landing (IM-1, Feb 2024)',
    headquarters: 'Houston, TX',
    employeeCount: 600,
  },
  {
    id: 'astrobotic',
    slug: 'astrobotic',
    name: 'Astrobotic Technology',
    tier: 'tier2',
    country: 'United States',
    countryCode: 'USA',
    products: ['lunar_landers', 'lunar_rovers', 'delivery_services'],
    customers: ['nasa', 'commercial', 'international-space-agencies'],
    suppliers: ['ula', 'honeywell-aerospace', 'aerojet-rocketdyne'],
    criticality: 'medium',
    description: 'CLPS lunar delivery service provider (Peregrine, Griffin). NASA VIPER rover delivery contract',
    headquarters: 'Pittsburgh, PA',
    employeeCount: 350,
  },

  // Tier 3 — Emerging & niche suppliers
  {
    id: 'lumen-orbit',
    slug: 'lumen-orbit',
    name: 'Lumen Orbit',
    tier: 'tier3',
    country: 'United States',
    countryCode: 'USA',
    products: ['orbital_data_centers', 'space_computing', 'edge_processing'],
    customers: ['ai-companies', 'cloud-providers', 'government'],
    suppliers: ['spacex', 'xilinx-amd', 'cobham-advanced'],
    criticality: 'medium',
    description: 'Startup building orbital data centers for AI/ML workloads leveraging free cooling and solar power in space',
    headquarters: 'San Francisco, CA',
    employeeCount: 50,
  },
  {
    id: 'orbitsedge',
    slug: 'orbitsedge',
    name: 'OrbitsEdge',
    tier: 'tier3',
    country: 'United States',
    countryCode: 'USA',
    products: ['edge_computing_satellites', 'space_data_processing', 'satcloud_platform'],
    customers: ['government', 'commercial', 'defense'],
    suppliers: ['hewlett-packard', 'xilinx-amd', 'cobham-advanced'],
    criticality: 'low',
    description: 'Space edge computing provider deploying hardened commercial compute to orbit (SatFrame micro data center)',
    headquarters: 'Melbourne, FL',
    employeeCount: 30,
  },
  {
    id: 'gitai',
    slug: 'gitai',
    name: 'GITAI',
    tier: 'tier3',
    country: 'United States',
    countryCode: 'USA',
    products: ['space_robots', 'robotic_arms', 'autonomous_assembly', 'intra_vehicular_robots'],
    customers: ['nasa', 'axiom-space', 'commercial'],
    suppliers: ['maxon-motors', 'harmonic-drive', 'analog-devices'],
    criticality: 'medium',
    description: 'Space robotics startup developing autonomous robots for ISS, commercial stations, and lunar surface ops',
    headquarters: 'Torrance, CA',
    employeeCount: 100,
  },
  {
    id: 'bradford-space',
    slug: 'bradford-space',
    name: 'Bradford Space',
    tier: 'tier3',
    country: 'Europe',
    countryCode: 'EUR',
    products: ['green_propulsion', 'hpgp_thrusters', 'propulsion_systems'],
    customers: ['satellite-manufacturers', 'esa', 'nasa'],
    suppliers: ['specialty-chemicals', 'valve-suppliers'],
    criticality: 'medium',
    description: 'Developer of High Performance Green Propulsion (HPGP) system using AF-M315E/LMP-103S as hydrazine replacement',
    headquarters: 'The Hague, Netherlands',
    employeeCount: 200,
  },
  {
    id: 'busek',
    slug: 'busek',
    name: 'Busek Co.',
    tier: 'tier3',
    country: 'United States',
    countryCode: 'USA',
    products: ['hall_effect_thrusters', 'electrospray_thrusters', 'cathodes', 'electric_propulsion'],
    customers: ['lockheed-martin', 'northrop-grumman', 'nasa', 'sda'],
    suppliers: ['specialty-ceramics', 'rare-earth-suppliers'],
    criticality: 'medium',
    description: 'Electric propulsion specialist producing Hall thrusters, electrospray, and RF ion engines for smallsats to large spacecraft',
    headquarters: 'Natick, MA',
    employeeCount: 120,
  },
];

// ============================================================
// Supply Relationships
// ============================================================

export const SUPPLY_RELATIONSHIPS: SupplyRelationship[] = [
  // SpaceX relationships
  {
    id: 'rel-1',
    supplierId: 'aerojet-rocketdyne',
    supplierName: 'Aerojet Rocketdyne',
    customerId: 'spacex',
    customerName: 'SpaceX',
    products: ['thrusters', 'attitude_control'],
    annualValue: 50000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  {
    id: 'rel-2',
    supplierId: 'honeywell-aerospace',
    supplierName: 'Honeywell Aerospace',
    customerId: 'spacex',
    customerName: 'SpaceX',
    products: ['avionics', 'sensors'],
    annualValue: 30000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  // Boeing relationships
  {
    id: 'rel-3',
    supplierId: 'aerojet-rocketdyne',
    supplierName: 'Aerojet Rocketdyne',
    customerId: 'boeing',
    customerName: 'Boeing',
    products: ['rs-25_engines', 'propulsion_systems'],
    annualValue: 200000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  {
    id: 'rel-4',
    supplierId: 'l3harris',
    supplierName: 'L3Harris Technologies',
    customerId: 'boeing',
    customerName: 'Boeing',
    products: ['communication_systems', 'sensors'],
    annualValue: 150000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  // Critical material dependencies
  {
    id: 'rel-5',
    supplierId: 'china-northern-rare-earth',
    supplierName: 'China Northern Rare Earth',
    customerId: 'honeywell-aerospace',
    customerName: 'Honeywell Aerospace',
    products: ['rare_earth_magnets', 'neodymium'],
    annualValue: 20000000,
    geopoliticalRisk: 'high',
    isCritical: true,
    notes: 'Critical dependency on Chinese rare earths',
  },
  {
    id: 'rel-6',
    supplierId: 'tsmc',
    supplierName: 'TSMC',
    customerId: 'analog-devices',
    customerName: 'Analog Devices',
    products: ['advanced_semiconductors'],
    annualValue: 100000000,
    geopoliticalRisk: 'medium',
    isCritical: true,
    notes: 'Taiwan geopolitical risk',
  },
  {
    id: 'rel-7',
    supplierId: 'vsmpo-avisma',
    supplierName: 'VSMPO-AVISMA',
    customerId: 'boeing',
    customerName: 'Boeing',
    products: ['titanium_forgings'],
    annualValue: 300000000,
    geopoliticalRisk: 'high',
    isCritical: true,
    notes: 'Russian titanium - seeking alternatives post-sanctions',
  },
  // European supply chain
  {
    id: 'rel-8',
    supplierId: 'arianegroup',
    supplierName: 'ArianeGroup',
    customerId: 'airbus-defence-space',
    customerName: 'Airbus Defence and Space',
    products: ['ariane_stages', 'propulsion'],
    annualValue: 500000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  {
    id: 'rel-9',
    supplierId: 'safran',
    supplierName: 'Safran',
    customerId: 'arianegroup',
    customerName: 'ArianeGroup',
    products: ['vulcain_engine_components'],
    annualValue: 200000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  // Material supply chains
  {
    id: 'rel-10',
    supplierId: 'materion',
    supplierName: 'Materion Corporation',
    customerId: 'lockheed-martin',
    customerName: 'Lockheed Martin',
    products: ['beryllium_structures'],
    annualValue: 50000000,
    geopoliticalRisk: 'none',
    isCritical: true,
    notes: 'Sole Western supplier of aerospace-grade beryllium',
  },
  {
    id: 'rel-11',
    supplierId: 'ati-specialty',
    supplierName: 'ATI Specialty Materials',
    customerId: 'aerojet-rocketdyne',
    customerName: 'Aerojet Rocketdyne',
    products: ['nickel_superalloys', 'titanium'],
    annualValue: 80000000,
    geopoliticalRisk: 'none',
    isCritical: true,
  },
  {
    id: 'rel-12',
    supplierId: 'glencore-cobalt',
    supplierName: 'Glencore (Cobalt)',
    customerId: 'ati-specialty',
    customerName: 'ATI Specialty Materials',
    products: ['cobalt_for_superalloys'],
    annualValue: 30000000,
    geopoliticalRisk: 'high',
    isCritical: true,
    notes: 'DRC cobalt supply concerns',
  },

  // ── New Relationships (Supply Chain Expansion) ─────────────

  // Collins Aerospace → Axiom Space (ECLSS and EVA suits)
  {
    id: 'rel-13',
    supplierId: 'collins-aerospace',
    supplierName: 'Collins Aerospace (RTX)',
    customerId: 'axiom-space',
    customerName: 'Axiom Space',
    products: ['eclss_systems', 'eva_suits', 'co2_removal', 'oxygen_generation'],
    annualValue: 150000000,
    geopoliticalRisk: 'none',
    isCritical: true,
    notes: 'Sole source for next-gen EVA suits (AxEMU) and ECLSS components for Axiom Station',
  },
  // MDA Space → NASA/CSA (Canadarm3 for Lunar Gateway)
  {
    id: 'rel-14',
    supplierId: 'mda-space',
    supplierName: 'MDA Space',
    customerId: 'northrop-grumman',
    customerName: 'Northrop Grumman',
    products: ['canadarm3', 'robotic_arms', 'satellite_servicing_robotics'],
    annualValue: 200000000,
    geopoliticalRisk: 'none',
    isCritical: true,
    notes: 'Canadarm3 for Lunar Gateway and MEV satellite servicing robotics',
  },
  // Cobham → Lumen Orbit (rad-hard electronics for orbital data centers)
  {
    id: 'rel-15',
    supplierId: 'cobham-advanced',
    supplierName: 'Cobham Advanced Electronic Solutions',
    customerId: 'lumen-orbit',
    customerName: 'Lumen Orbit',
    products: ['radiation_hardened_memory', 'space_electronics', 'rf_components'],
    geopoliticalRisk: 'none',
    isCritical: true,
    notes: 'Critical rad-hard electronics supplier for orbital data center compute modules',
  },
  // Mynaric → Northrop Grumman (optical terminals for SDA)
  {
    id: 'rel-16',
    supplierId: 'mynaric',
    supplierName: 'Mynaric',
    customerId: 'northrop-grumman',
    customerName: 'Northrop Grumman',
    products: ['optical_communication_terminals', 'condor_terminals'],
    annualValue: 80000000,
    geopoliticalRisk: 'low',
    isCritical: true,
    notes: 'CONDOR optical inter-satellite link terminals for SDA Tranche proliferated LEO constellation',
  },
  // Bradford Space → Rocket Lab (green propulsion for satellite buses)
  {
    id: 'rel-17',
    supplierId: 'bradford-space',
    supplierName: 'Bradford Space',
    customerId: 'rocket-lab',
    customerName: 'Rocket Lab',
    products: ['green_propulsion_systems', 'hpgp_thrusters'],
    annualValue: 15000000,
    geopoliticalRisk: 'none',
    isCritical: false,
    notes: 'HPGP green propulsion integration for Photon satellite bus',
  },
  // Thales Alenia → Axiom Space (station modules)
  {
    id: 'rel-18',
    supplierId: 'thales-alenia',
    supplierName: 'Thales Alenia Space',
    customerId: 'axiom-space',
    customerName: 'Axiom Space',
    products: ['pressurized_modules', 'space_station_structures'],
    annualValue: 300000000,
    geopoliticalRisk: 'none',
    isCritical: true,
    notes: 'Primary manufacturer of Axiom Station pressurized modules (heritage from ISS Columbus, MPLM, Cygnus)',
  },
  // Busek → Lockheed Martin (electric propulsion for LM satellites)
  {
    id: 'rel-19',
    supplierId: 'busek',
    supplierName: 'Busek Co.',
    customerId: 'lockheed-martin',
    customerName: 'Lockheed Martin',
    products: ['hall_effect_thrusters', 'electrospray_propulsion', 'cathodes'],
    annualValue: 25000000,
    geopoliticalRisk: 'none',
    isCritical: false,
    notes: 'Electric propulsion for smallsat and medium satellite programs',
  },
  // Honeywell → Intuitive Machines (avionics and sensors for lunar landers)
  {
    id: 'rel-20',
    supplierId: 'honeywell-aerospace',
    supplierName: 'Honeywell Aerospace',
    customerId: 'intuitive-machines',
    customerName: 'Intuitive Machines',
    products: ['navigation_sensors', 'avionics', 'inertial_measurement_units'],
    annualValue: 20000000,
    geopoliticalRisk: 'none',
    isCritical: true,
    notes: 'IMU and navigation avionics for Nova-C and Nova-D lunar lander programs',
  },
];

// ============================================================
// Supply Shortages and Risk Alerts
// ============================================================

export const SUPPLY_SHORTAGES: SupplyShortage[] = [
  {
    id: 'shortage-1',
    material: 'Radiation-Hardened Semiconductors',
    category: 'semiconductors',
    affectedProducts: ['satellite_avionics', 'deep_space_electronics', 'missile_guidance'],
    severity: 'critical',
    alternativeSuppliers: ['cobham-advanced', 'bae-systems-rad-hard'],
    notes: 'Limited global capacity for rad-hard chips. Lead times 18-24 months.',
    estimatedResolution: '2027',
    impactedCompanies: ['lockheed-martin', 'northrop-grumman', 'boeing', 'ball-aerospace'],
    geopoliticalFactors: ['US_CHIPS_Act', 'Defense_Priority'],
  },
  {
    id: 'shortage-2',
    material: 'Rare Earth Elements (Heavy)',
    category: 'rare_earth',
    affectedProducts: ['permanent_magnets', 'guidance_systems', 'electric_propulsion'],
    severity: 'critical',
    alternativeSuppliers: ['lynas-rare-earths', 'mp-materials'],
    notes: 'China controls 90%+ of heavy rare earth processing. Critical for defense.',
    estimatedResolution: '2028+',
    impactedCompanies: ['honeywell-aerospace', 'l3harris', 'general-dynamics'],
    geopoliticalFactors: ['China_Export_Controls', 'US_Stockpile_Efforts'],
  },
  {
    id: 'shortage-3',
    material: 'Aerospace-Grade Titanium',
    category: 'specialty_metals',
    affectedProducts: ['rocket_structures', 'satellite_frames', 'engine_components'],
    severity: 'high',
    alternativeSuppliers: ['ati-specialty', 'timet', 'kobe-steel'],
    notes: 'Russian sanctions impacted 30% of global aerospace titanium. Supply diversifying.',
    estimatedResolution: '2026',
    impactedCompanies: ['boeing', 'airbus-defence-space', 'spacex'],
    geopoliticalFactors: ['Russia_Sanctions', 'Supply_Diversification'],
  },
  {
    id: 'shortage-4',
    material: 'Beryllium',
    category: 'specialty_metals',
    affectedProducts: ['satellite_structures', 'optical_mounts', 'heat_shields'],
    severity: 'high',
    alternativeSuppliers: ['materion'],
    notes: 'Single Western supplier (Materion). Critical for James Webb-class optics.',
    estimatedResolution: 'Ongoing',
    impactedCompanies: ['ball-aerospace', 'lockheed-martin', 'boeing'],
    geopoliticalFactors: ['Single_Source_Risk', 'Strategic_Stockpile'],
  },
  {
    id: 'shortage-5',
    material: 'Space-Grade Solar Cells',
    category: 'power',
    affectedProducts: ['satellite_power', 'space_station_arrays', 'lunar_systems'],
    severity: 'medium',
    alternativeSuppliers: ['spectrolab', 'solaero', 'azur-space'],
    notes: 'High efficiency III-V cells in short supply. New capacity coming online.',
    estimatedResolution: '2025',
    impactedCompanies: ['maxar', 'northrop-grumman', 'lockheed-martin'],
  },
  {
    id: 'shortage-6',
    material: 'Gallium',
    category: 'semiconductors',
    affectedProducts: ['rf_components', 'power_electronics', 'led_systems'],
    severity: 'high',
    alternativeSuppliers: ['limited_non_china'],
    notes: 'China controls 80% of gallium. Export restrictions announced 2023.',
    estimatedResolution: '2027',
    impactedCompanies: ['l3harris', 'analog-devices', 'raytheon'],
    geopoliticalFactors: ['China_Export_Ban', 'Strategic_Material'],
  },
  {
    id: 'shortage-7',
    material: 'Cobalt',
    category: 'specialty_metals',
    affectedProducts: ['superalloys', 'batteries', 'high_temp_components'],
    severity: 'medium',
    alternativeSuppliers: ['glencore-cobalt', 'australian-mines'],
    notes: '70% from DRC with ethical and supply concerns. Recycling increasing.',
    estimatedResolution: '2026',
    impactedCompanies: ['aerojet-rocketdyne', 'pratt-whitney', 'ge-aerospace'],
    geopoliticalFactors: ['DRC_Instability', 'ESG_Concerns'],
  },
  {
    id: 'shortage-8',
    material: 'Advanced Composites (CFRP)',
    category: 'structures',
    affectedProducts: ['rocket_fairings', 'satellite_structures', 'pressure_vessels'],
    severity: 'medium',
    alternativeSuppliers: ['toray', 'hexcel', 'sgl-carbon'],
    notes: 'Aerospace carbon fiber demand exceeding supply. New capacity ramping.',
    estimatedResolution: '2025',
    impactedCompanies: ['spacex', 'rocket-lab', 'boeing'],
  },
  {
    id: 'shortage-9',
    material: 'Tantalum Capacitors',
    category: 'avionics',
    affectedProducts: ['electronics', 'power_systems', 'filters'],
    severity: 'medium',
    alternativeSuppliers: ['kemet', 'vishay', 'avx'],
    notes: 'Space-grade tantalum capacitors in tight supply. Lead times extended.',
    estimatedResolution: '2025',
    impactedCompanies: ['l3harris', 'honeywell-aerospace', 'collins-aerospace'],
    geopoliticalFactors: ['DRC_Tantalum_Mining'],
  },
  {
    id: 'shortage-10',
    material: 'Hydrazine',
    category: 'propulsion',
    affectedProducts: ['satellite_propulsion', 'attitude_control', 'spacecraft_thrusters'],
    severity: 'low',
    alternativeSuppliers: ['arch-chemicals', 'lonza'],
    notes: 'Limited production capacity. Green propellant alternatives emerging.',
    estimatedResolution: '2025',
    impactedCompanies: ['maxar', 'lockheed-martin', 'ball-aerospace'],
  },
  {
    id: 'shortage-11',
    material: 'Germanium',
    category: 'sensors',
    affectedProducts: ['infrared_optics', 'fiber_optics', 'solar_cells'],
    severity: 'high',
    alternativeSuppliers: ['limited_non_china'],
    notes: 'China export restrictions on germanium effective Aug 2023.',
    estimatedResolution: '2027',
    impactedCompanies: ['ball-aerospace', 'l3harris', 'raytheon'],
    geopoliticalFactors: ['China_Export_Ban'],
  },
  {
    id: 'shortage-12',
    material: 'Rocket-Grade Aluminum Alloys',
    category: 'structures',
    affectedProducts: ['rocket_tanks', 'spacecraft_structures'],
    severity: 'low',
    alternativeSuppliers: ['arconic', 'constellium', 'aleris'],
    notes: 'Supply adequate but lead times extended for large forgings.',
    estimatedResolution: '2025',
    impactedCompanies: ['spacex', 'ula', 'blue-origin'],
  },

  // ── Computing (Orbital Data Centers) ───────────────────────

  {
    id: 'shortage-13',
    material: 'Space-Qualified GPUs/TPUs',
    category: 'computing',
    affectedProducts: ['orbital_data_centers', 'onboard_ai_processing', 'edge_computing_satellites', 'autonomous_navigation'],
    severity: 'critical',
    alternativeSuppliers: ['xilinx-amd', 'microchip-technology', 'custom-asic-foundries'],
    notes: 'NVIDIA and AMD do not manufacture radiation-hardened GPU/TPU variants. Only radiation-tolerant options exist from Xilinx (now AMD) XQRKU060 FPGAs and custom ASIC designs. Space-grade AI accelerators are essentially non-existent — current solutions rely on FPGA-based inference or heavily derated commercial parts behind spot shielding. Lumen Orbit and OrbitsEdge are developing workarounds using commercial GPUs inside radiation-shielded enclosures, but this adds mass and limits performance. True space-qualified GPU compute remains 3-5 years away. US export controls on advanced AI chips further complicate international supply chains.',
    estimatedResolution: '2029+',
    impactedCompanies: ['lumen-orbit', 'orbitsedge', 'northrop-grumman', 'l3harris', 'ball-aerospace'],
    geopoliticalFactors: ['US_Export_Controls', 'Chip_War', 'ITAR_Restricted'],
  },
  {
    id: 'shortage-14',
    material: 'Radiation-Hardened Memory (SRAM/DRAM)',
    category: 'computing',
    affectedProducts: ['satellite_computers', 'flight_software_systems', 'data_recorders', 'orbital_data_centers'],
    severity: 'high',
    alternativeSuppliers: ['3d-plus', 'cobham-advanced', 'bae-systems-rad-hard'],
    notes: 'Radiation-hardened memory is essential for every satellite and spacecraft computer. BAE Systems RAD750-era components use older process nodes with limited density. 3D-Plus (France) and Cobham Advanced Electronic Solutions are the primary suppliers of space-grade SRAM and stacked memory modules. Lead times are 12-18 months. As LEO mega-constellations (Starlink, Kuiper, SDA Tranche) consume capacity, availability for government and science missions is squeezed. No space-qualified DDR4/DDR5 or HBM equivalents exist.',
    estimatedResolution: '2027',
    impactedCompanies: ['lockheed-martin', 'northrop-grumman', 'boeing', 'ball-aerospace', 'l3harris', 'maxar'],
    geopoliticalFactors: ['US_CHIPS_Act', 'Defense_Priority', 'Foundry_Capacity'],
  },
  {
    id: 'shortage-15',
    material: 'Space-Rated FPGAs',
    category: 'computing',
    affectedProducts: ['satellite_signal_processing', 'radar_systems', 'onboard_data_handling', 'software_defined_radios'],
    severity: 'high',
    alternativeSuppliers: ['xilinx-amd', 'microchip-rtg4', 'nanoxplore-ng-large'],
    notes: 'Only two primary space-qualified FPGA families exist: Xilinx (AMD) XQRKU060 Kintex UltraScale and Microchip RTG4. NanoXplore (France) NG-LARGE is emerging as a European alternative. Limited foundry capacity at TSMC for rad-hard process nodes creates bottlenecks. Every modern satellite requires multiple FPGAs for signal processing, data handling, and reconfigurable computing. SDA Tranche 2/3 proliferated LEO programs are consuming unprecedented quantities. Lead times have stretched to 12-24 months for some part numbers.',
    estimatedResolution: '2027',
    impactedCompanies: ['l3harris', 'northrop-grumman', 'ball-aerospace', 'lockheed-martin', 'maxar'],
    geopoliticalFactors: ['TSMC_Capacity', 'US_Export_Controls'],
  },
  {
    id: 'shortage-16',
    material: 'High-Bandwidth Optical Interconnects (Space-Rated)',
    category: 'computing',
    affectedProducts: ['orbital_data_center_backplanes', 'high_speed_satellite_buses', 'inter_module_links'],
    severity: 'medium',
    alternativeSuppliers: ['ii-vi-coherent', 'lumentum', 'custom-development'],
    notes: 'Orbital data centers require 400G+ optical transceivers for backplane and inter-rack connectivity at data center speeds. No space-qualified 400G optical transceivers exist. Terrestrial 400G-ZR/ZR+ modules from II-VI (Coherent) and Lumentum are not rated for radiation, thermal vacuum, or vibration environments. This gap forces orbital computing architectures to use lower-bandwidth copper or custom fiber links with significant performance penalties. Development of space-rated high-bandwidth photonic interconnects is in early TRL 3-4 stages.',
    estimatedResolution: '2030+',
    impactedCompanies: ['lumen-orbit', 'orbitsedge'],
    geopoliticalFactors: ['Photonics_Supply_Chain'],
  },

  // ── Optical / Sensors ──────────────────────────────────────

  {
    id: 'shortage-17',
    material: 'Large-Format Infrared Focal Plane Arrays',
    category: 'optical',
    affectedProducts: ['missile_warning_sensors', 'earth_observation_imagers', 'astronomy_instruments', 'weather_satellites'],
    severity: 'high',
    alternativeSuppliers: ['teledyne-flir', 'raytheon-vision-systems', 'lynred-france'],
    notes: 'Large-format IR focal plane arrays (2K x 2K and above in MWIR/LWIR) are produced by only two qualified US sources: Teledyne (formerly Rockwell Scientific) and Raytheon Vision Systems. These are ITAR-controlled and export-restricted. Lynred (France) offers European alternatives but with smaller formats. Demand is surging from OPIR (Overhead Persistent Infrared) missile warning satellites, hyperspectral Earth observation, and NASA science missions. Indium antimonide (InSb) and mercury cadmium telluride (HgCdTe) detector materials require specialized epitaxial growth facilities with multi-year qualification cycles.',
    estimatedResolution: '2028',
    impactedCompanies: ['lockheed-martin', 'northrop-grumman', 'ball-aerospace', 'l3harris'],
    geopoliticalFactors: ['ITAR_Restricted', 'Defense_Priority', 'Detector_Material_Supply'],
  },
  {
    id: 'shortage-18',
    material: 'Space-Qualified Laser Diodes (1550nm)',
    category: 'optical',
    affectedProducts: ['optical_communication_terminals', 'lidar_systems', 'laser_altimeters', 'intersatellite_links'],
    severity: 'medium',
    alternativeSuppliers: ['ii-vi-coherent', 'lumentum', 'ams-osram', 'trumpf'],
    notes: 'High-power 1550nm laser diodes are critical for optical communications (lasercom) and lidar. Eye-safe 1550nm wavelength is standard for inter-satellite and ground links. Space qualification requires extensive radiation testing and hermetic packaging. Few suppliers can provide flight-qualified units at production volumes needed for SDA proliferated constellations. CACI (formerly SA Photonics), Mynaric, General Atomics, and Tesat (Airbus) all need qualified laser sources. The terrestrial telecom laser supply chain is large but space qualification is a narrow bottleneck.',
    estimatedResolution: '2027',
    impactedCompanies: ['mynaric', 'l3harris', 'northrop-grumman', 'ball-aerospace'],
    geopoliticalFactors: ['Optical_Comms_Demand_Surge'],
  },
  {
    id: 'shortage-19',
    material: 'Precision Star Tracker Optics',
    category: 'optical',
    affectedProducts: ['star_trackers', 'attitude_determination', 'fine_pointing_systems'],
    severity: 'medium',
    alternativeSuppliers: ['ball-aerospace', 'sodern-airbus', 'jena-optronik', 'terma'],
    notes: 'Star trackers are required on virtually every satellite for attitude determination. Ball Aerospace (CT-2020) and Sodern (Airbus subsidiary, Hydra/Auriga) dominate the market. Jena-Optronik (Germany) and Terma (Denmark) provide European alternatives. Custom optical assemblies with radiation-resistant glass, precision baffles, and calibrated CCD/CMOS detectors require 8-14 month lead times. The explosion of LEO constellation demand has strained production capacity. Each Starlink satellite, for example, uses a custom star tracker variant.',
    estimatedResolution: '2026',
    impactedCompanies: ['ball-aerospace', 'maxar', 'airbus-defence-space', 'thales-alenia'],
  },

  // ── Life Support (Habitats & Stations) ─────────────────────

  {
    id: 'shortage-20',
    material: 'ECLSS CO2 Removal Canisters (LiOH/Metal Oxide)',
    category: 'life_support',
    affectedProducts: ['space_station_eclss', 'crew_capsule_life_support', 'lunar_habitat_eclss'],
    severity: 'high',
    alternativeSuppliers: ['honeywell-aerospace', 'paragon-space-development'],
    notes: 'Carbon Dioxide Removal Assembly (CDRA) systems using metal oxide sorbent beds are NASA sole-source from Collins Aerospace (formerly Hamilton Sundstrand). Lithium hydroxide (LiOH) canisters are used as backup and for short-duration missions (Orion, Starliner). As Axiom Station, Orbital Reef (Sierra Space/Blue Origin), Vast Haven-1, and Starlab (Voyager/Airbus) all require independent ECLSS, production capacity is severely constrained. No commercial production line exists outside the NASA/Collins ecosystem. Paragon Space Development is developing alternative ECLSS concepts but remains at TRL 5-6.',
    estimatedResolution: '2028',
    impactedCompanies: ['axiom-space', 'vast', 'sierra-space', 'boeing', 'collins-aerospace'],
    geopoliticalFactors: ['NASA_Sole_Source', 'Commercial_Station_Ramp'],
  },
  {
    id: 'shortage-21',
    material: 'Closed-Loop Water Recovery Systems',
    category: 'life_support',
    affectedProducts: ['space_station_water_processing', 'lunar_base_water_systems', 'mars_transit_eclss'],
    severity: 'high',
    alternativeSuppliers: ['collins-aerospace', 'paragon-space-development'],
    notes: 'The ISS Water Processing Assembly (WPA) and Urine Processing Assembly (UPA) are the only flight-proven closed-loop water recovery systems. Designed and maintained by Collins Aerospace with NASA JSC oversight. Achieving >90% water recovery is essential for beyond-LEO missions and reduces resupply mass by thousands of kg/year. No commercial off-the-shelf closed-loop water system exists. Each new commercial station must either license NASA technology, develop proprietary systems (multi-year effort), or rely on expendable water. Current systems have reliability issues — ISS WPA has required multiple repairs and spare parts are custom-manufactured.',
    estimatedResolution: '2029',
    impactedCompanies: ['axiom-space', 'vast', 'sierra-space', 'boeing'],
    geopoliticalFactors: ['NASA_Technology_Transfer', 'ISS_Heritage_Dependency'],
  },
  {
    id: 'shortage-22',
    material: 'Space-Grade Oxygen Generation (OGS) Assemblies',
    category: 'life_support',
    affectedProducts: ['space_station_atmosphere', 'crew_capsule_life_support', 'lunar_habitat_systems'],
    severity: 'medium',
    alternativeSuppliers: ['collins-aerospace', 'honeywell-aerospace'],
    notes: 'The ISS Oxygen Generation System uses solid polymer electrolysis (SPE) to electrolyze water into O2 and H2. Collins Aerospace is the single source manufacturer. Each commercial space station needs its own OGS, and the current production line was designed for ISS sustainment, not multi-customer commercial production. Alternative approaches include MOXIE-derived CO2 electrolysis (for Mars), KO2 chemical oxygen generators (emergency only), and advanced electrolysis systems. Scaling production for 4+ commercial stations simultaneously is the primary challenge.',
    estimatedResolution: '2027',
    impactedCompanies: ['axiom-space', 'vast', 'sierra-space', 'collins-aerospace'],
  },

  // ── Cryogenic Systems ──────────────────────────────────────

  {
    id: 'shortage-23',
    material: 'Zero-Boil-Off Cryocoolers (Large-Scale)',
    category: 'cryogenic',
    affectedProducts: ['propellant_depots', 'lh2_storage', 'lox_storage', 'in_space_refueling'],
    severity: 'critical',
    alternativeSuppliers: ['ball-aerospace', 'northrop-grumman-cryo', 'lockheed-martin-ncst'],
    notes: 'Zero-boil-off (ZBO) cryocooler technology is THE critical enabling technology for in-space propellant depots and long-duration cryogenic storage. Current flight-qualified cryocoolers are designed for small scientific instruments (tens of watts cooling). Propellant depots storing liquid hydrogen (LH2) at 20K or liquid oxygen (LOX) at 90K at scales of 10-100+ metric tons require cooling capacities of kilowatts — 100x beyond current flight heritage. NASA, Lockheed Martin (Nuclear Cryogenic Storage Technology), and Ball Aerospace are developing large-scale systems but they remain at TRL 5-6. Without ZBO, propellant depots lose 1-5% of stored propellant per day through boiloff, making long-term storage impossible. This is a key blocker for NASA lunar architecture, SpaceX Mars plans, and any in-space refueling infrastructure.',
    estimatedResolution: '2030+',
    impactedCompanies: ['lockheed-martin', 'ula', 'spacex', 'blue-origin', 'boeing'],
    geopoliticalFactors: ['NASA_Artemis_Dependency', 'In_Space_Refueling_Race'],
  },
  {
    id: 'shortage-24',
    material: 'Multilayer Insulation (MLI) Blankets (Space-Grade)',
    category: 'cryogenic',
    affectedProducts: ['cryogenic_tanks', 'satellite_thermal_protection', 'instrument_thermal_control', 'propellant_depots'],
    severity: 'low',
    alternativeSuppliers: ['dunmore', 'sheldahl', 'aerospace-fabrication'],
    notes: 'Space-grade MLI blankets from Dunmore and Sheldahl (Orcon division) have 6-9 month lead times for large custom orders. MLI is needed in quantity for every orbital system — cryogenic propellant depots may require 1000+ m2 of specialized MLI. The materials themselves (aluminized Kapton/Mylar with Dacron netting spacers) are available, but space-qualified manufacturing with controlled contamination, precise layer counts, and flight-heritage venting/grounding is a specialized capability. Demand is growing as commercial stations, propellant depots, and large space structures proliferate.',
    estimatedResolution: '2026',
    impactedCompanies: ['spacex', 'ula', 'lockheed-martin', 'blue-origin', 'boeing', 'northrop-grumman'],
  },

  // ── Robotics & Mechanisms ──────────────────────────────────

  {
    id: 'shortage-25',
    material: 'Space-Qualified Robotic Actuators',
    category: 'robotics',
    affectedProducts: ['robotic_arms', 'docking_mechanisms', 'antenna_gimbals', 'solar_array_drives', 'orbital_assembly_robots'],
    severity: 'high',
    alternativeSuppliers: ['maxon-motors', 'harmonic-drive-systems', 'moog', 'curtiss-wright'],
    notes: 'Space-qualified actuators with precision harmonic drives are critical for robotic arms, mechanism deployment, and satellite servicing. Maxon (Switzerland) and Harmonic Drive Systems (Japan/Germany) are effectively the only suppliers of space-qualified precision gearboxes. Moog provides larger actuators for solar array drives and antenna positioning. Lead times are 9-18 months for flight-qualified units. Demand is surging from: Canadarm3 (MDA for Lunar Gateway), orbital assembly demonstrations, satellite servicing vehicles (Northrop MEV, Astroscale), and emerging space robotics startups (GITAI, Motiv Space). The precision manufacturing and testing required for zero-gravity, vacuum, and thermal cycling environments limits production capacity.',
    estimatedResolution: '2027',
    impactedCompanies: ['mda-space', 'gitai', 'maxar', 'northrop-grumman', 'moog'],
    geopoliticalFactors: ['Japan_Supply_Chain', 'Swiss_Export_Controls'],
  },
  {
    id: 'shortage-26',
    material: 'International Docking System Standard (IDSS) Mechanisms',
    category: 'robotics',
    affectedProducts: ['docking_systems', 'space_station_ports', 'crew_vehicles', 'cargo_vehicles'],
    severity: 'high',
    alternativeSuppliers: ['boeing', 'sierra-space', 'csa-engineering'],
    notes: 'The International Docking System Standard (IDSS) was developed post-shuttle for uniform docking across vehicles and stations. Only Boeing (for Starliner) and Sierra Space (for Dream Chaser) currently produce qualified active IDSS docking mechanisms. NASA and ISS use the NDS/iLIDS variant. Every new commercial station (Axiom, Orbital Reef, Starlab, Vast Haven-1) needs multiple IDSS ports, and every visiting vehicle needs an active mechanism. There is no commercial off-the-shelf (COTS) docking system available for purchase — each customer essentially needs a custom development or licensing agreement. This is a major infrastructure bottleneck for the emerging multi-destination commercial LEO ecosystem.',
    estimatedResolution: '2028',
    impactedCompanies: ['axiom-space', 'vast', 'sierra-space', 'boeing', 'spacex'],
    geopoliticalFactors: ['NASA_Standard_Dependency'],
  },
  {
    id: 'shortage-27',
    material: 'EVA Suit Components (Next-Generation)',
    category: 'robotics',
    affectedProducts: ['eva_suits', 'lunar_surface_operations', 'space_station_maintenance', 'orbital_construction'],
    severity: 'critical',
    alternativeSuppliers: ['collins-aerospace', 'axiom-space-eva', 'david-clark-company'],
    notes: 'Collins Aerospace is the sole developer of the next-generation EVA suit (xEMU for NASA, AxEMU for Axiom). NASA\'s legacy EMU suits are 40+ years old with known reliability issues (water intrusion incidents). The new suit program has experienced significant delays and cost overruns. Critical components include: life support backpack (PLSS), helmet with 3D-printed polycarbonate visor, regenerable CO2 scrubber, advanced thermal garment, and dust-resistant pressure bearings. For Artemis lunar surface EVAs, the suit must handle lunar dust, temperature extremes (-280F to +260F), and provide 8+ hour sortie capability. Current production capacity is essentially one suit at a time — wholly inadequate for Artemis crew needs, ISS maintenance, and commercial station operations simultaneously.',
    estimatedResolution: '2029',
    impactedCompanies: ['axiom-space', 'collins-aerospace', 'lockheed-martin', 'spacex'],
    geopoliticalFactors: ['NASA_Artemis_Dependency', 'Sole_Source_Risk'],
  },

  // ── Communications ─────────────────────────────────────────

  {
    id: 'shortage-28',
    material: 'Ka-Band Phased Array Antennas',
    category: 'communications',
    affectedProducts: ['leo_broadband_satellites', 'data_relay_systems', 'ground_terminals', 'aero_connectivity'],
    severity: 'medium',
    alternativeSuppliers: ['ball-aerospace', 'viasat', 'hughes-echostar', 'kymeta', 'thinkom'],
    notes: 'Ka-band (26.5-40 GHz) electronically steered phased array antennas are the backbone of LEO broadband constellations. Ball Aerospace, Viasat, and Hughes (EchoStar) produce flight-qualified units, with Kymeta and ThinKom providing flat-panel user terminal variants. Demand is exploding from Telesat Lightspeed (298 satellites), Amazon Kuiper (3,236 satellites), and SDA Tranche proliferated constellations. Each satellite may need 2-4 phased array panels. The compound semiconductor (GaAs, GaN) MMIC chips driving the arrays are themselves in tight supply. User terminal production at millions of units per year (Starlink, Kuiper) further strains the GaN/GaAs wafer supply chain.',
    estimatedResolution: '2027',
    impactedCompanies: ['ball-aerospace', 'maxar', 'l3harris', 'northrop-grumman', 'airbus-defence-space'],
    geopoliticalFactors: ['GaN_Wafer_Supply', 'Spectrum_Competition'],
  },
  {
    id: 'shortage-29',
    material: 'Optical Communication Terminals (Flight-Qualified)',
    category: 'communications',
    affectedProducts: ['intersatellite_links', 'ground_to_space_lasercom', 'data_relay', 'space_internet_backbone'],
    severity: 'high',
    alternativeSuppliers: ['mynaric', 'tesat-airbus', 'caci-sa-photonics', 'general-atomics-ois'],
    notes: 'Optical inter-satellite link (OISL) terminals are the most demanded new space component of the 2020s. NASA LCRD demonstrated space-to-ground lasercom at 1.2 Gbps. SDA Tranche 2/3 requires hundreds of terminals for the proliferated LEO mesh network. SpaceX Starlink is adding laser links to every satellite (6,000+ planned). Mynaric (CONDOR), Tesat-Spacecom/Airbus (SCOT80), CACI/SA Photonics, and General Atomics Orbital Integrated Solutions are racing to scale production. Current combined global production capacity is estimated at 100-200 terminals/year, but demand is 1,000+/year and growing. Precision optical assemblies, space-qualified telescope systems, fine-pointing mechanisms, and high-power 1550nm lasers all have individual bottlenecks.',
    estimatedResolution: '2028',
    impactedCompanies: ['mynaric', 'northrop-grumman', 'l3harris', 'lockheed-martin', 'spacex'],
    geopoliticalFactors: ['SDA_Procurement_Surge', 'Optical_Component_Supply'],
  },
  {
    id: 'shortage-30',
    material: 'Deep Space Transponders (X-Band/Ka-Band)',
    category: 'communications',
    affectedProducts: ['deep_space_telecom', 'planetary_probes', 'mars_relay', 'lunar_comm_relay'],
    severity: 'medium',
    alternativeSuppliers: ['l3harris', 'general-dynamics-mission-systems', 'thales-alenia'],
    notes: 'Deep space transponders operating at X-band (7-8 GHz uplink, 8.4 GHz downlink) and Ka-band (32 GHz) for NASA Deep Space Network (DSN) compatibility are produced by L3Harris and General Dynamics Mission Systems. Production volumes are tiny (5-15 units/year) but each unit requires extensive qualification and testing. With the increase in lunar missions (Artemis, CLPS, Gateway, commercial landers) and Mars missions (MSR, future crewed), demand is outpacing the low-rate production line. Each transponder is effectively custom-built. ESA uses Thales Alenia-built transponders compatible with ESTRACK. The shift to optical deep space communications (DSOC) may eventually reduce transponder demand, but RF backup will remain required for decades.',
    estimatedResolution: '2027',
    impactedCompanies: ['l3harris', 'northrop-grumman', 'lockheed-martin', 'boeing', 'intuitive-machines', 'astrobotic'],
    geopoliticalFactors: ['NASA_DSN_Capacity', 'Deep_Space_Mission_Surge'],
  },

  // ── Propulsion (Extended) ──────────────────────────────────

  {
    id: 'shortage-31',
    material: 'Green Propellant (AF-M315E / LMP-103S)',
    category: 'propulsion',
    affectedProducts: ['satellite_thrusters', 'cubesat_propulsion', 'spacecraft_attitude_control', 'lunar_landers'],
    severity: 'medium',
    alternativeSuppliers: ['bradford-space', 'aerojet-rocketdyne-gr22', 'dawn-aerospace'],
    notes: 'AF-M315E (now marketed as ASCENT by Aerojet Rocketdyne) and LMP-103S (used by Bradford Space HPGP system) are hydroxyl ammonium nitrate (HAN) and ammonium dinitramide (ADN) based propellants replacing toxic hydrazine. NASA GPIM flight demonstrated AF-M315E in 2019. Green propellants offer higher density-Isp, lower toxicity, and simplified ground handling. However, production is limited — Aerojet Rocketdyne (GR-22 thruster) and Bradford Space (HPGP 1N-22N thrusters) are the only qualified propulsion system providers. Dawn Aerospace (New Zealand) is developing bipropellant green alternatives. Chemical precursor supply chains for HAN and ADN are narrow. As satellite operators increasingly specify green propulsion for ESG/regulatory reasons, demand is outpacing the production ramp.',
    estimatedResolution: '2027',
    impactedCompanies: ['bradford-space', 'busek', 'rocket-lab', 'maxar'],
    geopoliticalFactors: ['REACH_Regulation_Hydrazine', 'Green_Propulsion_Mandates'],
  },
  {
    id: 'shortage-32',
    material: 'Large Xenon/Krypton Tanks for Electric Propulsion',
    category: 'propulsion',
    affectedProducts: ['electric_propulsion_systems', 'satellite_xenon_storage', 'hall_thruster_feed_systems', 'ion_engine_propellant'],
    severity: 'high',
    alternativeSuppliers: ['cobham-advanced', 'ruag-space', 'arde-inc', 'mt-aerospace'],
    notes: 'Demand for high-pressure xenon and krypton storage tanks has surged dramatically with the proliferation of electric propulsion (EP) satellites. SpaceX Starlink (krypton Hall thrusters on 6,000+ satellites), OneWeb, SDA proliferated LEO, and virtually all modern GEO satellites use EP. COPV (composite overwrapped pressure vessels) rated for 350+ bar xenon/krypton storage at space qualification standards are produced by a handful of suppliers: Cobham, RUAG Space (Switzerland), ARDE Inc. (US), and MT Aerospace (Germany). Global xenon gas supply itself is constrained — xenon is a byproduct of air separation plants, and Ukraine (a major producer) has had supply disruptions. Krypton is more abundant but requires thruster redesign. Tank lead times are 12-18 months.',
    estimatedResolution: '2027',
    impactedCompanies: ['spacex', 'northrop-grumman', 'maxar', 'lockheed-martin', 'airbus-defence-space'],
    geopoliticalFactors: ['Xenon_Gas_Supply', 'Ukraine_Production_Disruption'],
  },
  {
    id: 'shortage-33',
    material: 'Hall Effect Thruster Cathodes',
    category: 'propulsion',
    affectedProducts: ['hall_thrusters', 'electric_propulsion', 'station_keeping_systems'],
    severity: 'medium',
    alternativeSuppliers: ['busek', 'exotrail', 'safran-pps', 'sitael'],
    notes: 'Hollow cathodes are the critical wear-limited component of Hall effect thrusters (HETs), the most popular electric propulsion technology for LEO and GEO satellites. Cathode lifetime determines thruster lifetime. Barium oxide (BaO) impregnated tungsten insert cathodes are the heritage design, but lanthanum hexaboride (LaB6) cathodes offer longer life. Busek (US), Exotrail (France), Safran (PPS-series), and SITAEL (Italy) produce flight-qualified cathodes. Each Starlink satellite has a cathode; replacements and new constellation builds consume thousands annually. The barium oxide insert manufacturing process is specialized and supply of aerospace-grade BaO inserts is limited to a few global sources.',
    estimatedResolution: '2026',
    impactedCompanies: ['busek', 'spacex', 'northrop-grumman', 'safran', 'airbus-defence-space'],
  },

  // ── Lunar/Mars-Specific ────────────────────────────────────

  {
    id: 'shortage-34',
    material: 'Lunar Regolith-Compatible Seals and Bearings',
    category: 'robotics',
    affectedProducts: ['lunar_rover_wheels', 'lunar_drill_mechanisms', 'spacesuit_bearings', 'lunar_habitat_airlocks', 'lunar_mining_equipment'],
    severity: 'critical',
    alternativeSuppliers: ['parker-hannifin-advanced', 'skf-aerospace', 'custom-nasa-development'],
    notes: 'Lunar regolith dust is one of the most destructive materials ever encountered in engineering. Apollo-era experience showed that conventional seals, bearings, and mechanisms are rapidly destroyed by the abrasive, electrostatically charged, sub-micron glass shards in lunar soil. No qualified supplier produces regolith-resistant seals and bearings at scale. The problem remains unsolved at the systems level — NASA GRC, Parker Hannifin, and SKF Aerospace are conducting research, but TRL is 3-5 for most solutions. Every mechanism on the lunar surface (rovers, drills, airlocks, suit joints, ISRU equipment) needs regolith-tolerant seals. This is a fundamental blocker for sustained lunar presence. Mitigation approaches include labyrinth seals, magnetic fluid seals, electrostatic dust repulsion, and sacrificial seal designs, but none are flight-proven.',
    estimatedResolution: '2030+',
    impactedCompanies: ['intuitive-machines', 'astrobotic', 'lockheed-martin', 'blue-origin', 'spacex'],
    geopoliticalFactors: ['NASA_Artemis_Dependency', 'Lunar_Surface_Systems_Gap'],
  },
  {
    id: 'shortage-35',
    material: 'Radiation-Hardened Power Electronics for Deep Space',
    category: 'power',
    affectedProducts: ['power_converters', 'solar_array_regulators', 'battery_management', 'motor_controllers', 'cislunar_systems'],
    severity: 'high',
    alternativeSuppliers: ['microchip-technology', 'infineon-hirex', 'stmicroelectronics', 'vishay-space'],
    notes: 'Beyond LEO, spacecraft encounter significantly higher radiation levels (Van Allen belts, solar particle events, galactic cosmic rays) that exceed the qualification envelope of most LEO-rated components. Cislunar, lunar surface, and Mars transit missions need power electronics (DC-DC converters, point-of-load regulators, GaN/SiC power switches, battery charge controllers) rated for total ionizing dose (TID) of 100-300+ krad and single-event effects (SEE) immunity. Microchip Technology, Infineon (HIREX product line), and STMicroelectronics offer some qualified parts, but the product range is limited and based on older silicon processes. Next-generation SiC and GaN power devices have minimal space heritage beyond LEO. Every cislunar mission — Lunar Gateway, CLPS landers, Artemis support vehicles — requires these components. Lead times for deep-space-qualified parts are 18-24 months.',
    estimatedResolution: '2028',
    impactedCompanies: ['lockheed-martin', 'northrop-grumman', 'intuitive-machines', 'astrobotic', 'boeing'],
    geopoliticalFactors: ['Deep_Space_Qualification_Gap', 'SiC_GaN_Space_Heritage'],
  },
];

// ============================================================
// Helper Functions
// ============================================================

export function getCompanyById(id: string): SupplyChainCompany | undefined {
  return SUPPLY_CHAIN_COMPANIES.find((c) => c.id === id);
}

export function getCompaniesByTier(tier: SupplyChainTier): SupplyChainCompany[] {
  return SUPPLY_CHAIN_COMPANIES.filter((c) => c.tier === tier);
}

export function getCompaniesByCountry(countryCode: string): SupplyChainCompany[] {
  return SUPPLY_CHAIN_COMPANIES.filter((c) => c.countryCode === countryCode);
}

export function getCompanySuppliers(companyId: string): SupplyChainCompany[] {
  const company = getCompanyById(companyId);
  if (!company) return [];
  return company.suppliers
    .map((s) => SUPPLY_CHAIN_COMPANIES.find((c) => c.id === s))
    .filter((c): c is SupplyChainCompany => c !== undefined);
}

export function getCompanyCustomers(companyId: string): SupplyChainCompany[] {
  const company = getCompanyById(companyId);
  if (!company) return [];
  return company.customers
    .map((c) => SUPPLY_CHAIN_COMPANIES.find((co) => co.id === c))
    .filter((c): c is SupplyChainCompany => c !== undefined);
}

export function getRelationshipsForCompany(companyId: string): SupplyRelationship[] {
  return SUPPLY_RELATIONSHIPS.filter(
    (r) => r.supplierId === companyId || r.customerId === companyId
  );
}

export function getHighRiskRelationships(): SupplyRelationship[] {
  return SUPPLY_RELATIONSHIPS.filter((r) => r.geopoliticalRisk === 'high');
}

export function getShortagesByCategory(category: string): SupplyShortage[] {
  return SUPPLY_SHORTAGES.filter((s) => s.category === category);
}

export function getCriticalShortages(): SupplyShortage[] {
  return SUPPLY_SHORTAGES.filter((s) => s.severity === 'critical');
}

export function getSupplyChainStats() {
  const companies = SUPPLY_CHAIN_COMPANIES;
  const relationships = SUPPLY_RELATIONSHIPS;
  const shortages = SUPPLY_SHORTAGES;

  return {
    totalCompanies: companies.length,
    primeContractors: companies.filter((c) => c.tier === 'prime').length,
    tier1Suppliers: companies.filter((c) => c.tier === 'tier1').length,
    tier2Suppliers: companies.filter((c) => c.tier === 'tier2').length,
    tier3Suppliers: companies.filter((c) => c.tier === 'tier3').length,
    totalRelationships: relationships.length,
    highRiskRelationships: relationships.filter((r) => r.geopoliticalRisk === 'high').length,
    criticalRelationships: relationships.filter((r) => r.isCritical).length,
    totalShortages: shortages.length,
    criticalShortages: shortages.filter((s) => s.severity === 'critical').length,
    highSeverityShortages: shortages.filter((s) => s.severity === 'high').length,
    countriesWithHighRisk: ['CHN', 'RUS', 'COD'],
    usCompanies: companies.filter((c) => c.countryCode === 'USA').length,
    europeanCompanies: companies.filter((c) => ['EUR', 'FRA', 'DEU', 'GBR'].includes(c.countryCode)).length,
  };
}
