import { NextResponse } from 'next/server';
import prisma from '@/lib/db';
import { internalError } from '@/lib/errors';
import { logger } from '@/lib/logger';

export const dynamic = 'force-dynamic';

export async function GET() {
  try {
    const [
      companies,
      newsArticles,
      spaceEvents,
      contactSubmissions,
      newsletterSubscribers,
      users,
      blogPosts,
      blogSources,
      spaceResources,
      launchProviders,
      businessOpportunities,
      exportClassifications,
      proposedRegulations,
      legalUpdates,
      planetaryBodies,
      surfaceLanders,
      solarFlares,
      orbitalSlots,
      satelliteOperators,
      debrisObjects,
      conjunctionEvents,
      insurancePolicies,
      spectrumAllocations,
      spectrumFilings,
      spaceJobPostings,
      launchWindows,
      celestialDestinations,
      governmentContracts,
      miningBodies,
      commodityPrices,
      regulatoryAgencies,
      spaceLicenseTypes,
      internationalSpaceTreaties,
      blueprints,
      orbitalServices,
      policyChanges,
      spaceLawCases,
      featureRequests,
      helpRequests,
    ] = await Promise.all([
      prisma.spaceCompany.count(),
      prisma.newsArticle.count(),
      prisma.spaceEvent.count(),
      prisma.contactSubmission.count(),
      prisma.newsletterSubscriber.count(),
      prisma.user.count(),
      prisma.blogPost.count(),
      prisma.blogSource.count(),
      prisma.spaceResource.count(),
      prisma.launchProvider.count(),
      prisma.businessOpportunity.count(),
      prisma.exportClassification.count(),
      prisma.proposedRegulation.count(),
      prisma.legalUpdate.count(),
      prisma.planetaryBody.count(),
      prisma.surfaceLander.count(),
      prisma.solarFlare.count(),
      prisma.orbitalSlot.count(),
      prisma.satelliteOperator.count(),
      prisma.debrisObject.count(),
      prisma.conjunctionEvent.count(),
      prisma.insurancePolicy.count(),
      prisma.spectrumAllocation.count(),
      prisma.spectrumFiling.count(),
      prisma.spaceJobPosting.count(),
      prisma.launchWindow.count(),
      prisma.celestialDestination.count(),
      prisma.governmentContract.count(),
      prisma.miningBody.count(),
      prisma.commodityPrice.count(),
      prisma.regulatoryAgency.count(),
      prisma.spaceLicenseType.count(),
      prisma.internationalSpaceTreaty.count(),
      prisma.blueprint.count(),
      prisma.orbitalService.count(),
      prisma.policyChange.count(),
      prisma.spaceLawCase.count(),
      prisma.featureRequest.count(),
      prisma.helpRequest.count(),
    ]);

    return NextResponse.json({
      stats: {
        companies,
        newsArticles,
        spaceEvents,
        contactSubmissions,
        newsletterSubscribers,
        users,
        blogPosts,
        blogSources,
        spaceResources,
        launchProviders,
        businessOpportunities,
        exportClassifications,
        proposedRegulations,
        legalUpdates,
        planetaryBodies,
        surfaceLanders,
        solarFlares,
        orbitalSlots,
        satelliteOperators,
        debrisObjects,
        conjunctionEvents,
        insurancePolicies,
        spectrumAllocations,
        spectrumFilings,
        spaceJobPostings,
        launchWindows,
        celestialDestinations,
        governmentContracts,
        miningBodies,
        commodityPrices,
        regulatoryAgencies,
        spaceLicenseTypes,
        internationalSpaceTreaties,
        blueprints,
        orbitalServices,
        policyChanges,
        spaceLawCases,
        featureRequests,
        helpRequests,
      },
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    logger.error('Failed to fetch dashboard overview', { error: error instanceof Error ? error.message : String(error) });
    return internalError('Failed to fetch dashboard overview');
  }
}
