'use client';

import { useEffect, useState } from 'react';
import type { GameState, GameReport, GameTab } from '@/lib/game/types';
import type { QuarterlyReport } from '@/lib/game/quarterly-reports';
import { LOCATION_MAP } from '@/lib/game/solar-system';
import { RESOURCE_MAP } from '@/lib/game/resources';
import type { ResourceId } from '@/lib/game/resources';
import { formatMoney, formatGameDate } from '@/lib/game/formulas';
import { quarterKey } from '@/lib/game/corp-report-registry';
import { toast } from '@/lib/toast';
import { ConsolePanel, DataChip } from './chrome';
import GameIcon, { type GameIconGlow } from './GameIcon';
import { resolveIcon, type IconName } from '@/lib/game/icons';
// Wave V3 (docs/VISUAL_DEPTH_2026-08.md §V3): "A unified Situation Log
// replaces scattered alerts... lives as the promoted content of the Reports
// tab (Reports remains the tab id — no IA change for mechanics)."
import SituationLog from './SituationLog';
import CompetitivePosturePanel from './CompetitivePosturePanel';
// AAA Round 1 wave E4 (docs/AAA_PROGRAM_2026-08.md §R1-E4). The Legacy Hall
// lands here rather than in a 29th tab, and rather than in the Victory tab
// that would gate a Tier-1 milestone system behind a Tier-5 unlock. Reports is
// where the corporation's *record* already lives — mail, situation log, and
// the automatic quarterly filings — and Round 1's own framing for the Hall is
// a ledger, not a mechanic: "a 22nd-century corporation with >$1B
// extraterrestrial assets is required by the Accord to report publicly; this
// is the corporate history that reporting produces."
import LegacyHallPanel from './LegacyHallPanel';
// AAA Program Round 2 (docs/AAA_PROGRAM_2026-08.md "Round 2"): the fifth
// Reports sub-view — the Accord emergency register, the exposure bar and
// its postures, and the Stabilization Assessment. No 29th tab.
import SystemicCrisisPanel from './SystemicCrisisPanel';
import { getCrisisStatus, type CrisisApproachId } from '@/lib/game/systemic-crises';
import { useHubSubView } from './useHubSubView';
import type { OrderQueueTarget } from '@/lib/game/order-queue';

// ─── Helpers ─────────────────────────────────────────────────────────────────

const REPORT_TYPE_ICON: Record<GameReport['type'], IconName> = {
  probe_discovery: 'megastructures',
  system_alert: 'warning',
  milestone: 'leaderboard',
};

const REPORT_TYPE_GLOW: Record<GameReport['type'], GameIconGlow> = {
  probe_discovery: 'cyan',
  system_alert: 'amber',
  milestone: 'purple',
};

function getReportAccent(type: GameReport['type']): string {
  switch (type) {
    case 'probe_discovery': return '#22d3ee'; // cyan
    case 'system_alert': return '#f59e0b'; // amber
    case 'milestone': return '#a78bfa'; // purple
  }
}

function formatTimeAgo(ms: number): string {
  const diff = Date.now() - ms;
  const seconds = Math.floor(diff / 1000);
  if (seconds < 60) return 'Just now';
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

function formatRewardMoney(amount: number): string {
  if (amount >= 1_000_000_000) return `$${(amount / 1_000_000_000).toFixed(1)}B`;
  if (amount >= 1_000_000) return `$${(amount / 1_000_000).toFixed(0)}M`;
  if (amount >= 1_000) return `$${(amount / 1_000).toFixed(0)}K`;
  return `$${amount}`;
}

// ─── Quarterly Reports sub-view ─────────────────────────────────────────────
// Per CLAUDE.md: "Every corporation produces an automatic public quarterly —
// revenue, growth rate, notable acquisitions. Fuel for rivalry and narrative."
// Reports are generated by src/lib/game/quarterly-reports.ts and hooked into
// the game-clock effect in space-tycoon/page.tsx.

function QuarterlyGrowthChip({ pct }: { pct: number | null }) {
  if (pct === null) {
    return (
      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-mono border border-white/10 text-slate-400 bg-white/[0.03]">
        First report on file
      </span>
    );
  }
  const positive = pct >= 0;
  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-mono font-bold border ${
        positive
          ? 'text-emerald-300 border-emerald-500/30 bg-emerald-500/10'
          : 'text-red-300 border-red-500/30 bg-red-500/10'
      }`}
    >
      <GameIcon name={positive ? 'arrow-up' : 'arrow-down'} size={10} />
      {positive ? '+' : ''}{pct.toFixed(1)}% net worth
    </span>
  );
}

// ─── Corporate Registry publish button ──────────────────────────────────────
// Per CLAUDE.md: "Corporate scouting is legitimate gameplay... Quarterly
// corporate reports. Every corporation produces an automatic public
// quarterly — revenue, growth rate, notable acquisitions. Fuel for rivalry
// and narrative." This is the opt-in trigger: nothing is ever published
// without the player explicitly clicking through the confirm step below.
// POSTs to /api/space-tycoon/corp-report, which derives corpId/corpName from
// the player's own session (see that route) — the client never claims an
// identity, it just sends the report snapshot.

function PublishToRegistry({ report }: { report: QuarterlyReport }) {
  const [status, setStatus] = useState<'idle' | 'confirming' | 'publishing' | 'published' | 'error'>('idle');
  const key = quarterKey(report.quarterIndex);

  // Check publish state once per report card mount — cheap, own-corp-only
  // read (see GET handler in the corp-report route).
  useEffect(() => {
    let cancelled = false;
    fetch('/api/space-tycoon/corp-report')
      .then((res) => (res.ok ? res.json() : null))
      .then((data) => {
        if (!cancelled && data?.publishedQuarters?.includes(key)) {
          setStatus('published');
        }
      })
      .catch(() => { /* non-critical — publish button just won't pre-populate */ });
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key]);

  const handlePublish = async () => {
    setStatus('publishing');
    try {
      const res = await fetch('/api/space-tycoon/corp-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          quarterIndex: report.quarterIndex,
          quarterNumber: report.quarterNumber,
          gameYear: report.gameYear,
          quarterOfYear: report.quarterOfYear,
          gameDate: report.gameDate,
          revenue: report.revenue,
          costs: report.costs,
          profit: report.profit,
          netWorth: report.netWorth,
          fleetCount: report.fleetCount,
          buildingCount: report.buildingCount,
          corporationTier: report.corporationTier,
          notableEvents: report.notableEvents,
          growthRatePct: report.growthRatePct,
          governorTaxQuarterly: report.governorTaxQuarterly,
          subsidiaryIncomeQuarterly: report.subsidiaryIncomeQuarterly,
          insurancePremiumQuarterly: report.insurancePremiumQuarterly,
          outstandingRepairCost: report.outstandingRepairCost,
        }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => null);
        throw new Error(data?.error || 'Publish failed');
      }
      setStatus('published');
      toast.success('Your Quarter ' + report.quarterNumber + ' report is now visible on the public Corporate Registry.', 'Published');
    } catch (err) {
      setStatus('error');
      toast.error(err instanceof Error ? err.message : 'Failed to publish report', 'Publish failed');
    }
  };

  if (status === 'published') {
    return (
      <DataChip tone="good" icon="services" className="rounded-full px-2 py-1">
        Published to Corporate Registry
      </DataChip>
    );
  }

  if (status === 'confirming') {
    return (
      <div className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-2.5 space-y-2">
        <p className="text-[11px] text-amber-200/90">
          This report — revenue, profit, net worth, and notable events — becomes publicly visible on the{' '}
          <span className="font-semibold">SpaceNexus Corporate Registry</span>, linked from your public corp profile.
          Anyone can view it, no login required.
        </p>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handlePublish}
            className="min-h-[36px] px-3 py-1.5 rounded-md text-[11px] font-bold bg-cyan-500 hover:bg-cyan-400 text-black transition-colors"
          >
            Confirm &amp; Publish
          </button>
          <button
            type="button"
            onClick={() => setStatus('idle')}
            className="min-h-[36px] px-3 py-1.5 rounded-md text-[11px] font-medium text-slate-400 hover:text-white transition-colors"
          >
            Cancel
          </button>
        </div>
      </div>
    );
  }

  return (
    <button
      type="button"
      onClick={() => setStatus('confirming')}
      disabled={status === 'publishing'}
      aria-busy={status === 'publishing'}
      className="min-h-[36px] inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-[11px] font-semibold border border-cyan-500/30 bg-cyan-500/10 text-cyan-300 hover:bg-cyan-500/20 transition-colors disabled:opacity-50"
    >
      <GameIcon name="services" size={13} />
      {status === 'publishing' ? 'Publishing…' : status === 'error' ? 'Retry publish' : 'Publish to the SpaceNexus Corporate Registry (public)'}
    </button>
  );
}

// ─── Weekly report email opt-in (2026-09-01) ────────────────────────────────
// The game's first email: a Monday per-corporation digest built from
// server-owned rows (src/lib/game/weekly-report-email.ts). Default OFF;
// persisted via the same route that owns the other per-profile opt-in
// (mentorOptIn — /api/space-tycoon/mentorship, action 'set_weekly_report').
// A signed-out or profile-less player simply sees nothing here.
function WeeklyReportOptIn() {
  const [enabled, setEnabled] = useState<boolean | null>(null);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    let cancelled = false;
    fetch('/api/space-tycoon/mentorship', { credentials: 'same-origin' })
      .then(r => (r.ok ? r.json() : null))
      .then(data => {
        if (!cancelled && data && typeof data.weeklyReportEmail === 'boolean') setEnabled(data.weeklyReportEmail);
      })
      .catch(() => { /* non-critical — the toggle just stays hidden */ });
    return () => { cancelled = true; };
  }, []);

  if (enabled === null) return null;

  const toggle = async (next: boolean) => {
    setSaving(true);
    const prev = enabled;
    setEnabled(next);
    try {
      const res = await fetch('/api/space-tycoon/mentorship', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'same-origin',
        body: JSON.stringify({ action: 'set_weekly_report', enabled: next }),
      });
      if (!res.ok) throw new Error('save failed');
      toast.success(next ? 'A corporate report lands in your inbox every Monday.' : 'Weekly report emails are off.', next ? 'Weekly report on' : 'Weekly report off');
    } catch {
      setEnabled(prev);
      toast.error('Could not save that preference. Try again.', 'Not saved');
    } finally {
      setSaving(false);
    }
  };

  return (
    <label className="flex items-start gap-3 rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-2.5 cursor-pointer min-h-[44px]">
      <input
        type="checkbox"
        className="mt-0.5 h-4 w-4 accent-cyan-400"
        checked={enabled}
        disabled={saving}
        onChange={e => toggle(e.target.checked)}
        aria-describedby="weekly-report-optin-help"
      />
      <span className="text-[11px] leading-snug">
        <span className="text-white font-medium">Email me a weekly corporation report</span>
        <span id="weekly-report-optin-help" className="block text-slate-500">
          Mondays: net worth and rank, a 7-day cash-flow table by reason, market volume, notable events and your latest published quarterly. Built from the server ledger only. Off by default; one-click unsubscribe in every email.
        </span>
      </span>
    </label>
  );
}

function QuarterlyReportsView({ state }: { state: GameState }) {
  const reports = state.quarterlyReports || [];
  const [expandedId, setExpandedId] = useState<string | null>(reports.length > 0 ? reports[reports.length - 1].id : null);

  if (reports.length === 0) {
    return (
      <div className="space-y-4">
        <ConsolePanel
          title="No Quarterly Reports Yet"
          icon="market"
          subtitle="Your first automatic corporate quarterly generates once a full in-game quarter (3 game-months) has elapsed since founding — revenue, profit, net worth, and growth rate, all summarized here."
        />
        <WeeklyReportOptIn />
      </div>
    );
  }

  const newestFirst = [...reports].reverse();
  const latestId = reports[reports.length - 1].id;

  return (
    <div className="space-y-4">
      {/* Era timeline — one node per completed quarter */}
      <ConsolePanel title="Corporate Era Timeline" icon="cal-corporate-era" compact asH3>
        <div
          className="flex items-center gap-1.5 overflow-x-auto pb-1"
          role="list"
          aria-label="Quarterly report history, oldest to newest"
        >
          {reports.map(r => {
            const isLatest = r.id === latestId;
            const isExpanded = expandedId === r.id;
            return (
              <button
                key={r.id}
                type="button"
                role="listitem"
                onClick={() => setExpandedId(r.id)}
                aria-current={isLatest ? 'true' : undefined}
                aria-pressed={isExpanded}
                title={`Quarter ${r.quarterNumber} — ${formatGameDate(r.gameDate)}`}
                className={`season-node shrink-0 min-w-[44px] min-h-[44px] w-11 h-11 rounded-full flex flex-col items-center justify-center text-[10px] font-bold border game-number transition-all focus:outline-none focus:ring-2 focus:ring-cyan-400 ${
                  isExpanded
                    ? 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40'
                    : isLatest
                      ? 'bg-amber-500/15 text-amber-300 border-amber-500/30 season-node-current'
                      : 'bg-white/[0.04] text-slate-300 border-white/10 season-node-claimed'
                }`}
              >
                <span aria-hidden="true">Q{r.quarterNumber}</span>
              </button>
            );
          })}
        </div>
        <p className="text-[10px] text-slate-500 mt-2">
          {reports.length} quarter{reports.length !== 1 ? 's' : ''} on record · latest is Q{reports[reports.length - 1].quarterNumber}, {formatGameDate(reports[reports.length - 1].gameDate)}
        </p>
      </ConsolePanel>

      {/* Report cards, newest first */}
      <div className="space-y-2">
        {newestFirst.map(r => {
          const isExpanded = expandedId === r.id;
          return (
            <div key={r.id} className="hud-frame relative rounded-xl border border-white/[0.06] bg-white/[0.02]">
              <span className="hud-corner-bl" aria-hidden="true" />
              <span className="hud-corner-br" aria-hidden="true" />
              <button
                type="button"
                onClick={() => setExpandedId(isExpanded ? null : r.id)}
                aria-expanded={isExpanded}
                className="w-full flex items-center justify-between gap-3 px-3 py-2.5 text-left min-h-[44px]"
              >
                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="font-hud text-sm font-semibold text-white">
                      Quarter {r.quarterNumber} Report
                    </h3>
                    {r.id === latestId && (
                      <DataChip tone="warn" className="rounded-full font-bold uppercase tracking-wider">
                        Latest
                      </DataChip>
                    )}
                  </div>
                  <p className="text-[10px] text-slate-500 mt-0.5">{formatGameDate(r.gameDate)} · Tier {r.corporationTier}</p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <QuarterlyGrowthChip pct={r.growthRatePct} />
                  <svg
                    className={`w-4 h-4 transition-transform ${isExpanded ? 'rotate-180' : ''}`}
                    style={{ color: 'rgba(255,255,255,0.3)' }}
                    fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2} aria-hidden="true"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                  </svg>
                </div>
              </button>

              {isExpanded && (
                <div className="px-3 pb-3 border-t border-white/[0.04]">
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-3">
                    <div className="rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-2">
                      <p className="text-[10px] uppercase tracking-wider text-slate-500">Revenue</p>
                      <p className="game-number text-emerald-300 text-sm font-bold">{formatMoney(r.revenue)}</p>
                    </div>
                    <div className="rounded-lg border border-red-500/20 bg-red-500/5 p-2">
                      <p className="text-[10px] uppercase tracking-wider text-slate-500">Costs</p>
                      <p className="game-number text-red-300 text-sm font-bold">{formatMoney(r.costs)}</p>
                    </div>
                    <div className={`rounded-lg border p-2 ${r.profit >= 0 ? 'border-cyan-500/20 bg-cyan-500/5' : 'border-amber-500/20 bg-amber-500/5'}`}>
                      <p className="text-[10px] uppercase tracking-wider text-slate-500">Profit</p>
                      <p className={`game-number text-sm font-bold ${r.profit >= 0 ? 'text-cyan-300' : 'text-amber-300'}`}>{formatMoney(r.profit)}</p>
                    </div>
                    <div className="rounded-lg border border-purple-500/20 bg-purple-500/5 p-2">
                      <p className="text-[10px] uppercase tracking-wider text-slate-500">Net Worth</p>
                      <p className="game-number text-purple-300 text-sm font-bold">{formatMoney(r.netWorth)}</p>
                    </div>
                  </div>
                  <div className="flex flex-wrap gap-1.5 mt-2">
                    <DataChip icon="fleet">{r.fleetCount} ship{r.fleetCount !== 1 ? 's' : ''}</DataChip>
                    <DataChip icon="build">{r.buildingCount} building{r.buildingCount !== 1 ? 's' : ''}</DataChip>
                  </div>

                  {/* Wave F (h): previously-invisible P&L lines. Older stored
                      reports (pre-Wave-F) don't have these fields — hide the
                      block entirely rather than showing misleading zeros. */}
                  {(r.governorTaxQuarterly !== undefined) && (
                    <div className="mt-3 pt-2 border-t border-white/[0.04]">
                      <p className="text-[10px] font-semibold text-white/50 uppercase tracking-wider mb-1.5">P&amp;L Detail</p>
                      <div className="grid grid-cols-2 gap-1.5 text-[10px]">
                        <div className="flex justify-between px-2 py-1 rounded bg-white/[0.02]">
                          <span className="text-slate-500">Governor Tax</span>
                          <span className={(r.governorTaxQuarterly || 0) > 0 ? 'text-emerald-300 font-mono' : 'text-slate-500 font-mono'}>
                            +{formatMoney(r.governorTaxQuarterly || 0)}
                          </span>
                        </div>
                        <div className="flex justify-between px-2 py-1 rounded bg-white/[0.02]">
                          <span className="text-slate-500">Subsidiary Income</span>
                          <span className={`font-mono ${(r.subsidiaryIncomeQuarterly || 0) >= 0 ? 'text-emerald-300' : 'text-red-300'}`}>
                            {(r.subsidiaryIncomeQuarterly || 0) >= 0 ? '+' : ''}{formatMoney(r.subsidiaryIncomeQuarterly || 0)}
                          </span>
                        </div>
                        <div className="flex justify-between px-2 py-1 rounded bg-white/[0.02]">
                          <span className="text-slate-500">Insurance Premiums</span>
                          <span className={(r.insurancePremiumQuarterly || 0) > 0 ? 'text-red-300 font-mono' : 'text-slate-500 font-mono'}>
                            −{formatMoney(r.insurancePremiumQuarterly || 0)}
                          </span>
                        </div>
                        <div className="flex justify-between px-2 py-1 rounded bg-white/[0.02]">
                          <span className="text-slate-500">Outstanding Repairs</span>
                          <span className={(r.outstandingRepairCost || 0) > 0 ? 'text-amber-300 font-mono' : 'text-slate-500 font-mono'}>
                            {formatMoney(r.outstandingRepairCost || 0)}
                          </span>
                        </div>
                      </div>
                    </div>
                  )}

                  {r.notableEvents.length > 0 && (
                    <div className="mt-3">
                      <p className="text-[10px] font-semibold text-white/50 uppercase tracking-wider mb-1.5">Notable This Quarter</p>
                      <ul className="space-y-1 text-[11px] text-slate-300">
                        {r.notableEvents.map((title, i) => (
                          <li key={i} className="flex items-start gap-1.5">
                            <span aria-hidden="true" className="text-slate-600">·</span> {title}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  <div className="mt-3 pt-2 border-t border-white/[0.04]">
                    <PublishToRegistry report={r} />
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
      <WeeklyReportOptIn />
    </div>
  );
}

// ─── Component ───────────────────────────────────────────────────────────────

interface ReportsPanelProps {
  state: GameState;
  onMarkRead: (reportId: string) => void;
  onMarkAllRead: () => void;
  /** Wave V3: Situation Log row navigation — same tab-switch + map-focus
   *  handlers the Outliner uses (page.tsx wires both to the identical
   *  setTab/setMapFocusRequest pair, so a click does the same thing from
   *  either surface). */
  onNavigateTab: (tab: GameTab) => void;
  onFocusMap: (target: OrderQueueTarget) => void;
  /** AAA Round 2 (docs/AAA_PROGRAM_2026-08.md): commit an emergency posture
   *  change. page.tsx owns the GameState hop; SystemicCrisisPanel is a pure
   *  lens like every other sub-view here. */
  onSetCrisisApproach: (approachId: CrisisApproachId) => { ok: boolean; reason?: string };
  /** Six-hub consolidation (2026-09): the Command row (Situation Log, P&L,
   *  Mail, Emergency) and the Records row (Chronicle) drive this panel's view
   *  through the sub-view bus, so the panel's own strip is hidden. Defaults
   *  to false — standalone behaviour unchanged. */
  embedded?: boolean;
}

type ReportsView = 'log' | 'mail' | 'quarterly' | 'legacy' | 'emergency';

export default function ReportsPanel({ state, onMarkRead, onMarkAllRead, onNavigateTab, onFocusMap, onSetCrisisApproach, embedded = false }: ReportsPanelProps) {
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [filter, setFilter] = useState<'all' | 'unread'>('all');
  // 'log' (Situation Log) is the promoted default — it's the surface the
  // Outliner's Attention section deep-links into.
  // Six-hub consolidation: the view is a two-way binding with the shell's
  // hub row (useHubSubView) — a parked or live `reports:*` request lands
  // here, and every change is announced back so the row lights the entry.
  const [topTab, setTopTab] = useHubSubView<ReportsView>(
    'reports',
    'log',
    requested => (requested === 'log' || requested === 'mail' || requested === 'quarterly' || requested === 'legacy' || requested === 'emergency') ? requested : null,
  );
  // AAA Round 2: derived once so the tab strip can badge a live emergency —
  // a crisis a player has to go looking for is a crisis they will miss.
  const crisisStatus = getCrisisStatus(state);
  // AAA Round 2: honour a `reports:emergency` deep-link from the Situation
  // Log / Outliner so a crisis row lands on the Emergency view rather than
  // on the hub's default. Same one-shot consume pattern MarketHubPanel and
  // WorkforcePanel already use.
  // 2026-09-01: the Situation Log's `quarter_closed` row and the quarter-close
  // cinematic's "Publish report" CTA both deep-link to `reports:quarterly`.
  const crisisLive = crisisStatus.eligibility.eligible
    || (crisisStatus.situation != null && !crisisStatus.situation.outcome);

  const reports = [...(state.reports || [])].reverse(); // newest first
  const filteredReports = filter === 'unread' ? reports.filter(r => !r.read) : reports;
  const unreadCount = reports.filter(r => !r.read).length;

  const handleExpand = (report: GameReport) => {
    if (expandedId === report.id) {
      setExpandedId(null);
    } else {
      setExpandedId(report.id);
      if (!report.read) {
        onMarkRead(report.id);
      }
    }
  };

  // Top-level tab strip — shared between the Log, Mail, Quarterly and Legacy
  // Hall sub-views. E4's fourth entry is where this strip stops fitting a
  // 375px viewport, so it scrolls horizontally inside itself (the pattern
  // StandingsHubPanel already uses) rather than pushing the page body wide.
  const TopTabs = (
    <div className="game-tab-bar flex gap-1 overflow-x-auto max-w-full" role="tablist" aria-label="Reports view">
      <button
        type="button"
        role="tab"
        aria-selected={topTab === 'log'}
        onClick={() => setTopTab('log')}
        className={`min-h-[44px] px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors flex items-center gap-1.5 whitespace-nowrap ${
          topTab === 'log' ? 'game-tab-active text-white' : 'text-slate-500 hover:text-white hover:bg-white/[0.04]'
        }`}
      >
        <GameIcon name="warning" size={13} /> Situation Log
      </button>
      <button
        type="button"
        role="tab"
        aria-selected={topTab === 'mail'}
        onClick={() => setTopTab('mail')}
        className={`min-h-[44px] px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors flex items-center gap-1.5 whitespace-nowrap ${
          topTab === 'mail' ? 'game-tab-active text-white' : 'text-slate-500 hover:text-white hover:bg-white/[0.04]'
        }`}
      >
        <GameIcon name="reports" size={13} /> Mail{unreadCount > 0 ? ` (${unreadCount})` : ''}
      </button>
      <button
        type="button"
        role="tab"
        aria-selected={topTab === 'quarterly'}
        onClick={() => setTopTab('quarterly')}
        className={`min-h-[44px] px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors flex items-center gap-1.5 whitespace-nowrap ${
          topTab === 'quarterly' ? 'game-tab-active text-white' : 'text-slate-500 hover:text-white hover:bg-white/[0.04]'
        }`}
      >
        <GameIcon name="market" size={13} /> Quarterly{(state.quarterlyReports || []).length > 0 ? ` (${(state.quarterlyReports || []).length})` : ''}
      </button>
      <button
        type="button"
        role="tab"
        aria-selected={topTab === 'legacy'}
        onClick={() => setTopTab('legacy')}
        className={`min-h-[44px] px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors flex items-center gap-1.5 whitespace-nowrap ${
          topTab === 'legacy' ? 'game-tab-active text-white' : 'text-slate-500 hover:text-white hover:bg-white/[0.04]'
        }`}
      >
        <GameIcon name="scroll" size={13} /> Legacy Hall
      </button>
      <button
        type="button"
        role="tab"
        aria-selected={topTab === 'emergency'}
        onClick={() => setTopTab('emergency')}
        className={`min-h-[44px] px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors flex items-center gap-1.5 whitespace-nowrap ${
          topTab === 'emergency' ? 'game-tab-active text-white' : 'text-slate-500 hover:text-white hover:bg-white/[0.04]'
        }`}
      >
        <GameIcon name="cal-systemic-crisis" size={13} /> Emergency{crisisLive ? ' •' : ''}
      </button>
    </div>
  );

  return (
    <div className="space-y-3">
      {!embedded && (
        <ConsolePanel
          title="Reports & Mail"
          icon="reports"
          subtitle="The Situation Log surfaces everything that needs a decision; Mail holds discovery reports and dispatches; Quarterly holds automated corporate filings; the Legacy Hall holds the permanent record; Emergency holds the Accord’s active crisis register."
          right={TopTabs}
        />
      )}

      {topTab === 'log' ? (
        <div className="space-y-3">
          {/* PvP Discoverability pass (2026-08): the Situation Log is already
              the "everything that needs a decision" surface, so the
              competitive posture readout belongs directly above it. Renders
              nothing for Frontier-protected or mid-FTUE saves. */}
          <CompetitivePosturePanel state={state} onNavigate={onNavigateTab} />
          <SituationLog state={state} onNavigate={onNavigateTab} onFocusMap={onFocusMap} compact />
        </div>
      ) : topTab === 'quarterly' ? (
        <QuarterlyReportsView state={state} />
      ) : topTab === 'legacy' ? (
        <LegacyHallPanel
          state={state}
          onNavigateTab={onNavigateTab}
          onOpenQuarterly={() => setTopTab('quarterly')}
        />
      ) : topTab === 'emergency' ? (
        <SystemicCrisisPanel state={state} onSetApproach={onSetCrisisApproach} />
      ) : reports.length === 0 ? (
        <ConsolePanel
          title="No Reports Yet"
          icon="reports"
          subtitle="Send survey probes to explore locations. When they complete their expeditions, detailed discovery reports will appear here with rewards and recommendations."
        />
      ) : (
        <ConsolePanel
          title="Mailbox"
          icon="reports"
          compact
          right={
            <>
              {unreadCount > 0 && (
                <span aria-live="polite" className="game-number px-2 py-0.5 rounded-full text-[10px] font-bold bg-cyan-500/20 text-cyan-400 border border-cyan-500/30">
                  {unreadCount} unread
                </span>
              )}
              <div className="flex rounded-lg overflow-hidden border border-white/[0.06]">
                <button
                  onClick={() => setFilter('all')}
                  aria-pressed={filter === 'all'}
                  className={`min-h-[44px] px-3 py-1 text-[10px] font-medium transition-colors ${
                    filter === 'all'
                      ? 'bg-white/[0.08] text-white'
                      : 'text-slate-500 hover:text-white hover:bg-white/[0.04]'
                  }`}
                >
                  All ({reports.length})
                </button>
                <button
                  onClick={() => setFilter('unread')}
                  aria-pressed={filter === 'unread'}
                  className={`min-h-[44px] px-3 py-1 text-[10px] font-medium transition-colors ${
                    filter === 'unread'
                      ? 'bg-white/[0.08] text-white'
                      : 'text-slate-500 hover:text-white hover:bg-white/[0.04]'
                  }`}
                >
                  Unread ({unreadCount})
                </button>
              </div>
              {unreadCount > 0 && (
                <button
                  onClick={onMarkAllRead}
                  className="min-h-[44px] px-2 py-1 text-[10px] text-slate-400 hover:text-cyan-400 transition-colors"
                >
                  Mark all read
                </button>
              )}
            </>
          }
        >
          {/* Reports list */}
          {filteredReports.length === 0 && filter === 'unread' && (
            <div className="text-center py-8">
              <p className="text-sm text-slate-500">All reports have been read.</p>
            </div>
          )}

          <div className="space-y-2">
            {filteredReports.map(report => {
              const isExpanded = expandedId === report.id;
              const accent = getReportAccent(report.type);
              const locName = report.locationId ? LOCATION_MAP.get(report.locationId)?.name : null;

              return (
                <div
                  key={report.id}
                  className="holo-row rounded-lg transition-all"
                  style={{
                    background: isExpanded ? 'rgba(255,255,255,0.04)' : 'rgba(255,255,255,0.02)',
                    border: `1px solid ${!report.read ? accent + '40' : 'rgba(255,255,255,0.06)'}`,
                  }}
                >
                  {/* Report header */}
                  <button
                    type="button"
                    onClick={() => handleExpand(report)}
                    aria-expanded={isExpanded}
                    className="w-full flex items-start gap-3 px-3 py-2.5 text-left"
                  >
                    {/* Unread indicator + icon */}
                    <div className="relative flex-shrink-0 mt-0.5">
                      <GameIcon name={REPORT_TYPE_ICON[report.type]} size={20} glow={REPORT_TYPE_GLOW[report.type]} />
                      {!report.read && (
                        <span
                          className="absolute -top-0.5 -right-0.5 w-2 h-2 rounded-full"
                          style={{ background: accent, boxShadow: `0 0 6px ${accent}` }}
                        />
                      )}
                    </div>

                    {/* Title + meta */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <h3
                          className="text-xs font-semibold truncate"
                          style={{ color: !report.read ? '#fff' : 'rgba(255,255,255,0.6)' }}
                        >
                          {report.title}
                        </h3>
                      </div>
                      <div className="flex items-center gap-2 mt-0.5">
                        {locName && (
                          <DataChip tone="neutral">{locName}</DataChip>
                        )}
                        <span className="text-[10px]" style={{ color: 'rgba(255,255,255,0.3)' }}>
                          {formatTimeAgo(report.createdAt)}
                        </span>
                      </div>
                    </div>

                    {/* Rewards summary (collapsed) */}
                    {!isExpanded && report.rewards && (
                      <div className="flex items-center gap-2 flex-shrink-0">
                        {report.rewards.money && (
                          <DataChip tone="good" icon="money" className="game-number">
                            {formatRewardMoney(report.rewards.money)}
                          </DataChip>
                        )}
                        {report.rewards.miningBonus && (
                          <DataChip tone="warn" icon="ship-mining">Mining Bonus</DataChip>
                        )}
                      </div>
                    )}

                    {/* Expand chevron */}
                    <svg
                      className={`w-4 h-4 transition-transform flex-shrink-0 mt-0.5 ${isExpanded ? 'rotate-180' : ''}`}
                      style={{ color: 'rgba(255,255,255,0.3)' }}
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                      strokeWidth={2}
                      aria-hidden="true"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                    </svg>
                  </button>

                  {/* Expanded body */}
                  {isExpanded && (
                    <div className="px-3 pb-3 border-t border-white/[0.04]">
                      {/* Report body text */}
                      <pre
                        className="text-xs leading-relaxed mt-2 whitespace-pre-wrap font-sans"
                        style={{ color: 'rgba(255,255,255,0.65)' }}
                      >
                        {report.body}
                      </pre>

                      {/* Rewards breakdown */}
                      {report.rewards && (
                        <div className="mt-3 p-2 rounded-lg" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)' }}>
                          <p className="text-[10px] font-semibold text-white/50 uppercase tracking-wider mb-1.5">Rewards Received</p>
                          <div className="flex flex-wrap gap-2">
                            {report.rewards.money && (
                              <DataChip tone="good" icon="money" className="text-[11px] font-mono px-2 py-1">
                                {formatRewardMoney(report.rewards.money)}
                              </DataChip>
                            )}
                            {report.rewards.resources && Object.entries(report.rewards.resources).map(([resId, qty]) => {
                              const res = RESOURCE_MAP.get(resId as ResourceId);
                              return (
                                <DataChip
                                  key={resId}
                                  tone="info"
                                  icon={resolveIcon(res?.icon, 'package')}
                                  className="text-[11px] font-mono px-2 py-1"
                                >
                                  {qty} {res?.name || resId}
                                </DataChip>
                              );
                            })}
                            {report.rewards.miningBonus && (
                              <DataChip tone="warn" icon="ship-mining" className="text-[11px] px-2 py-1">
                                +{report.rewards.miningBonus.bonusPct}%{' '}
                                {RESOURCE_MAP.get(report.rewards.miningBonus.resourceId as ResourceId)?.name || report.rewards.miningBonus.resourceId}{' '}
                                for {report.rewards.miningBonus.durationMonths}mo
                              </DataChip>
                            )}
                          </div>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </ConsolePanel>
      )}
    </div>
  );
}
