'use client';

import { useState } from 'react';
import type { GameState, GameReport } from '@/lib/game/types';
import { LOCATION_MAP } from '@/lib/game/solar-system';
import { RESOURCE_MAP } from '@/lib/game/resources';
import type { ResourceId } from '@/lib/game/resources';
import { formatMoney, formatGameDate } from '@/lib/game/formulas';

// ─── Helpers ─────────────────────────────────────────────────────────────────

function getReportIcon(type: GameReport['type']): string {
  switch (type) {
    case 'probe_discovery': return '🛰️';
    case 'system_alert': return '⚠️';
    case 'milestone': return '🏆';
  }
}

function getReportAccent(type: GameReport['type']): string {
  switch (type) {
    case 'probe_discovery': return '#22d3ee'; // cyan
    case 'system_alert': return '#f59e0b'; // amber
    case 'milestone': return '#a78bfa'; // purple
  }
}

function formatTimeAgo(ms: number): string {
  const diff = Date.now() - ms;
  const seconds = Math.floor(diff / 1000);
  if (seconds < 60) return 'Just now';
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

function formatRewardMoney(amount: number): string {
  if (amount >= 1_000_000_000) return `$${(amount / 1_000_000_000).toFixed(1)}B`;
  if (amount >= 1_000_000) return `$${(amount / 1_000_000).toFixed(0)}M`;
  if (amount >= 1_000) return `$${(amount / 1_000).toFixed(0)}K`;
  return `$${amount}`;
}

// ─── Quarterly Reports sub-view ─────────────────────────────────────────────
// Per CLAUDE.md: "Every corporation produces an automatic public quarterly —
// revenue, growth rate, notable acquisitions. Fuel for rivalry and narrative."
// Reports are generated by src/lib/game/quarterly-reports.ts and hooked into
// the game-clock effect in space-tycoon/page.tsx.

function QuarterlyGrowthChip({ pct }: { pct: number | null }) {
  if (pct === null) {
    return (
      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-mono border border-white/10 text-slate-400 bg-white/[0.03]">
        First report on file
      </span>
    );
  }
  const positive = pct >= 0;
  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-mono font-bold border ${
        positive
          ? 'text-emerald-300 border-emerald-500/30 bg-emerald-500/10'
          : 'text-red-300 border-red-500/30 bg-red-500/10'
      }`}
    >
      <span aria-hidden="true">{positive ? '▲' : '▼'}</span>
      {positive ? '+' : ''}{pct.toFixed(1)}% net worth
    </span>
  );
}

function QuarterlyReportsView({ state }: { state: GameState }) {
  const reports = state.quarterlyReports || [];
  const [expandedId, setExpandedId] = useState<string | null>(reports.length > 0 ? reports[reports.length - 1].id : null);

  if (reports.length === 0) {
    return (
      <div className="hud-frame relative text-center py-16 rounded-xl border border-white/[0.06] bg-white/[0.02]">
        <span className="hud-corner-bl" aria-hidden="true" />
        <span className="hud-corner-br" aria-hidden="true" />
        <div className="text-4xl mb-3">📊</div>
        <h3 className="font-hud text-lg font-semibold text-white mb-1">No Quarterly Reports Yet</h3>
        <p className="text-sm text-slate-400 max-w-md mx-auto">
          Your first automatic corporate quarterly generates once a full in-game quarter (3 game-months) has elapsed
          since founding — revenue, profit, net worth, and growth rate, all summarized here.
        </p>
      </div>
    );
  }

  const newestFirst = [...reports].reverse();
  const latestId = reports[reports.length - 1].id;

  return (
    <div className="space-y-4">
      {/* Era timeline — one node per completed quarter */}
      <div className="hud-frame relative rounded-xl border border-white/[0.06] bg-white/[0.02] p-3">
        <span className="hud-corner-bl" aria-hidden="true" />
        <span className="hud-corner-br" aria-hidden="true" />
        <h3 className="game-label mb-2">Corporate Era Timeline</h3>
        <div
          className="flex items-center gap-1.5 overflow-x-auto pb-1"
          role="list"
          aria-label="Quarterly report history, oldest to newest"
        >
          {reports.map(r => {
            const isLatest = r.id === latestId;
            const isExpanded = expandedId === r.id;
            return (
              <button
                key={r.id}
                type="button"
                role="listitem"
                onClick={() => setExpandedId(r.id)}
                aria-current={isLatest ? 'true' : undefined}
                aria-pressed={isExpanded}
                title={`Quarter ${r.quarterNumber} — ${formatGameDate(r.gameDate)}`}
                className={`season-node shrink-0 min-w-[44px] min-h-[44px] w-11 h-11 rounded-full flex flex-col items-center justify-center text-[10px] font-bold border game-number transition-all focus:outline-none focus:ring-2 focus:ring-cyan-400 ${
                  isExpanded
                    ? 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40'
                    : isLatest
                      ? 'bg-amber-500/15 text-amber-300 border-amber-500/30 season-node-current'
                      : 'bg-white/[0.04] text-slate-300 border-white/10 season-node-claimed'
                }`}
              >
                <span aria-hidden="true">Q{r.quarterNumber}</span>
              </button>
            );
          })}
        </div>
        <p className="text-[10px] text-slate-500 mt-2">
          {reports.length} quarter{reports.length !== 1 ? 's' : ''} on record · latest is Q{reports[reports.length - 1].quarterNumber}, {formatGameDate(reports[reports.length - 1].gameDate)}
        </p>
      </div>

      {/* Report cards, newest first */}
      <div className="space-y-2">
        {newestFirst.map(r => {
          const isExpanded = expandedId === r.id;
          return (
            <div key={r.id} className="hud-frame relative rounded-xl border border-white/[0.06] bg-white/[0.02]">
              <span className="hud-corner-bl" aria-hidden="true" />
              <span className="hud-corner-br" aria-hidden="true" />
              <button
                type="button"
                onClick={() => setExpandedId(isExpanded ? null : r.id)}
                aria-expanded={isExpanded}
                className="w-full flex items-center justify-between gap-3 px-3 py-2.5 text-left min-h-[44px]"
              >
                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="font-hud text-sm font-semibold text-white">
                      Quarter {r.quarterNumber} Report
                    </h3>
                    {r.id === latestId && (
                      <span className="text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded-full border border-amber-500/30 bg-amber-500/10 text-amber-300">
                        Latest
                      </span>
                    )}
                  </div>
                  <p className="text-[10px] text-slate-500 mt-0.5">{formatGameDate(r.gameDate)} · Tier {r.corporationTier}</p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <QuarterlyGrowthChip pct={r.growthRatePct} />
                  <svg
                    className={`w-4 h-4 transition-transform ${isExpanded ? 'rotate-180' : ''}`}
                    style={{ color: 'rgba(255,255,255,0.3)' }}
                    fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2} aria-hidden="true"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                  </svg>
                </div>
              </button>

              {isExpanded && (
                <div className="px-3 pb-3 border-t border-white/[0.04]">
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-3">
                    <div className="rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-2">
                      <p className="text-[9px] uppercase tracking-wider text-slate-500">Revenue</p>
                      <p className="game-number text-emerald-300 text-sm font-bold">{formatMoney(r.revenue)}</p>
                    </div>
                    <div className="rounded-lg border border-red-500/20 bg-red-500/5 p-2">
                      <p className="text-[9px] uppercase tracking-wider text-slate-500">Costs</p>
                      <p className="game-number text-red-300 text-sm font-bold">{formatMoney(r.costs)}</p>
                    </div>
                    <div className={`rounded-lg border p-2 ${r.profit >= 0 ? 'border-cyan-500/20 bg-cyan-500/5' : 'border-amber-500/20 bg-amber-500/5'}`}>
                      <p className="text-[9px] uppercase tracking-wider text-slate-500">Profit</p>
                      <p className={`game-number text-sm font-bold ${r.profit >= 0 ? 'text-cyan-300' : 'text-amber-300'}`}>{formatMoney(r.profit)}</p>
                    </div>
                    <div className="rounded-lg border border-purple-500/20 bg-purple-500/5 p-2">
                      <p className="text-[9px] uppercase tracking-wider text-slate-500">Net Worth</p>
                      <p className="game-number text-purple-300 text-sm font-bold">{formatMoney(r.netWorth)}</p>
                    </div>
                  </div>
                  <div className="flex flex-wrap gap-3 mt-2 text-[11px] text-slate-400">
                    <span>🚀 {r.fleetCount} ship{r.fleetCount !== 1 ? 's' : ''}</span>
                    <span>🏗️ {r.buildingCount} building{r.buildingCount !== 1 ? 's' : ''}</span>
                  </div>
                  {r.notableEvents.length > 0 && (
                    <div className="mt-3">
                      <p className="text-[10px] font-semibold text-white/50 uppercase tracking-wider mb-1.5">Notable This Quarter</p>
                      <ul className="space-y-1 text-[11px] text-slate-300">
                        {r.notableEvents.map((title, i) => (
                          <li key={i} className="flex items-start gap-1.5">
                            <span aria-hidden="true" className="text-slate-600">·</span> {title}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ─── Component ───────────────────────────────────────────────────────────────

interface ReportsPanelProps {
  state: GameState;
  onMarkRead: (reportId: string) => void;
  onMarkAllRead: () => void;
}

export default function ReportsPanel({ state, onMarkRead, onMarkAllRead }: ReportsPanelProps) {
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [filter, setFilter] = useState<'all' | 'unread'>('all');
  const [topTab, setTopTab] = useState<'mail' | 'quarterly'>('mail');

  const reports = [...(state.reports || [])].reverse(); // newest first
  const filteredReports = filter === 'unread' ? reports.filter(r => !r.read) : reports;
  const unreadCount = reports.filter(r => !r.read).length;

  const handleExpand = (report: GameReport) => {
    if (expandedId === report.id) {
      setExpandedId(null);
    } else {
      setExpandedId(report.id);
      if (!report.read) {
        onMarkRead(report.id);
      }
    }
  };

  // Top-level tab strip — shared between Mail and Quarterly sub-views
  const TopTabs = (
    <div className="flex rounded-lg overflow-hidden border border-white/[0.06] w-fit" role="tablist" aria-label="Reports view">
      <button
        type="button"
        role="tab"
        aria-selected={topTab === 'mail'}
        onClick={() => setTopTab('mail')}
        className={`min-h-[44px] px-3 py-1.5 text-[11px] font-medium transition-colors ${
          topTab === 'mail' ? 'bg-white/[0.08] text-white' : 'text-slate-500 hover:text-white hover:bg-white/[0.04]'
        }`}
      >
        📬 Mail{unreadCount > 0 ? ` (${unreadCount})` : ''}
      </button>
      <button
        type="button"
        role="tab"
        aria-selected={topTab === 'quarterly'}
        onClick={() => setTopTab('quarterly')}
        className={`min-h-[44px] px-3 py-1.5 text-[11px] font-medium transition-colors ${
          topTab === 'quarterly' ? 'bg-white/[0.08] text-white' : 'text-slate-500 hover:text-white hover:bg-white/[0.04]'
        }`}
      >
        📊 Quarterly{(state.quarterlyReports || []).length > 0 ? ` (${(state.quarterlyReports || []).length})` : ''}
      </button>
    </div>
  );

  if (topTab === 'quarterly') {
    return (
      <div className="space-y-3">
        {TopTabs}
        <QuarterlyReportsView state={state} />
      </div>
    );
  }

  if (reports.length === 0) {
    return (
      <div className="space-y-4">
        {TopTabs}
        <div className="hud-frame relative text-center py-16 rounded-xl border border-white/[0.06] bg-white/[0.02]">
          <span className="hud-corner-bl" aria-hidden="true" />
          <span className="hud-corner-br" aria-hidden="true" />
          <div className="text-4xl mb-3">📬</div>
          <h3 className="font-hud text-lg font-semibold text-white mb-1">No Reports Yet</h3>
          <p className="text-sm text-slate-400 max-w-md mx-auto">
            Send survey probes to explore locations. When they complete their expeditions, detailed discovery reports will appear here with rewards and recommendations.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-3">
      {TopTabs}
      {/* Header bar */}
      <div className="hud-frame relative flex items-center justify-between px-3 py-2 rounded-lg bg-white/[0.02] border border-white/[0.04]">
        <span className="hud-corner-bl" aria-hidden="true" />
        <span className="hud-corner-br" aria-hidden="true" />
        <div className="flex items-center gap-3">
          <h2 className="font-hud text-sm font-semibold text-white">📬 Reports &amp; Mail</h2>
          {unreadCount > 0 && (
            <span aria-live="polite" className="game-number px-2 py-0.5 rounded-full text-[10px] font-bold bg-cyan-500/20 text-cyan-400 border border-cyan-500/30">
              {unreadCount} unread
            </span>
          )}
        </div>
        <div className="flex items-center gap-2">
          {/* Filter toggle */}
          <div className="flex rounded-lg overflow-hidden border border-white/[0.06]">
            <button
              onClick={() => setFilter('all')}
              aria-pressed={filter === 'all'}
              className={`min-h-[44px] px-3 py-1 text-[10px] font-medium transition-colors ${
                filter === 'all'
                  ? 'bg-white/[0.08] text-white'
                  : 'text-slate-500 hover:text-white hover:bg-white/[0.04]'
              }`}
            >
              All ({reports.length})
            </button>
            <button
              onClick={() => setFilter('unread')}
              aria-pressed={filter === 'unread'}
              className={`min-h-[44px] px-3 py-1 text-[10px] font-medium transition-colors ${
                filter === 'unread'
                  ? 'bg-white/[0.08] text-white'
                  : 'text-slate-500 hover:text-white hover:bg-white/[0.04]'
              }`}
            >
              Unread ({unreadCount})
            </button>
          </div>
          {unreadCount > 0 && (
            <button
              onClick={onMarkAllRead}
              className="min-h-[44px] px-2 py-1 text-[10px] text-slate-400 hover:text-cyan-400 transition-colors"
            >
              Mark all read
            </button>
          )}
        </div>
      </div>

      {/* Reports list */}
      {filteredReports.length === 0 && filter === 'unread' && (
        <div className="text-center py-8">
          <p className="text-sm text-slate-500">All reports have been read.</p>
        </div>
      )}

      <div className="space-y-2">
        {filteredReports.map(report => {
          const isExpanded = expandedId === report.id;
          const accent = getReportAccent(report.type);
          const locName = report.locationId ? LOCATION_MAP.get(report.locationId)?.name : null;

          return (
            <div
              key={report.id}
              className="holo-row rounded-lg transition-all"
              style={{
                background: isExpanded ? 'rgba(255,255,255,0.04)' : 'rgba(255,255,255,0.02)',
                border: `1px solid ${!report.read ? accent + '40' : 'rgba(255,255,255,0.06)'}`,
              }}
            >
              {/* Report header */}
              <button
                type="button"
                onClick={() => handleExpand(report)}
                aria-expanded={isExpanded}
                className="w-full flex items-start gap-3 px-3 py-2.5 text-left"
              >
                {/* Unread indicator + icon */}
                <div className="relative flex-shrink-0 mt-0.5">
                  <span className="text-lg">{getReportIcon(report.type)}</span>
                  {!report.read && (
                    <span
                      className="absolute -top-0.5 -right-0.5 w-2 h-2 rounded-full"
                      style={{ background: accent, boxShadow: `0 0 6px ${accent}` }}
                    />
                  )}
                </div>

                {/* Title + meta */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <h3
                      className="text-xs font-semibold truncate"
                      style={{ color: !report.read ? '#fff' : 'rgba(255,255,255,0.6)' }}
                    >
                      {report.title}
                    </h3>
                  </div>
                  <div className="flex items-center gap-2 mt-0.5">
                    {locName && (
                      <span className="text-[10px] px-1.5 py-0.5 rounded" style={{ background: 'rgba(255,255,255,0.04)', color: 'rgba(255,255,255,0.4)' }}>
                        {locName}
                      </span>
                    )}
                    <span className="text-[10px]" style={{ color: 'rgba(255,255,255,0.3)' }}>
                      {formatTimeAgo(report.createdAt)}
                    </span>
                  </div>
                </div>

                {/* Rewards summary (collapsed) */}
                {!isExpanded && report.rewards && (
                  <div className="flex items-center gap-2 flex-shrink-0">
                    {report.rewards.money && (
                      <span className="game-number text-[10px] text-emerald-400">
                        {formatRewardMoney(report.rewards.money)}
                      </span>
                    )}
                    {report.rewards.miningBonus && (
                      <span className="text-[10px] px-1.5 py-0.5 rounded bg-amber-500/10 text-amber-400 border border-amber-500/20">
                        Mining Bonus
                      </span>
                    )}
                  </div>
                )}

                {/* Expand chevron */}
                <svg
                  className={`w-4 h-4 transition-transform flex-shrink-0 mt-0.5 ${isExpanded ? 'rotate-180' : ''}`}
                  style={{ color: 'rgba(255,255,255,0.3)' }}
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                  strokeWidth={2}
                  aria-hidden="true"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                </svg>
              </button>

              {/* Expanded body */}
              {isExpanded && (
                <div className="px-3 pb-3 border-t border-white/[0.04]">
                  {/* Report body text */}
                  <pre
                    className="text-xs leading-relaxed mt-2 whitespace-pre-wrap font-sans"
                    style={{ color: 'rgba(255,255,255,0.65)' }}
                  >
                    {report.body}
                  </pre>

                  {/* Rewards breakdown */}
                  {report.rewards && (
                    <div className="mt-3 p-2 rounded-lg" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)' }}>
                      <p className="text-[10px] font-semibold text-white/50 uppercase tracking-wider mb-1.5">Rewards Received</p>
                      <div className="flex flex-wrap gap-2">
                        {report.rewards.money && (
                          <span className="inline-flex items-center gap-1 px-2 py-1 rounded text-[11px] font-mono bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                            💰 {formatRewardMoney(report.rewards.money)}
                          </span>
                        )}
                        {report.rewards.resources && Object.entries(report.rewards.resources).map(([resId, qty]) => {
                          const res = RESOURCE_MAP.get(resId as ResourceId);
                          return (
                            <span
                              key={resId}
                              className="inline-flex items-center gap-1 px-2 py-1 rounded text-[11px] font-mono bg-blue-500/10 text-blue-400 border border-blue-500/20"
                            >
                              {res?.icon || '📦'} {qty} {res?.name || resId}
                            </span>
                          );
                        })}
                        {report.rewards.miningBonus && (
                          <span className="inline-flex items-center gap-1 px-2 py-1 rounded text-[11px] bg-amber-500/10 text-amber-400 border border-amber-500/20">
                            ⛏️ +{report.rewards.miningBonus.bonusPct}%{' '}
                            {RESOURCE_MAP.get(report.rewards.miningBonus.resourceId as ResourceId)?.name || report.rewards.miningBonus.resourceId}{' '}
                            for {report.rewards.miningBonus.durationMonths}mo
                          </span>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
