import { NextResponse } from 'next/server';
import prisma from '@/lib/db';
import { logger } from '@/lib/logger';
import { requireCronSecret } from '@/lib/errors';
// Phase 3 slice 1: buildings come from the ServerAsset registry (server-assets.ts).
import { loadServerBuildingsForProfiles } from '@/lib/game/server-assets';
import {
  computePoolAggregates,
  emaBlend,
  type ProfileActivitySummary,
} from '@/lib/game/demand-pools';

/**
 * POST /api/space-tycoon/demand-pools/update
 *
 * Economic PvP Wave E4 "Finite Demand Pools" (docs/ECONOMY_PVP_2026-08.md
 * §2.1/§E4) — the hourly server job that maintains the shared demand
 * markets. For every (location, serviceCategory):
 *
 *   dNpc     — authored NPC backdrop floor × population scaler that recedes
 *              as 30-day-active player count grows (§2.9: floor, never
 *              ceiling; the "NPC economy scales" invariant, CI-tested in
 *              demand-pools.test.ts).
 *   dDerived — demand generated by real activity at the location, aggregated
 *              from every profile synced in the last 7 days (buildings,
 *              crewed stations, ships, operating services). Rivals building
 *              at a location GROW its demand even as they compete to serve
 *              it — agglomeration.
 *   cSupply  — total supplier capacity: players' service stacks (base
 *              revenue × within-player saturation curve) + the NPC backdrop
 *              supplying NPC_SUPPLY_FRACTION of its own floor.
 *
 * Stored values are blended with a 7-day EMA (hourly alpha ≈ 0.012) so
 * pools shift on the DAILY loop, never tick-to-tick (SESSION_DESIGN.md:
 * don't collapse the tempo). topShares/supplierCount are stored raw — they
 * are display telemetry, not revenue inputs.
 *
 * The season super-cycle modifier is NOT stored — sync applies it at read
 * time so a new season shifts pools immediately and deterministically.
 *
 * Auth: Bearer CRON_SECRET via requireCronSecret (fail-closed). Note the
 * middleware cronPaths list only exempts these routes from the CSRF check —
 * it does NOT authenticate them; this handler does.
 * Registered as 'tycoon-demand-pools' in src/lib/cron-scheduler.ts.
 */
export async function POST(request: Request) {
  const auth = requireCronSecret(request);
  if (auth) return auth;

  try {
    const now = Date.now();
    const [active30d, profiles] = await Promise.all([
      prisma.gameProfile.count({
        where: { lastSyncAt: { gt: new Date(now - 30 * 24 * 3600_000) } },
      }),
      prisma.gameProfile.findMany({
        where: { lastSyncAt: { gt: new Date(now - 7 * 24 * 3600_000) } },
        select: { id: true, buildingsData: true, activeServicesData: true, shipsData: true },
        take: 2000,
      }),
    ]);

    const registryBuildings = await loadServerBuildingsForProfiles(profiles.map(p => ({ id: p.id, buildingsData: p.buildingsData })));
    const summaries: ProfileActivitySummary[] = profiles.map(p => {
      // Wave M2 (docs/MEANINGFUL_2026-08.md §M2 — finding F5): a
      // mothballed/reactivating/decommissioning building withdraws from the
      // demand-pool economy — no derived demand, no capacity claim ("a
      // visible supply withdrawal rivals can see in the pool intel"). Drop
      // the building AND any service solely linked to it from this profile's
      // contribution before it's aggregated into the shared pool.
      // Phase 3 slice 1 (docs/SECURITY_AUDIT_2026-09.md): the registry view
      // (union in shadow, server rows only in enforce), batched above.
      const rawBuildings = (registryBuildings.get(p.id)?.buildings ?? []) as unknown as
        { instanceId?: string; definitionId?: string; locationId?: string; isComplete?: boolean; status?: string }[];
      const nonOperationalIds = new Set(
        rawBuildings
          .filter(b => typeof b?.instanceId === 'string' && !!b?.status && b.status !== 'active')
          .map(b => b.instanceId as string)
      );
      return {
        id: p.id,
        buildings: rawBuildings
          .filter(b => typeof b?.definitionId === 'string' && typeof b?.locationId === 'string')
          .filter(b => !b?.instanceId || !nonOperationalIds.has(b.instanceId))
          .map(b => ({ definitionId: b.definitionId as string, locationId: b.locationId as string, isComplete: b.isComplete !== false })),
        services: Array.isArray(p.activeServicesData)
          ? (p.activeServicesData as { definitionId?: string; locationId?: string; linkedBuildingIds?: unknown }[])
              .filter(s => typeof s?.definitionId === 'string' && typeof s?.locationId === 'string')
              .filter(s => {
                const ids = Array.isArray(s.linkedBuildingIds)
                  ? s.linkedBuildingIds.filter((x): x is string => typeof x === 'string')
                  : [];
                return ids.length === 0 || ids.every(id => !nonOperationalIds.has(id));
              })
              .map(s => ({ definitionId: s.definitionId as string, locationId: s.locationId as string }))
          : [],
        ships: Array.isArray(p.shipsData)
          ? (p.shipsData as { currentLocation?: string }[]).map(s => ({ currentLocation: s?.currentLocation }))
          : [],
      };
    });

    const aggregates = computePoolAggregates(summaries, active30d);

    const existing = await prisma.locationDemandPool.findMany({
      select: { locationId: true, category: true, dNpc: true, dDerived: true, cSupply: true },
    });
    const existingByKey = new Map(existing.map(r => [`${r.locationId}:${r.category}`, r]));

    let upserted = 0;
    const entries = Array.from(aggregates.entries());
    for (const [key, agg] of entries) {
      const prev = existingByKey.get(key);
      // 7-day EMA per §2.1 — first observation seeds the row raw.
      const dNpc = Math.round(emaBlend(prev?.dNpc, agg.dNpc));
      const dDerived = Math.round(emaBlend(prev?.dDerived, agg.dDerived));
      const cSupply = Math.round(emaBlend(prev?.cSupply, agg.cSupply));
      await prisma.locationDemandPool.upsert({
        where: { locationId_category: { locationId: agg.locationId, category: agg.category } },
        create: {
          locationId: agg.locationId, category: agg.category,
          dNpc: agg.dNpc, dDerived: agg.dDerived, cSupply: agg.cSupply,
          topShares: agg.topShares, supplierCount: agg.supplierCount,
        },
        update: {
          dNpc, dDerived, cSupply,
          topShares: agg.topShares, supplierCount: agg.supplierCount,
        },
      });
      upserted++;
    }

    return NextResponse.json({
      success: true,
      pools: upserted,
      profilesAggregated: summaries.length,
      active30d,
    });
  } catch (error) {
    logger.error('Demand pool update failed', { error: String(error) });
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
