/**
 * Retire speculative AI-generated business opportunities (2026-08-14
 * data-integrity fix, founder decision).
 *
 * sourceType 'ai_generated' BusinessOpportunity rows (e.g. "Orbital
 * Bio-Enhancement Clinics", $1B-$5B, 0.82 confidence, generated by the now
 * -disabled weekly runAIAnalysis cron) were mixed in with real sam_gov /
 * news_analysis opportunities on /business-opportunities with
 * fabricated-precision valuations and no disclosure that they were AI
 * speculation rather than sourced intelligence.
 *
 * Rather than badge/label them, the founder decided to retire them
 * entirely. The BusinessOpportunity model has no isActive boolean, but it
 * does have a `status` field (active/expired/archived/flagged) that
 * getOpportunities()/getOpportunityStats() already filter on
 * (status: 'active') — and now also hard-exclude sourceType 'ai_generated'
 * regardless of status as a second line of defense. This script sets
 * status = 'archived' on every ai_generated row (non-destructive, reversible,
 * preserves history) rather than deleting.
 *
 * Usage:
 *   npx tsx scripts/retire-ai-generated-opportunities.ts             # DRY RUN
 *   npx tsx scripts/retire-ai-generated-opportunities.ts --apply     # write
 */

import prisma from '../src/lib/db';

const APPLY = process.argv.includes('--apply');

async function main() {
  console.log(`retire-ai-generated-opportunities — ${APPLY ? 'APPLY mode (writing)' : 'DRY RUN (pass --apply to write)'}\n`);

  const rows = await prisma.businessOpportunity.findMany({
    where: { sourceType: 'ai_generated', status: { not: 'archived' } },
    select: { id: true, slug: true, title: true, status: true, featured: true, discoveredAt: true },
    orderBy: { discoveredAt: 'desc' },
  });

  console.log(`Found ${rows.length} ai_generated rows to archive:\n`);
  for (const r of rows) {
    console.log(`  [${r.status}${r.featured ? ', FEATURED' : ''}] ${r.slug} — "${r.title}" (discovered ${r.discoveredAt.toISOString().slice(0, 10)})`);
  }

  if (APPLY) {
    const result = await prisma.businessOpportunity.updateMany({
      where: { sourceType: 'ai_generated', status: { not: 'archived' } },
      data: { status: 'archived', featured: false },
    });
    console.log(`\nArchived ${result.count} rows.`);
  } else {
    console.log('\nDry run only — re-run with --apply to write.');
  }

  const remainingActive = await prisma.businessOpportunity.count({ where: { status: 'active' } });
  const remainingAiActive = await prisma.businessOpportunity.count({ where: { status: 'active', sourceType: 'ai_generated' } });
  console.log(`\nActive opportunities remaining: ${remainingActive} (of which ai_generated: ${remainingAiActive})`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
