/**
 * Seed script for Space Defense & National Security module
 *
 * Populates all 5 sections: space-forces, defense-programs, recent-contracts,
 * counterspace-events, and alliances.
 *
 * Run with: npx tsx scripts/seed-space-defense.ts
 */

import { PrismaClient } from '@prisma/client';
import { getExpiresAt } from '../src/lib/freshness-policies';

const prisma = new PrismaClient();

async function upsertContent(
  module: string,
  section: string,
  data: unknown[],
  options: {
    sourceType?: string;
    aiConfidence?: number;
    isActive?: boolean;
    version?: number;
  } = {}
) {
  const now = new Date();
  const contentKey = `${module}:${section}`;

  const record = {
    module,
    section,
    data: JSON.stringify(data),
    sourceType: options.sourceType || 'seed',
    expiresAt: getExpiresAt(module),
    refreshedAt: now,
    lastVerified: now,
    aiConfidence: options.aiConfidence ?? 1.0,
    isActive: options.isActive ?? true,
    version: options.version ?? 1,
  };

  await prisma.dynamicContent.upsert({
    where: { contentKey },
    update: record,
    create: { contentKey, ...record },
  });

  console.log(`  ✓ ${contentKey} (${data.length} items)`);
}

// ═══════════════════════════════════════════════════════════════════
// 1. SPACE FORCES (10 organizations)
// ═══════════════════════════════════════════════════════════════════

const SPACE_FORCES = [
  {
    id: 'ussf',
    name: 'United States Space Force',
    country: 'United States',
    flag: 'US',
    established: 'December 20, 2019',
    personnel: '~9,800 Guardians + ~5,300 civilians',
    budget: '$29.4B (FY2025 request)',
    budgetYear: 'FY2025',
    parentService: 'Department of the Air Force',
    commander: 'Gen. B. Chance Saltzman, Chief of Space Operations',
    headquarters: 'The Pentagon, Arlington, VA',
    keyPrograms: [
      'National Security Space Launch (NSSL)',
      'GPS III / IIIF',
      'Next-Generation Overhead Persistent Infrared (Next-Gen OPIR)',
      'Evolved Strategic SATCOM (ESS)',
      'Space Development Agency (SDA) Proliferated Warfighter Space Architecture',
      'Space Fence (Kwajalein)',
      'Space Domain Awareness',
    ],
    description: 'The United States Space Force (USSF) is the space service branch of the U.S. Armed Forces, one of the eight uniformed services, and the world\'s first and currently only independent space force. Established on December 20, 2019, the USSF organizes, trains, and equips space forces to protect U.S. and allied interests in space and to provide space capabilities to the joint force. The FY2025 budget request of $29.4 billion reflects growing emphasis on space as a warfighting domain.',
    fieldCommands: [
      'Space Operations Command (SpOC) — Peterson SFB, CO',
      'Space Systems Command (SSC) — Los Angeles AFB, CA',
      'Space Training and Readiness Command (STARCOM) — Peterson SFB, CO',
    ],
  },
  {
    id: 'pla-ssf',
    name: 'PLA Strategic Support Force (Aerospace Systems Dept.)',
    country: 'China',
    flag: 'CN',
    established: 'December 31, 2015 (restructured April 2024 as Information Support Force)',
    personnel: '~150,000 (estimated, includes cyber/electronic)',
    budget: 'Classified (~$15B estimated space portion)',
    budgetYear: '2024',
    parentService: "People's Liberation Army",
    commander: 'Lt. Gen. Jü Qiansheng (Information Support Force)',
    headquarters: 'Beijing, China',
    keyPrograms: [
      'Beidou-3 Navigation Constellation (BDS)',
      'Yaogan reconnaissance satellite series',
      'Shiyan (experimental) technology demonstration',
      'Tianlian data relay satellite system',
      'Kuaizhou rapid-launch SLV',
      'SC-19 / DN-3 ASAT interceptors',
      'Shijian co-orbital inspection satellites',
    ],
    description: 'China\'s military space capabilities were consolidated under the PLA Strategic Support Force (SSF) in 2015, combining space, cyber, and electronic warfare missions. In April 2024, the SSF was restructured: space operations transferred to a new Information Support Force directly under the CMC. China operates the second-largest military satellite constellation and has demonstrated kinetic ASAT, co-orbital inspection, and directed-energy capabilities. Beidou-3 provides global PNT independent of GPS.',
    fieldCommands: [
      'Xichang Satellite Launch Center — Sichuan Province',
      'Jiuquan Satellite Launch Center — Inner Mongolia',
      'Taiyuan Satellite Launch Center — Shanxi Province',
      'Wenchang Space Launch Site — Hainan Province',
    ],
  },
  {
    id: 'russia-vks',
    name: 'Russian Aerospace Forces (VKS) — Space Troops',
    country: 'Russia',
    flag: 'RU',
    established: 'August 1, 2015 (Space Troops since 2001)',
    personnel: '~50,000 (Space Troops component)',
    budget: '~$3.5B estimated (from total defense ~$65B)',
    budgetYear: '2024',
    parentService: 'Russian Aerospace Forces (VKS)',
    commander: 'Col. Gen. Viktor Afzalov (VKS Commander-in-Chief)',
    headquarters: 'Moscow, Russia',
    keyPrograms: [
      'GLONASS navigation constellation',
      'Tundra/EKS missile warning satellites',
      'Liana SIGINT/ELINT constellation (Pion/Lotos)',
      'Nudol PL-19 direct-ascent ASAT',
      'Cosmos RPO/inspection satellites',
      'Angara launch vehicle family',
      'Sfera broadband constellation (planned)',
    ],
    description: 'The Russian Space Troops are a branch of the Russian Aerospace Forces (VKS) responsible for space launch, satellite operations, space surveillance, and ballistic missile early warning. Russia maintains GLONASS for global navigation, operates early-warning satellites, and has demonstrated both direct-ascent ASAT (Nudol, tested Nov 2021 against Cosmos 1408) and rendezvous/proximity operations. Budget constraints have slowed modernization, but Russia maintains significant legacy capabilities.',
    fieldCommands: [
      'Plesetsk Cosmodrome — Arkhangelsk Oblast',
      'Titov Main Space Testing Center — Krasnoznamenka',
      'Vostochny Cosmodrome — Amur Oblast',
    ],
  },
  {
    id: 'france-cde',
    name: 'French Space Command (Commandement de l\'Espace)',
    country: 'France',
    flag: 'FR',
    established: 'September 3, 2019',
    personnel: '~500 (growing to ~1,000 by 2030)',
    budget: '€3.6B (2019-2025 Military Programming Law allocation)',
    budgetYear: '2024',
    parentService: 'French Air and Space Force',
    commander: 'Général de brigade aérienne Philippe Adam',
    headquarters: 'Toulouse, France',
    keyPrograms: [
      'CERES SIGINT constellation (3 satellites)',
      'CSO optical reconnaissance (3 satellites)',
      'Syracuse IV SATCOM (2 launched)',
      'GRAVES space surveillance radar',
      'GEOTracker telescope network',
      'YODA in-orbit defense demonstrator',
      'IRIS next-gen space domain awareness',
    ],
    description: 'France established a dedicated Space Command in September 2019, becoming the first European country with an independent military space organization. Operating under the renamed Air and Space Force, the CDE is responsible for space defense strategy including active defense measures. France has invested in the YODA program for in-orbit maneuvering and protection capabilities. The CSO and CERES constellations provide high-resolution imagery and SIGINT.',
    fieldCommands: [
      'Centre National d\'Études Spatiales (CNES) — Toulouse',
      'Centre Opérationnel de Surveillance Militaire des Objets Spatiaux — Mont Verdun',
      'Guiana Space Centre (CSG) — Kourou, French Guiana',
    ],
  },
  {
    id: 'uk-space-command',
    name: 'UK Space Command',
    country: 'United Kingdom',
    flag: 'GB',
    established: 'April 1, 2021',
    personnel: '~700 (growing)',
    budget: '£1.4B (2022-2032 UK Space Defence Strategy)',
    budgetYear: '2024',
    parentService: 'Joint command (RAF lead)',
    commander: 'Air Vice-Marshal Paul Mayall',
    headquarters: 'RAF High Wycombe, Buckinghamshire',
    keyPrograms: [
      'Skynet 6 military SATCOM',
      'OneWeb LEO broadband (govt stake)',
      'ISTARI sovereign SSA capability',
      'Tyche SSA sensor programme',
      'Minerva SSA operations center',
      'Space Operations Centre (SpOC UK)',
    ],
    description: 'UK Space Command was established to lead joint military space operations, integrating capabilities from all three armed services. The UK holds a strategic stake in OneWeb and is developing Skynet 6 as the next generation of military communications satellites. The ISTARI program aims to deliver a sovereign space surveillance and tracking capability. The UK is a founding member of the Combined Space Operations initiative.',
  },
  {
    id: 'japan-sog',
    name: 'Japan Space Operations Group',
    country: 'Japan',
    flag: 'JP',
    established: 'May 18, 2020',
    personnel: '~100 (growing to 200+)',
    budget: '¥804B (~$5.5B, 2024 space-related defense budget)',
    budgetYear: 'FY2024',
    parentService: 'Japan Air Self-Defense Force',
    commander: 'Classified (under JASDF Chief of Staff)',
    headquarters: 'Fuchu Air Base, Tokyo',
    keyPrograms: [
      'Quasi-Zenith Satellite System (QZSS/Michibiki)',
      'X-band defense SATCOM (Kirameki)',
      'SSA satellite (collaboration with USSF)',
      'Information Gathering Satellites (IGS)',
      'Deep Space Radar (planned)',
      'HGV tracking satellite constellation (planned)',
    ],
    description: 'Japan established a Space Operations Group within the JASDF in 2020, reflecting growing concern over the space domain — particularly Chinese and North Korean threats. Japan operates QZSS for regional PNT enhancement and IGS reconnaissance satellites. The 2022 National Security Strategy significantly increased space defense spending, with plans for a hypersonic glide vehicle tracking satellite constellation and enhanced SSA cooperation with the US.',
  },
  {
    id: 'india-dsa',
    name: 'Defence Space Agency (DSA)',
    country: 'India',
    flag: 'IN',
    established: 'April 2019',
    personnel: '~200 (tri-service)',
    budget: '~$2B (estimated, space-related defense)',
    budgetYear: '2024',
    parentService: 'Tri-service joint agency under CDS',
    commander: 'Air Vice-Marshal SP Dharkar',
    headquarters: 'Bengaluru, India',
    keyPrograms: [
      'GSAT-7/7A military SATCOM',
      'RISAT radar imaging constellation',
      'NavIC/IRNSS regional navigation (7 satellites)',
      'Mission Shakti ASAT capability (tested 2019)',
      'Defence Space Research Agency (DSRO)',
      'Electronic intelligence satellites',
      'NETRA space situational awareness',
    ],
    description: 'India\'s Defence Space Agency was established in 2019 as a tri-service organization to handle space warfare and satellite-based defense needs. India demonstrated ASAT capability with Mission Shakti in March 2019, destroying a satellite in LEO. ISRO and DSRO collaborate on military applications including GSAT-7 naval SATCOM, RISAT synthetic aperture radar, and the NavIC regional navigation system. India is expanding its space domain awareness capabilities.',
  },
  {
    id: 'germany-weltraum',
    name: 'German Space Command (Weltraumkommando)',
    country: 'Germany',
    flag: 'DE',
    established: 'July 13, 2021',
    personnel: '~80 (planned growth to 200+)',
    budget: '~€500M (from Bundeswehr space activities)',
    budgetYear: '2024',
    parentService: 'Bundeswehr (German Armed Forces)',
    commander: 'Brig. Gen. Michael Traut',
    headquarters: 'Air Operations Centre, Uedem',
    keyPrograms: [
      'SARah radar reconnaissance constellation (3 satellites)',
      'Georg space domain awareness system',
      'SatCom BW Stufe 3 (next-gen MILSATCOM)',
      'LisaPathfinder contribution',
      'EU SST/Space Surveillance contribution',
      'FCAS remote carrier support',
    ],
    description: 'Germany established its Weltraumkommando (Space Command) in July 2021 within the Bundeswehr to centralize military space operations. Germany operates the SARah constellation of SAR reconnaissance satellites (replacing SAR-Lupe) and contributes to EU Space Surveillance and Tracking. The command coordinates SSA data and supports NATO space operations from the Combined Air Operations Centre in Uedem.',
  },
  {
    id: 'australia-dsc',
    name: 'Defence Space Command (Australia)',
    country: 'Australia',
    flag: 'AU',
    established: 'January 18, 2022',
    personnel: '~400 (tri-service)',
    budget: 'A$2.2B (2024-2034 Integrated Investment Program)',
    budgetYear: '2024',
    parentService: 'Australian Defence Force (RAAF lead)',
    commander: 'Air Vice-Marshal Catherine Roberts',
    headquarters: 'RAAF Base Edinburgh, South Australia',
    keyPrograms: [
      'JP 9102 Satellite Communications (MILSATCOM)',
      'JP 9360 Space Domain Awareness',
      'DEF 799 SSA sensors and C2',
      'Buccaneer LEO SSA pathfinder',
      'C-Band Space Surveillance Radar',
      'AUKUS space cooperation',
    ],
    description: 'Australia\'s Defence Space Command was established in January 2022, reflecting the growing importance of space in the Indo-Pacific region. Australia operates C-band space surveillance radar at Exmouth and contributes to the US Space Surveillance Network. Under AUKUS Pillar 2, Australia is expanding space cooperation with the US and UK on deep-space SSA, resilient SATCOM, and space domain awareness capabilities.',
  },
  {
    id: 'south-korea-scc',
    name: 'Space Operations Center (South Korea)',
    country: 'South Korea',
    flag: 'KR',
    established: 'December 2024 (Space Operations Command planned)',
    personnel: '~100 (initial cadre)',
    budget: '₩1.3T (~$950M, space defense related)',
    budgetYear: '2024',
    parentService: 'Republic of Korea Air Force',
    commander: 'Under ROKAF Chief of Staff',
    headquarters: 'Osan Air Base, Gyeonggi Province',
    keyPrograms: [
      'KASS Korean Augmentation System',
      'Baekdu surveillance satellite constellation (5 SAR)',
      'Next-gen military communications satellites',
      '425 Project reconnaissance satellite program',
      'Korea Positioning System (KPS, planned 2035)',
      'SSA radar/optical sensors',
    ],
    description: 'South Korea has accelerated space defense capabilities in response to North Korean missile and space threats. The 425 Project is building an indigenous SAR/EO reconnaissance satellite constellation. Korea plans to establish a dedicated Space Operations Command, announced in late 2024, to centralize military space operations. South Korea cooperates closely with the US on SSA and missile warning, and is developing the KPS for regional PNT independence.',
  },
];

// ═══════════════════════════════════════════════════════════════════
// 2. DEFENSE PROGRAMS (22 programs)
// ═══════════════════════════════════════════════════════════════════

const DEFENSE_PROGRAMS = [
  {
    id: 'gps-iii',
    name: 'GPS III / IIIF',
    abbreviation: 'GPS III',
    agency: 'USSF / Space Systems Command',
    contractor: 'Lockheed Martin',
    status: 'production',
    category: 'navigation',
    budget: '$7.2B (GPS IIIF block, 22 satellites)',
    description: 'GPS III provides 3x better accuracy and 8x improved anti-jamming capability over GPS IIF. GPS IIIF (Follow-on, SV11-32) adds regional military protection, search-and-rescue payload, and a new laser retroreflector array. 6 GPS III SV launched to date; IIIF first launch expected 2027.',
    nextMilestone: 'GPS IIIF SV11 first launch — 2027',
    constellation: '31 operational + new GPS III/IIIF replacing legacy Block IIR/IIF',
  },
  {
    id: 'next-gen-opir',
    name: 'Next-Generation Overhead Persistent Infrared',
    abbreviation: 'Next-Gen OPIR',
    agency: 'USSF / Space Systems Command',
    contractor: 'Lockheed Martin (GEO), Northrop Grumman (Polar)',
    status: 'development',
    category: 'missile_warning',
    budget: '$14.4B (total program)',
    description: 'Next-Gen OPIR replaces the legacy SBIRS missile warning constellation with more resilient, higher-capacity infrared sensors. The system comprises 3 GEO satellites (Lockheed Martin) and 2 polar-orbiting satellites (Northrop Grumman) to provide global persistent missile warning and tracking. Critical for detecting hypersonic and ballistic missile threats.',
    nextMilestone: 'GEO-1 launch — late 2025',
    constellation: '3 GEO + 2 Polar',
  },
  {
    id: 'sbirs',
    name: 'Space Based Infrared System',
    abbreviation: 'SBIRS',
    agency: 'USSF / Space Systems Command',
    contractor: 'Lockheed Martin',
    status: 'operational',
    category: 'missile_warning',
    budget: 'Sustainment',
    description: 'SBIRS provides global missile warning, missile defense, and battlespace characterization through a constellation of GEO and HEO payloads. All 6 GEO satellites and 4 HEO payloads are operational, being replaced by Next-Gen OPIR. SBIRS detects ballistic missile launches globally within seconds, providing critical warning to NORAD and USSTRATCOM.',
    constellation: '6 GEO + 4 HEO payloads',
  },
  {
    id: 'aehf-ess',
    name: 'Advanced EHF / Evolved Strategic SATCOM',
    abbreviation: 'AEHF / ESS',
    agency: 'USSF / Space Systems Command',
    contractor: 'Lockheed Martin (AEHF), Northrop Grumman (ESS)',
    status: 'development',
    category: 'communications',
    budget: '$8.9B (ESS program)',
    description: 'AEHF provides protected, jam-resistant communications for strategic command and control, including nuclear C3. 6 AEHF satellites are operational. Evolved Strategic SATCOM (ESS) is the next-gen replacement, featuring higher data rates, improved anti-jam, and cyber-hardened architecture to maintain nuclear command and control survivability.',
    nextMilestone: 'ESS first launch — ~2029',
    constellation: '6 AEHF operational, 3+ ESS planned',
  },
  {
    id: 'wgs',
    name: 'Wideband Global SATCOM',
    abbreviation: 'WGS',
    agency: 'USSF / Space Systems Command',
    contractor: 'Boeing',
    status: 'production',
    category: 'communications',
    budget: '$590M (WGS-11+)',
    description: 'WGS provides high-capacity wideband communications for DoD, allied nations, and the intelligence community. Each WGS satellite provides more bandwidth than the entire DSCS constellation it replaced. WGS-11+ features digital channelizers and enhanced cyber resilience. 10 satellites operational, with WGS-11 in production.',
    nextMilestone: 'WGS-11 launch — 2027',
    constellation: '10 operational GEO satellites',
  },
  {
    id: 'sda-transport',
    name: 'SDA Proliferated Warfighter Space Architecture — Transport Layer',
    abbreviation: 'SDA Transport',
    agency: 'Space Development Agency',
    contractor: 'York Space Systems, Lockheed Martin (Tranche 0/1); L3Harris, Northrop Grumman (Tranche 2)',
    status: 'production',
    category: 'sda',
    budget: '$4.5B+ (all tranches)',
    description: 'The SDA Transport Layer provides resilient, low-latency data transport via interconnected LEO satellites with optical inter-satellite links (OISL). Tranche 0 (28 satellites) launched 2023-2024 and is operational. Tranche 1 (126 satellites) launching 2024-2025. Tranche 2 (~200 satellites) awarded for delivery 2027. This mesh network is designed to be resilient against adversary attacks through proliferation.',
    nextMilestone: 'Tranche 1 constellation completion — 2025',
    constellation: '28 T0 + 126 T1 + ~200 T2 (LEO)',
  },
  {
    id: 'sda-tracking',
    name: 'SDA Proliferated Warfighter Space Architecture — Tracking Layer',
    abbreviation: 'SDA Tracking',
    agency: 'Space Development Agency',
    contractor: 'L3Harris, SpaceX (Tranche 0); Northrop Grumman, L3Harris (Tranche 1)',
    status: 'production',
    category: 'sda',
    budget: '$3.2B+ (all tranches)',
    description: 'The SDA Tracking Layer provides overhead persistent infrared missile warning/tracking from LEO, complementing the GEO-based Next-Gen OPIR. Designed to detect and track advanced missile threats including hypersonic glide vehicles. Tranche 0 (8 satellites) launched 2024. Tranche 1 (36 satellites) launching 2025-2026. Feeds data to the Transport Layer for rapid fire control.',
    nextMilestone: 'Tranche 1 first launches — 2025',
    constellation: '8 T0 + 36 T1 (LEO)',
  },
  {
    id: 'sda-custody',
    name: 'SDA Custody Layer',
    abbreviation: 'SDA Custody',
    agency: 'Space Development Agency',
    contractor: 'Raytheon, Millennium Space Systems',
    status: 'development',
    category: 'sda',
    budget: '~$700M (initial tranche)',
    description: 'The Custody Layer maintains persistent tracking and custody of time-sensitive targets (especially mobile missile launchers and HGVs) through medium-FOV sensors. It bridges the gap between wide-area search and engagement-quality tracking. Designed to work with JADC2 and integrated with Transport and Tracking layers for rapid targeting.',
    nextMilestone: 'First Custody Layer satellites — 2027',
  },
  {
    id: 'nssl',
    name: 'National Security Space Launch',
    abbreviation: 'NSSL',
    agency: 'USSF / Space Systems Command',
    contractor: 'SpaceX (Falcon 9/Heavy), ULA (Vulcan/Atlas V), Blue Origin (New Glenn — Phase 3)',
    status: 'operational',
    category: 'launch',
    budget: '$5.6B (Phase 2 awards, FY2025-2029)',
    description: 'NSSL ensures assured access to space for the most critical national security payloads. Phase 2 split launches 60/40 between ULA and SpaceX. Phase 3 (Lane 1 for smaller payloads) added Rocket Lab, Firefly, and Stoke Space alongside SpaceX. Blue Origin\'s New Glenn is entering NSSL certification. NSSL supports launches from CCSFS, VSFB, and Wallops.',
    nextMilestone: 'Vulcan NSSL certification — 2025',
  },
  {
    id: 'gssap',
    name: 'Geosynchronous Space Situational Awareness Program',
    abbreviation: 'GSSAP',
    agency: 'USSF / Space Operations Command',
    contractor: 'Orbital ATK / Northrop Grumman',
    status: 'operational',
    category: 'surveillance',
    budget: 'Classified',
    description: 'GSSAP satellites operate in near-geosynchronous orbit to provide space domain awareness of the GEO belt. These satellites perform rendezvous and proximity operations (RPO) to characterize resident space objects and assess threats. At least 6 satellites are believed to be operational. Publicly acknowledged but mission details classified.',
    constellation: '6+ satellites in near-GEO',
  },
  {
    id: 'silentbarker',
    name: 'SILENTBARKER / NROL-107',
    abbreviation: 'SILENTBARKER',
    agency: 'NRO / USSF',
    contractor: 'Northrop Grumman',
    status: 'operational',
    category: 'surveillance',
    budget: 'Classified',
    description: 'SILENTBARKER (NROL-107) is a next-generation space domain awareness mission launched in September 2023 on a ULA Atlas V from CCSFS. The satellite is believed to detect, track, and characterize threats in the GEO belt with greater capability than GSSAP. Details remain highly classified; it is the first publicly named NRO/USSF joint SDA mission.',
    nextMilestone: 'Possible follow-on missions classified',
  },
  {
    id: 'muos',
    name: 'Mobile User Objective System',
    abbreviation: 'MUOS',
    agency: 'U.S. Navy / USSF',
    contractor: 'Lockheed Martin',
    status: 'operational',
    category: 'communications',
    budget: 'Sustainment (~$300M/yr)',
    description: 'MUOS provides narrowband tactical mobile SATCOM for the DoD, replacing the UFO constellation. Five MUOS satellites use Wideband Code Division Multiple Access (WCDMA) to deliver 3G-like smartphone capabilities to warfighters globally. Supports beyond-line-of-sight communications for dismounted troops, UAVs, ships, and vehicles.',
    constellation: '5 GEO (4 operational + 1 spare)',
  },
  {
    id: 'space-fence',
    name: 'Space Fence',
    abbreviation: 'Space Fence',
    agency: 'USSF / Space Operations Command',
    contractor: 'Lockheed Martin',
    status: 'operational',
    category: 'ground',
    budget: '$1.5B (development + initial operations)',
    description: 'Space Fence is an S-band ground-based radar on Kwajalein Atoll in the Marshall Islands that provides uncued detection and tracking of objects in LEO and MEO. It can detect objects as small as 10 cm, dramatically increasing the space object catalog. Space Fence processes ~1.5 million observations per day and achieved IOC in March 2020.',
  },
  {
    id: 'egs',
    name: 'Enterprise Ground Services',
    abbreviation: 'EGS',
    agency: 'USSF / Space Systems Command',
    contractor: 'Raytheon Technologies',
    status: 'development',
    category: 'ground',
    budget: '$3.5B',
    description: 'EGS modernizes the satellite ground control architecture by replacing legacy, stovepiped ground systems with a common, cloud-native, modular framework. It will provide a unified interface for commanding and controlling GPS, AEHF, SBIRS/OPIR, and other constellations. The serviceability-oriented architecture enables rapid software updates and integration of new capabilities.',
    nextMilestone: 'GPS OCX Block 3F — 2026',
  },
  {
    id: 'skynet-6',
    name: 'Skynet 6',
    abbreviation: 'Skynet 6',
    agency: 'UK Ministry of Defence',
    contractor: 'Airbus Defence & Space',
    status: 'development',
    category: 'communications',
    budget: '£6B (full programme, including ground)',
    description: 'Skynet 6 is the UK\'s next-generation military SATCOM system, replacing the Skynet 5 constellation. It includes Skynet 6A (GEO, built by Airbus) and leverages commercial/LEO augmentation for resilience. The program integrates ground segment modernization and anti-jamming enhancements to maintain sovereign UK and allied MILSATCOM through the 2040s.',
    nextMilestone: 'Skynet 6A launch — 2025',
  },
  {
    id: 'cso',
    name: 'Composante Spatiale Optique',
    abbreviation: 'CSO',
    agency: 'French DGA / CNES',
    contractor: 'Airbus Defence & Space',
    status: 'operational',
    category: 'surveillance',
    budget: '€3.6B (programme)',
    description: 'CSO is France\'s next-generation military optical reconnaissance satellite system, replacing Helios 2. Three satellites launched (CSO-1 2018, CSO-2 2020, CSO-3 2023) in different orbits provide very high resolution imagery (20cm class), identification, and wide-area mapping. CSO data is shared with partner nations (Germany, Belgium, Sweden) under bilateral agreements.',
    constellation: '3 satellites (SSO and lower inclination)',
  },
  {
    id: 'sarah',
    name: 'SARah Radar Reconnaissance',
    abbreviation: 'SARah',
    agency: 'German BAAINBw',
    contractor: 'Airbus Defence & Space (reflector), OHB (phased array)',
    status: 'operational',
    category: 'surveillance',
    budget: '€816M',
    description: 'SARah is Germany\'s second-generation radar reconnaissance satellite system, replacing SAR-Lupe. It comprises 3 satellites: 1 with a large deployable reflector antenna (SARah-1, Airbus) and 2 with phased array antennas (SARah-2/3, OHB). SARah provides all-weather, day-night synthetic aperture radar imagery at sub-meter resolution for the Bundeswehr.',
    constellation: '3 SAR satellites',
  },
  {
    id: 'ceres',
    name: 'CERES SIGINT Constellation',
    abbreviation: 'CERES',
    agency: 'French DGA / CNES',
    contractor: 'Airbus Defence & Space / Thales',
    status: 'operational',
    category: 'surveillance',
    budget: '~€450M',
    description: 'Capacité de Renseignement Électromagnétique Spatiale (CERES) is France\'s first dedicated SIGINT satellite system, launched November 2021. Three satellites fly in formation to geolocate and characterize electromagnetic emitters (radars, communications) from space. CERES replaced the older ELISA demonstrator system and significantly enhances French electronic intelligence capabilities.',
    constellation: '3 satellites (formation flying)',
  },
  {
    id: 'syracuse-iv',
    name: 'Syracuse IV Military SATCOM',
    abbreviation: 'Syracuse IV',
    agency: 'French DGA / CNES',
    contractor: 'Thales Alenia Space',
    status: 'operational',
    category: 'communications',
    budget: '~€3.8B (full programme)',
    description: 'Syracuse IV is France\'s next-generation military communications satellite system. Two satellites launched (Syracuse 4A in 2021, 4B in 2023) provide jam-resistant, high-bandwidth communications for French forces and allies. Features flexible digital payloads, anti-jamming, and cybersecurity improvements over Syracuse III. Supports NATO SATCOM interoperability.',
    constellation: '2 GEO satellites',
  },
  {
    id: 'kirameki',
    name: 'X-Band Defense Communication (Kirameki)',
    abbreviation: 'Kirameki',
    agency: 'Japan MOD',
    contractor: 'DSN Corporation / NEC / Mitsubishi Electric',
    status: 'operational',
    category: 'communications',
    budget: '~¥250B (~$1.7B)',
    description: 'Kirameki is Japan\'s first dedicated military communications satellite system, with Kirameki-1 (2017) and Kirameki-2 (2017) providing X-band SATCOM for the JSDF. A third satellite is planned. The system replaced reliance on commercial SATCOM and provides secure, jam-resistant communications for ground, maritime, and air self-defense forces.',
    constellation: '2 GEO satellites (3rd planned)',
  },
  {
    id: 'gsat-7',
    name: 'GSAT-7 Series Military SATCOM',
    abbreviation: 'GSAT-7',
    agency: 'Indian MOD / ISRO',
    contractor: 'ISRO',
    status: 'operational',
    category: 'communications',
    budget: '~$310M (total series)',
    description: 'India\'s GSAT-7 series provides dedicated military communications. GSAT-7 (Rukmini, 2013) serves the Indian Navy with UHF/S/C/Ku-band coverage across the Indian Ocean. GSAT-7A (2018) serves the Indian Air Force. GSAT-7B/C are planned for the Indian Army and tri-service use. These represent India\'s first indigenous MILSATCOM capability.',
    constellation: '2 operational GEO, 2 planned',
  },
  {
    id: 'qzss',
    name: 'Quasi-Zenith Satellite System (Michibiki)',
    abbreviation: 'QZSS',
    agency: 'Japan Cabinet Office / MOD',
    contractor: 'Mitsubishi Electric',
    status: 'operational',
    category: 'navigation',
    budget: '~¥300B (~$2B)',
    description: 'QZSS is a regional satellite navigation system providing GPS augmentation with centimeter-level accuracy over Japan and the Asia-Oceania region. 4 satellites are operational (1 GEO + 3 quasi-zenith), expanding to 7 by 2026. While primarily civilian, QZSS provides military-grade authentication signals and serves as a GPS backup for JSDF operations in the Indo-Pacific.',
    nextMilestone: 'Expansion to 7 satellites — 2026',
    constellation: '4 operational (1 GEO + 3 QZO), expanding to 7',
  },
];

// ═══════════════════════════════════════════════════════════════════
// 3. RECENT CONTRACTS (16 major awards)
// ═══════════════════════════════════════════════════════════════════

const RECENT_CONTRACTS = [
  {
    id: 'nssl-phase2-spacex',
    title: 'National Security Space Launch Phase 2 — Lane 1',
    contractor: 'SpaceX',
    value: '$5.6B (60% of Phase 2)',
    awardDate: 'August 2020',
    agency: 'USSF / Space Systems Command',
    category: 'Launch Services',
    description: 'SpaceX was awarded ~60% of NSSL Phase 2 launch service agreements for FY2022-2027. Covers approximately 40 national security missions using Falcon 9, Falcon Heavy, and potentially Starship. Largest launch contract in USSF history.',
    period: 'FY2022-2027',
  },
  {
    id: 'nssl-phase2-ula',
    title: 'National Security Space Launch Phase 2 — Lane 1',
    contractor: 'United Launch Alliance (ULA)',
    value: '$3.1B (40% of Phase 2)',
    awardDate: 'August 2020',
    agency: 'USSF / Space Systems Command',
    category: 'Launch Services',
    description: 'ULA was awarded ~40% of NSSL Phase 2 launch service agreements using Atlas V and Vulcan Centaur. Vulcan must complete certification flights before assuming NSSL missions from Atlas V, which is being retired after remaining orders.',
    period: 'FY2022-2027',
  },
  {
    id: 'next-gen-opir-geo',
    title: 'Next-Gen OPIR GEO Satellites (3 units)',
    contractor: 'Lockheed Martin',
    value: '$4.9B',
    awardDate: 'March 2021',
    agency: 'USSF / Space Systems Command',
    category: 'Missile Warning',
    description: 'Contract for three Next-Gen OPIR GEO satellites to replace SBIRS. Each satellite features improved infrared sensors for detecting advanced threats including hypersonic weapons. Builds on Lockheed Martin\'s heritage with SBIRS GEO satellites.',
    period: '2021-2030',
  },
  {
    id: 'next-gen-opir-polar',
    title: 'Next-Gen OPIR Polar Satellites (2 units)',
    contractor: 'Northrop Grumman',
    value: '$2.9B',
    awardDate: 'June 2021',
    agency: 'USSF / Space Systems Command',
    category: 'Missile Warning',
    description: 'Contract for two Next-Gen OPIR Polar satellites providing missile warning and tracking from highly elliptical orbits (HEO). Replaces SBIRS HEO payloads with dedicated, more capable satellites for Arctic and northern hemisphere coverage.',
    period: '2021-2029',
  },
  {
    id: 'gps-iiif',
    title: 'GPS IIIF Follow-On Production (22 satellites)',
    contractor: 'Lockheed Martin',
    value: '$7.2B',
    awardDate: 'September 2018 (initial) + modifications',
    agency: 'USSF / Space Systems Command',
    category: 'Navigation',
    description: 'Production of 22 GPS IIIF satellites (SV11-32) with enhanced capabilities including Regional Military Protection (RMP), search-and-rescue payload, and laser retroreflector arrays. Represents the final modernization of the GPS constellation.',
    period: '2018-2035',
  },
  {
    id: 'sda-tranche2-transport',
    title: 'SDA Tranche 2 Transport Layer (72 satellites)',
    contractor: 'Northrop Grumman',
    value: '$732M',
    awardDate: 'February 2024',
    agency: 'Space Development Agency',
    category: 'SDA / Proliferated Architecture',
    description: 'Award for 72 Tranche 2 Transport Layer Beta satellites with optical inter-satellite links for the Proliferated Warfighter Space Architecture mesh network. Part of the ongoing effort to build a resilient, redundant data transport constellation in LEO.',
    period: '2024-2027',
  },
  {
    id: 'sda-tranche2-transport-l3',
    title: 'SDA Tranche 2 Transport Layer (36 satellites)',
    contractor: 'L3Harris Technologies',
    value: '$559M',
    awardDate: 'February 2024',
    agency: 'Space Development Agency',
    category: 'SDA / Proliferated Architecture',
    description: 'Award for 36 Tranche 2 Transport Layer Alpha satellites. Together with the Northrop Grumman award, completes the Tranche 2 transport layer procurement providing military mesh network communications in LEO.',
    period: '2024-2027',
  },
  {
    id: 'sda-tranche1-tracking',
    title: 'SDA Tranche 1 Tracking Layer (14 satellites)',
    contractor: 'L3Harris Technologies',
    value: '$700M',
    awardDate: 'October 2023',
    agency: 'Space Development Agency',
    category: 'Missile Warning / Tracking',
    description: 'Contract for 14 overhead persistent infrared wide-FOV satellites for hypersonic and ballistic missile tracking from LEO. Part of the Proliferated Warfighter Space Architecture designed to detect and track advanced missile threats.',
    period: '2023-2026',
  },
  {
    id: 'wgs-11',
    title: 'WGS-11+ Wideband SATCOM',
    contractor: 'Boeing',
    value: '$590M',
    awardDate: 'June 2023',
    agency: 'USSF / Space Systems Command',
    category: 'Communications',
    description: 'Contract to build WGS-11 with enhanced digital channelizer, improved cybersecurity, and greater bandwidth. Extends the wideband SATCOM constellation that provides high-data-rate communications for tactical military operations worldwide.',
    period: '2023-2028',
  },
  {
    id: 'ess-initial',
    title: 'Evolved Strategic SATCOM (ESS) Development',
    contractor: 'Northrop Grumman',
    value: '$1.3B (initial development)',
    awardDate: 'July 2023',
    agency: 'USSF / Space Systems Command',
    category: 'Strategic Communications',
    description: 'Initial development contract for the Evolved Strategic SATCOM system to replace AEHF for nuclear command, control, and communications (NC3). ESS will provide jam-resistant, cyber-hardened strategic communications with significantly higher data rates.',
    period: '2023-2030',
  },
  {
    id: 'egs-raytheon',
    title: 'Enterprise Ground Services',
    contractor: 'Raytheon Technologies',
    value: '$3.5B (lifecycle)',
    awardDate: '2018 (modified through 2024)',
    agency: 'USSF / Space Systems Command',
    category: 'Ground Systems',
    description: 'Raytheon is developing the unified, cloud-native ground control system for multiple USSF satellite constellations. EGS replaces stovepiped legacy ground systems with a modular, software-defined architecture. Initial deployment supports GPS OCX.',
    period: '2018-2030',
  },
  {
    id: 'skynet-6a-contract',
    title: 'Skynet 6A Military Communications Satellite',
    contractor: 'Airbus Defence & Space',
    value: '£5B+ (total Skynet 6 programme)',
    awardDate: 'July 2022',
    agency: 'UK MOD',
    category: 'Allied MILSATCOM',
    description: 'Airbus was awarded the contract to build Skynet 6A, the first satellite in the UK\'s next-generation military communications system. The contract includes the satellite, ground segment upgrades, and service provision through the 2040s. Includes anti-jam and enhanced cybersecurity capabilities.',
    period: '2022-2040+',
  },
  {
    id: 'nssl-phase3-lane1',
    title: 'NSSL Phase 3 Lane 1 (Small to Medium Launches)',
    contractor: 'SpaceX, Rocket Lab, Firefly Aerospace, Stoke Space',
    value: '~$5.6B (total lane, multiple IDIQ awards)',
    awardDate: 'June 2024',
    agency: 'USSF / Space Systems Command',
    category: 'Launch Services',
    description: 'Phase 3 Lane 1 awarded to four providers for small-to-medium national security launches. Represents the diversification of the NSSL program beyond the traditional two-provider model. Rocket Lab (Neutron), Firefly (Alpha/MLV), and Stoke Space join SpaceX (Falcon 9).',
    period: 'FY2025-2029',
  },
  {
    id: 'gambit-anduril',
    title: 'GAMBIT Mesh Satellite System',
    contractor: 'Anduril Industries',
    value: '$432M (initial contract)',
    awardDate: 'December 2024',
    agency: 'Space Development Agency',
    category: 'SDA / Proliferated Architecture',
    description: 'Anduril was awarded a contract for its GAMBIT mesh satellite system under SDA\'s Tranche 2 architecture. GAMBIT provides software-defined satellites with reconfigurable payloads supporting tactical military communications in contested environments.',
    period: '2024-2027',
  },
  {
    id: 'palantir-titan',
    title: 'TITAN Ground Station System',
    contractor: 'Palantir Technologies',
    value: '$250M (initial)',
    awardDate: 'March 2024',
    agency: 'U.S. Army / Space',
    category: 'Ground Systems / AI',
    description: 'Palantir\'s TITAN (Tactical Intelligence Targeting Access Node) integrates space sensor data with AI/ML for targeting and intelligence. TITAN processes satellite imagery, signals intelligence, and other space-derived data to create fused intelligence products for ground forces.',
    period: '2024-2028',
  },
  {
    id: 'space-fence-ops',
    title: 'Space Fence Operations & Sustainment',
    contractor: 'Lockheed Martin',
    value: '$1.3B (lifecycle operations)',
    awardDate: 'Ongoing (initial 2015)',
    agency: 'USSF / Space Operations Command',
    category: 'Space Domain Awareness',
    description: 'Lockheed Martin operates and maintains the Space Fence S-band radar on Kwajalein Atoll. The radar detects and tracks objects as small as 10cm in LEO/MEO, processing 1.5 million observations daily. Critical for collision avoidance and threat detection.',
    period: '2015-2030+',
  },
];

// ═══════════════════════════════════════════════════════════════════
// 4. COUNTERSPACE EVENTS (12 events)
// ═══════════════════════════════════════════════════════════════════

const COUNTERSPACE_EVENTS = [
  {
    id: 'china-fy1c-2007',
    date: 'January 11, 2007',
    nation: 'China',
    flag: 'CN',
    type: 'kinetic_asat',
    name: 'FY-1C Destruction',
    description: 'China destroyed its own FY-1C weather satellite at ~865 km altitude using a SC-19 kinetic kill vehicle launched from Xichang. This was the most debris-generating event in space history, creating ~3,500 trackable fragments. Many remain in orbit and continue to threaten operational satellites. The event prompted international condemnation and accelerated space debris mitigation discussions.',
    debrisGenerated: '~3,500 trackable fragments (>10cm), ~35,000 estimated >1cm',
    altitude: '~865 km (sun-synchronous orbit)',
    target: 'FY-1C (Fengyun-1C) weather satellite',
  },
  {
    id: 'usa-193-2008',
    date: 'February 21, 2008',
    nation: 'United States',
    flag: 'US',
    type: 'kinetic_asat',
    name: 'Operation Burnt Frost (USA-193)',
    description: 'The US destroyed the defunct NRO spy satellite USA-193 using a modified SM-3 Block IA missile fired from USS Lake Erie (CG-70) in the Pacific. Officially justified to prevent hazardous hydrazine from reaching Earth\'s surface. The satellite was struck at ~247 km altitude; most debris deorbited within weeks. Widely viewed as a demonstration of US ASAT capability.',
    debrisGenerated: '~174 trackable fragments (most deorbited within weeks)',
    altitude: '~247 km (low orbit, decay imminent)',
    target: 'USA-193 (NROL-21) reconnaissance satellite',
  },
  {
    id: 'india-shakti-2019',
    date: 'March 27, 2019',
    nation: 'India',
    flag: 'IN',
    type: 'kinetic_asat',
    name: 'Mission Shakti',
    description: 'India successfully tested an anti-satellite weapon, destroying the Microsat-R satellite at ~283 km altitude with a PDV Mark II kinetic kill vehicle launched from Abdul Kalam Island. India became the fourth nation to demonstrate ASAT capability. The relatively low altitude was chosen to minimize debris, most of which deorbited within months, though some fragments initially rose to higher altitudes.',
    debrisGenerated: '~400 trackable fragments (mostly decayed by 2020)',
    altitude: '~283 km',
    target: 'Microsat-R (69 kg test satellite)',
  },
  {
    id: 'russia-cosmos1408-2021',
    date: 'November 15, 2021',
    nation: 'Russia',
    flag: 'RU',
    type: 'kinetic_asat',
    name: 'Cosmos 1408 Destruction (Nudol ASAT)',
    description: 'Russia destroyed its own defunct Cosmos 1408 satellite (~2 tons) using a Nudol PL-19 direct-ascent interceptor. The test at ~480 km altitude created 1,500+ trackable debris fragments, forcing ISS crew to shelter in their spacecraft. The event drew strong international condemnation, including from US allies. Many fragments will remain in orbit for decades, threatening the ISS, Tiangong, and commercial constellations.',
    debrisGenerated: '~1,500 trackable fragments (multi-decade lifetime)',
    altitude: '~480 km',
    target: 'Cosmos 1408 (defunct ELINT satellite, 1982)',
  },
  {
    id: 'russia-luch-rpo-2014',
    date: 'September 2014 — ongoing',
    nation: 'Russia',
    flag: 'RU',
    type: 'rpo',
    name: 'Luch/Olymp Rendezvous Operations',
    description: 'Russia\'s Luch (Olymp) satellite has conducted repeated rendezvous and proximity operations (RPO) near Western military and commercial SATCOM satellites in GEO, including Intelsat, SES, and suspected military targets. Luch has been observed maneuvering between multiple GEO positions, likely conducting signals intelligence collection. The satellite\'s behavior prompted France to move one of its Syracuse satellites and publicly denounce the activity.',
    target: 'Multiple GEO SATCOM satellites (Intelsat, SES, military)',
  },
  {
    id: 'china-shiyan-rpo',
    date: '2010 — ongoing',
    nation: 'China',
    flag: 'CN',
    type: 'co_orbital',
    name: 'Shiyan / SJ Series Co-Orbital Operations',
    description: 'China has conducted numerous co-orbital and proximity operations using satellites in the Shiyan (Experiment) and Shijian (Practice) series. SJ-17 in GEO performed rendezvous with other Chinese satellites and has a robotic arm. SJ-21 grappled and removed a defunct BeiDou satellite from GEO in 2022. These missions demonstrate inspection, servicing, and potential offensive co-orbital ASAT capabilities.',
    target: 'Chinese and potentially foreign GEO satellites',
  },
  {
    id: 'viasat-hack-2022',
    date: 'February 24, 2022',
    nation: 'Russia',
    flag: 'RU',
    type: 'cyber',
    name: 'Viasat KA-SAT Cyberattack',
    description: 'Hours before Russia\'s invasion of Ukraine, a cyberattack attributed to Russian military intelligence (GRU) disabled Viasat\'s KA-SAT network by corrupting thousands of SurfBeam2 modem firmware via a VPN exploit. The attack disrupted Ukrainian military communications and also affected 30,000+ terminals across Europe, including German wind farm monitoring. Demonstrated that space systems can be attacked through ground infrastructure.',
    target: 'Viasat KA-SAT commercial satellite network',
  },
  {
    id: 'gps-jamming-ukraine',
    date: '2022 — ongoing',
    nation: 'Russia',
    flag: 'RU',
    type: 'electronic_warfare',
    name: 'GPS/GNSS Jamming & Spoofing (Ukraine/Baltic/Middle East)',
    description: 'Russia has conducted persistent and widespread GPS/GNSS jamming and spoofing operations in Ukraine, the Baltic states, Black Sea, and Eastern Mediterranean. Russian EW systems (Krasukha-4, Pole-21, Tirada-2) have disrupted GPS for military operations and civilian aviation. NATO allies have reported GPS outages across large areas. Spoofing attacks have relocated civilian aircraft positions by hundreds of miles on navigation displays.',
    target: 'GPS/GNSS signals (military and civilian receivers)',
  },
  {
    id: 'cosmos-2542-rpo-2020',
    date: 'January 2020',
    nation: 'Russia',
    flag: 'RU',
    type: 'rpo',
    name: 'Cosmos 2542/2543 USA-245 Shadowing',
    description: 'Russian satellite Cosmos 2542 maneuvered to shadow USA-245 (KH-11 reconnaissance satellite) in LEO. Cosmos 2542 then released a sub-satellite (Cosmos 2543) that also approached the US spy satellite. Gen. Raymond (then CSO) publicly called the behavior "unusual and disturbing." Cosmos 2543 later conducted a directed-energy or kinetic test, releasing a projectile in orbit.',
    target: 'USA-245 (KH-11 Block V reconnaissance satellite)',
  },
  {
    id: 'china-dn3-2018',
    date: 'February 5, 2018',
    nation: 'China',
    flag: 'CN',
    type: 'kinetic_asat',
    name: 'DN-3 Midcourse Interceptor Test',
    description: 'China conducted what the US assessed as a test of the DN-3 exoatmospheric kinetic interceptor, which has dual-use ballistic missile defense and ASAT capability. The test did not create debris (missed or hit a suborbital target). DN-3 is believed capable of reaching satellites in LEO and potentially MEO. China described it as a "ballistic missile defense test."',
    altitude: 'Exoatmospheric (specific altitude classified)',
    target: 'Suborbital target (no orbital debris created)',
  },
  {
    id: 'iran-starlink-jamming-2024',
    date: '2024',
    nation: 'Iran',
    flag: 'IR',
    type: 'electronic_warfare',
    name: 'Iran GPS/Starlink Interference',
    description: 'Iran has been reported to interfere with GPS signals in the Persian Gulf region and has attempted to jam or interfere with Starlink signals during regional tensions. Iranian EW capabilities, while less sophisticated than Russian systems, have disrupted civilian aviation GPS in the region. Iran has also developed cyber capabilities targeting satellite ground stations.',
    target: 'GPS and commercial satellite communications',
  },
  {
    id: 'north-korea-gps-2016',
    date: 'March-April 2016',
    nation: 'North Korea',
    flag: 'KP',
    type: 'electronic_warfare',
    name: 'North Korea GPS Jamming Campaign',
    description: 'North Korea conducted a sustained GPS jamming campaign from locations near the DMZ that disrupted GPS signals across the Seoul metropolitan area and at Incheon International Airport. Over 1,100 aircraft and 700 ships reported GPS disruptions. The jamming used truck-mounted systems with power levels sufficient to affect receivers at 100+ km range. South Korea deployed GPS backup systems in response.',
    target: 'GPS receivers in South Korea (military and civilian)',
  },
];

// ═══════════════════════════════════════════════════════════════════
// 5. ALLIANCES (9 alliances/partnerships)
// ═══════════════════════════════════════════════════════════════════

const ALLIANCES = [
  {
    id: 'cspo',
    name: 'Combined Space Operations Initiative',
    abbreviation: 'CSpO',
    established: '2014',
    members: ['United States', 'United Kingdom', 'Australia', 'Canada', 'New Zealand', 'France', 'Germany'],
    description: 'CSpO is a multinational initiative to improve space operations cooperation among allied nations. It focuses on sharing SSA data, coordinating space operations, and developing collective space defense strategies. CSpO has grown from the original Five Eyes nations to include France and Germany, reflecting the expanding recognition of space as a coalition warfighting domain.',
    keyActivities: [
      'Unified space tasking and SSA data sharing',
      'Combined Space Operations Center (CSpOC) at Vandenberg SFB',
      'Multinational space exercises (e.g., Global Sentinel)',
      'Shared space domain awareness architecture',
      'Interoperable space C2 protocols',
    ],
    headquarters: 'Vandenberg SFB, California',
  },
  {
    id: 'five-eyes-space',
    name: 'Five Eyes Space Cooperation',
    abbreviation: 'FVEY Space',
    established: '1946 (UKUSA Agreement; space cooperation formalized 2010s)',
    members: ['United States', 'United Kingdom', 'Australia', 'Canada', 'New Zealand'],
    description: 'The Five Eyes intelligence alliance (UKUSA) extends to space intelligence sharing, including SSA data, SIGINT collection from space, and overhead imagery cooperation. Five Eyes nations share satellite reconnaissance products, contribute ground-based SSA sensors to a shared picture, and coordinate signals intelligence satellite operations.',
    keyActivities: [
      'Shared access to NRO/GCHQ/ASD satellite imagery',
      'SSA data sharing via Five Eyes Surveillance Network',
      'Joint SIGINT satellite operations coordination',
      'Ground-based radar/telescope contributions to shared SSA',
      'Intelligence assessments on counterspace threats',
    ],
  },
  {
    id: 'nato-space-centre',
    name: 'NATO Space Centre',
    abbreviation: 'NATO Space Centre',
    established: 'October 2020',
    members: ['All 32 NATO member states'],
    description: 'NATO recognized space as an operational domain in December 2019 and established the NATO Space Centre at Allied Air Command (AIRCOM) in Ramstein, Germany in 2020. The Centre coordinates space support to NATO operations, integrates space effects into allied planning, and serves as a hub for space domain awareness. NATO does not own space assets but coordinates member nations\' capabilities.',
    keyActivities: [
      'Space domain awareness coordination for NATO operations',
      'Space support to NATO Mission and Joint Operations',
      'Counterspace threat assessment and warning',
      'NATO space policy and doctrine development',
      'Annual Space exercises (Astro Fighter, AsterX participation)',
      'Integration with SACEUR planning processes',
    ],
    headquarters: 'Allied Air Command, Ramstein, Germany',
  },
  {
    id: 'aukus-space',
    name: 'AUKUS Pillar II — Space Cooperation',
    abbreviation: 'AUKUS',
    established: 'September 2021',
    members: ['Australia', 'United Kingdom', 'United States'],
    description: 'AUKUS Pillar II includes advanced space capabilities as a key area of trilateral cooperation. The three nations are collaborating on deep space SSA, resilient satellite communications, space-based hypersonic missile tracking, and space domain awareness. AUKUS space cooperation builds on existing Five Eyes and CSpO relationships with a focus on Indo-Pacific security.',
    keyActivities: [
      'Deep Space Advanced Radar Capability (DARC)',
      'Resilient space-based PNT alternatives',
      'Shared hypersonic threat tracking from space',
      'Joint space domain awareness architecture',
      'Space industrial base cooperation',
      'AI/ML for space object characterization',
    ],
  },
  {
    id: 'quad-space',
    name: 'Quad Space Cooperation',
    abbreviation: 'Quad',
    established: '2022 (space cooperation stream)',
    members: ['United States', 'India', 'Japan', 'Australia'],
    description: 'The Quad (Quadrilateral Security Dialogue) established a space cooperation stream in 2022, focusing on SSA data sharing, space sustainability, and climate monitoring from space. The Quad Space Working Group coordinates civilian and defense-related space cooperation in the Indo-Pacific. Notable initiatives include shared SSA data to address debris and space sustainability.',
    keyActivities: [
      'SSA data sharing framework',
      'Space sustainability and debris mitigation',
      'Climate and disaster monitoring cooperation',
      'GNSS interoperability (GPS-NavIC-QZSS)',
      'Space-based maritime domain awareness',
    ],
  },
  {
    id: 'eu-sst',
    name: 'EU Space Surveillance and Tracking (EU SST)',
    abbreviation: 'EU SST',
    established: '2014 (Decision 541/2014)',
    members: ['France', 'Germany', 'Spain', 'Italy', 'Poland', 'Portugal', 'Romania', 'Netherlands', 'Czech Republic', 'Denmark', 'Finland', 'Greece', 'Latvia', 'Belgium', 'Slovakia', 'Austria', 'Sweden', 'Norway'],
    description: 'EU SST is a consortium of EU member states providing SSA services including collision avoidance warnings, re-entry predictions, and fragmentation event analysis. The consortium operates a network of ground-based radars, telescopes, and laser ranging stations. It provides free conjunction warnings to satellite operators worldwide and is a key pillar of the EU Space Programme.',
    keyActivities: [
      'Collision avoidance warnings for satellite operators',
      'Atmospheric re-entry predictions',
      'Fragmentation event detection and analysis',
      'Space object catalogue maintenance',
      'Integration with EUSPA and ESA SSA programs',
      'Public conjunction data services (SST Portal)',
    ],
    headquarters: 'EU SatCen, Torrejón de Ardoz, Spain',
  },
  {
    id: 'olympic-defender',
    name: 'Operation Olympic Defender',
    abbreviation: 'Olympic Defender',
    established: '2018',
    members: ['United States', 'United Kingdom', 'Australia', 'Canada', 'France'],
    description: 'Operation Olympic Defender is a multinational coalition for sharing space threat intelligence, coordinating defensive space operations, and developing shared tactics. The operation was established by USSPACECOM and partner nations to synchronize efforts in space protection and defense. Participants share indicators and warnings of counterspace activities and coordinate responses to threats.',
    keyActivities: [
      'Shared counterspace threat intelligence',
      'Coordinated defensive space operations',
      'Space threat response planning and coordination',
      'Shared indications and warning (I&W)',
      'Combined space defense exercises',
    ],
  },
  {
    id: 'japan-us-space',
    name: 'Japan-US Space Security Agreement',
    abbreviation: 'Japan-US SSA',
    established: '2023 (expanded cooperation)',
    members: ['Japan', 'United States'],
    description: 'Japan and the United States significantly expanded bilateral space security cooperation through a 2023 agreement covering SSA data sharing, allied satellite protection, hypersonic missile tracking, and integration of space capabilities into the bilateral alliance. The US will station a USSF unit at a JASDF base for the first time, and the nations will co-develop space-based missile tracking capabilities.',
    keyActivities: [
      'Real-time SSA data sharing',
      'USSF unit deployed to Japan (first overseas permanent presence)',
      'Joint hypersonic glide vehicle tracking satellite development',
      'Bilateral space operations coordination',
      'QZSS-GPS interoperability enhancement',
      'Japan participation in CSpO exercises',
    ],
    headquarters: 'Yokota Air Base, Japan / Vandenberg SFB, USA',
  },
  {
    id: 'schriever-wargame',
    name: 'Schriever Space Wargame Series',
    abbreviation: 'Schriever Wargame',
    established: '2001',
    members: ['United States', 'United Kingdom', 'Australia', 'Canada', 'New Zealand', 'France', 'Germany', 'Japan', 'South Korea'],
    description: 'The Schriever Wargame (now Schriever Spacepower Series) is a biennial multinational table-top exercise focused on space operations across the full spectrum of conflict. Hosted by USSPACECOM, it explores space deterrence, crisis escalation, and military operations in contested space environments. The wargame has been instrumental in developing allied space doctrine and cooperation frameworks.',
    keyActivities: [
      'Multinational space crisis scenario exercises',
      'Space doctrine and strategy development',
      'Allied space interoperability testing',
      'Counterspace threat response wargaming',
      'Space deterrence and escalation management',
      'Academic and think-tank integration',
    ],
    headquarters: 'USSPACECOM, Colorado Springs, CO',
  },
];

// ═══════════════════════════════════════════════════════════════════
// MAIN SEED FUNCTION
// ═══════════════════════════════════════════════════════════════════

async function main() {
  console.log('🛡️ Seeding Space Defense & National Security module...\n');

  console.log('1️⃣  Space Forces...');
  await upsertContent('space-defense', 'space-forces', SPACE_FORCES);

  console.log('2️⃣  Defense Programs...');
  await upsertContent('space-defense', 'defense-programs', DEFENSE_PROGRAMS);

  console.log('3️⃣  Recent Contracts...');
  await upsertContent('space-defense', 'recent-contracts', RECENT_CONTRACTS);

  console.log('4️⃣  Counterspace Events...');
  await upsertContent('space-defense', 'counterspace-events', COUNTERSPACE_EVENTS);

  console.log('5️⃣  Alliances & Partnerships...');
  await upsertContent('space-defense', 'alliances', ALLIANCES);

  console.log(`\n✅ Space Defense seed complete!`);
  console.log(`   • ${SPACE_FORCES.length} space forces`);
  console.log(`   • ${DEFENSE_PROGRAMS.length} defense programs`);
  console.log(`   • ${RECENT_CONTRACTS.length} recent contracts`);
  console.log(`   • ${COUNTERSPACE_EVENTS.length} counterspace events`);
  console.log(`   • ${ALLIANCES.length} alliances & partnerships`);
  console.log(`   • Total: ${SPACE_FORCES.length + DEFENSE_PROGRAMS.length + RECENT_CONTRACTS.length + COUNTERSPACE_EVENTS.length + ALLIANCES.length} items across 5 sections`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
