import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding procurement intelligence data...');

  // ============================================================
  // 1. Procurement Opportunities (35 entries)
  // ============================================================
  const opportunities = [
    {
      samNoticeId: 'SAM-NASA-2026-001',
      title: 'Artemis V Crew Module Environmental Control System',
      description: 'NASA seeks proposals for the design, development, and delivery of next-generation environmental control and life support systems (ECLSS) for the Artemis V crew module. The system must support a crew of four for missions lasting up to 42 days in cislunar space.',
      agency: 'NASA',
      subAgency: 'Marshall Space Flight Center',
      office: 'Exploration Systems Development',
      type: 'solicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      estimatedValue: 450000000,
      postedDate: new Date('2026-01-15'),
      responseDeadline: new Date('2026-03-15'),
      placeOfPerformance: 'Huntsville, AL',
      pointOfContact: 'Jennifer Morrison',
      contactEmail: 'artemis.procurement@nasa.gov',
      solicitationNumber: 'NNM26ABCDEF',
      samUrl: 'https://sam.gov/opp/example-001',
      tags: ['lunar', 'propulsion', 'small-business'],
    },
    {
      samNoticeId: 'SAM-USSF-2026-002',
      title: 'Next-Generation GPS IIIF Satellite Bus Procurement',
      description: 'The United States Space Force seeks qualified contractors to provide satellite bus platforms for the GPS IIIF follow-on program. This procurement supports the modernization of the GPS constellation with enhanced anti-jamming capabilities and increased signal power.',
      agency: 'Space Force',
      subAgency: 'Space Systems Command',
      office: 'PEO Space Production',
      type: 'solicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      estimatedValue: 1200000000,
      postedDate: new Date('2026-01-10'),
      responseDeadline: new Date('2026-04-10'),
      placeOfPerformance: 'El Segundo, CA',
      pointOfContact: 'Col. James Whitfield',
      contactEmail: 'gps.procurement@spaceforce.mil',
      solicitationNumber: 'FA8807-26-R-0001',
      samUrl: 'https://sam.gov/opp/example-002',
      tags: ['navigation', 'satellite'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-003',
      title: 'Commercial LEO Destination Services - Phase 2',
      description: 'NASA seeks proposals from commercial providers to deliver sustained human spaceflight services in low Earth orbit. This solicitation supports the transition from ISS to commercial destinations and includes requirements for crew transportation, research capabilities, and cargo services.',
      agency: 'NASA',
      subAgency: 'Johnson Space Center',
      office: 'Commercial LEO Development',
      type: 'solicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      estimatedValue: 3500000000,
      postedDate: new Date('2026-01-20'),
      responseDeadline: new Date('2026-05-20'),
      placeOfPerformance: 'Houston, TX',
      pointOfContact: 'Dr. Sarah Chen',
      contactEmail: 'cld.procurement@nasa.gov',
      solicitationNumber: 'NNJ26GHIJKL',
      samUrl: 'https://sam.gov/opp/example-003',
      tags: ['space-station', 'research'],
    },
    {
      samNoticeId: 'SAM-NOAA-2026-004',
      title: 'GOES-U Ground Segment Software Modernization',
      description: 'NOAA requires contractor support for the modernization of the GOES-U ground segment software systems. Work includes migration to cloud-based architecture, real-time data processing pipeline improvements, and integration with NESDIS data archive systems.',
      agency: 'NOAA',
      subAgency: 'NESDIS',
      office: 'Satellite Operations',
      type: 'solicitation',
      naicsCode: '541715',
      naicsDescription: 'R&D in Physical, Engineering, and Life Sciences',
      setAside: 'Total Small Business',
      estimatedValue: 35000000,
      postedDate: new Date('2026-01-25'),
      responseDeadline: new Date('2026-03-01'),
      placeOfPerformance: 'Suitland, MD',
      pointOfContact: 'Mark Thompson',
      contactEmail: 'noaa.procurement@noaa.gov',
      solicitationNumber: 'NOAA-NESDIS-2026-001',
      samUrl: 'https://sam.gov/opp/example-004',
      tags: ['satellite', 'small-business'],
    },
    {
      samNoticeId: 'SAM-NRO-2026-005',
      title: 'Electro-Optical Imaging Payload Integration',
      description: 'The National Reconnaissance Office seeks qualified contractors for the integration and test of advanced electro-optical imaging payloads for next-generation reconnaissance satellite systems. Secret clearance required.',
      agency: 'NRO',
      subAgency: null,
      office: 'Advanced Systems and Technology',
      type: 'presolicitation',
      naicsCode: '334511',
      naicsDescription: 'Search, Detection, Navigation, Guidance Systems',
      setAside: 'None',
      estimatedValue: 800000000,
      postedDate: new Date('2026-02-01'),
      responseDeadline: new Date('2026-04-01'),
      placeOfPerformance: 'Chantilly, VA',
      pointOfContact: 'Classified',
      solicitationNumber: 'NRO-AS-2026-001',
      samUrl: 'https://sam.gov/opp/example-005',
      tags: ['satellite', 'research'],
    },
    {
      samNoticeId: 'SAM-USSF-2026-006',
      title: 'Space Domain Awareness (SDA) Sensor Network Expansion',
      description: 'Space Force seeks proposals for expanding the Space Domain Awareness sensor network with ground-based and space-based optical/radar sensors. The program aims to enhance tracking of objects in deep space including cislunar and GEO regimes.',
      agency: 'Space Force',
      subAgency: 'Space Operations Command',
      office: 'Space Domain Awareness',
      type: 'sources_sought',
      naicsCode: '334511',
      naicsDescription: 'Search, Detection, Navigation, Guidance Systems',
      setAside: 'None',
      estimatedValue: 650000000,
      postedDate: new Date('2026-01-05'),
      responseDeadline: new Date('2026-02-15'),
      pointOfContact: 'Maj. Robert Davis',
      contactEmail: 'sda.procurement@spaceforce.mil',
      solicitationNumber: 'FA9453-26-S-0001',
      samUrl: 'https://sam.gov/opp/example-006',
      tags: ['navigation', 'cybersecurity'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-007',
      title: 'SLS Block 2 Exploration Upper Stage (EUS) Production',
      description: 'NASA is soliciting proposals for the production of the Exploration Upper Stage for the Space Launch System Block 2 configuration. The EUS will provide increased payload capacity for deep space missions.',
      agency: 'NASA',
      subAgency: 'Marshall Space Flight Center',
      office: 'SLS Program',
      type: 'solicitation',
      naicsCode: '336415',
      naicsDescription: 'Space Vehicle Propulsion Unit Manufacturing',
      setAside: 'None',
      estimatedValue: 2100000000,
      postedDate: new Date('2025-12-15'),
      responseDeadline: new Date('2026-03-30'),
      placeOfPerformance: 'Huntsville, AL',
      pointOfContact: 'Thomas Bradley',
      contactEmail: 'sls.procurement@nasa.gov',
      solicitationNumber: 'NNM26MNOPQR',
      samUrl: 'https://sam.gov/opp/example-007',
      tags: ['propulsion', 'launch'],
    },
    {
      samNoticeId: 'SAM-DARPA-2026-008',
      title: 'Nuclear Thermal Propulsion (NTP) Flight Demonstrator',
      description: 'DARPA seeks proposals for the Demonstration Rocket for Agile Cislunar Operations (DRACO) follow-on phase. This effort will develop and flight-test a nuclear thermal propulsion system for rapid deep-space transit.',
      agency: 'DARPA',
      subAgency: null,
      office: 'Tactical Technology Office',
      type: 'presolicitation',
      naicsCode: '336415',
      naicsDescription: 'Space Vehicle Propulsion Unit Manufacturing',
      setAside: 'None',
      estimatedValue: 500000000,
      postedDate: new Date('2026-01-28'),
      responseDeadline: new Date('2026-04-28'),
      pointOfContact: 'Dr. Michael Lewis',
      contactEmail: 'draco@darpa.mil',
      solicitationNumber: 'HR0011-26-S-0001',
      samUrl: 'https://sam.gov/opp/example-008',
      tags: ['propulsion', 'research'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-009',
      title: 'Lunar Surface Power System - Fission Surface Power',
      description: 'NASA seeks proposals for the development of a fission surface power system capable of providing 40 kW of continuous electrical power on the lunar surface. The system must operate for a minimum of 10 years and be transportable via commercial lunar lander.',
      agency: 'NASA',
      subAgency: 'Glenn Research Center',
      office: 'Power and In-Space Propulsion Division',
      type: 'solicitation',
      naicsCode: '541715',
      naicsDescription: 'R&D in Physical, Engineering, and Life Sciences',
      setAside: 'None',
      estimatedValue: 300000000,
      postedDate: new Date('2026-02-05'),
      responseDeadline: new Date('2026-05-05'),
      placeOfPerformance: 'Cleveland, OH',
      pointOfContact: 'Angela Martinez',
      contactEmail: 'fsp.procurement@nasa.gov',
      solicitationNumber: 'NNC26STUVWX',
      samUrl: 'https://sam.gov/opp/example-009',
      tags: ['lunar', 'research'],
    },
    {
      samNoticeId: 'SAM-USSF-2026-010',
      title: 'Resilient Missile Warning/Missile Tracking (MW/MT) Constellation',
      description: 'Space Force seeks proposals for the next tranche of the Resilient MW/MT satellite constellation. This program provides persistent, resilient, and survivable missile warning and tracking capabilities from a proliferated architecture.',
      agency: 'Space Force',
      subAgency: 'Space Development Agency',
      office: null,
      type: 'solicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      estimatedValue: 4200000000,
      postedDate: new Date('2025-12-01'),
      responseDeadline: new Date('2026-02-28'),
      placeOfPerformance: 'Washington, DC',
      pointOfContact: 'Col. Patricia Yuan',
      contactEmail: 'sda.procurement@sda.mil',
      solicitationNumber: 'HQ0860-26-R-0001',
      samUrl: 'https://sam.gov/opp/example-010',
      tags: ['satellite'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-011',
      title: 'Mars Sample Return - Earth Entry System',
      description: 'Design, development, and qualification of the Earth Entry System for the Mars Sample Return mission. The system must safely contain and return Mars samples to Earth.',
      agency: 'NASA',
      subAgency: 'Jet Propulsion Laboratory',
      office: 'Mars Exploration Program',
      type: 'solicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      estimatedValue: 900000000,
      postedDate: new Date('2026-01-12'),
      responseDeadline: new Date('2026-04-12'),
      placeOfPerformance: 'Pasadena, CA',
      pointOfContact: 'Dr. Wei Zhang',
      contactEmail: 'msr.procurement@jpl.nasa.gov',
      solicitationNumber: 'NNN26YZABCD',
      samUrl: 'https://sam.gov/opp/example-011',
      tags: ['mars', 'research'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-012',
      title: 'Small Business Innovation Research - Lunar Technologies',
      description: 'NASA SBIR Phase I solicitation for innovative lunar surface technologies including dust mitigation, in-situ resource utilization, autonomous construction, and extreme environment electronics.',
      agency: 'NASA',
      subAgency: 'STMD',
      office: 'SBIR/STTR Program Office',
      type: 'solicitation',
      naicsCode: '541715',
      naicsDescription: 'R&D in Physical, Engineering, and Life Sciences',
      setAside: 'Total Small Business',
      estimatedValue: 150000,
      postedDate: new Date('2026-02-01'),
      responseDeadline: new Date('2026-04-01'),
      placeOfPerformance: 'Multiple',
      pointOfContact: 'SBIR Program Office',
      contactEmail: 'sbir@nasa.gov',
      solicitationNumber: 'NNH26ZCQ001C',
      samUrl: 'https://sam.gov/opp/example-012',
      tags: ['lunar', 'sbir-sttr', 'small-business', 'research'],
    },
    {
      samNoticeId: 'SAM-USSF-2026-013',
      title: 'Evolved Strategic SATCOM (ESS) Ground System Modernization',
      description: 'Space Force seeks to modernize the ground segment for the Evolved Strategic SATCOM system to support nuclear command and control communications. Requires Top Secret/SCI clearance.',
      agency: 'Space Force',
      subAgency: 'Space Systems Command',
      office: 'PEO Strategic Space',
      type: 'presolicitation',
      naicsCode: '517410',
      naicsDescription: 'Satellite Telecommunications',
      setAside: 'None',
      estimatedValue: 750000000,
      postedDate: new Date('2026-01-18'),
      responseDeadline: new Date('2026-04-18'),
      placeOfPerformance: 'Los Angeles, CA',
      pointOfContact: 'Lt Col. David Kim',
      contactEmail: 'ess.procurement@spaceforce.mil',
      solicitationNumber: 'FA8823-26-R-0001',
      samUrl: 'https://sam.gov/opp/example-013',
      tags: ['satellite'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-014',
      title: 'Gateway Power and Propulsion Element - Resupply Services',
      description: 'NASA seeks proposals for resupply and logistics services to the Gateway lunar orbiting outpost. Includes fuel, consumables, and research equipment delivery using commercial vehicles.',
      agency: 'NASA',
      subAgency: 'Johnson Space Center',
      office: 'Gateway Program',
      type: 'solicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      estimatedValue: 1500000000,
      postedDate: new Date('2025-12-20'),
      responseDeadline: new Date('2026-03-20'),
      placeOfPerformance: 'Houston, TX',
      pointOfContact: 'Lisa Rodriguez',
      contactEmail: 'gateway.procurement@nasa.gov',
      solicitationNumber: 'NNJ26EFGHIJ',
      samUrl: 'https://sam.gov/opp/example-014',
      tags: ['lunar', 'space-station', 'launch'],
    },
    {
      samNoticeId: 'SAM-NOAA-2026-015',
      title: 'Commercial Weather Data Purchase - Space-Based Observations',
      description: 'NOAA Commercial Data Program seeks proposals from commercial satellite operators to provide space-based weather observation data including radio occultation, microwave radiometry, and hyperspectral infrared sounding data.',
      agency: 'NOAA',
      subAgency: 'NESDIS',
      office: 'Commercial Data Program',
      type: 'solicitation',
      naicsCode: '517410',
      naicsDescription: 'Satellite Telecommunications',
      setAside: 'Total Small Business',
      estimatedValue: 50000000,
      postedDate: new Date('2026-01-30'),
      responseDeadline: new Date('2026-03-30'),
      placeOfPerformance: 'Suitland, MD',
      pointOfContact: 'Karen Williams',
      contactEmail: 'cdp.procurement@noaa.gov',
      solicitationNumber: 'NOAA-CDP-2026-001',
      samUrl: 'https://sam.gov/opp/example-015',
      tags: ['satellite', 'small-business'],
    },
    // Awards
    {
      samNoticeId: 'SAM-NASA-2026-A001',
      title: 'CLPS Task Order 5 - South Pole Delivery',
      description: 'Award for Commercial Lunar Payload Services delivery to the lunar south pole. Includes delivery of ISRU demonstration and ice-prospecting instruments.',
      agency: 'NASA',
      subAgency: 'Marshall Space Flight Center',
      office: 'CLPS Program',
      type: 'award',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      awardAmount: 108000000,
      postedDate: new Date('2026-01-08'),
      awardDate: new Date('2026-01-08'),
      awardee: 'Intuitive Machines',
      placeOfPerformance: 'Houston, TX',
      pointOfContact: 'CLPS Program Office',
      solicitationNumber: 'NNM26CLPS05',
      samUrl: 'https://sam.gov/opp/example-a001',
      tags: ['lunar', 'launch'],
    },
    {
      samNoticeId: 'SAM-USSF-2026-A002',
      title: 'National Security Space Launch Phase 3 - Lane 1',
      description: 'Award for National Security Space Launch services providing access to orbit for national security payloads.',
      agency: 'Space Force',
      subAgency: 'Space Systems Command',
      office: 'Launch Enterprise',
      type: 'award',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      awardAmount: 5600000000,
      postedDate: new Date('2025-12-15'),
      awardDate: new Date('2025-12-15'),
      awardee: 'United Launch Alliance',
      placeOfPerformance: 'Centennial, CO',
      pointOfContact: 'NSSL Program Office',
      solicitationNumber: 'FA8811-26-C-0001',
      samUrl: 'https://sam.gov/opp/example-a002',
      tags: ['launch'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-A003',
      title: 'Next Space Technologies for Exploration Partnerships (NextSTEP-2)',
      description: 'Award for the development of a deep space habitat prototype supporting Artemis program objectives.',
      agency: 'NASA',
      subAgency: 'Johnson Space Center',
      office: 'AES',
      type: 'award',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      awardAmount: 935000000,
      postedDate: new Date('2025-11-20'),
      awardDate: new Date('2025-11-20'),
      awardee: 'Lockheed Martin',
      placeOfPerformance: 'Houston, TX',
      pointOfContact: 'NextSTEP Program Office',
      solicitationNumber: 'NNJ26NEXTSTEP',
      samUrl: 'https://sam.gov/opp/example-a003',
      tags: ['space-station', 'lunar'],
    },
    // Small business set-asides
    {
      samNoticeId: 'SAM-NASA-2026-016',
      title: 'Additive Manufacturing for In-Space Repair and Assembly',
      description: 'NASA seeks small business proposals for additive manufacturing technologies suitable for in-space repair and assembly of spacecraft components. Technologies should operate in microgravity and vacuum conditions.',
      agency: 'NASA',
      subAgency: 'Langley Research Center',
      office: 'Advanced Materials',
      type: 'solicitation',
      naicsCode: '336419',
      naicsDescription: 'Space Vehicle Parts Manufacturing',
      setAside: '8(a)',
      estimatedValue: 5000000,
      postedDate: new Date('2026-02-03'),
      responseDeadline: new Date('2026-03-15'),
      placeOfPerformance: 'Hampton, VA',
      pointOfContact: 'Dr. Michelle Park',
      contactEmail: 'advmfg@nasa.gov',
      solicitationNumber: 'NNL26ADVMFG',
      samUrl: 'https://sam.gov/opp/example-016',
      tags: ['small-business', 'research'],
    },
    {
      samNoticeId: 'SAM-USSF-2026-017',
      title: 'Cybersecurity Assessment for Satellite Ground Systems',
      description: 'Space Force seeks HUBZone small businesses to perform cybersecurity vulnerability assessments and penetration testing of satellite command and control ground systems.',
      agency: 'Space Force',
      subAgency: 'Space Systems Command',
      office: 'Cyber Division',
      type: 'solicitation',
      naicsCode: '334511',
      naicsDescription: 'Search, Detection, Navigation, Guidance Systems',
      setAside: 'HUBZone',
      estimatedValue: 12000000,
      postedDate: new Date('2026-01-22'),
      responseDeadline: new Date('2026-03-05'),
      placeOfPerformance: 'Peterson SFB, CO',
      pointOfContact: 'Capt. Andrew Stone',
      contactEmail: 'cyber.procurement@spaceforce.mil',
      solicitationNumber: 'FA2550-26-R-0001',
      samUrl: 'https://sam.gov/opp/example-017',
      tags: ['cybersecurity', 'small-business'],
    },
    // Sources Sought
    {
      samNoticeId: 'SAM-NASA-2026-018',
      title: 'Sources Sought - Autonomous Lunar Rover Navigation System',
      description: 'NASA is conducting market research for autonomous navigation systems for lunar surface rovers. Seeking information on capabilities for traversing challenging terrain, operating during lunar night, and communicating with orbiting relay satellites.',
      agency: 'NASA',
      subAgency: 'Jet Propulsion Laboratory',
      office: 'Autonomous Systems',
      type: 'sources_sought',
      naicsCode: '334511',
      naicsDescription: 'Search, Detection, Navigation, Guidance Systems',
      setAside: 'None',
      estimatedValue: null,
      postedDate: new Date('2026-02-06'),
      responseDeadline: new Date('2026-03-06'),
      placeOfPerformance: 'Pasadena, CA',
      pointOfContact: 'Dr. Carlos Mendez',
      contactEmail: 'rover.autonomy@jpl.nasa.gov',
      solicitationNumber: 'NNN26ROVER',
      samUrl: 'https://sam.gov/opp/example-018',
      tags: ['lunar', 'navigation', 'research'],
    },
    // Special Notices
    {
      samNoticeId: 'SAM-NASA-2026-019',
      title: 'NASA Industry Day - Habitable Worlds Observatory',
      description: 'NASA invites industry participation in an Industry Day for the Habitable Worlds Observatory, a flagship astrophysics mission to directly image and characterize Earth-like exoplanets. The event will cover mission requirements, technology needs, and partnership opportunities.',
      agency: 'NASA',
      subAgency: 'Goddard Space Flight Center',
      office: 'Astrophysics Division',
      type: 'special_notice',
      naicsCode: '541715',
      naicsDescription: 'R&D in Physical, Engineering, and Life Sciences',
      setAside: 'None',
      estimatedValue: null,
      postedDate: new Date('2026-02-07'),
      responseDeadline: new Date('2026-02-28'),
      placeOfPerformance: 'Greenbelt, MD',
      pointOfContact: 'Dr. Amanda Foster',
      contactEmail: 'hwo@nasa.gov',
      solicitationNumber: 'NNG26HWO',
      samUrl: 'https://sam.gov/opp/example-019',
      tags: ['research'],
    },
    {
      samNoticeId: 'SAM-USSF-2026-020',
      title: 'Tactical Surveillance Reconnaissance and Tracking (TSRT) Tranche 2',
      description: 'Space Development Agency solicitation for the second tranche of the TSRT satellite layer providing wide-field-of-view infrared sensing from LEO.',
      agency: 'Space Force',
      subAgency: 'Space Development Agency',
      office: null,
      type: 'solicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      estimatedValue: 2800000000,
      postedDate: new Date('2025-12-10'),
      responseDeadline: new Date('2026-03-10'),
      placeOfPerformance: 'Washington, DC',
      pointOfContact: 'SDA Acquisitions',
      solicitationNumber: 'HQ0860-26-R-0002',
      samUrl: 'https://sam.gov/opp/example-020',
      tags: ['satellite'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-021',
      title: 'In-Space Servicing, Assembly, and Manufacturing (ISAM) Demonstration',
      description: 'NASA seeks proposals for an on-orbit demonstration of in-space servicing, assembly, and manufacturing capabilities. The demonstration must include at least two of: refueling, component replacement, structural assembly, and additive manufacturing.',
      agency: 'NASA',
      subAgency: 'Goddard Space Flight Center',
      office: 'Satellite Servicing Projects Division',
      type: 'solicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      estimatedValue: 250000000,
      postedDate: new Date('2026-01-16'),
      responseDeadline: new Date('2026-04-16'),
      placeOfPerformance: 'Greenbelt, MD',
      pointOfContact: 'Dr. Rachel Stone',
      contactEmail: 'isam@nasa.gov',
      solicitationNumber: 'NNG26ISAM01',
      samUrl: 'https://sam.gov/opp/example-021',
      tags: ['satellite', 'research'],
    },
    {
      samNoticeId: 'SAM-NOAA-2026-022',
      title: 'JPSS-3 Satellite Data Processing and Distribution',
      description: 'NOAA seeks proposals for data processing, product generation, and distribution services for the JPSS-3 polar-orbiting weather satellite system.',
      agency: 'NOAA',
      subAgency: 'NESDIS',
      office: 'JPSS Program Office',
      type: 'solicitation',
      naicsCode: '541715',
      naicsDescription: 'R&D in Physical, Engineering, and Life Sciences',
      setAside: 'None',
      estimatedValue: 180000000,
      postedDate: new Date('2026-01-14'),
      responseDeadline: new Date('2026-03-14'),
      placeOfPerformance: 'Lanham, MD',
      pointOfContact: 'John McAlister',
      contactEmail: 'jpss.procurement@noaa.gov',
      solicitationNumber: 'NOAA-JPSS3-2026',
      samUrl: 'https://sam.gov/opp/example-022',
      tags: ['satellite'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-023',
      title: 'Lunar Surface Science Mobility Platform (LSSMP)',
      description: 'NASA seeks proposals for a pressurized rover capable of supporting two crew members for up to 14-day traverses across the lunar surface, supporting Artemis surface operations.',
      agency: 'NASA',
      subAgency: 'Johnson Space Center',
      office: 'Lunar Terrain Vehicle Program',
      type: 'presolicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      estimatedValue: 3800000000,
      postedDate: new Date('2026-02-04'),
      responseDeadline: new Date('2026-05-04'),
      placeOfPerformance: 'Houston, TX',
      pointOfContact: 'Michael Torres',
      contactEmail: 'ltv@nasa.gov',
      solicitationNumber: 'NNJ26LSSMP',
      samUrl: 'https://sam.gov/opp/example-023',
      tags: ['lunar'],
    },
    {
      samNoticeId: 'SAM-USSF-2026-024',
      title: 'Rocket Cargo Vanguard - Rapid Global Logistics',
      description: 'USTRANSCOM and Space Force seek to demonstrate point-to-point cargo delivery using commercial launch vehicles for Department of Defense logistics operations.',
      agency: 'Space Force',
      subAgency: 'Air Force Research Laboratory',
      office: 'Rocket Cargo Program',
      type: 'solicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      estimatedValue: 200000000,
      postedDate: new Date('2026-01-20'),
      responseDeadline: new Date('2026-03-20'),
      placeOfPerformance: 'Kirtland AFB, NM',
      pointOfContact: 'Col. Steven Park',
      solicitationNumber: 'FA9451-26-R-0001',
      samUrl: 'https://sam.gov/opp/example-024',
      tags: ['launch'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-025',
      title: 'WOSB Set-Aside: Space Communication Antenna Design',
      description: 'NASA seeks Women-Owned Small Business proposals for advanced high-gain antenna systems for deep space communication supporting the Deep Space Network modernization.',
      agency: 'NASA',
      subAgency: 'Jet Propulsion Laboratory',
      office: 'DSN Engineering',
      type: 'solicitation',
      naicsCode: '334220',
      naicsDescription: 'Broadcasting and Satellite Equipment',
      setAside: 'WOSB',
      estimatedValue: 8000000,
      postedDate: new Date('2026-01-27'),
      responseDeadline: new Date('2026-03-27'),
      placeOfPerformance: 'Pasadena, CA',
      pointOfContact: 'Dr. Priya Sharma',
      contactEmail: 'dsn@jpl.nasa.gov',
      solicitationNumber: 'NNN26DSN',
      samUrl: 'https://sam.gov/opp/example-025',
      tags: ['small-business'],
    },
    // More awards
    {
      samNoticeId: 'SAM-USSF-2026-A004',
      title: 'Proliferated Warfighter Space Architecture - Transport Layer Tranche 2',
      description: 'Contract award for the optical inter-satellite link mesh network providing resilient military data transport.',
      agency: 'Space Force',
      subAgency: 'Space Development Agency',
      type: 'award',
      naicsCode: '517410',
      naicsDescription: 'Satellite Telecommunications',
      setAside: 'None',
      awardAmount: 1800000000,
      postedDate: new Date('2025-11-15'),
      awardDate: new Date('2025-11-15'),
      awardee: 'Northrop Grumman',
      placeOfPerformance: 'Dulles, VA',
      solicitationNumber: 'HQ0860-25-C-0003',
      samUrl: 'https://sam.gov/opp/example-a004',
      tags: ['satellite'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-A005',
      title: 'Crew Transportation Services to ISS (CTS-3)',
      description: 'Task order award under CTS contract for crew rotation services to the International Space Station.',
      agency: 'NASA',
      subAgency: 'Kennedy Space Center',
      type: 'award',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      awardAmount: 290000000,
      postedDate: new Date('2025-12-28'),
      awardDate: new Date('2025-12-28'),
      awardee: 'SpaceX',
      placeOfPerformance: 'Kennedy Space Center, FL',
      solicitationNumber: 'NNK26CTS03',
      samUrl: 'https://sam.gov/opp/example-a005',
      tags: ['space-station', 'launch'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-026',
      title: 'SDVOSB: Space Radiation Monitoring System Development',
      description: 'Service-Disabled Veteran-Owned Small Business set-aside for development of real-time space radiation monitoring and crew dosimetry systems for deep space missions.',
      agency: 'NASA',
      subAgency: 'Johnson Space Center',
      office: 'Space Radiation Analysis Group',
      type: 'solicitation',
      naicsCode: '541715',
      naicsDescription: 'R&D in Physical, Engineering, and Life Sciences',
      setAside: 'SDVOSB',
      estimatedValue: 3500000,
      postedDate: new Date('2026-02-02'),
      responseDeadline: new Date('2026-03-20'),
      placeOfPerformance: 'Houston, TX',
      pointOfContact: 'Dr. James Cooper',
      contactEmail: 'srag@nasa.gov',
      solicitationNumber: 'NNJ26SRAG',
      samUrl: 'https://sam.gov/opp/example-026',
      tags: ['research', 'small-business'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-027',
      title: 'Europa Clipper Follow-On Science Investigation',
      description: 'NASA Announcement of Opportunity for follow-on science investigations to support the Europa Clipper mission data analysis and potential ocean world habitability assessment.',
      agency: 'NASA',
      subAgency: 'Jet Propulsion Laboratory',
      office: 'Planetary Science Division',
      type: 'special_notice',
      naicsCode: '541715',
      naicsDescription: 'R&D in Physical, Engineering, and Life Sciences',
      setAside: 'None',
      postedDate: new Date('2026-01-06'),
      responseDeadline: new Date('2026-04-06'),
      placeOfPerformance: 'Pasadena, CA',
      pointOfContact: 'Europa Science Office',
      contactEmail: 'europa@jpl.nasa.gov',
      solicitationNumber: 'NNH26EUROPA',
      samUrl: 'https://sam.gov/opp/example-027',
      tags: ['research'],
    },
    {
      samNoticeId: 'SAM-MDA-2026-028',
      title: 'Hypersonic and Ballistic Tracking Space Sensor (HBTSS) Production',
      description: 'Missile Defense Agency seeks proposals for production-rate manufacturing of the HBTSS constellation to provide persistent overhead tracking of hypersonic threats.',
      agency: 'Missile Defense Agency',
      subAgency: null,
      office: 'Space Sensors Directorate',
      type: 'solicitation',
      naicsCode: '334511',
      naicsDescription: 'Search, Detection, Navigation, Guidance Systems',
      setAside: 'None',
      estimatedValue: 3200000000,
      postedDate: new Date('2025-12-05'),
      responseDeadline: new Date('2026-03-05'),
      placeOfPerformance: 'Huntsville, AL',
      pointOfContact: 'HBTSS Program Office',
      solicitationNumber: 'HQ0147-26-R-0001',
      samUrl: 'https://sam.gov/opp/example-028',
      tags: ['satellite'],
    },
    {
      samNoticeId: 'SAM-USSF-2026-029',
      title: 'SpaceWERX - Orbital Prime Services',
      description: 'Space Force SpaceWERX seeks innovative small business solutions for on-orbit servicing capabilities including refueling, repair, relocation, and retirement of satellite assets.',
      agency: 'Space Force',
      subAgency: 'SpaceWERX',
      office: null,
      type: 'solicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'Total Small Business',
      estimatedValue: 25000000,
      postedDate: new Date('2026-01-15'),
      responseDeadline: new Date('2026-03-15'),
      placeOfPerformance: 'Multiple',
      pointOfContact: 'SpaceWERX Transitions',
      contactEmail: 'spacewerx@spaceforce.mil',
      solicitationNumber: 'FA8649-26-S-0001',
      samUrl: 'https://sam.gov/opp/example-029',
      tags: ['satellite', 'small-business'],
    },
    {
      samNoticeId: 'SAM-NASA-2026-030',
      title: 'Commercial Suborbital Research Services',
      description: 'NASA Flight Opportunities Program seeks proposals from commercial suborbital flight providers to offer technology demonstration and research flight services.',
      agency: 'NASA',
      subAgency: 'STMD',
      office: 'Flight Opportunities Program',
      type: 'solicitation',
      naicsCode: '336414',
      naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
      setAside: 'None',
      estimatedValue: 45000000,
      postedDate: new Date('2026-01-24'),
      responseDeadline: new Date('2026-04-24'),
      placeOfPerformance: 'Multiple',
      pointOfContact: 'Flight Opportunities Office',
      contactEmail: 'flightopps@nasa.gov',
      solicitationNumber: 'NNH26FLTOPP',
      samUrl: 'https://sam.gov/opp/example-030',
      tags: ['launch', 'research'],
    },
  ];

  for (const opp of opportunities) {
    await prisma.procurementOpportunity.upsert({
      where: { samNoticeId: opp.samNoticeId! },
      update: opp,
      create: { ...opp, isActive: true },
    });
  }
  console.log(`  Seeded ${opportunities.length} procurement opportunities`);

  // ============================================================
  // 2. SBIR/STTR Solicitations (18 entries)
  // ============================================================
  const sbirSolicitations = [
    {
      program: 'SBIR',
      agency: 'NASA',
      topicNumber: 'Z16.01',
      topicTitle: 'Lightweight Cryogenic Insulation for In-Space Propulsion',
      description: 'Develop lightweight, multi-layer insulation systems for long-duration cryogenic propellant storage in deep space. Solutions must minimize boil-off to less than 0.1% per day for liquid hydrogen and liquid oxygen.',
      phase: 'Phase I',
      awardAmount: 150000,
      openDate: new Date('2026-01-15'),
      closeDate: new Date('2026-03-15'),
      url: 'https://sbir.nasa.gov/topics/Z16.01',
      keywords: ['cryogenic', 'propulsion', 'insulation', 'deep-space'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'NASA',
      topicNumber: 'H16.02',
      topicTitle: 'Advanced Life Support Systems for Lunar Habitat',
      description: 'Develop closed-loop life support technologies for extended lunar surface habitation including water recovery, CO2 removal and conversion, and trace contaminant control.',
      phase: 'Phase I',
      awardAmount: 150000,
      openDate: new Date('2026-01-15'),
      closeDate: new Date('2026-03-15'),
      url: 'https://sbir.nasa.gov/topics/H16.02',
      keywords: ['lunar', 'life-support', 'habitat', 'ECLSS'],
      isActive: true,
    },
    {
      program: 'STTR',
      agency: 'NASA',
      topicNumber: 'T16.03',
      topicTitle: 'Autonomous Hazard Detection and Avoidance for Lunar Landing',
      description: 'Develop real-time hazard detection and avoidance algorithms and sensor systems for precision landing on the lunar surface, capable of identifying rocks, craters, and slopes.',
      phase: 'Phase I',
      awardAmount: 150000,
      openDate: new Date('2026-01-15'),
      closeDate: new Date('2026-03-15'),
      url: 'https://sbir.nasa.gov/topics/T16.03',
      keywords: ['lunar', 'landing', 'autonomy', 'sensors'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'SpaceWERX',
      topicNumber: 'SW26-001',
      topicTitle: 'On-Orbit Refueling Interface Standards and Hardware',
      description: 'Develop standardized mechanical and fluid interfaces for on-orbit refueling of satellite assets. Solutions must be compatible with existing satellite bus designs and support both storable and cryogenic propellants.',
      phase: 'Phase I',
      awardAmount: 250000,
      openDate: new Date('2026-01-20'),
      closeDate: new Date('2026-03-20'),
      url: 'https://spacewerx.us/topics/SW26-001',
      keywords: ['refueling', 'on-orbit-servicing', 'satellite'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'SpaceWERX',
      topicNumber: 'SW26-002',
      topicTitle: 'Resilient Optical Inter-Satellite Links for Contested Environments',
      description: 'Develop optical cross-link terminal technologies that provide resilient, high-bandwidth communications between satellites in contested electromagnetic environments.',
      phase: 'Phase I',
      awardAmount: 250000,
      openDate: new Date('2026-01-20'),
      closeDate: new Date('2026-03-20'),
      url: 'https://spacewerx.us/topics/SW26-002',
      keywords: ['optical-comm', 'satellite', 'resilient', 'inter-satellite-link'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'NASA',
      topicNumber: 'S16.04',
      topicTitle: 'Quantum Sensing for Space-Based Gravity Mapping',
      description: 'Develop quantum sensor technologies (atom interferometers, quantum accelerometers) for high-precision gravity field mapping from satellite platforms.',
      phase: 'Phase II',
      awardAmount: 750000,
      openDate: new Date('2025-10-01'),
      closeDate: new Date('2026-04-01'),
      url: 'https://sbir.nasa.gov/topics/S16.04',
      keywords: ['quantum-sensing', 'gravity', 'satellite', 'earth-observation'],
      isActive: true,
    },
    {
      program: 'STTR',
      agency: 'NASA',
      topicNumber: 'T16.05',
      topicTitle: 'In-Situ Resource Utilization - Lunar Regolith Processing',
      description: 'Develop technologies for extracting oxygen, water, and construction materials from lunar regolith. Approaches should demonstrate scalability to production rates supporting sustained human presence.',
      phase: 'Phase I',
      awardAmount: 150000,
      openDate: new Date('2026-01-15'),
      closeDate: new Date('2026-03-15'),
      url: 'https://sbir.nasa.gov/topics/T16.05',
      keywords: ['ISRU', 'lunar', 'regolith', 'oxygen-extraction'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'NASA',
      topicNumber: 'A16.06',
      topicTitle: 'Advanced Solar Electric Propulsion for Small Spacecraft',
      description: 'Develop compact, high-efficiency solar electric propulsion systems for SmallSat and CubeSat platforms targeting specific impulse greater than 2000 seconds with power levels of 500W to 5kW.',
      phase: 'Phase I',
      awardAmount: 150000,
      openDate: new Date('2026-01-15'),
      closeDate: new Date('2026-03-15'),
      url: 'https://sbir.nasa.gov/topics/A16.06',
      keywords: ['propulsion', 'solar-electric', 'smallsat', 'cubesat'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'SpaceWERX',
      topicNumber: 'SW26-003',
      topicTitle: 'Space-Based Cyber Threat Detection',
      description: 'Develop AI/ML-based cyber threat detection and response capabilities for satellite ground systems and space-to-ground communication links.',
      phase: 'Phase I',
      awardAmount: 250000,
      openDate: new Date('2026-02-01'),
      closeDate: new Date('2026-04-01'),
      url: 'https://spacewerx.us/topics/SW26-003',
      keywords: ['cybersecurity', 'AI', 'satellite', 'ground-systems'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'NOAA',
      topicNumber: 'NOAA-26-001',
      topicTitle: 'Advanced Radio Occultation Receivers for Commercial Satellites',
      description: 'Develop next-generation GNSS radio occultation receivers suitable for integration on commercial satellite platforms to provide atmospheric profiling data for weather forecasting.',
      phase: 'Phase I',
      awardAmount: 125000,
      openDate: new Date('2026-01-10'),
      closeDate: new Date('2026-03-10'),
      url: 'https://sbir.gov/topics/NOAA-26-001',
      keywords: ['radio-occultation', 'weather', 'GNSS', 'atmospheric'],
      isActive: true,
    },
    // Phase II and III awards
    {
      program: 'SBIR',
      agency: 'NASA',
      topicNumber: 'Z15.07',
      topicTitle: 'Radiation-Hardened AI Accelerator for Autonomous Spacecraft',
      description: 'Phase II development of a radiation-hardened AI inference accelerator chip for autonomous spacecraft operations including real-time navigation, anomaly detection, and scientific data triage.',
      phase: 'Phase II',
      awardAmount: 750000,
      openDate: new Date('2025-06-01'),
      closeDate: new Date('2026-06-01'),
      url: 'https://sbir.nasa.gov/topics/Z15.07',
      keywords: ['AI', 'radiation-hardened', 'autonomous', 'spacecraft'],
      isActive: true,
    },
    {
      program: 'STTR',
      agency: 'NASA',
      topicNumber: 'T15.08',
      topicTitle: 'Metamaterial-Based Thermal Protection for Mars Entry',
      description: 'Phase II development of engineered metamaterial thermal protection systems for Mars atmospheric entry vehicles, enabling higher ballistic coefficient entries for heavier payloads.',
      phase: 'Phase II',
      awardAmount: 750000,
      openDate: new Date('2025-07-01'),
      closeDate: new Date('2026-07-01'),
      url: 'https://sbir.nasa.gov/topics/T15.08',
      keywords: ['thermal-protection', 'mars', 'metamaterial', 'entry'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'SpaceWERX',
      topicNumber: 'SW25-010',
      topicTitle: 'Deployable Space Solar Power Demonstrator',
      description: 'Phase III transition of deployable solar power collection and beaming technology for space-based power generation. Must demonstrate 1kW beaming capability at relevant distances.',
      phase: 'Phase III',
      awardAmount: 5000000,
      openDate: new Date('2025-09-01'),
      closeDate: new Date('2027-09-01'),
      url: 'https://spacewerx.us/topics/SW25-010',
      keywords: ['solar-power', 'space-based', 'deployable', 'beaming'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'NASA',
      topicNumber: 'H16.09',
      topicTitle: 'Compact Nuclear Power for Lunar Surface Operations',
      description: 'Develop compact fission reactor designs for lunar surface power systems in the 1-10 kWe range, suitable for deployment via CLPS landers and operation in the permanently shadowed regions.',
      phase: 'Phase I',
      awardAmount: 150000,
      openDate: new Date('2026-01-15'),
      closeDate: new Date('2026-03-15'),
      url: 'https://sbir.nasa.gov/topics/H16.09',
      keywords: ['nuclear', 'lunar', 'power', 'fission'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'NASA',
      topicNumber: 'S16.10',
      topicTitle: 'Miniaturized Mass Spectrometer for Planetary Science',
      description: 'Develop a miniaturized mass spectrometer instrument suitable for SmallSat or CubeSat platforms to analyze atmospheric composition of planetary bodies and small body outgassing.',
      phase: 'Phase I',
      awardAmount: 150000,
      openDate: new Date('2026-01-15'),
      closeDate: new Date('2026-03-15'),
      url: 'https://sbir.nasa.gov/topics/S16.10',
      keywords: ['mass-spectrometer', 'planetary-science', 'instrument', 'smallsat'],
      isActive: true,
    },
    {
      program: 'STTR',
      agency: 'SpaceWERX',
      topicNumber: 'SW26-004',
      topicTitle: 'Machine Learning for Satellite Anomaly Resolution',
      description: 'Develop ML-based systems that can autonomously detect, diagnose, and resolve satellite anomalies in real-time, reducing dependence on ground-based mission control for routine operations.',
      phase: 'Phase I',
      awardAmount: 250000,
      openDate: new Date('2026-02-01'),
      closeDate: new Date('2026-04-01'),
      url: 'https://spacewerx.us/topics/SW26-004',
      keywords: ['machine-learning', 'anomaly-detection', 'satellite', 'autonomous'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'NASA',
      topicNumber: 'Z16.11',
      topicTitle: 'Advanced Composite Materials for Cryogenic Fuel Tanks',
      description: 'Develop advanced composite material systems for cryogenic fuel tank applications on next-generation launch vehicles and in-space stages, targeting 30% mass reduction compared to metallic designs.',
      phase: 'Phase I',
      awardAmount: 150000,
      openDate: new Date('2026-01-15'),
      closeDate: new Date('2026-03-15'),
      url: 'https://sbir.nasa.gov/topics/Z16.11',
      keywords: ['composite', 'cryogenic', 'fuel-tank', 'launch-vehicle'],
      isActive: true,
    },
    {
      program: 'SBIR',
      agency: 'NOAA',
      topicNumber: 'NOAA-26-002',
      topicTitle: 'AI-Enhanced Satellite Imagery for Ocean Monitoring',
      description: 'Develop AI/ML processing pipelines for automated detection and tracking of marine phenomena including harmful algal blooms, oil spills, and illegal fishing activities from commercial satellite imagery.',
      phase: 'Phase I',
      awardAmount: 125000,
      openDate: new Date('2026-01-10'),
      closeDate: new Date('2026-03-10'),
      url: 'https://sbir.gov/topics/NOAA-26-002',
      keywords: ['AI', 'ocean-monitoring', 'satellite-imagery', 'earth-observation'],
      isActive: true,
    },
  ];

  for (const sbir of sbirSolicitations) {
    await prisma.sBIRSolicitation.create({ data: sbir });
  }
  console.log(`  Seeded ${sbirSolicitations.length} SBIR/STTR solicitations`);

  // ============================================================
  // 3. Space Budget Items (FY2024-2026)
  // ============================================================
  const budgetItems = [
    // NASA FY2026
    { agency: 'NASA', fiscalYear: 2026, category: 'Exploration', program: 'Artemis', requestAmount: 7800, enactedAmount: null, previousYear: 7500, changePercent: 4.0, source: "President's FY2026 Budget Request", notes: 'Includes SLS, Orion, Gateway, and HLS' },
    { agency: 'NASA', fiscalYear: 2026, category: 'Exploration', program: 'International Space Station', requestAmount: 1300, enactedAmount: null, previousYear: 1400, changePercent: -7.1, source: "President's FY2026 Budget Request", notes: 'Gradual reduction as commercial destinations come online' },
    { agency: 'NASA', fiscalYear: 2026, category: 'Exploration', program: 'Commercial LEO Destinations', requestAmount: 400, enactedAmount: null, previousYear: 300, changePercent: 33.3, source: "President's FY2026 Budget Request", notes: 'Supporting CLD program development' },
    { agency: 'NASA', fiscalYear: 2026, category: 'Science', program: 'Planetary Science', requestAmount: 3200, enactedAmount: null, previousYear: 3100, changePercent: 3.2, source: "President's FY2026 Budget Request", notes: 'Includes Mars Sample Return restructured approach' },
    { agency: 'NASA', fiscalYear: 2026, category: 'Science', program: 'Astrophysics', requestAmount: 1800, enactedAmount: null, previousYear: 1650, changePercent: 9.1, source: "President's FY2026 Budget Request", notes: 'Includes Habitable Worlds Observatory Phase A' },
    { agency: 'NASA', fiscalYear: 2026, category: 'Science', program: 'Earth Science', requestAmount: 2400, enactedAmount: null, previousYear: 2300, changePercent: 4.3, source: "President's FY2026 Budget Request", notes: 'Earth System Observatory continuation' },
    { agency: 'NASA', fiscalYear: 2026, category: 'Science', program: 'Heliophysics', requestAmount: 850, enactedAmount: null, previousYear: 800, changePercent: 6.3, source: "President's FY2026 Budget Request" },
    { agency: 'NASA', fiscalYear: 2026, category: 'Space Technology', program: 'Technology Development', requestAmount: 1500, enactedAmount: null, previousYear: 1400, changePercent: 7.1, source: "President's FY2026 Budget Request", notes: 'Nuclear propulsion, ISRU, and advanced materials' },
    { agency: 'NASA', fiscalYear: 2026, category: 'Space Technology', program: 'SBIR/STTR', requestAmount: 320, enactedAmount: null, previousYear: 300, changePercent: 6.7, source: "President's FY2026 Budget Request" },
    { agency: 'NASA', fiscalYear: 2026, category: 'Aeronautics', program: 'Aeronautics Research', requestAmount: 1000, enactedAmount: null, previousYear: 980, changePercent: 2.0, source: "President's FY2026 Budget Request", notes: 'Includes X-59 QueSST operations' },
    { agency: 'NASA', fiscalYear: 2026, category: 'Space Operations', program: 'Space Communications', requestAmount: 650, enactedAmount: null, previousYear: 600, changePercent: 8.3, source: "President's FY2026 Budget Request", notes: 'DSN modernization and commercial relay services' },

    // NASA FY2025 (enacted)
    { agency: 'NASA', fiscalYear: 2025, category: 'Exploration', program: 'Artemis', requestAmount: 7500, enactedAmount: 7400, previousYear: 7100, changePercent: 4.2, source: 'FY2025 Consolidated Appropriations Act' },
    { agency: 'NASA', fiscalYear: 2025, category: 'Exploration', program: 'International Space Station', requestAmount: 1400, enactedAmount: 1350, previousYear: 1500, changePercent: -10.0, source: 'FY2025 Consolidated Appropriations Act' },
    { agency: 'NASA', fiscalYear: 2025, category: 'Science', program: 'Planetary Science', requestAmount: 3100, enactedAmount: 3050, previousYear: 2900, changePercent: 5.2, source: 'FY2025 Consolidated Appropriations Act' },
    { agency: 'NASA', fiscalYear: 2025, category: 'Science', program: 'Astrophysics', requestAmount: 1650, enactedAmount: 1600, previousYear: 1550, changePercent: 3.2, source: 'FY2025 Consolidated Appropriations Act' },
    { agency: 'NASA', fiscalYear: 2025, category: 'Space Technology', program: 'Technology Development', requestAmount: 1400, enactedAmount: 1380, previousYear: 1300, changePercent: 6.2, source: 'FY2025 Consolidated Appropriations Act' },

    // Space Force FY2026
    { agency: 'Space Force', fiscalYear: 2026, category: 'Space Procurement', program: 'GPS III/IIIF', requestAmount: 2100, enactedAmount: null, previousYear: 1800, changePercent: 16.7, source: "President's FY2026 Budget Request", notes: 'Accelerated GPS IIIF production' },
    { agency: 'Space Force', fiscalYear: 2026, category: 'Space Procurement', program: 'NSSL', requestAmount: 3500, enactedAmount: null, previousYear: 3200, changePercent: 9.4, source: "President's FY2026 Budget Request", notes: 'National Security Space Launch Phase 3' },
    { agency: 'Space Force', fiscalYear: 2026, category: 'Space Procurement', program: 'Missile Warning/Tracking', requestAmount: 4800, enactedAmount: null, previousYear: 4200, changePercent: 14.3, source: "President's FY2026 Budget Request", notes: 'SDA Proliferated Warfighter Space Architecture' },
    { agency: 'Space Force', fiscalYear: 2026, category: 'Space Procurement', program: 'Space Domain Awareness', requestAmount: 2200, enactedAmount: null, previousYear: 1900, changePercent: 15.8, source: "President's FY2026 Budget Request" },
    { agency: 'Space Force', fiscalYear: 2026, category: 'RDT&E', program: 'Space Technology', requestAmount: 3800, enactedAmount: null, previousYear: 3400, changePercent: 11.8, source: "President's FY2026 Budget Request", notes: 'Includes NTP, on-orbit servicing R&D' },
    { agency: 'Space Force', fiscalYear: 2026, category: 'Operations', program: 'Space Operations', requestAmount: 5200, enactedAmount: null, previousYear: 4800, changePercent: 8.3, source: "President's FY2026 Budget Request" },

    // Space Force FY2025
    { agency: 'Space Force', fiscalYear: 2025, category: 'Space Procurement', program: 'GPS III/IIIF', requestAmount: 1800, enactedAmount: 1750, previousYear: 1600, changePercent: 9.4, source: 'FY2025 NDAA' },
    { agency: 'Space Force', fiscalYear: 2025, category: 'Space Procurement', program: 'Missile Warning/Tracking', requestAmount: 4200, enactedAmount: 4100, previousYear: 3500, changePercent: 17.1, source: 'FY2025 NDAA' },

    // NOAA FY2026
    { agency: 'NOAA', fiscalYear: 2026, category: 'Satellite Programs', program: 'GOES-U Operations', requestAmount: 450, enactedAmount: null, previousYear: 420, changePercent: 7.1, source: "President's FY2026 Budget Request" },
    { agency: 'NOAA', fiscalYear: 2026, category: 'Satellite Programs', program: 'JPSS', requestAmount: 850, enactedAmount: null, previousYear: 800, changePercent: 6.3, source: "President's FY2026 Budget Request", notes: 'Polar satellite constellation operations' },
    { agency: 'NOAA', fiscalYear: 2026, category: 'Satellite Programs', program: 'Commercial Data Purchase', requestAmount: 120, enactedAmount: null, previousYear: 95, changePercent: 26.3, source: "President's FY2026 Budget Request", notes: 'Expanding commercial weather data acquisitions' },

    // NASA FY2024 (historical)
    { agency: 'NASA', fiscalYear: 2024, category: 'Exploration', program: 'Artemis', requestAmount: 7100, enactedAmount: 7000, previousYear: 6800, changePercent: 2.9, source: 'FY2024 Consolidated Appropriations Act' },
    { agency: 'NASA', fiscalYear: 2024, category: 'Science', program: 'Planetary Science', requestAmount: 2900, enactedAmount: 2850, previousYear: 2750, changePercent: 3.6, source: 'FY2024 Consolidated Appropriations Act' },
  ];

  for (const item of budgetItems) {
    await prisma.spaceBudgetItem.upsert({
      where: {
        agency_fiscalYear_category_program: {
          agency: item.agency,
          fiscalYear: item.fiscalYear,
          category: item.category,
          program: item.program!,
        },
      },
      update: item,
      create: item,
    });
  }
  console.log(`  Seeded ${budgetItems.length} budget items`);

  // ============================================================
  // 4. Congressional Activities (15 entries)
  // ============================================================
  const congressionalActivities = [
    {
      type: 'hearing',
      committee: 'Senate Commerce',
      subcommittee: 'Space and Science',
      title: 'NASA FY2026 Budget Request Review',
      description: 'Review of NASA\'s FY2026 budget request focusing on Artemis program timelines, Mars Sample Return restructuring, and Commercial LEO Destination development.',
      date: new Date('2026-03-15'),
      status: 'scheduled',
      witnesses: ['NASA Administrator', 'NASA CFO', 'IG Representative'],
      relevance: 'Directly impacts NASA contract funding levels and program priorities for the space industry.',
      sourceUrl: 'https://commerce.senate.gov/hearings',
    },
    {
      type: 'hearing',
      committee: 'House Science',
      subcommittee: 'Space and Aeronautics',
      title: 'Space Situational Awareness and Orbital Sustainability',
      description: 'Hearing on the state of space situational awareness capabilities, orbital debris mitigation, and the need for enhanced tracking infrastructure.',
      date: new Date('2026-02-20'),
      status: 'scheduled',
      witnesses: ['USSF Space Operations Commander', 'Commerce Dept OSC Director', 'Industry Expert Panel'],
      relevance: 'May result in new requirements for satellite operators and increased SSA funding.',
      sourceUrl: 'https://science.house.gov/hearings',
    },
    {
      type: 'markup',
      committee: 'SASC',
      subcommittee: 'Strategic Forces',
      title: 'FY2026 National Defense Authorization Act - Space Provisions',
      description: 'Markup of space-related provisions in the FY2026 NDAA, including Space Force procurement authorities, commercial space utilization, and space domain awareness.',
      date: new Date('2026-05-10'),
      status: 'scheduled',
      witnesses: [],
      relevance: 'Sets authorization levels for all DoD space programs and may include new commercial space provisions.',
      sourceUrl: 'https://armed-services.senate.gov',
    },
    {
      type: 'hearing',
      committee: 'Senate Commerce',
      subcommittee: 'Space and Science',
      title: 'Commercial Space Transportation: Safety, Innovation, and the Regulatory Framework',
      description: 'Examination of FAA commercial space transportation regulatory framework, learning period extension, and the balance between safety and innovation.',
      date: new Date('2026-02-28'),
      status: 'scheduled',
      witnesses: ['FAA AST Associate Administrator', 'SpaceX VP Government Affairs', 'Blue Origin VP', 'Rocket Lab VP'],
      relevance: 'Could impact commercial launch regulatory requirements and the human spaceflight learning period.',
      sourceUrl: 'https://commerce.senate.gov/hearings',
    },
    {
      type: 'authorization',
      committee: 'House Science',
      title: 'NASA Authorization Act of 2026',
      description: 'Comprehensive NASA authorization bill setting program priorities and funding authorizations for FY2026-2028, including Artemis, commercial space, and science missions.',
      date: new Date('2026-04-15'),
      status: 'scheduled',
      billNumber: 'H.R. 4567',
      witnesses: [],
      relevance: 'Multi-year authorization provides long-term program stability and funding certainty for NASA contractors.',
      sourceUrl: 'https://science.house.gov',
    },
    {
      type: 'hearing',
      committee: 'HASC',
      subcommittee: 'Strategic Forces',
      title: 'Space Force Acquisition Reform and Commercial Integration',
      description: 'Review of Space Force acquisition reform efforts, commercial space integration strategy, and the role of SpaceWERX in accelerating technology adoption.',
      date: new Date('2026-03-05'),
      status: 'scheduled',
      witnesses: ['USSF Chief of Space Operations', 'Space Systems Command Commander', 'SpaceWERX Director'],
      relevance: 'May accelerate commercial space procurement pathways and expand SpaceWERX authorities.',
      sourceUrl: 'https://armedservices.house.gov',
    },
    {
      type: 'appropriation',
      committee: 'Senate Appropriations',
      subcommittee: 'Commerce, Justice, Science',
      title: 'FY2026 CJS Appropriations - NASA and NOAA',
      description: 'Appropriations markup for NASA, NOAA, and other science agency budgets for FY2026.',
      date: new Date('2026-06-20'),
      status: 'scheduled',
      witnesses: [],
      relevance: 'Determines final funding levels for NASA, NOAA satellite programs, and SBIR/STTR.',
      sourceUrl: 'https://appropriations.senate.gov',
    },
    {
      type: 'hearing',
      committee: 'Senate Commerce',
      subcommittee: 'Space and Science',
      title: 'Cislunar Economy: Building the Foundation for Sustained Lunar Presence',
      description: 'Hearing examining the emerging cislunar economy including CLPS program, Gateway logistics, ISRU development, and commercial lunar services.',
      date: new Date('2026-04-01'),
      status: 'scheduled',
      witnesses: ['NASA Exploration Director', 'Intuitive Machines CEO', 'Astrobotic CEO', 'Lunar Industry Association'],
      relevance: 'Could lead to expanded CLPS program funding and new lunar infrastructure authorities.',
      sourceUrl: 'https://commerce.senate.gov/hearings',
    },
    {
      type: 'report',
      committee: 'House Science',
      title: 'GAO Report: NASA Artemis Program Cost and Schedule Assessment',
      description: 'Government Accountability Office report assessing Artemis program cost growth, schedule delays, and management challenges across SLS, Orion, HLS, and Gateway.',
      date: new Date('2026-01-20'),
      status: 'completed',
      billNumber: 'GAO-26-105',
      witnesses: [],
      relevance: 'GAO findings may influence congressional oversight and contract modifications for Artemis prime contractors.',
      sourceUrl: 'https://gao.gov/reports',
    },
    {
      type: 'hearing',
      committee: 'HASC',
      subcommittee: 'Strategic Forces',
      title: 'Resilient Space Architecture: Defending Against Counter-Space Threats',
      description: 'Classified and unclassified hearing on counter-space threats and DoD resilient space architecture strategy.',
      date: new Date('2026-03-20'),
      status: 'scheduled',
      witnesses: ['NRO Director', 'DIA Director', 'USSF Deputy CSO'],
      relevance: 'May accelerate proliferated constellation programs and increase demand for responsive launch services.',
      sourceUrl: 'https://armedservices.house.gov',
    },
    {
      type: 'hearing',
      committee: 'Senate Commerce',
      title: 'Spectrum Management for the Space Age',
      description: 'Hearing on spectrum allocation challenges for proliferated satellite constellations, interference mitigation, and international coordination requirements.',
      date: new Date('2026-02-15'),
      status: 'scheduled',
      witnesses: ['FCC Chairperson', 'NTIA Administrator', 'ITU Representative', 'SpaceX Spectrum Lead'],
      relevance: 'Spectrum policy decisions directly impact satellite constellation operators and ground system providers.',
      sourceUrl: 'https://commerce.senate.gov/hearings',
    },
    {
      type: 'authorization',
      committee: 'SASC',
      title: 'Space Force Establishment and Operations Act Amendments',
      description: 'Legislation to amend the Space Force establishment act, expanding authorities for commercial space partnerships and streamlined acquisition.',
      date: new Date('2026-04-30'),
      status: 'scheduled',
      billNumber: 'S. 2345',
      witnesses: [],
      relevance: 'Would create new pathways for commercial companies to provide services to Space Force.',
      sourceUrl: 'https://armed-services.senate.gov',
    },
    {
      type: 'report',
      committee: 'Senate Commerce',
      title: 'CBO Report: Federal Space Spending Trends 2020-2030',
      description: 'Congressional Budget Office analysis of federal space spending trends across NASA, DoD, NOAA, and other agencies with projections through 2030.',
      date: new Date('2026-02-10'),
      status: 'completed',
      witnesses: [],
      relevance: 'Provides comprehensive view of government space spending trajectory informing industry investment decisions.',
      sourceUrl: 'https://cbo.gov/reports',
    },
    {
      type: 'hearing',
      committee: 'House Science',
      subcommittee: 'Space and Aeronautics',
      title: 'STEM Workforce for the Space Economy',
      description: 'Hearing on STEM workforce development needs for the growing space industry, examining university programs, apprenticeships, and clearance pipeline challenges.',
      date: new Date('2026-03-25'),
      status: 'scheduled',
      witnesses: ['NSF Director', 'University Space Research Association President', 'Industry HR Leaders Panel'],
      relevance: 'May lead to new STEM funding programs and workforce development initiatives for the space sector.',
      sourceUrl: 'https://science.house.gov/hearings',
    },
    {
      type: 'markup',
      committee: 'HASC',
      title: 'FY2026 NDAA - Full Committee Markup',
      description: 'Full committee markup of the FY2026 National Defense Authorization Act including all space provisions from the Strategic Forces subcommittee.',
      date: new Date('2026-06-05'),
      status: 'scheduled',
      witnesses: [],
      relevance: 'Final committee action on DoD space authorization levels before floor vote.',
      sourceUrl: 'https://armedservices.house.gov',
    },
  ];

  for (const activity of congressionalActivities) {
    await prisma.congressionalActivity.create({ data: activity });
  }
  console.log(`  Seeded ${congressionalActivities.length} congressional activities`);

  console.log('\nProcurement intelligence seeding complete!');
  console.log(`  Total: ${opportunities.length} opportunities, ${sbirSolicitations.length} SBIR/STTR, ${budgetItems.length} budget items, ${congressionalActivities.length} congressional activities`);
}

main()
  .catch((e) => {
    console.error('Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
