import { NextResponse } from 'next/server';
import prisma from '@/lib/db';
import { logger } from '@/lib/logger';
import { requireCronSecret } from '@/lib/errors';

export const dynamic = 'force-dynamic';

// ════════════════════════════════════════════════════════════════
// Comprehensive Space Funding Opportunities (50 curated entries)
// ════════════════════════════════════════════════════════════════

interface OpportunityData {
  externalId: string;
  title: string;
  description: string;
  agency: string;
  program?: string;
  fundingType: string;
  amountMin?: number;
  amountMax?: number;
  totalBudget?: number;
  deadline?: string; // ISO date string
  openDate?: string;
  status: string;
  eligibility: string[];
  setAside?: string;
  categories: string[];
  applicationUrl?: string;
  sourceUrl?: string;
  source: string;
  contactName?: string;
  contactEmail?: string;
  naicsCode?: string;
  solicitationNumber?: string;
  stateIncentive?: boolean;
  state?: string;
  recurring?: boolean;
}

const FUNDING_OPPORTUNITIES: OpportunityData[] = [
  // ── US Federal: NASA ──────────────────────────────────────────

  {
    externalId: 'nasa-sbir-phase1-2026',
    title: 'NASA SBIR Phase I - Advanced Space Technologies',
    description: 'NASA SBIR Phase I awards support feasibility studies for innovative space technologies. Topics include advanced propulsion, life support systems, in-space manufacturing, autonomous systems, and entry/descent/landing technologies. Phase I contracts are typically 6 months with potential progression to Phase II.',
    agency: 'NASA',
    program: 'SBIR Phase I',
    fundingType: 'sbir',
    amountMin: 150000,
    amountMax: 150000,
    totalBudget: 45000000,
    deadline: '2026-04-15',
    openDate: '2026-01-10',
    status: 'open',
    eligibility: ['small_business'],
    categories: ['propulsion', 'in_space', 'general'],
    applicationUrl: 'https://sbir.nasa.gov/solicitations',
    sourceUrl: 'https://sbir.nasa.gov/',
    source: 'sbir.gov',
    solicitationNumber: 'NASA-SBIR-2026-I',
    recurring: true,
  },
  {
    externalId: 'nasa-sbir-phase2-2026',
    title: 'NASA SBIR Phase II - Prototype Development',
    description: 'Phase II awards fund the development of prototypes based on successful Phase I feasibility studies. Awards support 24 months of prototype development, testing, and validation for technologies aligned with NASA mission directorates including STMD, SMD, ARMD, and ESDMD.',
    agency: 'NASA',
    program: 'SBIR Phase II',
    fundingType: 'sbir',
    amountMin: 750000,
    amountMax: 750000,
    totalBudget: 100000000,
    deadline: '2026-06-20',
    openDate: '2026-03-01',
    status: 'open',
    eligibility: ['small_business'],
    categories: ['general', 'propulsion', 'in_space'],
    applicationUrl: 'https://sbir.nasa.gov/solicitations',
    sourceUrl: 'https://sbir.nasa.gov/',
    source: 'sbir.gov',
    solicitationNumber: 'NASA-SBIR-2026-II',
    recurring: true,
  },
  {
    externalId: 'nasa-sttr-phase1-2026',
    title: 'NASA STTR Phase I - University-Industry Partnerships',
    description: 'The STTR program requires collaboration between small businesses and research institutions. Phase I supports early-stage research partnerships in areas including space biology, astrophysics instrumentation, planetary science sensors, and advanced materials for spaceflight applications.',
    agency: 'NASA',
    program: 'STTR Phase I',
    fundingType: 'sttr',
    amountMin: 150000,
    amountMax: 150000,
    totalBudget: 30000000,
    deadline: '2026-04-15',
    openDate: '2026-01-10',
    status: 'open',
    eligibility: ['small_business', 'university'],
    categories: ['exploration', 'general'],
    applicationUrl: 'https://sbir.nasa.gov/solicitations',
    sourceUrl: 'https://sbir.nasa.gov/',
    source: 'sbir.gov',
    solicitationNumber: 'NASA-STTR-2026-I',
    recurring: true,
  },
  {
    externalId: 'nasa-sttr-phase2-2026',
    title: 'NASA STTR Phase II - Collaborative Technology Maturation',
    description: 'STTR Phase II continues the university-industry partnership to advance technologies from proof-of-concept through prototype. Focus areas include quantum sensing for navigation, advanced thermal protection systems, novel space communication architectures, and in-situ resource utilization.',
    agency: 'NASA',
    program: 'STTR Phase II',
    fundingType: 'sttr',
    amountMin: 750000,
    amountMax: 750000,
    totalBudget: 50000000,
    deadline: '2026-06-20',
    openDate: '2026-03-01',
    status: 'open',
    eligibility: ['small_business', 'university'],
    categories: ['exploration', 'communications', 'navigation'],
    applicationUrl: 'https://sbir.nasa.gov/solicitations',
    sourceUrl: 'https://sbir.nasa.gov/',
    source: 'sbir.gov',
    solicitationNumber: 'NASA-STTR-2026-II',
    recurring: true,
  },
  {
    externalId: 'nasa-tipping-point-2026',
    title: 'NASA Tipping Point - Commercial Space Capabilities',
    description: 'NASA partners with industry to advance commercial space technologies at a tipping point in development. Priority areas for 2026 include cryogenic fluid management, lunar surface power systems, in-space propulsion, and sustainable lunar architecture. Cost-sharing partnerships with significant industry investment required.',
    agency: 'NASA',
    program: 'Space Technology Mission Directorate',
    fundingType: 'cooperative_agreement',
    amountMin: 2000000,
    amountMax: 25000000,
    totalBudget: 150000000,
    deadline: '2026-05-30',
    openDate: '2026-02-15',
    status: 'open',
    eligibility: ['any'],
    categories: ['in_space', 'lunar', 'propulsion'],
    applicationUrl: 'https://www.nasa.gov/directorates/stmd/solicitations/',
    sourceUrl: 'https://www.nasa.gov/directorates/stmd/',
    source: 'nasa.gov',
    solicitationNumber: 'NNH26ZOA001N-TIP',
    recurring: true,
  },
  {
    externalId: 'nasa-roses-2026',
    title: 'NASA ROSES 2026 - Research Opportunities in Space and Earth Sciences',
    description: 'Omnibus solicitation covering all NASA Science Mission Directorate research programs. Includes heliophysics, planetary science, astrophysics, earth science, and biological/physical sciences. Multiple program elements with individual due dates throughout the year.',
    agency: 'NASA',
    program: 'ROSES / NSPIRES',
    fundingType: 'grant',
    amountMin: 100000,
    amountMax: 2000000,
    totalBudget: 1800000000,
    status: 'rolling',
    eligibility: ['university', 'nonprofit', 'any'],
    categories: ['exploration', 'earth_science', 'earth_observation'],
    applicationUrl: 'https://nspires.nasaprs.com/external/solicitations/summary.do?solId={%22ROSES-2026%22}',
    sourceUrl: 'https://nspires.nasaprs.com/',
    source: 'nasa.gov',
    solicitationNumber: 'NNH26ZDA001N',
    recurring: true,
  },
  {
    externalId: 'nasa-clps-2026',
    title: 'NASA CLPS - Commercial Lunar Payload Services Task Orders',
    description: 'Indefinite-delivery/indefinite-quantity contracts for commercial lunar lander services. NASA selects CLPS providers to deliver instruments, experiments, and technology demonstrations to the lunar surface. Task orders range from $30M to $100M+ depending on mission complexity.',
    agency: 'NASA',
    program: 'Commercial Lunar Payload Services',
    fundingType: 'contract',
    amountMin: 30000000,
    amountMax: 100000000,
    totalBudget: 2600000000,
    status: 'rolling',
    eligibility: ['any'],
    categories: ['lunar', 'exploration'],
    applicationUrl: 'https://www.nasa.gov/commercial-lunar-payload-services/',
    sourceUrl: 'https://www.nasa.gov/commercial-lunar-payload-services/',
    source: 'nasa.gov',
    recurring: true,
  },
  {
    externalId: 'nasa-ecf-2026',
    title: 'NASA Early Career Fellowship Program',
    description: 'Supports untenured faculty and researchers within 10 years of their terminal degree. Awards fund innovative research in NASA-relevant science and engineering disciplines including space technology, earth science, planetary science, and astrophysics.',
    agency: 'NASA',
    program: 'Early Career Fellowship',
    fundingType: 'grant',
    amountMin: 100000,
    amountMax: 500000,
    deadline: '2026-03-28',
    openDate: '2025-12-01',
    status: 'open',
    eligibility: ['university'],
    categories: ['exploration', 'earth_science', 'general'],
    applicationUrl: 'https://nspires.nasaprs.com/',
    sourceUrl: 'https://nspires.nasaprs.com/',
    source: 'nasa.gov',
    solicitationNumber: 'NNH26ZDA001N-ECF',
    recurring: true,
  },
  {
    externalId: 'nasa-lsi-2026',
    title: 'NASA Lunar Surface Innovation Initiative',
    description: 'Funds development of capabilities needed for sustained lunar presence under Artemis. Focus areas include excavation and construction, surface power and energy storage, dust mitigation, and ISRU processing. Open to industry teams and research institutions.',
    agency: 'NASA',
    program: 'Space Technology Mission Directorate',
    fundingType: 'cooperative_agreement',
    amountMin: 500000,
    amountMax: 5000000,
    deadline: '2026-07-15',
    openDate: '2026-03-01',
    status: 'upcoming',
    eligibility: ['any'],
    categories: ['lunar', 'in_space'],
    applicationUrl: 'https://www.nasa.gov/directorates/stmd/grants/lunar-surface-innovation-initiative/',
    sourceUrl: 'https://www.nasa.gov/directorates/stmd/',
    source: 'nasa.gov',
    recurring: true,
  },

  // ── US Federal: DARPA ─────────────────────────────────────────

  {
    externalId: 'darpa-draco-2026',
    title: 'DARPA DRACO - Demonstration Rocket for Agile Cislunar Operations',
    description: 'Nuclear thermal propulsion demonstration program. DARPA seeks proposals for reactor and spacecraft components, ground testing support, and flight demonstration systems. Aims to demonstrate NTP technology in orbit by 2027.',
    agency: 'DARPA',
    program: 'DRACO',
    fundingType: 'contract',
    amountMin: 1000000,
    amountMax: 50000000,
    status: 'rolling',
    eligibility: ['any'],
    categories: ['propulsion', 'defense', 'exploration'],
    applicationUrl: 'https://www.darpa.mil/program/demonstration-rocket-for-agile-cislunar-operations',
    sourceUrl: 'https://www.darpa.mil/',
    source: 'sam.gov',
    recurring: false,
  },
  {
    externalId: 'darpa-gambit-2026',
    title: 'DARPA GAMBIT - Geosynchronous Awareness & Monitoring via Bilateral Intelligence Tasking',
    description: 'Seeks novel capabilities for space domain awareness in the geosynchronous orbit belt. BAA solicits proposals for advanced sensor concepts, autonomous tasking algorithms, and distributed architectures for persistent GEO surveillance.',
    agency: 'DARPA',
    program: 'Strategic Technology Office BAA',
    fundingType: 'contract',
    amountMin: 500000,
    amountMax: 15000000,
    deadline: '2026-08-01',
    openDate: '2026-01-15',
    status: 'open',
    eligibility: ['any'],
    categories: ['defense', 'debris'],
    applicationUrl: 'https://www.darpa.mil/work-with-us/opportunities',
    sourceUrl: 'https://www.darpa.mil/',
    source: 'sam.gov',
    solicitationNumber: 'HR001126S0015',
  },
  {
    externalId: 'darpa-nom4d-2026',
    title: 'DARPA NOM4D - Novel Orbital and Moon Manufacturing, Materials, and Mass-efficient Design',
    description: 'Program to develop technologies for manufacturing large structures in space using adaptive, deployable designs. Focus on structures 10x-100x larger than current limits using in-space manufacturing techniques and novel materials.',
    agency: 'DARPA',
    program: 'Defense Sciences Office',
    fundingType: 'contract',
    amountMin: 2000000,
    amountMax: 20000000,
    status: 'rolling',
    eligibility: ['any'],
    categories: ['in_space', 'defense'],
    applicationUrl: 'https://www.darpa.mil/program/novel-orbital-moon-manufacturing',
    sourceUrl: 'https://www.darpa.mil/',
    source: 'sam.gov',
    recurring: false,
  },

  // ── US Federal: Space Force ───────────────────────────────────

  {
    externalId: 'spacewerx-sbir-2026',
    title: 'SpaceWERX SBIR/STTR Open Topics - FY2026',
    description: 'US Space Force innovation arm soliciting proposals through the AFWERX platform. Open topics include space domain awareness, satellite cybersecurity, resilient communications, responsive launch, and orbital logistics. Includes Direct-to-Phase-II pathway for mature technologies.',
    agency: 'US Space Force',
    program: 'SpaceWERX / AFWERX',
    fundingType: 'sbir',
    amountMin: 50000,
    amountMax: 1500000,
    totalBudget: 80000000,
    status: 'rolling',
    eligibility: ['small_business'],
    categories: ['defense', 'communications', 'debris'],
    applicationUrl: 'https://spacewerx.us/opportunities/',
    sourceUrl: 'https://spacewerx.us/',
    source: 'sbir.gov',
    recurring: true,
  },
  {
    externalId: 'spacewerx-tacfi-2026',
    title: 'SpaceWERX Tactical Funding Increase (TACFI)',
    description: 'Accelerated funding for commercially viable space technologies ready for rapid transition to Space Force missions. Proposals evaluated on readiness level and immediate applicability to USSF operational needs. Faster award timeline than traditional SBIR.',
    agency: 'US Space Force',
    program: 'SpaceWERX TACFI',
    fundingType: 'contract',
    amountMin: 750000,
    amountMax: 3000000,
    deadline: '2026-09-30',
    openDate: '2026-01-01',
    status: 'open',
    eligibility: ['small_business'],
    categories: ['defense', 'communications'],
    applicationUrl: 'https://spacewerx.us/tacfi/',
    sourceUrl: 'https://spacewerx.us/',
    source: 'sam.gov',
    recurring: true,
  },
  {
    externalId: 'spaceforce-orca-2026',
    title: 'Space Force ORCA - Orbital Resiliency and Contested Architecture',
    description: 'Solicitation for technologies enabling resilient space architectures under contested conditions. Focus areas include rapid reconstitution, disaggregated architectures, maneuvering capabilities, and hardened satellite systems.',
    agency: 'US Space Force',
    program: 'Space Systems Command',
    fundingType: 'contract',
    amountMin: 5000000,
    amountMax: 50000000,
    deadline: '2026-06-15',
    openDate: '2026-02-01',
    status: 'open',
    eligibility: ['any'],
    categories: ['defense', 'in_space'],
    applicationUrl: 'https://www.ssc.spaceforce.mil/Doing-Business/Opportunities',
    sourceUrl: 'https://www.ssc.spaceforce.mil/',
    source: 'sam.gov',
    solicitationNumber: 'FA8818-26-R-0001',
  },

  // ── US Federal: NSF ───────────────────────────────────────────

  {
    externalId: 'nsf-ast-2026',
    title: 'NSF Astronomical Sciences - Individual Investigator Grants',
    description: 'NSF Division of Astronomical Sciences supports research in observational, theoretical, and computational astrophysics. Includes stellar astronomy, extragalactic astronomy, cosmology, and planetary astronomy. Proposals reviewed twice annually.',
    agency: 'NSF',
    program: 'Division of Astronomical Sciences (AST)',
    fundingType: 'grant',
    amountMin: 100000,
    amountMax: 600000,
    status: 'rolling',
    eligibility: ['university'],
    categories: ['exploration', 'general'],
    applicationUrl: 'https://new.nsf.gov/funding/opportunities/astronomy-astrophysics-research-grants-aag',
    sourceUrl: 'https://www.nsf.gov/',
    source: 'grants.gov',
    solicitationNumber: 'NSF 24-570',
    recurring: true,
  },
  {
    externalId: 'nsf-mri-space-2026',
    title: 'NSF MRI - Major Research Instrumentation for Space Science',
    description: 'Supports acquisition or development of major research instrumentation critical to space and astronomical sciences. Includes telescopes, detector systems, spacecraft instruments, and ground-based observation platforms.',
    agency: 'NSF',
    program: 'Major Research Instrumentation (MRI)',
    fundingType: 'grant',
    amountMin: 100000,
    amountMax: 4000000,
    deadline: '2026-01-22',
    openDate: '2025-10-01',
    status: 'open',
    eligibility: ['university', 'nonprofit'],
    categories: ['exploration', 'earth_observation'],
    applicationUrl: 'https://new.nsf.gov/funding/opportunities/major-research-instrumentation-program-mri',
    sourceUrl: 'https://www.nsf.gov/',
    source: 'grants.gov',
    solicitationNumber: 'NSF 23-519',
    recurring: true,
  },
  {
    externalId: 'nsf-engines-space-2026',
    title: 'NSF Regional Innovation Engines - Space Technology Hub',
    description: 'Large-scale investments to create regional innovation ecosystems. Space-focused engine proposals address launch, satellite manufacturing, space data analytics, or space-adjacent industries. Awards support up to 10 years of ecosystem development.',
    agency: 'NSF',
    program: 'NSF Regional Innovation Engines',
    fundingType: 'cooperative_agreement',
    amountMin: 15000000,
    amountMax: 160000000,
    deadline: '2026-06-01',
    openDate: '2025-11-01',
    status: 'open',
    eligibility: ['university', 'nonprofit', 'government'],
    categories: ['general', 'launch'],
    applicationUrl: 'https://new.nsf.gov/funding/initiatives/regional-innovation-engines',
    sourceUrl: 'https://www.nsf.gov/',
    source: 'grants.gov',
    recurring: true,
  },

  // ── US Federal: DOE ───────────────────────────────────────────

  {
    externalId: 'doe-arpa-e-space-2026',
    title: 'DOE ARPA-E - Advanced Nuclear Concepts for Space Power',
    description: 'ARPA-E open solicitation for transformational energy technologies applicable to space. Focus on compact nuclear reactors for space propulsion, advanced radioisotope power systems, and novel energy storage for deep space missions.',
    agency: 'DOE',
    program: 'ARPA-E',
    fundingType: 'cooperative_agreement',
    amountMin: 500000,
    amountMax: 10000000,
    totalBudget: 40000000,
    deadline: '2026-05-15',
    openDate: '2026-02-01',
    status: 'open',
    eligibility: ['small_business', 'university', 'any'],
    categories: ['propulsion', 'exploration'],
    applicationUrl: 'https://arpa-e.energy.gov/open-funding-opportunities',
    sourceUrl: 'https://arpa-e.energy.gov/',
    source: 'grants.gov',
    recurring: true,
  },
  {
    externalId: 'doe-sbir-space-2026',
    title: 'DOE SBIR/STTR - Fusion and Advanced Energy for Space Applications',
    description: 'DOE small business innovation research topics relevant to space energy systems. Includes compact fusion concepts, advanced solar cell technologies, high-efficiency power conversion, and thermal management for spacecraft.',
    agency: 'DOE',
    program: 'SBIR/STTR',
    fundingType: 'sbir',
    amountMin: 200000,
    amountMax: 1100000,
    deadline: '2026-03-31',
    openDate: '2025-12-15',
    status: 'open',
    eligibility: ['small_business'],
    categories: ['propulsion', 'general'],
    applicationUrl: 'https://science.osti.gov/sbir',
    sourceUrl: 'https://science.osti.gov/sbir',
    source: 'sbir.gov',
    recurring: true,
  },

  // ── US State Programs ─────────────────────────────────────────

  {
    externalId: 'state-fl-space-grant-consortium',
    title: 'Florida Space Grant Consortium - Research & Fellowship Awards',
    description: 'NASA-funded state program supporting space-related research, scholarships, and fellowships at Florida universities. Includes undergraduate research assistantships, graduate fellowships, and faculty seed grants in aerospace engineering, planetary science, and space policy.',
    agency: 'Florida Space Grant Consortium',
    program: 'NASA Space Grant',
    fundingType: 'grant',
    amountMin: 5000,
    amountMax: 50000,
    deadline: '2026-02-28',
    openDate: '2025-10-01',
    status: 'open',
    eligibility: ['university'],
    categories: ['general', 'exploration'],
    applicationUrl: 'https://floridaspacegrant.org/funding/',
    sourceUrl: 'https://floridaspacegrant.org/',
    source: 'manual',
    stateIncentive: true,
    state: 'FL',
    recurring: true,
  },
  {
    externalId: 'state-fl-space-florida-ispp',
    title: 'Space Florida - Innovation & Space Project Program (ISPP)',
    description: 'Financial incentives and project support for space companies establishing or expanding operations in Florida. Includes capital investment incentives, infrastructure development grants, and workforce training subsidies for launch, satellite, and space technology companies.',
    agency: 'Space Florida',
    program: 'ISPP',
    fundingType: 'grant',
    amountMin: 100000,
    amountMax: 5000000,
    status: 'rolling',
    eligibility: ['any'],
    categories: ['launch', 'general'],
    applicationUrl: 'https://www.spaceflorida.gov/offering/incentives/',
    sourceUrl: 'https://www.spaceflorida.gov/',
    source: 'manual',
    stateIncentive: true,
    state: 'FL',
    recurring: true,
  },
  {
    externalId: 'state-tx-space-commission-2026',
    title: 'Texas Space Commission - Space Exploration & Technology Grants',
    description: 'Newly established Texas Space Commission distributing $350M in grants for space infrastructure, research, and workforce development. Priority areas include spaceport development, launch support infrastructure, space technology R&D, and STEM pipeline programs.',
    agency: 'Texas Space Commission',
    program: 'Space Technology Grants',
    fundingType: 'grant',
    amountMin: 250000,
    amountMax: 25000000,
    totalBudget: 350000000,
    deadline: '2026-06-30',
    openDate: '2025-09-01',
    status: 'open',
    eligibility: ['any'],
    categories: ['launch', 'general'],
    applicationUrl: 'https://www.txspacecommission.org/grants',
    sourceUrl: 'https://www.txspacecommission.org/',
    source: 'manual',
    stateIncentive: true,
    state: 'TX',
    recurring: true,
  },
  {
    externalId: 'state-co-ai-aerospace-2026',
    title: 'Colorado Advanced Industries Grant - Aerospace Track',
    description: 'Proof of concept ($150K) and early-stage capital ($250K) grants for Colorado aerospace companies. Requires match from industry partner. Colorado is home to 400+ aerospace companies including the US Space Command headquarters.',
    agency: 'Colorado OEDIT',
    program: 'Advanced Industries Accelerator',
    fundingType: 'grant',
    amountMin: 150000,
    amountMax: 250000,
    deadline: '2026-04-15',
    openDate: '2026-01-15',
    status: 'open',
    eligibility: ['small_business', 'university'],
    categories: ['general', 'defense'],
    applicationUrl: 'https://oedit.colorado.gov/advanced-industries-accelerator-programs',
    sourceUrl: 'https://oedit.colorado.gov/',
    source: 'manual',
    stateIncentive: true,
    state: 'CO',
    recurring: true,
  },
  {
    externalId: 'state-al-innovation-fund-2026',
    title: 'Alabama Innovation Fund - Aerospace & Defense Technology',
    description: 'Grant funding for aerospace and defense technology development in Alabama. Supports companies in the Huntsville-Decatur metropolitan area and other Alabama locations near MSFC and Redstone Arsenal. Includes lab-to-market grants and workforce development.',
    agency: 'Alabama Department of Commerce',
    program: 'Alabama Innovation Fund',
    fundingType: 'grant',
    amountMin: 25000,
    amountMax: 500000,
    status: 'rolling',
    eligibility: ['small_business', 'university'],
    categories: ['defense', 'propulsion', 'general'],
    applicationUrl: 'https://www.madeinalabama.com/industries/aerospace/',
    sourceUrl: 'https://www.madeinalabama.com/',
    source: 'manual',
    stateIncentive: true,
    state: 'AL',
    recurring: true,
  },

  // ── International: ESA ────────────────────────────────────────

  {
    externalId: 'esa-bic-europe-2026',
    title: 'ESA Business Incubation Centre (BIC) Network - All Locations',
    description: 'Two-year business incubation for startups using space technology or space data for terrestrial applications. Over 20 BIC locations across Europe offering up to EUR 50,000 in funding, office space, technical/business mentorship, and access to ESA IP and facilities.',
    agency: 'ESA',
    program: 'ESA BIC Network',
    fundingType: 'grant',
    amountMax: 55000,
    status: 'rolling',
    eligibility: ['small_business'],
    categories: ['general', 'earth_observation'],
    applicationUrl: 'https://commercialisation.esa.int/startups/',
    sourceUrl: 'https://commercialisation.esa.int/',
    source: 'esa.int',
    recurring: true,
  },
  {
    externalId: 'esa-incubed-2026',
    title: 'ESA InCubed - Investing in Industrial Innovation for EO',
    description: 'Co-funding program for innovative Earth observation products and services. ESA co-invests up to 50% of development costs with companies producing novel EO-based commercial applications. Fast-track approval within 3 months for qualifying projects.',
    agency: 'ESA',
    program: 'InCubed (Investing in Industrial Innovation)',
    fundingType: 'cooperative_agreement',
    amountMin: 100000,
    amountMax: 2000000,
    status: 'rolling',
    eligibility: ['any'],
    categories: ['earth_observation'],
    applicationUrl: 'https://incubed.phi.esa.int/',
    sourceUrl: 'https://incubed.phi.esa.int/',
    source: 'esa.int',
    recurring: true,
  },
  {
    externalId: 'esa-artes-2026',
    title: 'ESA ARTES - Advanced Research in Telecommunications Systems',
    description: 'ESA programme supporting telecommunications satellite technology and services development. Includes ARTES Core Competitiveness (technology R&D), ARTES Partnership Projects (co-funded with industry), and ARTES Pioneer (disruptive concepts). Open to ESA member state entities.',
    agency: 'ESA',
    program: 'ARTES',
    fundingType: 'cooperative_agreement',
    amountMin: 200000,
    amountMax: 10000000,
    status: 'rolling',
    eligibility: ['any'],
    categories: ['communications'],
    applicationUrl: 'https://connectivity.esa.int/artes-opportunities',
    sourceUrl: 'https://connectivity.esa.int/',
    source: 'esa.int',
    recurring: true,
  },
  {
    externalId: 'esa-navisp-2026',
    title: 'ESA NAVISP - Navigation Innovation and Support Programme',
    description: 'Supports development of innovative PNT (Positioning, Navigation, and Timing) technologies and applications. Three elements: national R&D activities, innovative PNT solutions, and synergies with Galileo. Open to entities in participating ESA member states.',
    agency: 'ESA',
    program: 'NAVISP',
    fundingType: 'cooperative_agreement',
    amountMin: 100000,
    amountMax: 3000000,
    status: 'rolling',
    eligibility: ['any'],
    categories: ['navigation'],
    applicationUrl: 'https://navisp.esa.int/',
    sourceUrl: 'https://navisp.esa.int/',
    source: 'esa.int',
    recurring: true,
  },
  {
    externalId: 'esa-ssp-2026',
    title: 'ESA Space Safety Programme - Debris Mitigation & SSA',
    description: 'ESA programme addressing space debris, space weather, and planetary defense. Current calls focus on active debris removal technologies, debris-resistant spacecraft design, space surveillance capabilities, and space weather monitoring systems.',
    agency: 'ESA',
    program: 'Space Safety',
    fundingType: 'contract',
    amountMin: 500000,
    amountMax: 15000000,
    status: 'rolling',
    eligibility: ['any'],
    categories: ['debris', 'in_space'],
    applicationUrl: 'https://www.esa.int/Safety_Security/Space_Safety',
    sourceUrl: 'https://www.esa.int/Safety_Security/',
    source: 'esa.int',
    recurring: true,
  },

  // ── International: UK Space Agency ────────────────────────────

  {
    externalId: 'uk-nsip-2026',
    title: 'UK National Space Innovation Programme (NSIP)',
    description: 'UK Space Agency grants for innovative space technologies. Funds range from GBP 50K for feasibility studies to GBP 3M for demonstration projects. Priority themes include satellite communications, EO, in-orbit servicing, and space sustainability.',
    agency: 'UK Space Agency',
    program: 'NSIP',
    fundingType: 'grant',
    amountMin: 65000,
    amountMax: 3900000,
    deadline: '2026-05-30',
    openDate: '2026-01-15',
    status: 'open',
    eligibility: ['small_business', 'university'],
    categories: ['general', 'communications', 'earth_observation'],
    applicationUrl: 'https://www.gov.uk/government/collections/national-space-innovation-programme',
    sourceUrl: 'https://www.gov.uk/government/organisations/uk-space-agency',
    source: 'manual',
    recurring: true,
  },
  {
    externalId: 'uk-enabling-tech-2026',
    title: 'UK Space Agency - Enabling Technologies Programme',
    description: 'Supports UK companies developing critical space technology building blocks. Focus areas include advanced manufacturing for space, quantum technologies for satellite applications, AI for autonomous spacecraft operations, and novel propulsion concepts.',
    agency: 'UK Space Agency',
    program: 'Enabling Technologies',
    fundingType: 'grant',
    amountMin: 100000,
    amountMax: 1500000,
    deadline: '2026-04-30',
    openDate: '2026-01-05',
    status: 'open',
    eligibility: ['small_business', 'university'],
    categories: ['propulsion', 'in_space', 'general'],
    applicationUrl: 'https://www.gov.uk/government/publications/uk-space-agency-enabling-technologies-programme',
    sourceUrl: 'https://www.gov.uk/government/organisations/uk-space-agency',
    source: 'manual',
    recurring: true,
  },
  {
    externalId: 'uk-space-sustainability-2026',
    title: 'UK Space Agency - Active Debris Removal Programme',
    description: 'UK-funded programme supporting development of technologies for active debris removal and in-orbit servicing. Includes studies on capture mechanisms, de-orbit systems, and regulatory frameworks for responsible space operations.',
    agency: 'UK Space Agency',
    program: 'Space Sustainability',
    fundingType: 'grant',
    amountMin: 200000,
    amountMax: 5000000,
    deadline: '2026-07-31',
    openDate: '2026-03-01',
    status: 'upcoming',
    eligibility: ['any'],
    categories: ['debris', 'in_space'],
    applicationUrl: 'https://www.gov.uk/government/organisations/uk-space-agency',
    sourceUrl: 'https://www.gov.uk/government/organisations/uk-space-agency',
    source: 'manual',
    recurring: true,
  },

  // ── International: Canadian Space Agency ──────────────────────

  {
    externalId: 'csa-stdp-2026',
    title: 'Canadian Space Agency - Space Technology Development Program (STDP)',
    description: 'Funds Canadian organizations to develop space technologies from concept to prototype. Focus areas include EO instruments, satellite communications, robotics and AI, and space life sciences. Supports TRL 2-6 advancement.',
    agency: 'Canadian Space Agency',
    program: 'STDP',
    fundingType: 'grant',
    amountMin: 200000,
    amountMax: 2000000,
    deadline: '2026-04-15',
    openDate: '2025-11-01',
    status: 'open',
    eligibility: ['small_business', 'university'],
    categories: ['general', 'communications', 'earth_observation'],
    applicationUrl: 'https://www.asc-csa.gc.ca/eng/funding-programs/programs/stdp/',
    sourceUrl: 'https://www.asc-csa.gc.ca/',
    source: 'manual',
    recurring: true,
  },
  {
    externalId: 'csa-fast-2026',
    title: 'Canadian Space Agency - Flights and Fieldwork for Advancement of Science & Technology (FAST)',
    description: 'Supports Canadian researchers using suborbital flights, balloon campaigns, and field campaigns for space science and technology validation. Includes microgravity experiments, atmospheric research, and Earth observation calibration/validation.',
    agency: 'Canadian Space Agency',
    program: 'FAST',
    fundingType: 'grant',
    amountMin: 50000,
    amountMax: 500000,
    deadline: '2026-03-15',
    openDate: '2025-12-01',
    status: 'open',
    eligibility: ['university', 'small_business'],
    categories: ['exploration', 'earth_science'],
    applicationUrl: 'https://www.asc-csa.gc.ca/eng/funding-programs/programs/fast/',
    sourceUrl: 'https://www.asc-csa.gc.ca/',
    source: 'manual',
    recurring: true,
  },
  {
    externalId: 'csa-leap-2026',
    title: 'Canadian Space Agency - Lunar Exploration Accelerator Program (LEAP)',
    description: 'Supports Canadian companies developing payloads for lunar missions. Part of Canada\'s contribution to the Artemis program. Funds science instruments, technology demonstrations, and commercial services for the lunar surface and orbit.',
    agency: 'Canadian Space Agency',
    program: 'LEAP',
    fundingType: 'contract',
    amountMin: 500000,
    amountMax: 5000000,
    totalBudget: 150000000,
    status: 'rolling',
    eligibility: ['small_business', 'university'],
    categories: ['lunar', 'exploration'],
    applicationUrl: 'https://www.asc-csa.gc.ca/eng/funding-programs/programs/leap/',
    sourceUrl: 'https://www.asc-csa.gc.ca/',
    source: 'manual',
    recurring: true,
  },

  // ── International: EU Horizon Europe ──────────────────────────

  {
    externalId: 'eu-horizon-space-2026',
    title: 'EU Horizon Europe - Space Research & Innovation Cluster',
    description: 'EU framework programme funding collaborative space research. 2025-2027 work programme covers space data for Earth science, competitive space technologies, secure & resilient space infrastructure, and international cooperation. Consortium-based with 2-4 year project timelines.',
    agency: 'European Commission',
    program: 'Horizon Europe Cluster 4',
    fundingType: 'grant',
    amountMin: 1000000,
    amountMax: 10000000,
    totalBudget: 580000000,
    deadline: '2026-03-18',
    openDate: '2025-10-15',
    status: 'open',
    eligibility: ['university', 'small_business', 'any'],
    categories: ['general', 'earth_observation', 'communications'],
    applicationUrl: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search',
    sourceUrl: 'https://ec.europa.eu/info/funding-tenders/',
    source: 'manual',
    recurring: true,
  },
  {
    externalId: 'eu-cassini-2026',
    title: 'EU CASSINI - Space Entrepreneurship Initiative',
    description: 'EU programme supporting space entrepreneurship including hackathons, mentoring, business accelerator, seed funding, and matchmaking. The CASSINI Seed & Growth Fund provides EUR 100K-2M for space startups and scaleups leveraging EU space data from Copernicus and Galileo.',
    agency: 'European Commission',
    program: 'CASSINI',
    fundingType: 'grant',
    amountMin: 100000,
    amountMax: 2000000,
    status: 'rolling',
    eligibility: ['small_business'],
    categories: ['general', 'earth_observation', 'navigation'],
    applicationUrl: 'https://www.cassini.eu/',
    sourceUrl: 'https://www.cassini.eu/',
    source: 'manual',
    recurring: true,
  },

  // ── International: Australian Space Agency ────────────────────

  {
    externalId: 'aus-mtm-2026',
    title: 'Australian Space Agency - Moon to Mars Initiative',
    description: 'Multi-year program funding Australian contributions to the Artemis program and Mars exploration. Trailblazer grants ($200K-$10M) for robotics, automation, communications, EO, and resource utilization. Supply chain grants support Australian SMEs joining international missions.',
    agency: 'Australian Space Agency',
    program: 'Moon to Mars Initiative',
    fundingType: 'grant',
    amountMin: 200000,
    amountMax: 10000000,
    totalBudget: 150000000,
    deadline: '2026-06-30',
    openDate: '2026-01-15',
    status: 'open',
    eligibility: ['small_business', 'university'],
    categories: ['lunar', 'exploration', 'communications'],
    applicationUrl: 'https://www.industry.gov.au/science-technology-and-innovation/space/moon-to-mars',
    sourceUrl: 'https://www.space.gov.au/',
    source: 'manual',
    recurring: true,
  },
  {
    externalId: 'aus-space-infrastructure-2026',
    title: 'Australian Space Agency - Space Infrastructure Fund',
    description: 'Capital grants for nationally significant space infrastructure including ground stations, mission control facilities, test ranges, and space manufacturing facilities. Aims to triple Australia\'s space sector to A$12B by 2030.',
    agency: 'Australian Space Agency',
    program: 'Space Infrastructure Fund',
    fundingType: 'grant',
    amountMin: 500000,
    amountMax: 20000000,
    status: 'rolling',
    eligibility: ['any'],
    categories: ['general', 'launch'],
    applicationUrl: 'https://www.space.gov.au/what-we-do/space-infrastructure-fund',
    sourceUrl: 'https://www.space.gov.au/',
    source: 'manual',
    recurring: true,
  },

  // ── International: German Space Agency (DLR) ──────────────────

  {
    externalId: 'dlr-ino-2026',
    title: 'DLR INNOspace Masters - Space Innovation Competition',
    description: 'German Aerospace Center innovation competition for new space technology concepts. Winners receive funding, DLR facility access, mentoring, and partnership opportunities. Categories include Earth observation, navigation, communications, robotics, and space transportation.',
    agency: 'DLR',
    program: 'INNOspace Masters',
    fundingType: 'prize',
    amountMin: 25000,
    amountMax: 250000,
    deadline: '2026-05-15',
    openDate: '2026-01-01',
    status: 'open',
    eligibility: ['small_business', 'university'],
    categories: ['general', 'earth_observation'],
    applicationUrl: 'https://www.innospace-masters.de/',
    sourceUrl: 'https://www.dlr.de/',
    source: 'manual',
    recurring: true,
  },
  {
    externalId: 'dlr-technology-2026',
    title: 'DLR Technology Transfer Programme',
    description: 'Supports transfer of DLR-developed space technologies to commercial applications. Provides funding for feasibility studies, prototype development, and market entry. Priority areas include satellite-based services, materials technology, and energy systems derived from space research.',
    agency: 'DLR',
    program: 'Technology Transfer',
    fundingType: 'grant',
    amountMin: 50000,
    amountMax: 500000,
    status: 'rolling',
    eligibility: ['small_business'],
    categories: ['general'],
    applicationUrl: 'https://www.dlr.de/en/research-and-transfer/technology-transfer',
    sourceUrl: 'https://www.dlr.de/',
    source: 'manual',
    recurring: true,
  },

  // ── International: French Space Agency (CNES) ─────────────────

  {
    externalId: 'cnes-connect-2026',
    title: 'CNES Connect by CNES - Space Startup Acceleration',
    description: 'French Space Agency startup acceleration programme providing technical mentorship, access to CNES facilities, and funding for space startups. Includes lab access at Toulouse Space Centre, industry networking, and potential co-development partnerships with CNES engineers.',
    agency: 'CNES',
    program: 'Connect by CNES',
    fundingType: 'grant',
    amountMin: 50000,
    amountMax: 300000,
    status: 'rolling',
    eligibility: ['small_business'],
    categories: ['general'],
    applicationUrl: 'https://cnes.fr/en/connect-cnes',
    sourceUrl: 'https://cnes.fr/',
    source: 'manual',
    recurring: true,
  },
  {
    externalId: 'cnes-rd-collab-2026',
    title: 'CNES R&D Collaborative Research Grants',
    description: 'CNES co-funds collaborative research with French universities and labs in space domains including orbital mechanics, space debris modeling, atmospheric re-entry, and Earth observation algorithms. Annual call with specific thematic priorities.',
    agency: 'CNES',
    program: 'Research Collaboration',
    fundingType: 'grant',
    amountMin: 100000,
    amountMax: 1000000,
    deadline: '2026-04-30',
    openDate: '2025-12-15',
    status: 'open',
    eligibility: ['university'],
    categories: ['exploration', 'debris', 'earth_observation'],
    applicationUrl: 'https://cnes.fr/en/research',
    sourceUrl: 'https://cnes.fr/',
    source: 'manual',
    recurring: true,
  },

  // ── International: JAXA ───────────────────────────────────────

  {
    externalId: 'jaxa-jaxass-2026',
    title: 'JAXA Space Innovation through Partnership and Co-creation (J-SPARC)',
    description: 'JAXA co-creation programme pairing startups and businesses with JAXA researchers and facilities. Focus areas include space food, space medicine, orbital debris removal, and lunar ISRU. Provides access to JAXA test facilities, technical mentorship, and joint IP development.',
    agency: 'JAXA',
    program: 'J-SPARC',
    fundingType: 'cooperative_agreement',
    status: 'rolling',
    eligibility: ['small_business', 'any'],
    categories: ['general', 'lunar', 'in_space'],
    applicationUrl: 'https://aerospacebiz.jaxa.jp/solution/j-sparc/',
    sourceUrl: 'https://global.jaxa.jp/',
    source: 'manual',
    recurring: true,
  },
  {
    externalId: 'jaxa-exploration-2026',
    title: 'JAXA International Collaboration - Lunar & Mars Exploration',
    description: 'JAXA international partnership opportunities for lunar lander payloads, Mars sample return support, and Martian Moons eXploration (MMX) mission instruments. Primarily collaborative agreements with shared costs and IP.',
    agency: 'JAXA',
    program: 'International Exploration',
    fundingType: 'cooperative_agreement',
    amountMin: 100000,
    amountMax: 5000000,
    status: 'rolling',
    eligibility: ['university', 'any'],
    categories: ['lunar', 'exploration'],
    applicationUrl: 'https://global.jaxa.jp/activity/pr/',
    sourceUrl: 'https://global.jaxa.jp/',
    source: 'manual',
    recurring: true,
  },
  {
    externalId: 'jaxa-sbir-2026',
    title: 'JAXA SBIR - Small Business Innovation Research (Japan)',
    description: 'Japanese government SBIR program with JAXA-specific topics including satellite bus miniaturization, optical intersatellite links, synthetic aperture radar innovations, and autonomous navigation systems for deep space missions.',
    agency: 'JAXA',
    program: 'SBIR (Japan)',
    fundingType: 'sbir',
    amountMin: 50000,
    amountMax: 500000,
    deadline: '2026-05-31',
    openDate: '2026-02-01',
    status: 'open',
    eligibility: ['small_business'],
    categories: ['communications', 'navigation', 'earth_observation'],
    applicationUrl: 'https://www.smrj.go.jp/english/sbir/',
    sourceUrl: 'https://global.jaxa.jp/',
    source: 'manual',
    recurring: true,
  },
];

// ════════════════════════════════════════════════════════════════
// POST handler - seed all funding opportunities
// ════════════════════════════════════════════════════════════════

export async function POST(request: Request) {
  const authError = requireCronSecret(request);
  if (authError) return authError;

  try {
    logger.info(`Seeding ${FUNDING_OPPORTUNITIES.length} funding opportunities...`);
    let upserted = 0;
    let errors = 0;

    for (const opp of FUNDING_OPPORTUNITIES) {
      try {
        await prisma.fundingOpportunity.upsert({
          where: { externalId: opp.externalId },
          create: {
            externalId: opp.externalId,
            title: opp.title,
            description: opp.description,
            agency: opp.agency,
            program: opp.program,
            fundingType: opp.fundingType,
            amountMin: opp.amountMin,
            amountMax: opp.amountMax,
            totalBudget: opp.totalBudget,
            deadline: opp.deadline ? new Date(opp.deadline) : undefined,
            openDate: opp.openDate ? new Date(opp.openDate) : undefined,
            status: opp.status,
            eligibility: opp.eligibility,
            setAside: opp.setAside,
            categories: opp.categories,
            applicationUrl: opp.applicationUrl,
            sourceUrl: opp.sourceUrl,
            source: opp.source,
            contactName: opp.contactName,
            contactEmail: opp.contactEmail,
            naicsCode: opp.naicsCode,
            solicitationNumber: opp.solicitationNumber,
            stateIncentive: opp.stateIncentive || false,
            state: opp.state,
            recurring: opp.recurring || false,
          },
          update: {
            title: opp.title,
            description: opp.description,
            agency: opp.agency,
            program: opp.program,
            fundingType: opp.fundingType,
            amountMin: opp.amountMin,
            amountMax: opp.amountMax,
            totalBudget: opp.totalBudget,
            deadline: opp.deadline ? new Date(opp.deadline) : undefined,
            openDate: opp.openDate ? new Date(opp.openDate) : undefined,
            status: opp.status,
            eligibility: opp.eligibility,
            categories: opp.categories,
            applicationUrl: opp.applicationUrl,
            sourceUrl: opp.sourceUrl,
            source: opp.source,
            solicitationNumber: opp.solicitationNumber,
            stateIncentive: opp.stateIncentive || false,
            state: opp.state,
            recurring: opp.recurring || false,
            lastUpdated: new Date(),
          },
        });
        upserted++;
      } catch (err) {
        errors++;
        logger.error(`Failed to upsert opportunity: ${opp.title}`, {
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }

    const result = {
      success: true,
      total: FUNDING_OPPORTUNITIES.length,
      upserted,
      errors,
    };

    logger.info('Funding opportunities seed complete', result);
    return NextResponse.json(result);
  } catch (error) {
    logger.error('Failed to seed funding opportunities', {
      error: error instanceof Error ? error.message : String(error),
    });
    return NextResponse.json(
      { error: 'Failed to seed funding opportunities' },
      { status: 500 }
    );
  }
}
