export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { logger } from '@/lib/logger';
import { requireCronSecret } from '@/lib/errors';

// ────────────────────────────────────────
// Seed Data: Procurement Opportunities
// ────────────────────────────────────────

const PROCUREMENT_OPPORTUNITIES = [
  {
    samNoticeId: 'SAM-FA8818-25-R-0001',
    title: 'Next-Generation Overhead Persistent Infrared (OPIR) Ground System Sustainment',
    description: 'The Space Force Space Systems Command seeks proposals for sustainment and modernization of the Next-Generation OPIR ground segment, including software development, integration testing, and cybersecurity upgrades for missile warning and missile defense.',
    agency: 'Space Force',
    subAgency: 'Space Systems Command',
    office: 'SSC/SZK',
    type: 'solicitation',
    naicsCode: '541512',
    naicsDescription: 'Computer Systems Design Services',
    setAside: 'None',
    classificationCode: 'D310',
    estimatedValue: 450000000,
    postedDate: new Date('2025-11-15'),
    responseDeadline: new Date('2026-03-28'),
    placeOfPerformance: 'Los Angeles AFB, CA',
    pointOfContact: 'Maj. Sarah Chen',
    contactEmail: 'sarah.chen@spaceforce.mil',
    solicitationNumber: 'FA8818-25-R-0001',
    samUrl: 'https://sam.gov/opp/fa8818-25-r-0001',
    isActive: true,
    tags: ['missile-warning', 'ground-systems', 'OPIR', 'cybersecurity', 'space-force'],
  },
  {
    samNoticeId: 'SAM-80NSSC25R0034',
    title: 'Artemis V Lunar Surface Power System Design and Fabrication',
    description: 'NASA seeks proposals for the design, development, and fabrication of a modular nuclear fission surface power system for Artemis V and subsequent lunar surface missions. The system shall provide 40+ kW of continuous electrical power.',
    agency: 'NASA',
    subAgency: 'Space Technology Mission Directorate',
    office: 'Glenn Research Center',
    type: 'solicitation',
    naicsCode: '334419',
    naicsDescription: 'Other Electronic Component Manufacturing',
    setAside: 'None',
    classificationCode: 'H363',
    estimatedValue: 275000000,
    postedDate: new Date('2025-12-01'),
    responseDeadline: new Date('2026-04-15'),
    placeOfPerformance: 'Cleveland, OH / Kennedy Space Center, FL',
    pointOfContact: 'Dr. James Rodriguez',
    contactEmail: 'james.m.rodriguez@nasa.gov',
    solicitationNumber: '80NSSC25R0034',
    samUrl: 'https://sam.gov/opp/80nssc25r0034',
    isActive: true,
    tags: ['artemis', 'lunar-surface', 'nuclear-power', 'fission', 'STMD'],
  },
  {
    samNoticeId: 'SAM-HR001125S0008',
    title: 'Blackjack Tranche 2 Satellite Bus Procurement',
    description: 'DARPA seeks proposals for the next tranche of the Blackjack LEO constellation program. Vendors shall provide satellite buses capable of hosting diverse military payloads with autonomous mesh networking capabilities.',
    agency: 'DARPA',
    subAgency: 'Strategic Technology Office',
    office: 'Contracts Management Office',
    type: 'solicitation',
    naicsCode: '336414',
    naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
    setAside: 'None',
    classificationCode: 'H050',
    estimatedValue: 380000000,
    postedDate: new Date('2025-10-20'),
    responseDeadline: new Date('2026-03-01'),
    placeOfPerformance: 'Various CONUS',
    pointOfContact: 'Col. Michael Torres',
    contactEmail: 'michael.torres@darpa.mil',
    solicitationNumber: 'HR001125S0008',
    samUrl: 'https://sam.gov/opp/hr001125s0008',
    isActive: true,
    tags: ['LEO-constellation', 'satellite-bus', 'mesh-networking', 'blackjack', 'DARPA'],
  },
  {
    samNoticeId: 'SAM-NRO-25-C-0042',
    title: 'Electro-Optical Reconnaissance Payload Advanced Development',
    description: 'The National Reconnaissance Office seeks proposals for the development and qualification of next-generation electro-optical payloads with enhanced resolution and on-board AI processing capabilities for national security space missions.',
    agency: 'NRO',
    subAgency: 'Advanced Systems and Technology Directorate',
    office: 'Mission Contracts Division',
    type: 'presolicitation',
    naicsCode: '334511',
    naicsDescription: 'Search, Detection, Navigation, Guidance, Aeronautical Systems',
    setAside: 'None',
    classificationCode: 'H050',
    estimatedValue: 625000000,
    postedDate: new Date('2026-01-10'),
    responseDeadline: new Date('2026-05-01'),
    placeOfPerformance: 'Chantilly, VA',
    pointOfContact: 'Classified POC',
    contactEmail: 'contracts@nro.mil',
    solicitationNumber: 'NRO-25-C-0042',
    samUrl: 'https://sam.gov/opp/nro-25-c-0042',
    isActive: true,
    tags: ['reconnaissance', 'electro-optical', 'AI', 'NRO', 'classified'],
  },
  {
    samNoticeId: 'SAM-HQ008425R0012',
    title: 'Missile Defense Space Sensor Layer (SSA Enhancement)',
    description: 'The Missile Defense Agency seeks proposals for space-based sensor systems to enhance missile tracking in the midcourse phase. The program will augment the Hypersonic and Ballistic Tracking Space Sensor (HBTSS) constellation.',
    agency: 'Missile Defense Agency',
    subAgency: null,
    office: 'MDA/DBI',
    type: 'solicitation',
    naicsCode: '336414',
    naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
    setAside: 'None',
    classificationCode: 'H050',
    estimatedValue: 520000000,
    postedDate: new Date('2025-09-05'),
    responseDeadline: new Date('2026-03-15'),
    placeOfPerformance: 'Huntsville, AL / Colorado Springs, CO',
    pointOfContact: 'Dr. Priya Nair',
    contactEmail: 'priya.nair@mda.mil',
    solicitationNumber: 'HQ008425R0012',
    samUrl: 'https://sam.gov/opp/hq008425r0012',
    isActive: true,
    tags: ['missile-defense', 'space-sensor', 'HBTSS', 'tracking', 'MDA'],
  },
  {
    samNoticeId: 'SAM-FA2517-26-R-0003',
    title: 'GPS III Follow-On (GPS IIIF) Satellite Production Lot 3',
    description: 'Space Force Space Systems Command seeks proposals for the production of GPS IIIF satellites 17-22, including M-code signal generation, enhanced anti-jam capabilities, and Search and Rescue (SAR) payloads.',
    agency: 'Space Force',
    subAgency: 'Space Systems Command',
    office: 'PEO Space Superiority',
    type: 'presolicitation',
    naicsCode: '336414',
    naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
    setAside: 'None',
    classificationCode: 'H050',
    estimatedValue: 1200000000,
    postedDate: new Date('2026-01-20'),
    responseDeadline: new Date('2026-06-15'),
    placeOfPerformance: 'El Segundo, CA',
    pointOfContact: 'Lt Col David Kim',
    contactEmail: 'david.kim.3@spaceforce.mil',
    solicitationNumber: 'FA2517-26-R-0003',
    samUrl: 'https://sam.gov/opp/fa2517-26-r-0003',
    isActive: true,
    tags: ['GPS', 'GPS-IIIF', 'navigation', 'M-code', 'anti-jam'],
  },
  {
    samNoticeId: 'SAM-80NSSC26K0011',
    title: 'Commercial LEO Destination Development - Phase C',
    description: 'NASA Commercial LEO Development Program seeks proposals for Phase C (Final Design and Fabrication) of commercial space stations to succeed the International Space Station. Awards under this program will fund critical design reviews through initial hardware fabrication.',
    agency: 'NASA',
    subAgency: 'Space Operations Mission Directorate',
    office: 'Johnson Space Center',
    type: 'solicitation',
    naicsCode: '336414',
    naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
    setAside: 'None',
    classificationCode: 'H050',
    estimatedValue: 300000000,
    postedDate: new Date('2026-02-01'),
    responseDeadline: new Date('2026-05-30'),
    placeOfPerformance: 'Various',
    pointOfContact: 'Angela Wright',
    contactEmail: 'angela.wright@nasa.gov',
    solicitationNumber: '80NSSC26K0011',
    samUrl: 'https://sam.gov/opp/80nssc26k0011',
    isActive: true,
    tags: ['commercial-LEO', 'space-station', 'CLD', 'ISS-successor', 'NASA'],
  },
  {
    samNoticeId: 'SAM-FA8811-25-R-0090',
    title: 'Tactically Responsive Space (TacRS) Launch Services IDIQ',
    description: 'Space Force Space Rapid Capabilities Office seeks proposals for an IDIQ contract for responsive launch services capable of delivering 100-500 kg payloads to LEO within 24-72 hours of call-up.',
    agency: 'Space Force',
    subAgency: 'Space Rapid Capabilities Office',
    office: 'SpRCO/PKA',
    type: 'solicitation',
    naicsCode: '336415',
    naicsDescription: 'Guided Missile and Space Vehicle Propulsion Unit Manufacturing',
    setAside: 'Total Small Business',
    classificationCode: 'H050',
    estimatedValue: 150000000,
    postedDate: new Date('2025-11-01'),
    responseDeadline: new Date('2026-02-28'),
    placeOfPerformance: 'Cape Canaveral, FL / Vandenberg SFB, CA',
    pointOfContact: 'Capt. Ryan O\'Brien',
    contactEmail: 'ryan.obrien@spaceforce.mil',
    solicitationNumber: 'FA8811-25-R-0090',
    samUrl: 'https://sam.gov/opp/fa8811-25-r-0090',
    isActive: true,
    tags: ['responsive-launch', 'TacRS', 'small-launch', 'IDIQ', 'rapid-space-access'],
  },
  {
    samNoticeId: 'SAM-DARPA-SN-26-0015',
    title: 'On-Orbit Servicing, Assembly, and Manufacturing (OSAM) Robotic Servicing',
    description: 'DARPA issues this special notice to announce interest in developing autonomous robotic capabilities for on-orbit satellite servicing, including refueling, inspection, and component replacement for GEO and MEO assets.',
    agency: 'DARPA',
    subAgency: 'Tactical Technology Office',
    office: 'TTO',
    type: 'special_notice',
    naicsCode: '541715',
    naicsDescription: 'Research and Development in the Physical Sciences',
    setAside: 'None',
    classificationCode: 'H050',
    estimatedValue: 95000000,
    postedDate: new Date('2026-02-05'),
    responseDeadline: new Date('2026-04-20'),
    placeOfPerformance: 'Arlington, VA',
    pointOfContact: 'Dr. Marcus Wheeler',
    contactEmail: 'marcus.wheeler@darpa.mil',
    solicitationNumber: 'DARPA-SN-26-0015',
    samUrl: 'https://sam.gov/opp/darpa-sn-26-0015',
    isActive: true,
    tags: ['OSAM', 'on-orbit-servicing', 'robotics', 'GEO', 'satellite-servicing'],
  },
  {
    samNoticeId: 'SAM-80NSSC25K0088',
    title: 'Space Weather Research and Forecasting Instrument Suite',
    description: 'NASA Heliophysics Division seeks proposals for the development and delivery of a comprehensive space weather monitoring instrument suite for the Space Weather Follow-On (SWFO-L1) mission at the Sun-Earth L1 Lagrange point.',
    agency: 'NASA',
    subAgency: 'Science Mission Directorate',
    office: 'Goddard Space Flight Center',
    type: 'solicitation',
    naicsCode: '334519',
    naicsDescription: 'Other Measuring and Controlling Device Manufacturing',
    setAside: 'None',
    classificationCode: 'H363',
    estimatedValue: 88000000,
    postedDate: new Date('2025-08-22'),
    responseDeadline: new Date('2026-03-10'),
    placeOfPerformance: 'Greenbelt, MD',
    pointOfContact: 'Dr. Linda Vasquez',
    contactEmail: 'linda.vasquez@nasa.gov',
    solicitationNumber: '80NSSC25K0088',
    samUrl: 'https://sam.gov/opp/80nssc25k0088',
    isActive: true,
    tags: ['space-weather', 'heliophysics', 'L1', 'instruments', 'SWFO'],
  },
  {
    samNoticeId: 'SAM-FA8818-25-R-0045',
    title: 'Unified Data Library for Space Domain Awareness',
    description: 'Space Force seeks proposals for a cloud-native, AI-powered unified data library that integrates space domain awareness data from government, commercial, and allied sensors for the Combined Space Operations Center (CSpOC).',
    agency: 'Space Force',
    subAgency: 'Space Operations Command',
    office: 'Vandenberg SFB',
    type: 'sources_sought',
    naicsCode: '541512',
    naicsDescription: 'Computer Systems Design Services',
    setAside: 'None',
    classificationCode: 'D307',
    estimatedValue: 200000000,
    postedDate: new Date('2026-01-28'),
    responseDeadline: new Date('2026-03-15'),
    placeOfPerformance: 'Vandenberg SFB, CA / Schriever SFB, CO',
    pointOfContact: 'TSgt Maria Gonzalez',
    contactEmail: 'maria.gonzalez@spaceforce.mil',
    solicitationNumber: 'FA8818-25-R-0045',
    samUrl: 'https://sam.gov/opp/fa8818-25-r-0045',
    isActive: true,
    tags: ['SDA', 'space-domain-awareness', 'AI', 'cloud-native', 'CSpOC'],
  },
  {
    samNoticeId: 'SAM-W9113M-26-R-0002',
    title: 'Hypersonic Glide Body Re-entry Tracking Constellation',
    description: 'MDA seeks proposals for a constellation of space-based sensors optimized for tracking and characterizing hypersonic glide vehicles during their terminal phase. Must integrate with existing fire control networks.',
    agency: 'Missile Defense Agency',
    subAgency: null,
    office: 'MDA/BC',
    type: 'presolicitation',
    naicsCode: '336414',
    naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
    setAside: 'None',
    classificationCode: 'H050',
    estimatedValue: 780000000,
    postedDate: new Date('2026-02-10'),
    responseDeadline: new Date('2026-07-01'),
    placeOfPerformance: 'Huntsville, AL',
    pointOfContact: 'Dr. Anthony Bell',
    contactEmail: 'anthony.bell@mda.mil',
    solicitationNumber: 'W9113M-26-R-0002',
    samUrl: 'https://sam.gov/opp/w9113m-26-r-0002',
    isActive: true,
    tags: ['hypersonic', 'tracking', 'missile-defense', 'constellation', 'fire-control'],
  },
  {
    samNoticeId: 'SAM-NRO-25-SB-0018',
    title: 'Small Business Innovation for Resilient Ground Architecture',
    description: 'NRO seeks small business proposals for innovative ground segment technologies to improve the resilience, redundancy, and security of satellite command and control systems against advanced cyber threats.',
    agency: 'NRO',
    subAgency: 'Ground Enterprise Directorate',
    office: 'Small Business Programs',
    type: 'solicitation',
    naicsCode: '541512',
    naicsDescription: 'Computer Systems Design Services',
    setAside: 'Total Small Business',
    classificationCode: 'D310',
    estimatedValue: 35000000,
    postedDate: new Date('2025-12-15'),
    responseDeadline: new Date('2026-04-01'),
    placeOfPerformance: 'Chantilly, VA',
    pointOfContact: 'Jennifer Park',
    contactEmail: 'smallbiz@nro.mil',
    solicitationNumber: 'NRO-25-SB-0018',
    samUrl: 'https://sam.gov/opp/nro-25-sb-0018',
    isActive: true,
    tags: ['small-business', 'ground-systems', 'cybersecurity', 'resilience', 'NRO'],
  },
  {
    samNoticeId: 'SAM-80NSSC26R0055',
    title: 'Mars Sample Return Earth Entry System',
    description: 'NASA JPL seeks proposals for the design and development of the Earth Entry System for the Mars Sample Return campaign, including the sample containment vessel, heat shield, and parachute recovery systems.',
    agency: 'NASA',
    subAgency: 'Science Mission Directorate',
    office: 'Jet Propulsion Laboratory',
    type: 'solicitation',
    naicsCode: '336414',
    naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
    setAside: 'None',
    classificationCode: 'H050',
    estimatedValue: 190000000,
    postedDate: new Date('2026-01-05'),
    responseDeadline: new Date('2026-04-30'),
    placeOfPerformance: 'Pasadena, CA',
    pointOfContact: 'Dr. Robert Chang',
    contactEmail: 'robert.chang@jpl.nasa.gov',
    solicitationNumber: '80NSSC26R0055',
    samUrl: 'https://sam.gov/opp/80nssc26r0055',
    isActive: true,
    tags: ['mars-sample-return', 'MSR', 'earth-entry', 'JPL', 'planetary-science'],
  },
  {
    samNoticeId: 'SAM-FA8818-26-R-0010',
    title: 'Protected Tactical SATCOM (PTS) Enterprise Ground Segment',
    description: 'Space Force procures the enterprise ground segment for Protected Tactical SATCOM providing anti-jam, low-probability-of-intercept satellite communications for joint warfighter use across all domains.',
    agency: 'Space Force',
    subAgency: 'Space Systems Command',
    office: 'SSC/BCG',
    type: 'solicitation',
    naicsCode: '334220',
    naicsDescription: 'Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing',
    setAside: 'None',
    classificationCode: 'D304',
    estimatedValue: 340000000,
    postedDate: new Date('2026-02-12'),
    responseDeadline: new Date('2026-06-01'),
    placeOfPerformance: 'Peterson SFB, CO / Los Angeles AFB, CA',
    pointOfContact: 'Lt Col Rachel Adams',
    contactEmail: 'rachel.adams@spaceforce.mil',
    solicitationNumber: 'FA8818-26-R-0010',
    samUrl: 'https://sam.gov/opp/fa8818-26-r-0010',
    isActive: true,
    tags: ['SATCOM', 'protected-comms', 'anti-jam', 'PTS', 'ground-segment'],
  },
  {
    samNoticeId: 'SAM-80NSSC25R0102',
    title: 'Commercial Cargo to the Moon (CLPS Task Order 6)',
    description: 'NASA Commercial Lunar Payload Services program issues Task Order 6 for delivery of science instruments and technology demonstrations to the lunar south pole region in support of Artemis surface operations.',
    agency: 'NASA',
    subAgency: 'Science Mission Directorate',
    office: 'Marshall Space Flight Center',
    type: 'award',
    naicsCode: '336414',
    naicsDescription: 'Guided Missile and Space Vehicle Manufacturing',
    setAside: 'None',
    classificationCode: 'H050',
    estimatedValue: 120000000,
    awardAmount: 118500000,
    postedDate: new Date('2025-07-15'),
    awardDate: new Date('2026-01-22'),
    placeOfPerformance: 'Various',
    pointOfContact: 'Steve Palmer',
    contactEmail: 'steve.palmer@nasa.gov',
    solicitationNumber: '80NSSC25R0102',
    awardee: 'Intuitive Machines',
    samUrl: 'https://sam.gov/opp/80nssc25r0102',
    isActive: true,
    tags: ['CLPS', 'lunar-lander', 'Artemis', 'south-pole', 'commercial-moon'],
  },
  {
    samNoticeId: 'SAM-FA8814-25-R-0078',
    title: 'Space Fence Follow-On Radar Upgrade (Kwajalein Site)',
    description: 'Space Force issues solicitation for major upgrade to the Space Fence S-band radar at Kwajalein Atoll, improving detection of objects in LEO down to 2 cm and expanding catalog capacity by 300%.',
    agency: 'Space Force',
    subAgency: 'Space Systems Command',
    office: 'SSC/SZS',
    type: 'solicitation',
    naicsCode: '334511',
    naicsDescription: 'Search, Detection, Navigation, Guidance, Aeronautical Systems',
    setAside: 'None',
    classificationCode: 'J019',
    estimatedValue: 165000000,
    postedDate: new Date('2025-10-08'),
    responseDeadline: new Date('2026-03-22'),
    placeOfPerformance: 'Kwajalein Atoll, Marshall Islands',
    pointOfContact: 'Maj. Lisa Thompson',
    contactEmail: 'lisa.thompson@spaceforce.mil',
    solicitationNumber: 'FA8814-25-R-0078',
    samUrl: 'https://sam.gov/opp/fa8814-25-r-0078',
    isActive: true,
    tags: ['space-fence', 'SSA', 'radar', 'debris-tracking', 'Kwajalein'],
  },
  {
    samNoticeId: 'SAM-DARPA-BAA-26-01',
    title: 'Space-BACN Phase 3: Optical Inter-Satellite Link (OISL) Production',
    description: 'DARPA Space-BACN program transitions to Phase 3 production of low-cost optical inter-satellite link terminals that enable heterogeneous constellation interoperability. Target unit cost below $100K.',
    agency: 'DARPA',
    subAgency: 'Strategic Technology Office',
    office: 'STO',
    type: 'solicitation',
    naicsCode: '334511',
    naicsDescription: 'Search, Detection, Navigation, Guidance, Aeronautical Systems',
    setAside: 'Total Small Business',
    classificationCode: 'H050',
    estimatedValue: 72000000,
    postedDate: new Date('2026-01-15'),
    responseDeadline: new Date('2026-04-10'),
    placeOfPerformance: 'Various CONUS',
    pointOfContact: 'Dr. Kevin Nguyen',
    contactEmail: 'kevin.nguyen@darpa.mil',
    solicitationNumber: 'DARPA-BAA-26-01',
    samUrl: 'https://sam.gov/opp/darpa-baa-26-01',
    isActive: true,
    tags: ['Space-BACN', 'optical-link', 'OISL', 'mesh-network', 'small-business'],
  },
];

// ────────────────────────────────────────
// Seed Data: SBIR/STTR Solicitations
// ────────────────────────────────────────

const SBIR_SOLICITATIONS = [
  {
    program: 'SBIR',
    agency: 'NASA',
    topicNumber: 'SBIR-25-1-S4.01',
    topicTitle: 'Advanced Thermal Protection Systems for Extreme Entry Environments',
    description: 'Develop novel ablative or reusable thermal protection system materials and concepts for planetary entry at velocities exceeding 12 km/s, targeting Mars Sample Return and Venus missions.',
    phase: 'Phase I',
    awardAmount: 150000,
    openDate: new Date('2025-11-01'),
    closeDate: new Date('2026-03-15'),
    url: 'https://sbir.nasa.gov/content/sbir-25-1-s401',
    keywords: ['thermal-protection', 'TPS', 'entry-systems', 'ablative', 'Mars'],
    isActive: true,
  },
  {
    program: 'SBIR',
    agency: 'NASA',
    topicNumber: 'SBIR-25-1-H12.02',
    topicTitle: 'Closed-Loop Life Support Systems for Deep Space Habitats',
    description: 'Innovate technologies for closed-loop water recovery, air revitalization, and waste processing systems achieving 98%+ resource recovery rates for crewed missions beyond LEO.',
    phase: 'Phase I',
    awardAmount: 150000,
    openDate: new Date('2025-11-01'),
    closeDate: new Date('2026-03-15'),
    url: 'https://sbir.nasa.gov/content/sbir-25-1-h1202',
    keywords: ['life-support', 'ECLSS', 'water-recovery', 'deep-space', 'habitat'],
    isActive: true,
  },
  {
    program: 'STTR',
    agency: 'NASA',
    topicNumber: 'STTR-25-1-T11.01',
    topicTitle: 'AI-Driven Autonomous Navigation for Cislunar Operations',
    description: 'Research and develop AI/ML-based autonomous navigation algorithms for spacecraft operating in the cislunar domain, capable of operating without ground-in-the-loop for extended periods.',
    phase: 'Phase I',
    awardAmount: 150000,
    openDate: new Date('2025-11-01'),
    closeDate: new Date('2026-03-15'),
    url: 'https://sbir.nasa.gov/content/sttr-25-1-t1101',
    keywords: ['autonomous-navigation', 'AI', 'cislunar', 'machine-learning', 'GNC'],
    isActive: true,
  },
  {
    program: 'SBIR',
    agency: 'SpaceWERX',
    topicNumber: 'SF251-001',
    topicTitle: 'Rapid Reconstitution of Space-Based Communications',
    description: 'Develop technologies enabling rapid reconstitution of degraded or destroyed satellite communication capabilities within 48 hours, including responsive launch integration and automated payload deployment.',
    phase: 'Phase I',
    awardAmount: 250000,
    openDate: new Date('2025-12-01'),
    closeDate: new Date('2026-04-01'),
    url: 'https://spacewerx.us/sf251-001',
    keywords: ['reconstitution', 'responsive-space', 'SATCOM', 'resilience', 'rapid-launch'],
    isActive: true,
  },
  {
    program: 'SBIR',
    agency: 'SpaceWERX',
    topicNumber: 'SF251-002',
    topicTitle: 'Space Domain Awareness using Commercial Radar Constellations',
    description: 'Innovative approaches to leverage commercial SAR and RF sensing constellations for military space domain awareness, including algorithms for object detection, tracking, and characterization.',
    phase: 'Phase I',
    awardAmount: 250000,
    openDate: new Date('2025-12-01'),
    closeDate: new Date('2026-04-01'),
    url: 'https://spacewerx.us/sf251-002',
    keywords: ['SDA', 'commercial-radar', 'SAR', 'object-tracking', 'space-surveillance'],
    isActive: true,
  },
  {
    program: 'SBIR',
    agency: 'SpaceWERX',
    topicNumber: 'SF251-003',
    topicTitle: 'Counter-Space Electronic Warfare Simulation Environment',
    description: 'Develop a high-fidelity simulation environment for modeling electronic warfare threats to space systems, including jamming, spoofing, and cyber-attack scenarios for training and capability development.',
    phase: 'Phase II',
    awardAmount: 1500000,
    openDate: new Date('2026-01-15'),
    closeDate: new Date('2026-05-15'),
    url: 'https://spacewerx.us/sf251-003',
    keywords: ['electronic-warfare', 'counter-space', 'simulation', 'jamming', 'cybersecurity'],
    isActive: true,
  },
  {
    program: 'STTR',
    agency: 'SpaceWERX',
    topicNumber: 'SF251-T01',
    topicTitle: 'Quantum Key Distribution for Space-Ground Secure Communications',
    description: 'Partner with a research institution to develop and demonstrate quantum key distribution (QKD) technology for secure satellite-to-ground communication links resistant to quantum computing attacks.',
    phase: 'Phase I',
    awardAmount: 250000,
    openDate: new Date('2026-01-15'),
    closeDate: new Date('2026-05-15'),
    url: 'https://spacewerx.us/sf251-t01',
    keywords: ['quantum', 'QKD', 'encryption', 'secure-comms', 'quantum-resistant'],
    isActive: true,
  },
  {
    program: 'SBIR',
    agency: 'NASA',
    topicNumber: 'SBIR-25-2-Z9.04',
    topicTitle: 'In-Situ Resource Utilization for Lunar Regolith Processing',
    description: 'Phase II development of technologies for extracting water ice, oxygen, metals, and construction materials from lunar regolith to support sustained human presence on the Moon.',
    phase: 'Phase II',
    awardAmount: 850000,
    openDate: new Date('2025-10-01'),
    closeDate: new Date('2026-03-01'),
    url: 'https://sbir.nasa.gov/content/sbir-25-2-z904',
    keywords: ['ISRU', 'lunar-regolith', 'water-extraction', 'oxygen', 'Moon'],
    isActive: true,
  },
  {
    program: 'SBIR',
    agency: 'NOAA',
    topicNumber: 'NOAA-SBIR-26-01',
    topicTitle: 'Next-Generation Smallsat Weather Instruments for LEO Constellations',
    description: 'Develop compact, cost-effective weather observation instruments suitable for smallsat constellations to augment NOAA operational weather observation capabilities with improved temporal resolution.',
    phase: 'Phase I',
    awardAmount: 200000,
    openDate: new Date('2026-01-10'),
    closeDate: new Date('2026-04-15'),
    url: 'https://sbir.noaa.gov/noaa-sbir-26-01',
    keywords: ['weather', 'smallsat', 'instruments', 'LEO-constellation', 'NOAA'],
    isActive: true,
  },
  {
    program: 'STTR',
    agency: 'NASA',
    topicNumber: 'STTR-25-2-T15.03',
    topicTitle: 'Advanced Electric Propulsion for Interplanetary SmallSats',
    description: 'Phase II development of high-efficiency, compact electric propulsion systems enabling interplanetary SmallSat missions with delta-V capabilities exceeding 10 km/s.',
    phase: 'Phase II',
    awardAmount: 850000,
    openDate: new Date('2025-09-15'),
    closeDate: new Date('2026-02-28'),
    url: 'https://sbir.nasa.gov/content/sttr-25-2-t1503',
    keywords: ['electric-propulsion', 'ion-thruster', 'SmallSat', 'interplanetary', 'propulsion'],
    isActive: true,
  },
  {
    program: 'SBIR',
    agency: 'SpaceWERX',
    topicNumber: 'SF252-010',
    topicTitle: 'Autonomous Collision Avoidance for Proliferated Constellations',
    description: 'Develop autonomous, distributed collision avoidance algorithms for large satellite constellations (1000+ spacecraft) that minimize operational disruption while maintaining orbital safety in contested environments.',
    phase: 'Phase I',
    awardAmount: 250000,
    openDate: new Date('2026-02-01'),
    closeDate: new Date('2026-06-01'),
    url: 'https://spacewerx.us/sf252-010',
    keywords: ['collision-avoidance', 'constellation-management', 'autonomous', 'orbital-safety', 'STM'],
    isActive: true,
  },
  {
    program: 'SBIR',
    agency: 'NASA',
    topicNumber: 'SBIR-25-1-A2.08',
    topicTitle: 'Additive Manufacturing of Refractory Alloys for Rocket Nozzles',
    description: 'Advance additive manufacturing techniques for producing refractory metal alloy components (niobium, molybdenum, tungsten) for next-generation rocket engine nozzles and combustion chambers.',
    phase: 'Phase I',
    awardAmount: 150000,
    openDate: new Date('2025-11-01'),
    closeDate: new Date('2026-03-15'),
    url: 'https://sbir.nasa.gov/content/sbir-25-1-a208',
    keywords: ['additive-manufacturing', '3D-printing', 'refractory-alloy', 'rocket-nozzle', 'propulsion'],
    isActive: true,
  },
];

// ────────────────────────────────────────
// Seed Data: Space Budget Items
// ────────────────────────────────────────

const BUDGET_ITEMS = [
  // NASA FY2026
  { agency: 'NASA', fiscalYear: 2026, category: 'Exploration', program: 'Artemis Campaign', requestAmount: 7650, enactedAmount: null, previousYear: 7150, changePercent: 7.0, notes: 'Includes SLS, Orion, HLS, Gateway, and Exploration Ground Systems', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NASA', fiscalYear: 2026, category: 'Exploration', program: 'Space Launch System (SLS)', requestAmount: 2500, enactedAmount: null, previousYear: 2600, changePercent: -3.8, notes: 'Block 1B development and production continues', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NASA', fiscalYear: 2026, category: 'Exploration', program: 'Orion Multi-Purpose Crew Vehicle', requestAmount: 1350, enactedAmount: null, previousYear: 1400, changePercent: -3.6, notes: 'Production of Artemis V-VII vehicles', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NASA', fiscalYear: 2026, category: 'Exploration', program: 'Human Landing System (HLS)', requestAmount: 1900, enactedAmount: null, previousYear: 1800, changePercent: 5.6, notes: 'SpaceX Starship HLS and Blue Origin second provider', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NASA', fiscalYear: 2026, category: 'Science', program: 'Planetary Science', requestAmount: 3200, enactedAmount: null, previousYear: 3100, changePercent: 3.2, notes: 'Mars Sample Return, Europa Clipper ops, Dragonfly development', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NASA', fiscalYear: 2026, category: 'Science', program: 'Earth Science', requestAmount: 2100, enactedAmount: null, previousYear: 2050, changePercent: 2.4, notes: 'Earth System Observatory, PACE operations, climate monitoring', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NASA', fiscalYear: 2026, category: 'Science', program: 'Astrophysics', requestAmount: 1650, enactedAmount: null, previousYear: 1580, changePercent: 4.4, notes: 'JWST operations, Roman Space Telescope, Habitable Worlds Observatory studies', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NASA', fiscalYear: 2026, category: 'Space Operations', program: 'International Space Station', requestAmount: 1350, enactedAmount: null, previousYear: 1500, changePercent: -10.0, notes: 'Reduced as ISS approaches end-of-life (2030)', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NASA', fiscalYear: 2026, category: 'Space Operations', program: 'Commercial LEO Destinations', requestAmount: 450, enactedAmount: null, previousYear: 350, changePercent: 28.6, notes: 'Increased funding for CLD development (Axiom, Blue Origin, Vast)', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NASA', fiscalYear: 2026, category: 'Space Technology', program: 'Space Technology Mission Directorate', requestAmount: 1480, enactedAmount: null, previousYear: 1400, changePercent: 5.7, notes: 'Nuclear thermal propulsion, ISRU, advanced materials', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NASA', fiscalYear: 2026, category: 'Aeronautics', program: 'Aeronautics Research', requestAmount: 965, enactedAmount: null, previousYear: 935, changePercent: 3.2, notes: 'X-59 quiet supersonic, sustainable aviation, UAM integration', source: 'FY2026 Presidential Budget Request' },

  // NASA FY2025 (enacted)
  { agency: 'NASA', fiscalYear: 2025, category: 'Exploration', program: 'Artemis Campaign', requestAmount: 7150, enactedAmount: 7400, previousYear: 6850, changePercent: 4.4, notes: 'Congress added $250M over request', source: 'FY2025 Consolidated Appropriations Act' },
  { agency: 'NASA', fiscalYear: 2025, category: 'Science', program: 'Planetary Science', requestAmount: 3100, enactedAmount: 3250, previousYear: 2900, changePercent: 6.9, notes: 'Congress restored MSR funding cuts', source: 'FY2025 Consolidated Appropriations Act' },
  { agency: 'NASA', fiscalYear: 2025, category: 'Space Operations', program: 'International Space Station', requestAmount: 1500, enactedAmount: 1500, previousYear: 1600, changePercent: -6.3, notes: 'Ramping down toward 2030 deorbit', source: 'FY2025 Consolidated Appropriations Act' },

  // Space Force FY2026
  { agency: 'Space Force', fiscalYear: 2026, category: 'Space Procurement', program: 'GPS III Follow-On', requestAmount: 2100, enactedAmount: null, previousYear: 1800, changePercent: 16.7, notes: 'GPS IIIF satellites 17-22 production', source: 'FY2026 Presidential Budget Request' },
  { agency: 'Space Force', fiscalYear: 2026, category: 'Space Procurement', program: 'Next-Gen OPIR', requestAmount: 2800, enactedAmount: null, previousYear: 2500, changePercent: 12.0, notes: 'Space and ground segments for missile warning', source: 'FY2026 Presidential Budget Request' },
  { agency: 'Space Force', fiscalYear: 2026, category: 'Space Procurement', program: 'National Security Space Launch', requestAmount: 2450, enactedAmount: null, previousYear: 2200, changePercent: 11.4, notes: 'NSSL Phase 3 launch services', source: 'FY2026 Presidential Budget Request' },
  { agency: 'Space Force', fiscalYear: 2026, category: 'Space RDT&E', program: 'Resilient Missile Warning/Tracking', requestAmount: 3100, enactedAmount: null, previousYear: 2700, changePercent: 14.8, notes: 'Proliferated LEO constellation for missile tracking', source: 'FY2026 Presidential Budget Request' },
  { agency: 'Space Force', fiscalYear: 2026, category: 'Space RDT&E', program: 'Space Domain Awareness', requestAmount: 1650, enactedAmount: null, previousYear: 1400, changePercent: 17.9, notes: 'Deep Space Advanced Radar, Space Fence upgrade, commercial SSA integration', source: 'FY2026 Presidential Budget Request' },
  { agency: 'Space Force', fiscalYear: 2026, category: 'Space RDT&E', program: 'Protected Tactical SATCOM', requestAmount: 890, enactedAmount: null, previousYear: 750, changePercent: 18.7, notes: 'Anti-jam protected communications for warfighter', source: 'FY2026 Presidential Budget Request' },
  { agency: 'Space Force', fiscalYear: 2026, category: 'Operations & Maintenance', program: 'Space Operations & Sustainment', requestAmount: 4200, enactedAmount: null, previousYear: 3850, changePercent: 9.1, notes: 'Combined Space Operations Center, Delta operations', source: 'FY2026 Presidential Budget Request' },

  // Space Force FY2025 (enacted)
  { agency: 'Space Force', fiscalYear: 2025, category: 'Space Procurement', program: 'GPS III Follow-On', requestAmount: 1800, enactedAmount: 1900, previousYear: 1650, changePercent: 9.1, notes: 'GPS IIIF production', source: 'FY2025 NDAA' },
  { agency: 'Space Force', fiscalYear: 2025, category: 'Space RDT&E', program: 'Resilient Missile Warning/Tracking', requestAmount: 2700, enactedAmount: 2850, previousYear: 2300, changePercent: 17.4, notes: 'Congress added $150M for PWSA acceleration', source: 'FY2025 NDAA' },

  // DARPA Space Programs FY2026
  { agency: 'DARPA', fiscalYear: 2026, category: 'Space Technology', program: 'Blackjack', requestAmount: 280, enactedAmount: null, previousYear: 310, changePercent: -9.7, notes: 'Transitioning Tranche 1 to Space Force, Tranche 2 development', source: 'FY2026 Presidential Budget Request' },
  { agency: 'DARPA', fiscalYear: 2026, category: 'Space Technology', program: 'Space-BACN', requestAmount: 115, enactedAmount: null, previousYear: 95, changePercent: 21.1, notes: 'Optical inter-satellite link production phase', source: 'FY2026 Presidential Budget Request' },
  { agency: 'DARPA', fiscalYear: 2026, category: 'Space Technology', program: 'DRACO Nuclear Thermal Propulsion', requestAmount: 180, enactedAmount: null, previousYear: 150, changePercent: 20.0, notes: 'In-space demonstration preparation with NASA', source: 'FY2026 Presidential Budget Request' },

  // NOAA FY2026
  { agency: 'NOAA', fiscalYear: 2026, category: 'Satellite Systems', program: 'GOES-U Operations', requestAmount: 350, enactedAmount: null, previousYear: 420, changePercent: -16.7, notes: 'GOES-U operational phase after FY2025 launch', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NOAA', fiscalYear: 2026, category: 'Satellite Systems', program: 'JPSS/Polar Satellites', requestAmount: 580, enactedAmount: null, previousYear: 550, changePercent: 5.5, notes: 'JPSS-2 operations and follow-on planning', source: 'FY2026 Presidential Budget Request' },
  { agency: 'NOAA', fiscalYear: 2026, category: 'Satellite Systems', program: 'Space Weather Follow-On', requestAmount: 120, enactedAmount: null, previousYear: 95, changePercent: 26.3, notes: 'SWFO-L1 mission development for operational space weather monitoring', source: 'FY2026 Presidential Budget Request' },
];

// ────────────────────────────────────────
// Seed Data: Congressional Activity
// ────────────────────────────────────────

const CONGRESSIONAL_ACTIVITIES = [
  {
    type: 'authorization',
    committee: 'SASC',
    subcommittee: 'Subcommittee on Strategic Forces',
    title: 'FY2026 National Defense Authorization Act - Space Force Provisions',
    description: 'The NDAA FY2026 includes provisions for Space Force end strength increase to 16,000 personnel, acceleration of the Resilient Missile Warning/Tracking constellation, authorization of a new Space Force acquisition pilot program, and establishment of a commercial space integration office.',
    date: new Date('2025-12-20'),
    status: 'completed',
    billNumber: 'S. 3847',
    witnesses: [],
    relevance: 'Authorizes $29.4B for Space Force programs, up 12% from FY2025. Creates new acquisition pathways for commercial space integration. Mandates study on space industrial base resilience.',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/3847',
  },
  {
    type: 'hearing',
    committee: 'Senate Commerce',
    subcommittee: 'Subcommittee on Space and Science',
    title: 'Commercial Space Transportation: Addressing Regulatory Bottlenecks',
    description: 'Oversight hearing examining FAA licensing backlogs for commercial launch and reentry operations. Witnesses from SpaceX, Rocket Lab, Blue Origin, and the Commercial Spaceflight Federation testified about regulatory modernization needs.',
    date: new Date('2026-02-05'),
    status: 'completed',
    billNumber: null,
    witnesses: ['Gwynne Shotwell (SpaceX)', 'Peter Beck (Rocket Lab)', 'Dave Limp (Blue Origin)', 'Karina Drees (CSF)'],
    relevance: 'Senators signaled bipartisan support for FAA licensing reform. Draft legislation expected by Q2 2026 to streamline launch licensing from 18 months to 6 months.',
    sourceUrl: 'https://www.commerce.senate.gov/hearings/commercial-space-transportation',
  },
  {
    type: 'appropriation',
    committee: 'Senate Appropriations',
    subcommittee: 'Commerce, Justice, Science',
    title: 'FY2026 CJS Appropriations Bill - NASA and NOAA Space Programs',
    description: 'Senate CJS Appropriations markup includes $25.8B for NASA (2.3% increase) and $6.2B for NOAA satellite programs. Key additions include $300M for Mars Sample Return above request and full funding for Commercial LEO Destinations.',
    date: new Date('2026-03-15'),
    status: 'scheduled',
    billNumber: null,
    witnesses: [],
    relevance: 'Signals strong Congressional support for flagship science missions and commercial space station transition. MSR funding restoration prevents program cancellation.',
    sourceUrl: null,
  },
  {
    type: 'hearing',
    committee: 'House Science',
    subcommittee: 'Subcommittee on Space and Aeronautics',
    title: 'Sustaining American Leadership in Space: Workforce and STEM Pipeline',
    description: 'Hearing on the space industry workforce shortage, examining challenges in recruiting and retaining aerospace engineers, technicians, and STEM professionals. Panel includes NASA Administrator, industry executives, and university deans.',
    date: new Date('2026-02-18'),
    status: 'completed',
    billNumber: null,
    witnesses: ['Bill Nelson (NASA Administrator)', 'Tory Bruno (ULA)', 'Dr. Ellen Stofan (Smithsonian)', 'Dr. Jim Free (NASA Assoc. Admin)'],
    relevance: 'Committee considering legislation to expand aerospace workforce development programs. Potential $500M authorization for STEM scholarships and apprenticeships over 5 years.',
    sourceUrl: 'https://science.house.gov/hearings/space-workforce-stem',
  },
  {
    type: 'markup',
    committee: 'HASC',
    subcommittee: 'Subcommittee on Strategic Forces',
    title: 'FY2026 NDAA Space Provisions Markup',
    description: 'House Armed Services Committee markup of space-related NDAA provisions including Space Force manning levels, commercial space reserve component pilot, USSF acquisition reform, and cislunar domain awareness requirements.',
    date: new Date('2026-03-10'),
    status: 'scheduled',
    billNumber: 'H.R. 4521',
    witnesses: [],
    relevance: 'Expected to include provisions for Space National Guard establishment and mandate for commercial SSA data procurement, impacting commercial space surveillance companies.',
    sourceUrl: null,
  },
  {
    type: 'report',
    committee: 'Senate Commerce',
    subcommittee: null,
    title: 'GAO Report: Assessment of NASA Artemis Program Cost and Schedule',
    description: 'The Government Accountability Office released its biannual assessment of the Artemis program, finding SLS Block 1B development is 18 months behind schedule and $800M over budget. HLS progress rated as "on track with risks."',
    date: new Date('2026-01-28'),
    status: 'completed',
    billNumber: null,
    witnesses: [],
    relevance: 'Report recommendations may influence FY2027 budget discussions. GAO recommends NASA establish firmer cost baselines and milestones for SLS Block 2 development.',
    sourceUrl: 'https://www.gao.gov/products/gao-26-105955',
  },
  {
    type: 'authorization',
    committee: 'House Science',
    subcommittee: null,
    title: 'NASA Authorization Act of 2026',
    description: 'Comprehensive NASA reauthorization bill addressing Artemis program milestones, commercial space station transition timeline, Mars exploration roadmap, space technology investment priorities, and establishment of a lunar infrastructure development program.',
    date: new Date('2026-04-01'),
    status: 'scheduled',
    billNumber: 'H.R. 5102',
    witnesses: [],
    relevance: 'First comprehensive NASA authorization in 4 years. Would mandate Artemis VI launch by 2029, require commercial LEO station operational by 2031, and authorize $2B for lunar surface infrastructure.',
    sourceUrl: null,
  },
  {
    type: 'hearing',
    committee: 'SASC',
    subcommittee: 'Subcommittee on Strategic Forces',
    title: 'Space Domain Threats: Adversary Counterspace Capabilities Assessment',
    description: 'Classified and open hearing sessions examining the evolving counterspace threat environment, including Chinese and Russian ASAT capabilities, directed energy weapons, and cyberattacks against space systems.',
    date: new Date('2026-03-20'),
    status: 'scheduled',
    billNumber: null,
    witnesses: ['Gen. Stephen Whiting (USSPACECOM)', 'Avril Haines (DNI)', 'Frank Calvelli (NRO Director)'],
    relevance: 'Expected to drive additional FY2027 funding for space resilience programs. May result in classified annex directing acceleration of certain counter-space programs.',
    sourceUrl: null,
  },
];

// ────────────────────────────────────────
// POST Handler
// ────────────────────────────────────────

export async function POST(request: Request) {
  const authError = requireCronSecret(request);
  if (authError) return authError;

  try {
    const results = {
      opportunities: { created: 0, skipped: 0 },
      sbir: { created: 0, skipped: 0 },
      budget: { created: 0, skipped: 0 },
      congressional: { created: 0, skipped: 0 },
    };

    // Seed Procurement Opportunities
    for (const opp of PROCUREMENT_OPPORTUNITIES) {
      const existing = opp.samNoticeId
        ? await prisma.procurementOpportunity.findUnique({
            where: { samNoticeId: opp.samNoticeId },
            select: { id: true },
          })
        : null;

      if (existing) {
        results.opportunities.skipped++;
      } else {
        await prisma.procurementOpportunity.create({
          data: opp as any,
        });
        results.opportunities.created++;
      }
    }

    // Seed SBIR Solicitations
    for (const sbir of SBIR_SOLICITATIONS) {
      const existing = sbir.topicNumber
        ? await prisma.sBIRSolicitation.findFirst({
            where: { topicNumber: sbir.topicNumber },
            select: { id: true },
          })
        : null;

      if (existing) {
        results.sbir.skipped++;
      } else {
        await prisma.sBIRSolicitation.create({
          data: sbir as any,
        });
        results.sbir.created++;
      }
    }

    // Seed Budget Items
    for (const item of BUDGET_ITEMS) {
      const existing = await prisma.spaceBudgetItem.findFirst({
        where: {
          agency: item.agency,
          fiscalYear: item.fiscalYear,
          category: item.category,
          program: item.program,
        },
        select: { id: true },
      });

      if (existing) {
        results.budget.skipped++;
      } else {
        await prisma.spaceBudgetItem.create({
          data: item as any,
        });
        results.budget.created++;
      }
    }

    // Seed Congressional Activities
    for (const activity of CONGRESSIONAL_ACTIVITIES) {
      const existing = await prisma.congressionalActivity.findFirst({
        where: {
          title: activity.title,
          committee: activity.committee,
        },
        select: { id: true },
      });

      if (existing) {
        results.congressional.skipped++;
      } else {
        await prisma.congressionalActivity.create({
          data: activity as any,
        });
        results.congressional.created++;
      }
    }

    logger.info('Procurement data initialization completed', results);

    return NextResponse.json({
      success: true,
      message: 'Procurement data initialized successfully',
      results,
    });
  } catch (error) {
    logger.error('Failed to initialize procurement data', {
      error: error instanceof Error ? error.message : String(error),
    });
    return NextResponse.json(
      { success: false, error: 'Failed to initialize procurement data: ' + (error instanceof Error ? error.message : String(error)) },
      { status: 500 }
    );
  }
}
